### ISSUE TITLE
Improve delete folder backup email

### ISSUE THREAD

**Issue by frenetic** [samuelclay/NewsBlur#1003]
When a user deletes a folder, it receives an email message with a backup of all its sites. It is amazing!
However, if it is the first time you are deleting a folder, the message can scare you.
It just happened to me, that's why Im opening this issue.

The thing is, the following message:
https://github.com/samuelclay/NewsBlur/blob/90498f5b9511072c62a2b37cd2172a058c614ed2/apps/reader/views.py#L1964
`You have deleted an entire folder of feeds, so here's a backup just in case.`

It will get concatenated with another string - the total number of your feeds.
https://github.com/samuelclay/NewsBlur/blob/55c36a24f38c25561e64b4365767547e3945ac1b/templates/mail/email_opml_export.txt

So, the final message will be something like:
`You have deleted an entire folder of feeds, so here's a backup just in case. It contains 66 sites.`

If you deleted an empty folder, this email message may make you feel like NewsBlur had a bug and deleted everything you owned.
My heart stopped for a second...

My suggestion is to change the first string to something like
`You have deleted an entire folder of feeds, so here's a backup OF ALL YOUR FEEDS just in case.`

The ALL YOUR FEEDS part do not need to go in caps.

**Comment by samuelclay** [comment]
Thanks! This was great feedback. Now deployed.
