### ISSUE TITLE
API login issue

### ISSUE THREAD

**Issue by apierz** [samuelclay/NewsBlur#1005]
I'm learning the NewsBlur API for a python application, but I am stuck at the login.

here is my test code:
``` python
head = {'username' : uname, "password" : pword}
ret = requests.post(url + "/api/login", params=head)
print(ret.status_code)
print(ret.headers['content-type'])
print(json.dumps(ret.json(), indent=2))
```

What I get back is:
```
200
application/json
{
  "code": -1,
  "authenticated": false,
  "errors": {
    "username": [
      "Please enter a username."
    ]
  },
  "result": "ok"
}
```

I guess I must be formatting my params wrong but I can't find any examples to copy.

**Comment by samuelclay** [comment]
Hi apierz, it doesn't take JSON input. You have to give it POST parameters.

**Comment by samuelclay** [comment]
I'm not sure what's going on. This code works for me:

    >>> requests.post('http://nb.local.com/api/login', {'username': 'samuel', 'password': 'x'}).text
    u'{"code": -1, "authenticated": false, "errors": {"__all__": ["Whoopsy-daisy, wrong password. Try again."]}, "result": "ok"}'

**Comment by samuelclay** [comment]
Ah-ha, don't use `params=`. Just pass the dict.

**Comment by apierz** [comment]
Knew I had to be making a mistake somewhere, thanks for the help.

**Comment by r-k-b** [comment]
For others like me ― that Python code is sending the credentials by `multipart/form-data` request; here's a curl equivalent:

    curl -X POST \
      https://newsblur.com/api/login \
      -H 'Cache-Control: no-cache' \
      -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
      -F 'username=samuel' \
      -F password=x
