### ISSUE TITLE
Text and Story views for "other" sites

### ISSUE THREAD

**Issue by brechmos** [samuelclay/NewsBlur#1012]
I am loving newsblur but had a question.  There are some feeds that I would love to include in feed list so the Text or Story view shows more of the "interesting parts".  

One example is Stackoverflow feeds.  I tried adding an RSS feed but the "Text" view only shows the initial question. When I click the "Story" view it switches to the Feed View.   I would love to see the answers in the Text view.

Is this something that would be easy to change in the code, or would this require code that is too specific?  I can clarify my thoughts if needed.

**Comment by samuelclay** [comment]
Hi brechmos, it is not easy to add custom support for sites for the Text view. It's all or nothing. I could possibly add StackOverflow support to the Text view but that would be time consuming and not a high enough priority relative to the other tasks I'm working on. I agree it would be a  nice to have, but unless a lot of users ask for it, I can't dedicate my few resources to it.
