### ISSUE TITLE
newsblur.com and ssl

### ISSUE THREAD

**Issue by brechmos** [samuelclay/NewsBlur#1013]
This may not be exactly the right place to put this but I would really encourage you to look into using SSL for the newsblur.com website.  Obviously free with Let's Encrypt etc.  Though maybe there might be issues with insecure feeds coming in through a secure connection (had that issue in the past with things).

**Comment by samuelclay** [comment]
I'm already using an expensive wildcard SSL certificate. I just allow non-https because a number of users want to get around browser restrictions that prevent http-only content from showing up on an https site. So I allow http-only.
