### ISSUE TITLE
Android: Switch between Text/Story view should be feed-sticky

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1018]
I noticed this in a single feed: when I switch to the Text view, it should make very subsequent story in that feed use the Text view. Essentially, when I use the Text view on a feed, all other stories in that feed should use the same Text view. Same as on the web. And so in a folder, if I'm swiping between stories of different feeds, each feed should retain its own Text/Story view.

**Comment by dosiecki** [comment]
If you change view mode using the `Default View` menu item, it change should be sticky.  If not, let me know exact repro steps so I can debug.

Quickly swapping to text view using the overlay button is analogous to hitting the "Enter" key on web, which, unless it has changed, is not sticky for me.  Is this incorrect?

**Comment by samuelclay** [comment]
Ah-ha, I get it. Yeah, that's not the correct behavior. The Text button is sticky. There is no temporary switch like the enter key on the web.

**Comment by dosiecki** [comment]
Okay, fixed this so the overlay button now works more like a left/right mode switch rather than the enter-key mode switch and stick for the given feed/folder being read.  (took a bit of doing, since previously there was exactly one place in the app where it could change and now there are a couple)

**Comment by dosiecki** [comment]
deployed to Prod
