### ISSUE TITLE
Web: Folder rename pre-populates with old name

### ISSUE THREAD

**Issue by cyranix** [samuelclay/NewsBlur#1026]
Steps to repro:

1. Have a folder of feeds named "A".
1. Choose "Rename this folder" from the folder dropdown; rename it to "B" and save.
1. Choose "Rename this folder" from the folder dropdown again.

Expected: Initial text in form field is "B".
Actual: Initial text in form field is "A".

**Comment by samuelclay** [comment]
This will be fixed with #1322.
