### ISSUE TITLE
Android: Subscribe intent

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1029]
We should build a share intent so that folks can subscribe to sites right from the site (or shared URL). I imagine 95% of this feature will be used from chrome. 

If possible let's do a v1 and v2. V2 is the in app dialog with async requests and confirmation. V1 just kicks the user over to the app or something relatively quick. More of quick way to get a URL subscribed and into a folder. We may just have to build v2. 

This has been a popular request for as long as I can remember and I think it's time we made it easier to get urls into newsblur.

**Comment by dosiecki** [comment]
released in v6.1
