### ISSUE TITLE
Web: Add notes and highlighting to saved stories

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1035]
Notes should look and work like shared stories but with a different background and a note about how only you can see this. Would be built on shared stories but would've the third category after friends and public comments. 

Highlighting is trickier. Multiple sections and it should interact with natural text selection. Also need an easy way to clear highlights. Also would be nice to list out highlights as its own saved story special feed.

**Comment by lukaskawerau** [comment]
The idea came to me when I repeatedly sent articles from Newsblur to Instapaper to highlight and comment text I was reading (esp. on the iPad app). I think Instapaper does this really nicely UI-wise, so might be worth looking for clues there. Thank you!

**Comment by samuelclay** [comment]
Ahh just thinking about the number of features I've stolen from Instapaper. Great idea!

**Comment by samuelclay** [comment]
This is sooooo close to launching but I can't figure out how to unhighlight passages reliably and that's killing it.

**Comment by samuelclay** [comment]
(From the other thread) Just fixed it a few days ago! I'll be launching it this week, it's all ready to go. I might silently launch it tomorrow after I stress test it a bit more.

**Comment by samuelclay** [comment]
This has now launched! I'll be blogging it tomorrow.

**Comment by samuelclay** [comment]
Oops, forgot the notes part. Adding that in now to both the bookmarklet and the website.

**Comment by samuelclay** [comment]
Ok, private notes are in. Will be blogging soon.
