### ISSUE TITLE
URL to add a feed from external apps/scripts.

### ISSUE THREAD

**Issue by caschbre** [samuelclay/NewsBlur#104]
I've used the RSS Subscription Extension (https://chrome.google.com/webstore/detail/rss-subscription-extensio/bmjffnfcokiodbeiamclanljnaheeoke) to easily add feeds to google reader.  To use that extension with newsblur I have to provide the url so the extension can pass the feed to newsblur. 

Where can I find that?

**Comment by KurtPreston** [comment]
Just to be explicit, the URL you want to enter is `http://www.newsblur.com/?url=%s`
