### ISSUE TITLE
400 Bad Request when trying to connect from Android App

### ISSUE THREAD

**Issue by Nixellion** [samuelclay/NewsBlur#1042]
I'm trying to connect to python socketio server from Android Java app, using the following code:

```
import com.github.nkzawa.socketio.client.IO;
import com.github.nkzawa.socketio.client.Socket;

 private Socket mSocket;
    {
        try {
            SSLContext sc = SSLContext.getInstance("SSL");
            sc.init(null, null, new SecureRandom());
            IO.setDefaultSSLContext(sc);
            HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier(){
                public boolean verify(String hostname, SSLSession session){
                    return true;
                }
            });
            IO.Options opts = new IO.Options();
            opts.forceNew = true;
            opts.reconnection = true;
            opts.secure = true;
            opts.sslContext = sc;


            mSocket = IO.socket("https url", opts);
        }
        catch (URISyntaxException e) {}
    }
```

But in server logs I get this:

`ERROR - 192.168.1.1 - - [18/Sep/2017 00:19:36] code 400, message Bad request syntax ('\x16\x03\x01\x00´\x01\x00\x00°\x03\x03,Ö') `

My server is self-signed, and it's 'green' in browsers.

First I tried without SSL code, then I found out that SSL might be the cause of this problem, but it looks that either my SSL code in Java is wrong, or the problem lies elsewhere.

What is the general guideline in connecting to Python SocketIO server from Android Java app? What could be the usual suspects for this kind of error?

Thanks in advance!

**Comment by samuelclay** [comment]
Hmm, why are you connecting to the socket.io server? It's not a Python server, it's running Node.js and Socketio.js. It's only for real-time notifications and it's not meant for third parties.

**Comment by Nixellion** [comment]
I'm not connecting to 'https://socket.io/'.

I'm running my own server, with my own Python Flask-SocketIO server running on it. I know that it's python, because I wrote it. 

I writing my personal voice-assistant, and it works as client-server. The server side is written in Python Flask and flask-socketio. Right now I have a web-client that works perfectly. But I want to write a native android client as well.

Client must be able to recognize text (got that part) and  just send a text string to the server and receive a response.

**Comment by Nixellion** [comment]
Wait, why is this in newsblur. This is supposed to be in java socketio git, what!? This is weird, sorry
