### ISSUE TITLE
Web + iOS: Scrolling to mark as read should leave marked as unread stories as unread

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1044]
From a user's support request:

Noticing a bug in this release I want to share.

When reading through a site's feed or a folder's list of articles, articles that were read and then marked as unread become re-marked as read as I keep scrolling through the rest of the unread stories.

So after going through a feed of unread stories, if you saved a few along the way and hit Done at the end, the user will lose those saved news items.

**Comment by Dejal** [comment]
I just tested this on iOS, and it does appear to do the right thing. I'll leave this open in case the web needs fixing; please close if all good.
