### ISSUE TITLE
unable to hide read articles

### ISSUE THREAD

**Issue by blshkv** [samuelclay/NewsBlur#1046]
I have set read filter to "unread only" option and it works with some websites. However, it does not work with others. News feeds which I already read still displays in gray (as read).
 Here is an example of feeds where it does not work:

https://isc.sans.edu/dailypodcast.xml
https://www.reddit.com/r/netsec/.rss
https://insinuator.net/feed/

Both web/mobile versions affected. Could you have a look please?

Thank you.

**Comment by samuelclay** [comment]
Whats your username and what's an example of a story title that won't stay hidden?

**Comment by blshkv** [comment]
Please subscribe to netsec and test it. It might be something to do with the fact that I did not have time to read it all.

username "blshkv". Here is the screenshot:
http://imageshack.com/a/img923/2104/mg2cFW.png

**Comment by samuelclay** [comment]
Try hitting mark all as read. Do the stories come back as unread? After how long? Immediately?

**Comment by blshkv** [comment]
I think the issue appears after the rss feed wasn't read for a long time, a month or couple weeks at least.
Hitting "all as read" button fixes the issue immediately.

**Comment by blshkv** [comment]
Seems fixed indeed. Thanks a lot!

**Comment by blshkv** [comment]
@samuelclay I would like to re-open this bug as the issue is not fixed. I haven't read all fees for about a months and got ~150 new articles. I have read them all, one by one but the old "read" articles show up n my next visit.  I had to click "mark all as read" even if there are visible unread feeds. That's the only solution for now.

Thank you
