### ISSUE TITLE
Selecting a YouTube channel feed redirects whole page to youtube.com after a few seconds

### ISSUE THREAD

**Issue by desbma** [samuelclay/NewsBlur#1050]
When I select a youtube channel feed, after a few seconds the whole page sometimes gets redirected to the youtube homepage.

It seems to occur only in some conditions, or randomly but it is not systematic, although it occurs quite frequently for me.

When that occurs, if I hit "back" to go back to Newsblur page, I then almost instantly get redirected to YouTube again. The only workaround I have found is to go a few pages back to a Newsblur page where no YouTube feed is selected.

I have ~125 feed and this issues only occurs with Youtube feeds.

I'm on Firefox 56, my layout is configured in "story mode" with horizontal split.

**Comment by samuelclay** [comment]
I bet it's Story mode that's causing it. They probably have an iframe buster that NewsBlur isn't able to stop. Why not just use Feed view?

**Comment by desbma** [comment]
It's just annoying to manually switch view, for all youtube feeds, to work around this bug.

Isn't there a way to protect from these redirects?

**Comment by samuelclay** [comment]
You can change your default to the Feed or Text view. You can also use keyboard shortcuts to quickly change views. Change to "All Feeds" so you see all youtube feeds. Then hit the left arrow key to switch views and then j/k to move between feeds. That'll be sticky as well, so it should be a quick change.

**Comment by desbma** [comment]
Thanks @samuelclay however these are just workarounds and do not solve the root problem.

Isn't it possible to simply prevent redirects for example using an iframe with the [sandbox attribute](https://developer.mozilla.org/fr/docs/Web/HTML/Element/iframe)?

The fact that a feed in an iframe can actually redirect the parent page is actually **very worrying security wise**. Any feed could redirect the page to a Newsblur clone site and inject/steal/modify anything in a browser session starting from this.
