### ISSUE TITLE
Android: Infrequent Site Stories

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1051]
Pass 'infrequent': true to the same river endpoint as All Site Stories, along with all the feed ids as you normally would. This will filter stories down to feeds that publish < 1 story/day. You can try it out on debug.newsblur.com.

**Comment by dosiecki** [comment]
So I know what to test - what is the expected behaviour here?  Would these stories not already be showing up in their respective feeds or folders?  I'm only seeing the API return stories I've already got via the unreads API, and most of them from fairly high-volume feeds.

**Comment by samuelclay** [comment]
I haven't launched it yet, so you'll need to hit debug.newsblur.com to test the new 'infrequent' endpoint.

**Comment by dosiecki** [comment]
Ah, looks like I may have found a bug in the web UI, not the API.  If I click on the infrequent folder and switch unread filters for it, I get punted back to the normal All Stories folder.

**Comment by samuelclay** [comment]
Looks like the deploy didn't update fully. Should be working now.

**Comment by dosiecki** [comment]
I'm having trouble getting the API to actually filter.  Normally I request All Stories like:

`debug.newsblur.com/reader/river_stories?order=newest&include_hidden=true&page=1&read_filter=all`

And if I add the suggested paramter like so, I get exactly the same set of stories:

`debug.newsblur.com/reader/river_stories?order=newest&include_hidden=true&page=1&read_filter=all&infrequent=true`

**Comment by samuelclay** [comment]
I just changed the API to infrequent=# where # is 5, 15, 30, 60, or 90. Alternatively you can submit 'false' and it will behave just like the old call. I also deployed dit to prod, so you don't have to use debug.

**Comment by samuelclay** [comment]
I also updated the API to reflect this.

**Comment by samuelclay** [comment]
I believe you should be able to see it on the web, as I made it available to staff. 
<img width="1036" alt="screen shot 2017-11-06 at nov 6 5 20 40 pm" src="https://user-images.githubusercontent.com/44229/32472301-d63dd8f0-c316-11e7-9afd-7b465e3913b3.png">

**Comment by dosiecki** [comment]
Just tried this:

`newsblur.com/reader/river_stories?order=newest&include_hidden=true&page=1&read_filter=all&infrequent=30`

and got exactly the same set of stories as:

`newsblur.com/reader/river_stories?order=newest&include_hidden=true&page=1&read_filter=all`

Same results using `infrequent=1` and on both the debug and non-debug endpoints.

**Comment by samuelclay** [comment]
Check it on the web, do you get the same results?

**Comment by dosiecki** [comment]
Web looks good.  The Infrequent folder does in fact show a more limited subset of stories.

**Comment by samuelclay** [comment]
This is the URL I have on the web for Infrequent:

http://www.newsblur.com/reader/river_stories?feeds=452556&feeds=21129&feeds=4311755&feeds=1403400&feeds=5939784&feeds=1059&feeds=6050&feeds=5586842&feeds=69&feeds=6446515&feeds=6058694&feeds=5586600&feeds=21309&feeds=5994357&feeds=3581&feeds=182426&feeds=188693&feeds=37&feeds=3200601&feeds=1299648&feeds=5855816&feeds=50&feeds=52&feeds=1010775&feeds=34&feeds=1269508&feeds=682660&feeds=1503770&feeds=1075771&feeds=5638121&feeds=19&feeds=4403&feeds=588673&feeds=2941&feeds=16805&feeds=3460291&feeds=4856&feeds=5726200&feeds=183787&feeds=223599&feeds=203010&feeds=365&feeds=16995&feeds=1072&feeds=785&feeds=4881306&feeds=2851170&feeds=6043968&feeds=2661956&feeds=1340342&feeds=4611&feeds=1493574&feeds=91&feeds=821794&feeds=2186&feeds=1342402&feeds=6553853&feeds=213925&feeds=6755702&feeds=644144&feeds=22&feeds=23&feeds=799&feeds=197108&feeds=6563232&feeds=5439135&feeds=6184213&feeds=5663943&feeds=6241345&feeds=6235352&feeds=6227985&feeds=6246499&feeds=6252798&feeds=6236185&feeds=6248051&feeds=6240813&feeds=6246915&feeds=6837401&feeds=6233925&feeds=6792853&feeds=6245336&feeds=6831738&feeds=6540291&feeds=6302601&feeds=6363196&feeds=6227190&feeds=6236242&feeds=6549181&feeds=6228626&feeds=6235759&feeds=6407426&feeds=6229886&feeds=5946&feeds=5761116&feeds=6634686&feeds=1489673&feeds=97100&feeds=5436133&feeds=787&feeds=202849&feeds=1480023&feeds=6297641&feeds=6327282&feeds=6002602&feeds=140145&feeds=6403785&feeds=3846409&feeds=12&feeds=6674065&feeds=6319042&feeds=6319428&feeds=6319302&feeds=6655188&feeds=6325015&feeds=6319051&feeds=6652851&feeds=6319283&feeds=6319061&feeds=93882&feeds=349136&feeds=2237676&feeds=1478918&feeds=3264361&feeds=97798&feeds=672769&page=1&order=newest&read_filter=unread&query=&include_hidden=true&infrequent=30&_=1510016073349

**Comment by dosiecki** [comment]
So, it appears that the difference is that I am not passing a list of feed IDs.  What is that big list?  Is that a list of every feed to which the user is subscribed, or just the feeds with infrequent stories?  If the latter, where does that list come from?  In my experience, the `/reader/river_stories` API doesn't take a list of feed IDs unless it is a specific folder.

**Comment by samuelclay** [comment]
It's a list of feeds that have an unread story, either in Unread mode or in Focus mode. I suppose I can add logic to do the work after the feeds are retrieved. It's just more efficient to not have to fetch the user's subscriptions.

I just added some logic to check for infrequent feeds again if all feeds aren't provided. Go ahead and check now.

By the way, don't use the debug server anymore, as I'm not pushing to it and can't vouch for it's state.

**Comment by dosiecki** [comment]
Excellent, they now match!

**Comment by dosiecki** [comment]
live in production
