### ISSUE TITLE
Android: Grid View

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#1052]
Android is missing the grid-style story list mode that prioritizes thumbnails.  We should modernize the ItemsList activity to use a RecyclerView that will allow us to support more novel layouts than the vertical lists of old.

**Comment by dosiecki** [comment]
Completed in #1095.

**Comment by bingoxo** [comment]
can this be ported to ios client ? (please)

**Comment by samuelclay** [comment]
Yep, this is now #1270.
