### ISSUE TITLE
Web: Long feed names has line breaks in new firefox quantum

### ISSUE THREAD

**Issue by creiner** [samuelclay/NewsBlur#1058]
In the new firefox (Version 57.0) longer feednames are broken into mutiple rows, see picture:
![image](https://user-images.githubusercontent.com/137896/32979883-69581dea-cc5d-11e7-9cb4-1f7352d8ca6d.png)
Edit: Same in IE11

**Comment by samuelclay** [comment]
Fixed in #1059.
