### ISSUE TITLE
Android: long press a link in a story should open the Share menu

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1061]
User requested it recently and I realized Android doesn't have this feature.

**Comment by caleb-allen** [comment]
looks as if it was added a while ago with f173e6881cbbd94e6de53d55a230cc374428455e, at least partially. 

Just an "open link" modal--@samuelclay should this be shifted to share?

Here's what it is now 
![Screenshot_1566251345](https://user-images.githubusercontent.com/3279748/63301945-1931f500-c299-11e9-9e1f-3364a1b9dec5.png)

**Comment by samuelclay** [comment]
Yeah let's shift that to the native share dialog so users can do anything from there.
