### ISSUE TITLE
iOS: UX feature request with All/Unread/Focus/Saved filter

### ISSUE THREAD

**Issue by axlekb** [samuelclay/NewsBlur#1063]
I frequently mistakenly hit the 'Focus' filter at the bottom of the iOS App and go for days thinking I'm up to date on all my feeds, only to log into the web app where it is filtered to 'Unread' and see that I'm hundreds of articles behind.

I guess it's probably because I tend to ignore that functionality at the bottom of the page because I'm only ever using 'Unread'. 

It would be great to see some sort of indication that I'm missing 'Unread' articles when I've 0 unread "Focus" stories.

**Comment by samuelclay** [comment]
You should see a "No unread Focus stories, switch to Unread." message. I know I cleaned this up in today's big 7.0 release, so let me know if that fixes it when it's released later today.
