### ISSUE TITLE
Some forum feeds no longer fetch posts

### ISSUE THREAD

**Issue by xeranas** [samuelclay/NewsBlur#1070]
Hello, 

Seems some phpBB forum feeds no longer fetch posts for me via web client (newsblur.com) e.g.: ```https://forum.minetest.net/feed.php?f=15``` says:

> 
> 2017-12-27 10:07:00 Not an RSS feed (553)
> 2017-12-26 23:44:56 Not an RSS feed (553)
> 2017-12-26 12:34:26 Not an RSS feed (553)

In case of re-adding same URL message appears:

> This address does not point to an RSS feed or a website with an RSS feed.

About week ago (around dec 19) it worked fine. I'm not sure is this is problem of NewsBlur or forum RSS configuration issue. However, Firefox recognizes ```https://forum.minetest.net/feed.php?f=15``` page as  RSS feed.

**Comment by samuelclay** [comment]
Was probably temporary as the feed now works fine: http://www.newsblur.com/site/6908156/minetest-forums
