### ISSUE TITLE
iOS: Long press makes a story sticky across folders

### ISSUE THREAD

**Issue by adeftu** [samuelclay/NewsBlur#1072]
1. Go to one folder and long press on any story.

![img_1041](https://user-images.githubusercontent.com/13695993/34596483-10ceeeb2-f1ae-11e7-9307-5d8a730c5541.PNG)

2. Move it while holding it until that blue 2 appears in the top right corner (what is that?), then release hold.

![img_1042](https://user-images.githubusercontent.com/13695993/34596508-4fa8df1c-f1ae-11e7-921e-36d23ef87c67.jpg)

3. Go to another folder and observe the story from the previous folder is still there, masking the actual story from current folder.

![img_1043](https://user-images.githubusercontent.com/13695993/34596532-9333cd82-f1ae-11e7-95e3-841432d624ff.PNG)

4. Long press on it to reveal the actual story that's supposed to be in that position.

![img_1044](https://user-images.githubusercontent.com/13695993/34596568-e56d4b64-f1ae-11e7-9905-6c6f986fb1f6.PNG)

Suggestion: Have an option to disable long press and move (step 2.) above which I am not sure what's supposed to do but which I very often do it by mistake while browsing (e.g. scrolling down the stories) and consequently make stories "sticky".

Version 7.1.1.

**Comment by nriley** [comment]
The "2" indicates 2 items being dragged.  iPhone doesn't support drag and drop across apps in any case, so likely the best solution here would be to disable dragging from the table of stories entirely.

**Comment by adeftu** [comment]
Which 2 items would those be? It's only one story being dragged.
In any case, is there an option to disable dragging? I couldn't find one. Currently my folders are a mess with stories from others (you can tell by the different border color). In this example below, the 3 stories with the non-orange border appear in all my folders on top of the original stories and I don't know how to unstick them.

![img_1045](https://user-images.githubusercontent.com/13695993/34640772-3ecca998-f2c7-11e7-8838-eace0884c840.PNG)

**Comment by nriley** [comment]
The 2 items currently are the story's title and its URL.  (You get 3 items if there's also an image for the story.)

Again, this is almost completely useless on iPhone as you can't drag cross-app and any dragging intra-app in NewsBlur is not helpful; on iPad this will let you drag a story into Notes or an email, for example.

I've made some changes that entirely disable dragging on iPhone and (IMO) improve the dragging experience on iPad.

**Comment by adeftu** [comment]
Cool, thanks!

**Comment by samuelclay** [comment]
Will deploy in next release. Thanks for bringing this up.

**Comment by nriley** [comment]
Verified, can't drag on iPhone in 7.1.2 and the iPad stuff seems to be working fine.
