### ISSUE TITLE
Possible to add notifications filtered on the basis of keywords?

### ISSUE THREAD

**Issue by shadowbone94** [samuelclay/NewsBlur#1079]
Similar to the new intelligence trainer feature, could you perhaps push notifications based on certain keywords? 

Eg: BBC news feed might push all sorts of content. Instead just get notifications if only a breaking news appear after setting that as a keyword.

**Comment by samuelclay** [comment]
This already exists but you'll have to use the intelligence trainer and choose to only send "Focus" stories.
