### ISSUE TITLE
Android: scroll past last story title when marking stories read on scroll

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1082]
See https://getsatisfaction.com/newsblur/topics/cannot-scroll-article-list-when-all-content-is-visible

Only show the extra tall footer if mark read on scroll is enabled. I recently added this to iOS.

**Comment by samuelclay** [comment]
![c544d060-1766-42be-b7f1-b661ebc06abc](https://user-images.githubusercontent.com/44229/36499875-6d8728c2-16f7-11e8-9b65-5cc106d28a4d.png)

**Comment by dosiecki** [comment]
Will do.  This is 100% untested feature (since I don't use it), so keep the recommendations coming.

**Comment by dosiecki** [comment]
included in #1095
