### ISSUE TITLE
duplicate folders issue

### ISSUE THREAD

**Issue by matsuiny2004** [samuelclay/NewsBlur#1086]
Ive been using the nested folders features but once i get into the 4th or 5th layer of nested folders I cant view my site feeds or even move individual site feeds from folder to folder. what i mean by layers is like nesting 4 or 5 folders within each other. once i do this the problem happens. this happens in the browser version. wasnt a problem with the android app. multiple browsers. including chrome and firefox. might be due to the fact they are duplicate folders of the same thing.  it only happrens with duplicate folders after looking into the problem.

 Update: main problem was just that i had a bunch of duplicated files and couldnt view my site feeds for the duplicates.

**Comment by matsuiny2004** [comment]
what i mean by layers is like nesting 4 or 5 folders within each other. once i do this the problem happens.

**Comment by samuelclay** [comment]
Unfortunately duplicate folder names are not well handled. One day we'll migrate to a better folder naming system. 

I wrote #1322 to handle this work. I believe this will *finally* be fixed soon.
