### ISSUE TITLE
Bug found in news blur when in landscape mode 

### ISSUE THREAD

**Issue by jubreal** [samuelclay/NewsBlur#1094]
#### Expected behavior
The application should be have the same functions and display when in portrait view of landscape view .

#### Actual behavior
When rotated to landscape view,  some displays which were present in portrait view are cut off and missing. Display features such as "I need to register " ,"I have forgotten my password " and  "I have custom server" are cut off and missing in landscape view. 

#### How to reproduce
1. Download the news blur app
2. Launch the app 
3. Rotate to landscape view.  Some parts of the display which is present in portrait are missing in landscape view .  
Display features such as "I need to register " ,"I have forgotten my password " and "I have custom server" are cut off and missing in landscape view.
* Browser: News blur app version 7.0.3
* Operating system: android 6.0 infinix Note 3

#### Recording Of The Bug
https://youtu.be/qmfjHRcdTZE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jubreal/bug-found-in-news-blur-when-in-landscape-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dosiecki** [comment]
addressed in #1095
