### ISSUE TITLE
iOS: Video autoplay from non-current stories

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1096]
See https://getsatisfaction.com/newsblur/topics/videos-autoplaying-on-ios-unmuted.

I think this is just a one-word fix so I'm not even bothering with a pull request.

**Comment by samuelclay** [comment]
You want to remove the autoplay tag from <video> elements? I don't understand why iOS doesn't respect the `playsinline` and `muted` attributes. Also, this is only for twitter videos. DO you see something I'm not seeing?

**Comment by samuelclay** [comment]
Ah-ha, thank you for the explanation. I've reverted the commit and will push in an upcoming iOS update.
