### ISSUE TITLE
Web: Add Save Story to sharing bookmarklet

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1097]
This is to complement the share story feature that already exists. Saving a story would allow the user to add saved story tags, with one automatically filled out: a "from the web" tag automatically added.

**Comment by garymh** [comment]
Is there any movement on this by chance? Sorry to be annoying! 😅

**Comment by samuelclay** [comment]
This launched in June of this year!

<img width="903" alt="Screen Shot 2020-10-16 at Oct 16 4 50 41 PM" src="https://user-images.githubusercontent.com/44229/96307497-bdafe400-0fcf-11eb-8877-162f26d83f5c.png">
