### ISSUE TITLE
Add to Newsblur link don’t work if you’re not already logged in (better landing pages)

### ISSUE THREAD

**Issue by da2x** [samuelclay/NewsBlur#1098]
`https://www.newsblur.com/?url=http://blog.newsblur.com/rss`

If you don’t have an account, the position of the dialog is off/mostly out of screen. This has been broken for years … .

The dialog isn’t useful as it only shows an error about needing an account. Users should be prompted to login and then prompt them to add the feed again. Or if you register a new account, it should subscribe you to the referring feed like the promotional landing pages Feedly uses.

`https://feedly.com/i/welcome/feed/http://blog.newsblur.com/rss`

**Comment by reetikaSR** [comment]
seems this to be an issue. Is anyone working on this?

**Comment by samuelclay** [comment]
Thanks for writing this up! I'm working on fixing all of these issues and this has now been fixed. If you're not logged in, you will now be presented with the login form, and then once logged in the feed url is preserved and easily added.

**Comment by da2x** [comment]
@samuelclay could you add a "Log in or sign up to subscribe to $feed_url" message above the login form? It kind of just drops you on the page with no explanation. Such a message would help explain what's going on and potentially land you some extra sign up from new users who stumbled upon a Subscribe link on an external website.

**Comment by samuelclay** [comment]
I think that's part of a broader redesign of the static pages, which I'm hoping to get to one day but is not higher priority than much of the other web issues. I'm going to table this for now, partially because designing that isn't straight-forward.
