### ISSUE TITLE
media/admin is a dead symlink

### ISSUE THREAD

**Issue by hnrd** [samuelclay/NewsBlur#1101]
The media/admin subdirectory contains a symbolic link to a full non-relative path:
`/Users/sclay/projects/django/django/contrib/admin/static/admin`

See: https://github.com/samuelclay/NewsBlur/blob/master/media/admin

**Comment by samuelclay** [comment]
Thank you! This is now fixed.

**Comment by samuelclay** [comment]
How did you discover this?

**Comment by hnrd** [comment]
Thanks! :)

I scp-ed my clone from one server to another and caught a glimpse of the error, as the symlink could not be resolved.
