### ISSUE TITLE
Android: Use internal browser

### ISSUE THREAD

**Issue by Limero** [samuelclay/NewsBlur#1106]
For my news, I use the NewsBlur and Slide for Reddit apps for Android. When links are opened in Slide, they are shown in an internal browser whilst NewsBlur opens them in the regular external browser; Firefox in my case.

My suggestion is that by default, or by a setting, NewsBlur should open links in an internal browser, as it is more conventient than opening another application and switching back and forth.

**Comment by dosiecki** [comment]
On 21 May 2018 12:48:16 GMT-07:00, David Pedersen <notifications@github.com> wrote:
>For my news, I use the NewsBlur and Slide for Reddit apps for Android.
>When links are opened in Slide, they are shown in an internal browser
>whilst NewsBlur opens them in the regular external browser; Firefox in
>my case.
>
>My suggestion is that by default, or by a setting, NewsBlur should open
>links in an internal browser, as it is more conventient than opening
>another application and switching back and forth.

What version of Android are you running? We use the most default Intent to open stories, so the launch behaviour is 100% determined by your system. On reasonably modern devices, stories should open in-app (a "Chrome Custom Tab", technically).

**Comment by Limero** [comment]
I use Android 8.1.0 (LineageOS 15.1). I tried installing Chrome and it still opens links externally by switching to the app. I think it's up to each app to decide, as Slide has a setting for it.

**Comment by dosiecki** [comment]
Broadening this issue to cover the whole gamut of desired controls around overriding system-wide defaults for browser intent handling, per: https://forum.newsblur.com/t/android-default-browser/7146

**Comment by samuelclay** [comment]
Closed in lieu oif #1319
