### ISSUE TITLE
Logo Design Offer as Open Source Contributor

### ISSUE THREAD

**Issue by fajrijauhari** [samuelclay/NewsBlur#1107]
Hi sir. I am a graphic designer. I want provide a logo for you. Would you mind if i propose a new logo design for your application as my Open Source Contributor ?
Thanks before.

**Comment by samuelclay** [comment]
Sure, I'd love your contribution. I'll mention you just had poor timing as I left for China on May 18th and just moved into my new apartment this week. But I'm back and would be happy to see your design.

**Comment by fajrijauhari** [comment]
Hello, Sir @samuelclay . These is my logo proposal for your project. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

Version 1
![version 1-01](https://user-images.githubusercontent.com/38754587/42578775-bfed284e-84db-11e8-955c-3dd155d1c340.png)

Version 2
![version 2-01](https://user-images.githubusercontent.com/38754587/42578787-c821b9c6-84db-11e8-9fc2-e1e599ae7894.png)

**Comment by samuelclay** [comment]
That's a very nice logo but I don't feel it is appropriate for NewsBlur as it has none of the history or uses none of the existing elements or design from the current logo and site. NewsBlur has a consistent theme and logo and I'd like for any new logo to use the tone of the old logo.

**Comment by fajrijauhari** [comment]
version 3
![untitled-1-01](https://user-images.githubusercontent.com/38754587/42585047-7618d926-84e9-11e8-8b97-8d8c7c05d49e.png)

**Comment by samuelclay** [comment]
That's a nice image but now it's a very dense and complicated logo. I think simplifying the outer rays would have a better payoff.

**Comment by fajrijauhari** [comment]
version 4
![untitled-2-01](https://user-images.githubusercontent.com/38754587/42604628-a755b63c-8528-11e8-9abd-ab448fe00c19.png)

**Comment by fajrijauhari** [comment]
version 5
![version 5-02](https://user-images.githubusercontent.com/38754587/42627501-149a1f72-8582-11e8-8dfd-5c25fed2e9cf.png)

version 6
![version 5-03](https://user-images.githubusercontent.com/38754587/42627512-1b6b708a-8582-11e8-9561-6124c56f0450.png)

Hope you like it :)

**Comment by samuelclay** [comment]
![logo_512](https://user-images.githubusercontent.com/44229/42648400-caabec12-85d4-11e8-8d0d-b62bec0b5dee.png)

I still like the original better. It's a simpler, more recognizable form. I'm not wild about some of the curves in it but it feels consistent and is less busy than the proposed alternatives above.

**Comment by samuelclay** [comment]
![logo_newsblur_blur](https://user-images.githubusercontent.com/44229/42648467-05e8275a-85d5-11e8-8b12-d41b8c8a3319.png)

and of course the blurred version (used in emails).

**Comment by fajrijauhari** [comment]
Ok. Thanks
