### ISSUE TITLE
Docker: Replace libmysqlclient-dev is unavailable, replace with default-libmysqlclient-dev instead?

### ISSUE THREAD

**Issue by myoriginalusername** [samuelclay/NewsBlur#1113]
When using Docker to build the images, in the [Dockerfile](https://github.com/samuelclay/NewsBlur/blob/master/docker/Dockerfile), we try to use `libmysqlclient-dev` however, this returns the following error messages:

```
Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libmysqlclient-dev' has no installation candidate
ERROR: Service 'newsblur' failed to build:
```

As you can see, the newsblur image fails to build because of `libmysqlclient-dev`.

This seems to be fixed by updating the Dockerfile and replacing line 26 so that `libmysqlclient-dev \` becomes `default-libmysqlclient-dev \`

When we update the Dockerfile to use `default-libmysqlclient-dev` we are able to build the newsblur Docker image just fine.

**Comment by samuelclay** [comment]
Hey, this would make for a perfect PR. Mind submitting your change? I'd be happy to accept it.

**Comment by myoriginalusername** [comment]
No worries, PR created! #1115

**Comment by samuelclay** [comment]
Thanks!
