### ISSUE TITLE
Firefox is removing support for registerContentHandler

### ISSUE THREAD

**Issue by gijsk** [samuelclay/NewsBlur#1116]
See https://www.fxsitecompat.com/en-CA/docs/2018/navigator-registercontenthandler-has-been-removed/

I noticed that this repository contains some code that tries to register the site on which it runs as a content handler for some feed types. This will stop working once Firefox 62 is released (scheduled for the beginning of September, https://wiki.mozilla.org/Release_Management/Calendar ).

Firefox is also thinking about removing built-in feed support, so like Chrome I expect you would soon want/need an add-on if you wanted to handle RSS/Atom feeds opened in "normal" browser tabs by redirecting them to newsblur.

**Comment by ktosiek** [comment]
This has already happened - I've reinstalled my system and I can't add Newsblur to the RSS subscription options from goodies.

**Comment by samuelclay** [comment]
For anybody seeing this thread, here are some options for managing RSS in Firefox:

https://support.mozilla.org/en-US/questions/1244312
