### ISSUE TITLE
Toggle/Open sidebar pane doesn't move story pane left

### ISSUE THREAD

**Issue by thinkpoop** [samuelclay/NewsBlur#1117]
When toggling the sidebar off and on again, the story-pane-container div doesn't update its "left" css attribute when re-opening. After a pause of 1 or more seconds any manual resize event will fix it.

My best guess is that maybe something like a call to $story_pane.css('left',x) is changing the css value without jQuery.layout knowing about it, so it doesn't correct the value right away. Not sure why the this.resize_window right after open('west') isn't triggering it though.

Both Chrome & Firefox on windows. It's been happening for a couple years, so low priority.

**Comment by samuelclay** [comment]
Just tested this (with the shift+u keyboard shortcut) and it seems to be working fine. Can you post a screenshot so I can reproduce it exactly?

**Comment by thinkpoop** [comment]
Detail I forgot to add: it's when stories are in the "full" view.

Before hiding the side panel:
<img width="960" alt="1-Before Hiding Side Panel" src="https://user-images.githubusercontent.com/3870583/84179847-2d272d00-aa4c-11ea-93e2-55008c30291e.PNG">

While side panel is hidden (pressing shift+u):
<img width="960" alt="2-Side Panel Hidden" src="https://user-images.githubusercontent.com/3870583/84179860-3617fe80-aa4c-11ea-8d58-d020f6cdce12.PNG">

After reopening the side panel (pressing shift+u again):
<img width="960" alt="3-After Unhiding Side Panel" src="https://user-images.githubusercontent.com/3870583/84179865-3a441c00-aa4c-11ea-995b-45fa4d03af1d.PNG">

This is just a super low priority "would be nice to have fixed someday" thing, feel free to leave it closed.
