### ISSUE TITLE
Self hosting: What causes the dashboard realtime spinner GIF to be NB-error?

### ISSUE THREAD

**Issue by myoriginalusername** [samuelclay/NewsBlur#1119]
Having managed to get NB initially running as a self-hosted Docker-ised instance, I've noticed that trying to import an OPML file can be painfully slow as it trundles through site after site loading RSS feeds.

I'm not sure why this is happening. Incidentally, I've noticed that the spinner GIF is red, indicating an error:
![image](https://user-images.githubusercontent.com/13319608/43550372-451d3530-95db-11e8-8cfc-37c5cfa9e05f.png)

![image](https://user-images.githubusercontent.com/13319608/43550394-5786b840-95db-11e8-9798-f4a15f9560a2.png)

I sound like I'm clutching on straws here but is there a link between why the spinner GIF has the `NB-error` class appended to it and why ingestion is slow?

**Comment by samuelclay** [comment]
You'll want to run the node server for real-time updates. Also, stories will update faster if you run `./manage.py refresh_feeds -u username`.
