### ISSUE TITLE
Web: Add preference for image preview on left

### ISSUE THREAD

**Issue by kwoxer** [samuelclay/NewsBlur#1124]
I cannot find a way to bring the images in the List View in Desktop Browser from the right to the left side.

As You can see from the image it would be way better and would improve readability of the whole feed when look at the images besides the text instead of moving the eyes far far away.

![2018-09-07 16_14_03- 1 250_83 newsblur - firefox developer edition](https://user-images.githubusercontent.com/1167229/45224026-34d70200-b2b9-11e8-9f21-3760791f55d7.png)

If not possible right now, would it be possible to add it as a setting. Thank you so much.

**Comment by nriley** [comment]
Agree this makes sense. I don't use List view (it looks fine in Split view) but the other problem is that the dates don't line up if only some items have images.

![image](https://user-images.githubusercontent.com/68303/45224212-6505ad00-b287-11e8-8415-897406591228.png)

**Comment by kwoxer** [comment]
I don't like the Split view because I more like to read to article on the actual website :)

But indeed that date viewing issue should also be fixed tho.

**Comment by samuelclay** [comment]
That's strange, it looks fine to me on both List and Split view. An option to move images to the left is something I'd consider.

![screen shot 2018-09-07 at sep 7 1 31 50 pm](https://user-images.githubusercontent.com/44229/45233995-6ee8d980-b2a2-11e8-863f-03f91e577935.png)
![screen shot 2018-09-07 at sep 7 1 31 26 pm](https://user-images.githubusercontent.com/44229/45233998-6f817000-b2a2-11e8-814b-c37209eaac94.png)

**Comment by kwoxer** [comment]
Indeed @samuelclay I'm also not able to reproduce the date issue from @nriley .

Anyway I mentioned that in the Split View there is the same issue (at least for me) with a bad placement of images.

So yeah it's totaly nice to have. Would be awesome to have.

Thank you anyway for this great project. Feel free to close here and update here when you have time to fix this. All the best.

**Comment by nriley** [comment]
@samuelclay The layout issue I saw seems to happen immediately after changing from Split to List view. If I refresh the view it's fixed.

**Comment by kwoxer** [comment]
I cannot reproduce this @samuelclay . Maybe you have a special browser version or feature enabled?

**Comment by nriley** [comment]
OK, a bit more testing — with Safari and Chrome with current release NewsBlur:

1. Set NewsBlur to Split or Full view.
2. Reload NewsBlur.
3. Click List.

If NewsBlur started out in the Grid view, or was in List view to start with, then you can switch from other views to List without a problem.

**Comment by samuelclay** [comment]
This has launched on beta.newsblur.com. It's also the new default layout, combined with Split view and stories on Left.
<img width="639" alt="Screen Shot 2021-05-13 at May 13 7 27 11 PM" src="https://user-images.githubusercontent.com/44229/118199478-3ae5ef00-b421-11eb-8486-720b55b0d30e.png">
