### ISSUE TITLE
App: Compared to Feedly and InoReader image loading is not performant

### ISSUE THREAD

**Issue by kwoxer** [samuelclay/NewsBlur#1125]
As the title says, this is about reading Feeds on the Smartphone app. 

I really like the small image View. All the big Feed Reader (Feedly, InoReader and Newsblur) having this view and it's pretty easy to compare how much is needed to scroll through the same Feed.

So round about I can say that the InoReader is taking the lowest bandwidth. Let me show that in a (round about) bandwidth comparison:
- InoReader 0,8 MB
- Feedly 2,2 MB
- NewsBlur 2,6 MB

Would it be possible to improve that view by serving compressed images or smaller images like InoReader does.

This is by the way the reason why I currently prefer InoReader. But I more like NewsBlur as it fits much better to my UX experience.

Thanks and hopefully it's not that hard to fix.

**Comment by dosiecki** [comment]
The design goal of the app is certainly to serve up feeds' content without altering it too much, which includes keeping images at their original resolution as chosen by publishers/authors.  Have you tried enabling downloading offline stories/images?  This will prefetch almost all content when you are on WiFi (or your selected network type of choice) and vastly reduce how much bandwidth is used while reading.

**Comment by kwoxer** [comment]
I see and this a good thing for sure. I totally understand that there is no real will to change that.

Alright so I noticed I didn't have the settings (fetch stories/images) enabled. My fail.

So now they are enabled but I'm not quite sure what to check in the Download Using section. Is it **Unmetered Wifi or Ethernet Only** for denying downloading(fetching) without Wifi network. Am I right?

**Comment by dosiecki** [comment]
Yes, that default setting (unmetered WiFi / ethernet only) will only allow prefetch when on such unlimited-style networks. Images will still be loaded on demand regardless of network if they weren't cached, of course.

**Comment by kwoxer** [comment]
Great, issue solved with that solution. Thanks.
