### ISSUE TITLE
Android: Failing WebView Loads

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#1126]
Since approximately the rollout of Android 6, the system WebView component used by the app has increasingly been failing to load the HTML we pass to it.  This appears to happen across a fairly broad sample of devices, especially newer ones.

The failure can manifest in one of two ways: either the story never renders at all and the resulting viewport is zero-height, or the WebView appears to have loaded something, setting itself a height that appears correct but stays visibly blank.

Re-setting the story HTML will generally (but not always) succeed.

These failures to load do seem to be reported back to us via the WebView error hooks.  However, the error codes reported are the same as the ones used any time a single page component fails to load (such as a missing image).  As a result, the error callbacks alone are insufficient to identify the situation without a large number of false positives.

HTML blocks featuring images appear to be affected more then text-only content.

Since the WebView component provided to us varies wildly across devices and is mostly a black box, we don't have a great deal of control surface to tune or change.  I will add some investigation ideas and potential workarounds in the comments.

**Comment by dosiecki** [comment]
Intereting update: some time in the last few updates of the Chrome WebView component from the Play Store, my devices let me fix these missing webview loads by simply tapping on the blank screen where the story should be.

No new logs from the webview component, and no relevant-looking items in the chromium release notes, but a possible work-around for folks who keep their devices up-to-date.

**Comment by dosiecki** [comment]
Not much progress on this, since we're still dealing with the black box platform browser widget.  However, I believe I have discovered a device that does this 100% of the time, the LG G7 runing ROM v8.0.0bOPR1.170623.032.  Hoping this may assist in future debugging efforts.

**Comment by PKRoma** [comment]
Maybe the app could be updated to record the version of WebView used and it could be included in the feedback, like from my device below, which exhibits the problem?

app version: 8.0.0
android version: 9 (PQ2A.190405.003)
device: Google Pixel 3 XL (crosshatch)
sqlite version: 3.22.0
username: PKRoma
server: default
memory: normal
speed: 271 feeds in  conn:1338 read:19 parse:28 store:30
pending actions:  pre:0 post:0
premium: no
prefetch: no
notifications: no
keepread: no
thumbs: yes
