### ISSUE TITLE
Unread stories are prefiltered - how to see all unfiltered stories

### ISSUE THREAD

**Issue by kwoxer** [samuelclay/NewsBlur#1127]
As it's easier to see from images here are images of NewsBlur and InoReader. In a nutshell, the Inoreader shows the correct number of unread stories, but NewsBlur does not.

Both Feed Reader are marked unread yesterday at the same time.

NewsBlur:
See the yellow stories, that are somehow prefiltered (marked as read).
![2018-09-08 08_44_36-window](https://user-images.githubusercontent.com/1167229/45251296-f5092c80-b343-11e8-80ff-3b11d5efb5ce.png)

InoReader:
The correct number of stories (nothing marked as read).
![2018-09-08 08_45_16-window](https://user-images.githubusercontent.com/1167229/45251297-f5092c80-b343-11e8-8de7-5ae0705d5b0f.png)

It seems that the feeds are somehow prefiltered. Maybe it's marked as unread by relevance somehow? But I don't want NewsBlur doing this. How can I disable this feature and see my feeds unfiltered. Thanks.

**Comment by samuelclay** [comment]
I believe you have stories being filtered out using the Intelligence Trainer. Can you right-click on the feed title and go to the trainer and see if anything is in red? Alternatively, do you see a "Show Hidden Stories" button at the top?

**Comment by kwoxer** [comment]
Indeed I accidentially used the intelligence Trainer. But on that feed there is nothing red anyway.

I cannot find a way to disable that Trainer. Where is that global disable setting placed? Thanks.

**Comment by kwoxer** [comment]
Sorry but I tested so much. I cannot get the same number of stories as in  InoReader.

InoReader always has more stories. Somehow Newsblur always filters, also when the Intellegence feature i disabled.

This is so strange. Also currently it seems as if the servers are a bit laggy. I cannot really save settings of my feeds. Also I have a special RSS Feed (http://hukd.mydealz.de/rss/hot) that cannot be added somehow.

I really want to use NewsBlur, but it's too buggy right now =(

**Comment by samuelclay** [comment]
Looks like 
http://hukd.mydealz.de/rss/hot is http://www.newsblur.com/site/1496997/mydealz. I added it and it popped up immediately. As for the other feed, can you tell me the title of stories that you don't see? What's your username, I'd be happy to take a look.

**Comment by kwoxer** [comment]
Puh, ok it's so damn hard to compare als NewsBlur and InoReader are not sorting the same way. I tried to make it a bit clearer with colouring the stories. 

**Differences between Feed-Reader**
As you can see, some of the not coloured InoReader stories are missing in NewsBlur. Best Examle is the "Goldene Kamera...". This is not appearing in Newsblur. In InoReader I can access the story on Spiegel website. So it's not deleted.

Another issue might be that some of the stories might have been updated? That's why there are multiple of the same in InoReader, right? 

![grafik](https://user-images.githubusercontent.com/1167229/46200988-54d76f80-c313-11e8-9d28-1977e4a10100.png)

**Comment by kwoxer** [comment]
Hey @samuelclay could you help me on this issue? Or just tell me the reason for this. Maybe I can find a workaround on this. Thanks.

**Comment by samuelclay** [comment]
Oof this is a hard one. I'm not sure I can help you because when I attempted to download the feed, every story showed up that was in the feed. Not sure what NewsBlur is doing, but it's not deleting stories until they fall off the bottom.
