### ISSUE TITLE
iOS 12:  Shared stories (Newsblur Logo) button missing

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#1128]
In iOS 12, the "shared" button (aka the Newsblur logo) in the top left corner of the UI on the main screen is missing (indicated by the red circle in the attached image).  It appears to be a layout issue, at least on my iPhone X and iPad Pro 12.9", as while the view animations from a story back to the main screen, it shows briefly before it disappearing again.

It's also worth noting that the activity button (the pulse graph icon on the far right) is also horizontally compressed, implying that something is going on with the layout of the toolbar.

I use this feature daily to show my wife some interesting stories I've shared, so it's an important feature to me.  Thanks!

![img_1403](https://user-images.githubusercontent.com/3717537/45694394-2c8a8c80-bb2d-11e8-8ee0-ce3f3b5caa3d.jpg)

**Comment by samuelclay** [comment]
Yep, noticed this, too. We'll get it fixed.
