### ISSUE TITLE
iOS 12: Locking device while playing a video from a story over AirPlay stops the video

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#1129]
Every day I save YouTube videos on my computer and iPad in NewsBlur, and every morning and evening I stream them to my AppleTV from my iPhone X via AirPlay ("Screen Sharing", whatever it's called today).  In the past, this worked great, but with iOS 12 it seems that when the iPhone locks (manually with the side button or through the auto-lock setting), the video stops playing.  As you can imagine, this makes it hard to watch videos -- I either have to tap the screen periodically to keep it awake, or turn off auto-lock.  It's made worse by the fact that after unlocking the device, the video often jumps back a minute or two instead of continuing to play back from where it stopped.

A secondary "issue" is that playing video doesn't automatically go full screen.  This is minor, since I can just tap the "full screen" button after the video starts.  Removing that extra step would be nice, but the fact that locking the device stops AirPlay video playback is a much bigger concern for me.

Thanks!

**Comment by samuelclay** [comment]
Interesting, we'll take a look!
