### ISSUE TITLE
iOS: Add link to privacy policy and terms of use to premium upgrade dialog

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1135]
Apple rejected the app stating that those two links need to be present. Can we design an attributed string that says "See NewsBlur's [privacy policy] and [terms of use] for details." and link to newsblur.com/privacy and newsblur.com/tos.

**Comment by samuelclay** [comment]
Add the attributed string right below the subtitle paragraph and above the subscription price

**Comment by Dejal** [comment]
Sure, I'll do that right now.  Putting the text (and links) between the purchase policy text (... "Cancel at any time from Account Settings in iTunes.") and the products table might be better, since it's grouping the policies.  It'd also be significantly easier, which of course is less important.
