### ISSUE TITLE
iOS: Feed list shouldn't scroll to top on reload

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1139]
One issue I’ve noticed is that the feed list scrolls to the top before the syncing stories step. I often find myself scrolling down the feed list and being yanked back to the top.

**Comment by samuelclay** [comment]
There's also something bizarre going on with folder titles when opening the app. I see this every time I use the app and it's hurting my eyes. I think the folder title ghosting into place was a bug I introduced a while ago, but now it's being triggered multiple times when refreshing the feed list.

**Comment by samuelclay** [comment]
I'm going to push out a release after this bug cause it's so annoying.

**Comment by Dejal** [comment]
I'd like to fix this, but can't reproduce it.

To clarify, is this on iPhone or iPad?

So you launch the app, it starts fetching updates, you scroll down the feeds list, and it jumps back to the top when fetching completes?

Can you perhaps attach a screen recording showing it? That might help.

**Comment by samuelclay** [comment]
Here you go, multiple drawing issues in this video, mostly around folder title positions. 

https://www.dropbox.com/s/oah7avt1nz048si/ScreenRecording_11-11-2018%2014-06-50.MP4?dl=0

**Comment by samuelclay** [comment]
The feed list shouldn't bounce or move on pull to refresh (the search bar jumps in and out). The feed list also draws from below on load. And lastly, folder titles are offset incorrectly when scrolling and the pull-to-refresh spinner is visible.

**Comment by samuelclay** [comment]
There's more to this issue. See this video. I force-closed the app just before I ran this video.

https://www.dropbox.com/s/u9zsgwd34wx19bg/newsblur-ios-folder-title-jumping.MP4?dl=0

**Comment by Dejal** [comment]
I have no idea what is going on there.  I can't reproduce that behavior on my iPhone, iPad, or the simulator. I wonder if it's account-specific, somehow; is it something that only happens with your account, or others? If you can give me access to a test account that demos it, I should be able to trace it. Otherwise, I'll look through the code and see if I can spot anything that might do that, but I wouldn't be hopeful.

**Comment by samuelclay** [comment]
Go ahead and login to my account (username: samuel). You should have access, yeah?

**Comment by Dejal** [comment]
I seem to recall there's a way to access that, but I forget where.

**Comment by Dejal** [comment]
Okay, I found the Login As command, but the server gives error 500 when I try to log in as you.

**Comment by Dejal** [comment]
I get that error when logging in to my own test account, `DejalTest`, too.  So either the feature is broken, or you have the server hardwired to only accept it from your account.  If the latter, please authorize my main `Dejal` account for that feature.

**Comment by samuelclay** [comment]
Just added you as staff.

**Comment by Dejal** [comment]
Thank you. Good news: I can reproduce the issue when logged in to your account. Let's see if I can trace it....

**Comment by samuelclay** [comment]
Between "Counting" and "Syncing" the feed list is moving up to hide the search bar. Can we either hide the search bar initially or not have it hide later? I want to stop having the feed list move.

**Comment by samuelclay** [comment]
Also, sometimes when I return to the feed list (usually while it's still loading and I've entered a feed and then returned to the feed list), I see this.

![img_bf2769e4694a-1](https://user-images.githubusercontent.com/44229/48500702-73cd8a80-e809-11e8-8245-1065a8636fbd.jpeg)

**Comment by nriley** [comment]
Similar issues happen with the story list; you end up with an unwanted search bar way pretty much all the time.

Can confirm that the folder title ghosting seems to be much better now, however folder title animations seem to be rather strange (e.g. when I switch between "ALL" and "UNREAD"); the top of the list doesn't seem to stay 'stuck' to the top of the scrollable area when going from fewer to more folders, whereas going from more to few folders, there's no animation at all.

For example:

https://sabi.net/temp/newsblur-all-unread.mov

**Comment by Dejal** [comment]
I've changed it so the search bar remains visible. It might be a little tidier to hide it, but that has issues when there are few visible rows, so keeping it visible has a more consistent experience. I can't reproduce the too-far-scrolled issue, so that might be fixed too, but I can't be sure. I'll leave this issue open for now.

**Comment by nriley** [comment]
On iPad the search bar doesn't appear on the right side initially, but does after you swipe to reload.  I'm surprised (maybe I shouldn't be given my own painful experience with UITableView?) that it's so hard to make it work when pretty much every other app I use frequently auto-hides its search bar.

Also, now there are search boxes everywhere, the inconsistent height of the top/bottom bars on the main screen becomes pretty glaring on iPad.  The left sided bars are standard iOS sizes (at least they match Mail) but the right sided ones aren't; it might make sense to enlarge the right sided ones.

Also reminds me there's an icon sizing issue with the generic blurblog icon, but should probably file another issue for that!

![screen shot 2018-11-25 at 10 50 10 am](https://user-images.githubusercontent.com/68303/48981177-3e922980-f0a0-11e8-946a-0f2cff1173ca.png)

**Comment by Dejal** [comment]
I've fixed the misalignment issues in #1151, which adds compatibility with the new iPad Pros, by converting the dashboard to use auto-layout.

Re search fields, I could either do some more work on hiding the feeds list search field (which may take a while), or always show the feed list search field (which would be quick).  Sam, please let me know which you'd prefer.

Hiding it is complex, for one reason the pull-to-refresh will show it, so I used to animate it away, which caused more scrolling. And other issues.

**Comment by samuelclay** [comment]
I'm happy with the search bar being visible, so long as it doesn't move. I tested it out and it's looking a lot better. I did notice a weird scroll lag but I'm not sure if anybody else has seen it. And I haven't seen it again.
