### ISSUE TITLE
Fetch more than 25 Stories at once

### ISSUE THREAD

**Issue by dougbrose** [samuelclay/NewsBlur#1141]
Does anyone know how to fetch more than 25 stories?  I'm self-hosting a version so that I can grab really large (academic) rss feeds.  They will have 100s of new stories each day.  Every time I run the command below from cron it only adds 25 stories.  I run it several times a day, but then I miss about 1/2 as new ones come in.

/opt/NewsBlur/manage.py refresh_feeds --user=doug --force

Thank you

**Comment by samuelclay** [comment]
Thanks for the idea! I added `settings.OVERRIDE_STORY_COUNT_MAX`.
