### ISSUE TITLE
Text view for phoronix.com is incorrect

### ISSUE THREAD

**Issue by desbma** [samuelclay/NewsBlur#1147]
Text view for the phoronix.com feed (http://www.phoronix.com/rss.php) shows the whole feed instead of just individual articles.

**Comment by samuelclay** [comment]
NewsBlur uses the Mercury Parser, which takes pull requests. A NewsBlur user has submitted pull requests to them before and I've integrated those changes, so I'd be happy to do it again.

https://github.com/postlight/mercury-parser
