### ISSUE TITLE
iOS: Login-as returns bad data

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1148]
When using the Login As staff function in the iOS app, the server returns success (`200`), but includes invalid (missing?) data, so the app reports an error, even though the operation really succeeded.

The error message is:

```Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/html, NSErrorFailingURLKey=http://www.newsblur.com/, com.alamofire.serialization.response.error.data=<0a3c2144 4f435459 50452068 746d6c3e 0a3c6874 6d6c3e0a``` ...

**Comment by samuelclay** [comment]
Seems only broken on iOS. It returns a redirect to the homepage. iOS should ignore that are just refresh the feed list.
