### ISSUE TITLE
iOS: Mark stories read on scroll doesn't work while page is loading

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1149]
As I scroll story titles they are getting marked as read. But when a page is loading stories aren't being marked as read. I have to wait until the network request completes before stories are marked as read on scroll again.

**Comment by Dejal** [comment]
I'm not sure exactly what you mean (iPhone or iPad, which views). Can you please provide a screen recording showing it?

**Comment by samuelclay** [comment]
Both iPad and iPhone. Do you have the network link conditioner? Turn it on to 99% loss so every request takes 10 seconds to complete. 

If that doesn't work, add `?delay=5` to a single feed page request and it will insert a 5 second delay on a single feed page load. That way you can see it yourself. Notice that stories aren't being marked as read on scroll while a page of stories are being loaded (the blue fading load bar is visible).
