### ISSUE TITLE
docker-compose fails to build, error 137

### ISSUE THREAD

**Issue by kylegoetz** [samuelclay/NewsBlur#1153]
after git clone, I run `docker-compose up -d` and it begins to build as expected. But it errors out eventually and fails to build. Here's the tail of the output:

    Collecting python-gflags==3.1.0 (from -r requirements.txt (line 45))
      Downloading     https://files.pythonhosted.org/packages/82/9c/7ed91459f01422d90a734afcf30de7df6b701b90a2e7c7a7d01fd580242d/python-gflags-3.1.0.tar.gz (52kB)
    Collecting pytz==2018.3 (from -r requirements.txt (line 46))
      Downloading https://files.pythonhosted.org/packages/3c/80/32e98784a8647880dedf1f6bf8e2c91b195fe18fdecc6767dcf5104598d6/pytz-2018.3-py2.py3-none-any.whl (509kB)
    Collecting raven==6.5.0 (from -r requirements.txt (line 47))
      Downloading https://files.pythonhosted.org/packages/33/b3/d626d5136de3a5b7bf99a98cb983261baee30320fa220f7a5726dcafefbd/raven-6.5.0-py2.py3-none-any.whl (281kB)
    Collecting redis==2.10.5 (from -r requirements.txt (line 48))
      Downloading https://files.pythonhosted.org/packages/08/c1/457428f7507e27ba7144758a7b716ea35766e6d602f4a0c16e443ab3d381/redis-2.10.5-py2.py3-none-any.whl (60kB)
    Collecting requests==2.20.0 (from -r requirements.txt (line 49))
      Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl (60kB)
    Collecting scipy==0.18.1 (from -r requirements.txt (line 50))
      Downloading https://files.pythonhosted.org/packages/13/cb/8e74d28e1519b34636e4d985d49d01c23778064e01eb102914f844cd6051/scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl (40.3MB)
    Killed
    ERROR: Service 'newsblur' failed to build: The command '/bin/sh -c set -ex           && rundDeps='                   libpq5                   libjpeg62                   libxslt1.1                             '           && buildDeps='                     patch                     python-dev                     gfortran                     lib32ncurses5-dev                      libblas-dev                     libffi-dev                     libjpeg-dev                     default-libmysqlclient-dev                     libpq-dev                     libreadline6-dev                     liblapack-dev                     libxml2-dev                     libxslt1-dev                     ncurses-dev                     zlib1g-dev                             '             && apt-get update             && apt-get install -y $rundDeps $buildDeps --no-install-recommends             && pip install -r requirements.txt             && apt-get purge -y --auto-remove ${buildDeps}             && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 137

**Comment by kylegoetz** [comment]
Because the RUN is one long series of commands &&'ed together, I don't know where the 137 is coming from. I'm assuming in the pip install.

**Comment by samuelclay** [comment]
We're working on rewriting the docker installation right now and will have this done soon. Watch #1316 for updates.

**Comment by samuelclay** [comment]
Try the `docker_dango3.0` branch which has fixed all of the known Docker issues.
