### ISSUE TITLE
iOS: vertical story scrolling should have full screen interactive gesture to go back to story titles

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1157]
So for the new vertical scroll option we launched a few months ago I’d like to have interactive horizontal gestures that let you slide the story detail view back into the story titles view. Obviously this isn’t possible with the horizontal scrolling preference.

**Comment by samuelclay** [comment]
Looks like this change may have disabled interactive swipe back on all views?

**Comment by samuelclay** [comment]
Why is the interactive swipe disabled on the story detail page? I'd like it on all screens, esp. this one. Can we restore it and make it more reliable? For some reason it was trickier to begin an interactive swipe gesture on full screen. It worked, but only when you consciously hit the very edge of the screen. Can we increase that region to match the system level region for interactive swipes?

**Comment by samuelclay** [comment]
When in full screen the swipe back gesture doesn't work. It used to as of a week ago but now it's no longer working, even with this latest commit.

**Comment by Dejal** [comment]
Yeah, I could have sworn it did, too, even for horizontal story paging, though I'm not sure. I tried rolling the code back to that commit, and it still didn't work. I wonder if it was broken by the recent iOS update? Maybe you could try that previous commit to confirm that.

*[Meta comment: I will be on vacation for the next week, so won't be able to do more till after that.]*
