### ISSUE TITLE
iOS: Preserve story for backgrounding

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1160]
Basically just return to the last feed/folder > story > story scroll position when starting the app. Would be nice if we had a choice preference for "Return to last story [on/off]" so you could turn this feature off (status quo), but default it to on.

**Comment by samuelclay** [comment]
Some discussion on the forum: https://forum.newsblur.com/t/internal-browser-state-is-often-lost-when-app-is-backgrounded/5291/6

**Comment by Dejal** [comment]
This is related to issue #1173.

The ideal solution for both would be to implement state restoration, so the app relaunches in the state it was last used, or as close as possible.

Not a trivial undertaking, given the complex nature of the views, but perhaps worthwhile.

For the preference, it might make sense to have a time limit, e.g. only restore the state if within 24 hours, or similar. That could be a preference, perhaps with options like Never, Within 24 Hours, Within 12 Hours, ..., Always.

**Comment by samuelclay** [comment]
Love the preference for this. It's something I know I wish I could change in other apps.

**Comment by Dejal** [comment]
Now supported for iPhone; iPad support will be added later, so I'll leave this open for now.

**Comment by samuelclay** [comment]
Can we increase the max from 1 day to 1 week? I find that I check NewsBlur once or twice a day but it doesn't preserve my location perfectly yet. I have a feeling it's just taking too long between refreshes.

**Comment by Dejal** [comment]
The maximum already is 1 week (or never). You might need to scroll to see that option if you're using a small screen.

**Comment by samuelclay** [comment]
So I'm having some difficulty getting this feature to open the right story or reload the river. When I'm looking at a story list and leave the app, when I return the feed/folder isn't always reloaded. Sometimes it is, though.

Secondly, when I'm looking at a story, if the feed has lots of stories, the story is gone and I'm on some random story, which is not a good experience. I'd rather kick the user back out to the feed list than load them on to the wrong story.

**Comment by Dejal** [comment]
If you force quit the app, it doesn't do state restoration.

I've changed it to pop to the feed detail if the story isn't available, instead of loading the next unread one as before.
