### ISSUE TITLE
Android: "Loading..." text but story doesn't load. Tapping out then in shows the story.

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1163]
Tell us a bit about your problem:

It often happens that I open an article, but only see the text "Loading..." forever (or longer than I'm willing to wait). But in those cases, tapping the Back button and trying again makes the article show up immediately.

The attached log is from this sequence of actions:
- open article, see loading
- tap back button
- tap article again
- tap article title to open in browser (this particular feed is incomplete)
- switch back to NewsBlur
- hit back a few times and pull up the bug report thing from the menu

Sorry if there is too much log spam; I can make a cleaner version if needed.

The extra weird thing is that I've got Download Stories enabled and am on a reliable 50 Mbit internet connection. Even the article's preview image is shown in the article list. So whatever is"loading", if anything, is probably not coming from the internet.

I'm an Android developer myself, so if there's anything I can do to help debug this annoyance, please let me know!

app version: 9.0b1
android version: 6.0.1 (M4B30Z)
device: LGE Nexus 5 (hammerhead)
sqlite version: 3.8.10.2
server: default
speed: 154 feeds in  conn:781 read:98 parse:97 store:216
pending actions:  pre:0 post:0
premium: yes
prefetch: yes
notifications: no
keepread: no
thumbs: yes

**Comment by dosiecki** [comment]
Would need to see the actual bug report logs to do much on this one.  I suspect that the beta version (which GOOG has forced us to target towards increasingly newer device versions) may not be playing nicely with older ROMs.

**Comment by samuelclay** [comment]
Hey @sictiru are you able to reproduce this issue?

**Comment by sictiru** [comment]
@samuelclay I'm not able to reproduce this issue. The only time this happened to me was during development for the Android Widget but that was solved before release. Are there new reports on this?

**Comment by samuelclay** [comment]
Seems so: https://forum.newsblur.com/t/twitter-images-dont-load-on-android/8248/9?u=samuelclay

**Comment by sictiru** [comment]
Loading feeds logic was refactored a bit in 2022 and since there are no new recent reports or observations, the ticket is being closed.
Feel free to reopen if there are new occurrences as of 2023.
