### ISSUE TITLE
Android: Posts with block quotes showing up incorrectly

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1164]
Posts beginning with a list or block quote (and maybe others) sometimes aren't fetched properly. Blurbs in feed view properly show post content, but some comment (not necessarily the first one) or sidebar is displayed when a post is opened.

I've noticed this behavior on a few feeds, but it happens most often on Marginal Revolution (https://marginalrevolution.com/).

Block quote example:
Do moving and making big decisions tend to happen together?
September 25, 2018 at 2:27
Some comment is displayed.

List example:
Monday assorted links
September 24, 2018 at 2:17 pm
Sidebar is displayed. 

app version: 8.0.0
android version: 8.0.0 (R16NW.G930PVPS7CRH2)
device: samsung SM-G930P (msm8996)
sqlite version: 3.18.2
server: default
memory: normal
speed: 99 feeds in  conn:789 read:10 parse:28 store:51
pending actions:  pre:0 post:0
premium: yes
prefetch: no
notifications: no
keepread: no
thumbs: yes

**Comment by dosiecki** [comment]
This sounds like our story CSS override needs a tweak, but we'd need a specific feed URL and story ID that repros.
