### ISSUE TITLE
Gravatar: Uses old e-mail on front-page

### ISSUE THREAD

**Issue by julemand101** [samuelclay/NewsBlur#1170]
It looks like there are some bug in the calculation of the MD5 sum for Gravatar on the front-page:
![image](https://user-images.githubusercontent.com/116227/53103385-d5e70b80-352d-11e9-9138-d815b269b55e.png)

When looking into account settings I have the following for my mail:
![image](https://user-images.githubusercontent.com/116227/53103433-ec8d6280-352d-11e9-9ba8-0b7c54d0adcd.png)

I can see the Gravatar icon points to the following page:
https://www.gravatar.com/avatar/5e1edee6f5c779f92df32ce2723c2d07

Which is not the correct MD5 sum for my Archlinux.dk mail:
echo -n julemand101@archlinux.dk | md5sum
50b08d90afd96271299a4dc0fcf672f2  -

Instead, I can see the MD5 sum are for my old E-mail:
echo -n julemand101@gmail.com | md5sum
5e1edee6f5c779f92df32ce2723c2d07  -

The strange thing is that in the following window I got the correct Gravatar (which points to 50b08d90afd96271299a4dc0fcf672f2):
![image](https://user-images.githubusercontent.com/116227/53103695-5d347f00-352e-11e9-92b3-44fa951c5b29.png)

So it could seem that Newsblur does not change my E-mail in all places in the backend when I change the mail in the Account page.

I have tested on multiple computers, multiple browsers and in incognito mode.

**Comment by samuelclay** [comment]
Thanks for posting such a thorough writeup! It made it easy to find and fix the issue. I also fixed your account so it should now be accurate.
