### ISSUE TITLE
iOS: Autoscroll

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1171]
I’d love to build a feature for those exercising. I’d like to see the page auto scroll after you toggle it, per story, from the story detail view’s settings menu. Of course it should use the new full screen feature, regardless if it’s enabled for all stories. And that frees us up for a scroll speed toggle. How about a set of + - buttons similar to the story traversal buttons, and they only appear on tap and fade out after 1 sec.

**Comment by Dejal** [comment]
Interesting idea! Sounds like you want it only be on for an individual story, so when you go to the next story it has to be re-enabled? That could be annoying. Maybe if autoscrolling was enabled before, it could show an AUTOSCROLL button above the traversal buttons, and if tapped, it starts auto-scrolling. Or if ignored, it fades out.

The + - buttons should probably also have a STOP or PAUSE (icon) button, which toggles to a START (play triangle icon) to resume.

**Comment by samuelclay** [comment]
Looking really good! I noticed that you can't scroll with your thumb around the autoscroll buttons when they are visible, including all the way to the side of the view

**Comment by samuelclay** [comment]
Looks like the autoscroll controls don't work on iPad. I touch them but they don't engage.

**Comment by Dejal** [comment]
Looks like it doesn't get the tap when over an image. It works when over text, so manually scroll a bit as a workaround. Will fix.

**Comment by samuelclay** [comment]
This autoscroll control is moving around quite a bit on iPad.

**Comment by Dejal** [comment]
It moves between two locations, as mentioned in the commit:

> - Tweaked the autoscroll controls position on iPad to line up with traverse when visible, or go a bit higher when not (to avoid the home indicator).

That seems best to me, but I could keep it at the bottom if you don't like that.

**Comment by samuelclay** [comment]
But it seems to move (in landscape orientation) randomly as I swipe between stories.

**Comment by samuelclay** [comment]
It also hit the bottom of the screen, then reappeared above the controls, but in landscape it should have plenty of room.
