### ISSUE TITLE
Android: Autoscroll

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1172]
Like it says on 
https://github.com/samuelclay/NewsBlur/issues/1171

**Comment by sictiru** [comment]
@samuelclay Is this a feature that we still want to add support for?

**Comment by samuelclay** [comment]
Nah, nobody is asking for it but me.

**Comment by samuelclay** [comment]
I still use it on iOS but until somebody on Android wants Autoscroll let's punt on it.
