### ISSUE TITLE
iOS: Address memory issues causing app to be killed when in background

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1173]
People lose their story positions on a quick jump out of the app. Only memory issues can cause this I believe. So can we hook it up to Instruments and diagnose whatever is causing the OS to kill the app?

From this thread: https://forum.newsblur.com/t/ios-app-reloads-on-ipad-losing-current-story/6515/7

**Comment by Dejal** [comment]
This is the same as issue #1160. It probably isn't a memory issue with NewsBlur, but other app usage causing inactive apps to be evicted from memory.  See discussion there.
