### ISSUE TITLE
Remove Kippt from social sharing services

### ISSUE THREAD

**Issue by d2s** [samuelclay/NewsBlur#1174]
_Sharing services_ -section on the Preferences still has Kippt as an option,
even while that service was closed down in September 6, 2015.

<img width="527" alt="2019-03-04-newsblur-issue-kippt" src="https://user-images.githubusercontent.com/135053/53759469-16993a00-3ec9-11e9-850d-f7c6e4ad6e0d.PNG">

> "Since 2014 we have moved work on other projects and decided to keep Kippt running for people still using it. You can read more from our blog post. As time has gone by, our energy towards maintaining Kippt has gone down and the cost of running the service has gone up. With a heavy heart we have decided to end the journey of Kippt for now and shut the service down."

![screencapture-kippt-2019-03-04-21_47_58](https://user-images.githubusercontent.com/135053/53759588-5b24d580-3ec9-11e9-9dd2-9265ad6030f6.png)

_More details:_
- [Kippt is shutting down](http://kippt.com/) message on the front-page of the service from September 6, 2015.

## Code to be cleaned

Following Kippt related code should be cleaned out from the codebase.

### `reader_preferences.js`

https://github.com/samuelclay/NewsBlur/blob/c4bea0623dcaace02f634447832ae389ea19ad35/media/js/newsblur/reader/reader_preferences.js#L675-L677

### `reader.js`

https://github.com/samuelclay/NewsBlur/blob/96df94f8b44500d3cc8f0603b9d791e6a84d1021/media/js/newsblur/reader/reader.js#L2658-L2672

https://github.com/samuelclay/NewsBlur/blob/96df94f8b44500d3cc8f0603b9d791e6a84d1021/media/js/newsblur/reader/reader.js#L3714-L3718

https://github.com/samuelclay/NewsBlur/blob/96df94f8b44500d3cc8f0603b9d791e6a84d1021/media/js/newsblur/reader/reader.js#L3761-L3762

### `reader.css`

https://github.com/samuelclay/NewsBlur/blob/5e12fed81348b69bad3a4a64044d59c4881a8df0/media/css/reader.css#L7511-L7513

https://github.com/samuelclay/NewsBlur/blob/5e12fed81348b69bad3a4a64044d59c4881a8df0/media/css/reader.css#L7548

https://github.com/samuelclay/NewsBlur/blob/5e12fed81348b69bad3a4a64044d59c4881a8df0/media/css/reader.css#L7584-L7586

https://github.com/samuelclay/NewsBlur/blob/5e12fed81348b69bad3a4a64044d59c4881a8df0/media/css/reader.css#L10037-L10039

**Comment by samuelclay** [comment]
Thanks for the excellent writeup! Just finished it. You also could have submitted this as a PR (since you clearly got all the right places) and I would have accepted it.
