### ISSUE TITLE
iOS: iPad display oddities in split view when opening story permalink

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1177]
In split view, with NewsBlur at 33%, the app crashes when opening a story permalink.

**Comment by Dejal** [comment]
Sorry, I can't reproduce this. I assume you mean tapping the title when reading a story? Do you have it open in Safari, or one of the other browser options?

**Comment by samuelclay** [comment]
Looks good now.

**Comment by samuelclay** [comment]
Wait, there's still some display bugs when I open a story's permalink in split view and then back out to the story content. See screenshot.

![IMG_0046](https://user-images.githubusercontent.com/44229/56100519-9a423f80-5ee7-11e9-913f-4b56b13870f1.PNG)
