### ISSUE TITLE
Android: Bump Target SDK to 28

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#1178]
Per (https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html), GOOG's draconian rules about target API versions have once again been bumped.  The effort started in our 9.0_b1 alpha will need to be expanded to go up another few versions so we can actually push updates to production.

**Comment by samuelclay** [comment]
Hey, sorry I sent an email to you before seeing this ticket. Is there any way to prioritize this work for deployment this week or next?

**Comment by dosiecki** [comment]
As expected, bumping the target APIs to a version high enough that GOOG will accept our update for publication has broken quite a few things.  Mainly, since the newer APIs now prohibit the old style Service-based background sync we were using, we have to use the new JobService based background worker that I pushed up to master in a09e1e7.  However, as anyone who has built and used that code might notice, some of our hooks into launching the service in the forground trigger some incredibly bad UI lag on some devices.  I'm working to re-wire invocation to something we can fully control, but there are more than a few touch points required.

**Comment by caleb-allen** [comment]
As suggested, I'm picking this up where it was left off, and bringing the target to 28. Also looking into the UI lag to nail down what's going on.

**Comment by caleb-allen** [comment]
@dosiecki do you have any test cases that produce the UI lag you mentioned?

**Comment by samuelclay** [comment]
There's a test account called `android_speed` that you can login to. I believe the password is newsblur.

**Comment by samuelclay** [comment]
Oh, what's your username? I'll mark you as staff so you can login as any user necessary.

**Comment by dosiecki** [comment]
On May 8, 2019 3:45:18 PM PDT, Caleb Allen <notifications@github.com> wrote:
>@dosiecki do you have any test cases that produce the UI lag you
>mentioned?

Any build off master in the last few months should exhibit the issue on O or P devices. My prototype migration to JobService technically syncs under the new background service restrictions, but it spikes refresh latencies way past the jank threshold. I never had the resources to properly debug things, but I suspect that some step in the mechanism I used to enqueue background jobs hits the main thread, which causes the problem. A quick run through the thread profiler should give some great clues as to why. (our design runs almost nothing on the main thread when it is correctly implemented, as in the current production build)

**Comment by caleb-allen** [comment]
> Oh, what's your username? I'll mark you as staff so you can login as any user necessary.

@samuelclay it is caleballen

@dosiecki thanks! Much appreciated

**Comment by caleb-allen** [comment]
I've done a good amount of profiling, here's what I've got.

I'm not able to recreate any huge amount of lag on my Pixel XL on Q or the emulator, aside from a few dropped frames right around the redraw after the results arrive. That seems present on my 5.0 Samsung test device as well, though.

Specifically, the frames are lost after the `QueryCursorLoader.deliverResult` method is called and in turn calls the callback `FolderListFragment.onLoadFinished`. The subsequent JSON deserialization in adapting the data appears to be what's hanging up the UI thread for a dozen frames or so.

Another potential cause might be the system call to `startService`. The [docs](https://developer.android.com/reference/android/content/Context.html#startService(android.content.Intent)) say this

> Note: Each call to startService() results in significant work done by the system to manage service lifecycle surrounding the processing of the intent, which can take multiple milliseconds of CPU time. Due to this cost, startService() should not be used for frequent intent delivery to a service, and only for scheduling significant work. Use bound services for high frequency calls.

Although the frame drops I'm seeing are not at the start of the service. I've attached a GPU profiling from my Pixel, which shows that lag spike. The green horizontal line is 16ms, for reference.
![Screenshot_20190508-204712](https://user-images.githubusercontent.com/3279748/57424451-ee81cc00-71d4-11e9-91b1-2cc845116913.png)

Additionally, the Google Play console isn't indicating ANRs for the users that are running this. 

Besides the Cursor redraw, I am not seeing any extreme lagginess, and the threads appear to be behaving correctly. Am I off base here?

**Comment by caleb-allen** [comment]
With large datasets, that json deserialization happening on the UI thread might cause significant lag, although that shoudn't be affected by API level

**Comment by caleb-allen** [comment]
@samuelclay I continue to investigate, and am not finding any issues besides the above mentioned few dropped frames from the json deserializations (which I believe to be independent of API level). I'm also not seeing any user reports in the forums, or lag issues reported via Google Play on the beta track.

What are your thoughts on a progressive rolling release, including the fix #1179, with close monitoring of performance issues?

**Comment by samuelclay** [comment]
Sorry, I just emailed you! Yes, that'd be a great idea. Does that mean you'll update the manifest to the latest api version?

**Comment by dosiecki** [comment]
On May 15, 2019 3:37:15 PM PDT, Caleb Allen <notifications@github.com> wrote:
>@samuelclay I continue to investigate, and am not finding any issues
>besides the above mentioned few dropped frames from the json
>deserializations (which I believe to be independent of API level). I'm
>also not seeing any user reports in the forums, or lag issues reported
>via Google Play on the beta track.
>
>What are your thoughts on a progressive rolling release, including the
>fix #1179, with close monitoring of performance issues?

It is certainly possible that some of the latency issues have been improved on the platform side since we last had a chance to test the beta, so if things look fine for y'all, I certainly support doing a release.  

I'll be frank in that the newer API support I built last year is something of a partially conceived prototype, so there may be other bugs lurking. But I'll happily keep triaging bug reports as quickly as possible.

**Comment by caleb-allen** [comment]
Yeah, I'll push that shorty.

As far as the new API support, I've been poking at it a lot and haven't
found any glaring issues (so kudos on a greeat first pass!) but I'm hoping
a cautious rolling release will give us more confidence on the upgrade, and
user feedback for the more nuanced changes or bugs the upgrade is sure to
have with it

**Comment by caleb-allen** [comment]
@samuelclay if https://github.com/samuelclay/NewsBlur/pull/1190 is accepted we can begin the rollout

**Comment by caleb-allen** [comment]
We are getting some crash reports of `IllegalStateException` while attempting to start the sync service in the `onResume` of the main activity. All reports are from Android 9.

https://issuetracker.google.com/issues/113122354

Weird issue, looks like others are seeing it as well, just on Android 9.
