### ISSUE TITLE
iOS: scroll performance in feed list after viewing a feed

### ISSUE THREAD

**Issue by kemayo** [samuelclay/NewsBlur#1183]
In the iOS app, after viewing a feed, scroll performance when scrolling upwards in the feed list is extremely jerky. Scrolling downwards seems unaffected.

Video [here](https://www.dropbox.com/s/q8s69n6gngypk4p/newsblur%20scroll%20issue%20Mar%2031%2C%2011%2057%2045%20AM.MP4?dl=0).

Reproduction steps:
1. On feed list, scroll down
2. Tap to enter a feed view
3. Go back to the feed list
4. Scroll upwards, observe jitter

Seen on current release version, 8.1.

**Comment by samuelclay** [comment]
Yes, i've noticed this too! It's only on the feed list. We made the story list more performant, but we need to do something about this weird scrolling jitter.

**Comment by kemayo** [comment]
Oh, I should say after some further reflection, it does sometimes happen on the initial view as well, rather than just after viewing a feed. It seems far more consistent after the feed view, though.

**Comment by Dejal** [comment]
I can detect a very slight hesitation when scrolling down, perhaps around the saved stories, but not when scrolling up. I've tried profiling it, and temporarily avoiding some drawing, but haven't found any bottlenecks. I'll try again later, but if you can narrow it down at all, that might help.

**Comment by samuelclay** [comment]
I get this all the time. It only happens when "Counting is difficult" is happening (and the syncing stories step, basically just not the downloading stories/images step).

**Comment by Dejal** [comment]
Maybe my iPhone is too fast (it's an iPhone XS Max). The simulator doesn't help, either. Perhaps I should see if I can dig out an old device. The "counting" step takes less than a second, and does reload the table when done, which may have some impact on scrolling, but can't be avoided, and probably isn't the issue.

Can you record an example of what you see? That might help. If I can't reproduce it, all I can do is see what you experience, and try to narrow down the likely areas of the code.

**Comment by samuelclay** [comment]
I have an iPhone 7, fwiw.

**Comment by samuelclay** [comment]
https://www.dropbox.com/s/7do8ea1zcnsv1cf/2019-04-17%2022.51.27.mov?dl=0

Here's a video of it happening. Turn sout it happens during story downloading too. But I'm sure I've seen it during the regular syncing as well.

**Comment by Dejal** [comment]
That is very funky. I haven't seen anything like that. I just fetched my old iPhone 6 and installed NewsBlur and repeatedly scrolled up and down while it was syncing, and it scrolled very smoothly, without any jitters.

I wonder if it's caused by some preference? I can't think of any relevant ones, though.

**Comment by samuelclay** [comment]
Another user posted a video of it happening: https://www.dropbox.com/s/ymqfs5g6jl3eky1/RPReplay_Final1557694331.MP4?dl=0

**Comment by ryanjmorgan** [comment]
Also, I just did one on my iPad as well.  Launched the app and started scrolling and it was jittery...

https://www.dropbox.com/s/17321r6wh45ndrj/RPReplay_Final1557696959.MP4?dl=0

**Comment by Dejal** [comment]
I managed to reproduce this once, but not reliably. I'll keep trying.

I notice that all of the examples are in Unread mode; that is where I reproduced it, too. The next time this occurs, try switching to All and see if it still occurs, then back to Unread and try again. May be a coincidence, or may be a clue.

**Comment by samuelclay** [comment]
It's caused by hiding feeds. So my guess is that Focus mode should cause it to happen the most. I also subscribe to a ton of shared users and I keep that section collapsed, so it takes a while to scroll past.
