### ISSUE TITLE
Web: Completely disable Blurblog

### ISSUE THREAD

**Issue by medecau** [samuelclay/NewsBlur#1184]
Please allow users to completely disable BlurBlog feature.

Have NewsBlur behave the same way for disabled BlurBlog feature as with non-existing accounts. That is when someone requests <account_name>.newsblur.com have the request redirected to www.newsblur.com

**Comment by samuelclay** [comment]
Agreed, it would be nice to be able to opt-out of social features. Just make this a single preference on the web, below the hiding of public shares. This preference would remove the blurblog and hide the share buttons 

 * [x] Enable story sharing and comments
 * [] Disable story sharing and hide all comments
