### ISSUE TITLE
Rename feeds

### ISSUE THREAD

**Issue by epitron** [samuelclay/NewsBlur#1187]
A useful feature would be the ability to change the title of RSS feeds.

On rare occasions, a website that's hosting a feed gives it a strange title (overly verbose, underly verbose, overly vague, etc). It would be helpful if the client allowed me to rename it.

(There doesn't seem to be another issue about this, which is surprising to me. Maybe I missed it?)

**Comment by samuelclay** [comment]
You can do this today! Right click on a feed (or hit the little arrow) and rename it there. Same goes for the iOS and Android mobile apps: hit the settings button when inside the feed.

**Comment by epitron** [comment]
Thanks for the quick reply!

I don't seem to have a settings button in my Android app: https://0x0.st/zTkA.jpg

Is this because I'm using the f-droid build of NewsBlur?

**Comment by samuelclay** [comment]
You know, I don't remember the status of our f-droid build. Hey @caleb-allen, what do you know of f-droid?

**Comment by samuelclay** [comment]
Well, whoever is updating our f-droid entry, it's at the latest version now.

Version 8.0.0 (159) - Added on 2018-08-14

You know, I believe it's likely that we added Rename Feed for Android right after that version but it's still in beta and should be out of beta within the next few weeks.

**Comment by caleb-allen** [comment]
> You know, I don't remember the status of our f-droid build. Hey @caleb-allen, what do you know of f-droid?

I've used F-Droid, haven't deployed to it though.

Happy to keep F-Droid in parity with Google Play. Looks like that is managed through gitlab issues, by setting up builds for F-Droid to build and sign?

I'll be sure to see what can be done after this coming update.
