### ISSUE TITLE
Android: Several feeds missing from feed list

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1194]
See https://forum.newsblur.com/t/several-feeds-not-showing-up-in-android-app/7622

Receiving a handful of reports about this. I think you received the email with the specific sites that are causing the issue (in screenshots). I can send those if you'd like.

**Comment by caleb-allen** [comment]
@samuelclay this has been resolved, correct?

**Comment by samuelclay** [comment]
Think so!
