### ISSUE TITLE
Android: Story traversal progress bar is inaccurate in folders

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1199]
That circular progress bar embedded in the Next Story button looks like it is inaccurate when reading by folder. Tapping on it also shows the wrong count.

**Comment by idontusenumbers** [comment]
This happens in "all stories" for me

**Comment by caleb-allen** [comment]
@idontusenumbers does the issue go away if you re-sync, and then click back into the folder (might need to try a few times)?

The cause might be the local reading session carrying over unreads from bad places, and a sync would clear that. Still, the queries will need to be looked at if that's the case

**Comment by idontusenumbers** [comment]
## How to skip a JavaBean property
Sometimes there is a need to avoid dumping some JavaBean properties.

Use the `@Transient` annotation on the getter:
```
import java.beans.Transient;

class MyBean {
	private int value;
	
	public MyBean(int value) {
		this.value = value;
	}
	
	@Transient
	public int getValue() {
		return value;
	}
	
	public void setValue(int value) {
		this.value = value;
	}
}
```

The requirement may be dynamic, based on the value of the property. For instance empty collections or 'null' values should not be dumped (serialized). This is an example how it can be implemented:

    class PointRepresenter extends Representer {

        @Override
        protected NodeTuple representJavaBeanProperty(Object javaBean, Property property,
                Object propertyValue, Tag customTag) {
            if (javaBean instanceof Point && "location".equals(property.getName())) {
                return null;
            } else {
                return super.representJavaBeanProperty(javaBean, property, propertyValue, customTag);
            }
        }
    }
where * javaBean - is the actual instance of the JavaBean * property - internal representation of the JavaBean property * propertyValue - the actual value which holds the property (in this example it is not used)

**Comment by idontusenumbers** [comment]
Sorry about that previous content, wrong repo.

I uninstalled, reinstalled, cleared data and cache, opened, logged in, clicked "all stories", circle was still inaccurate

**Comment by caleb-allen** [comment]
Ha. oops. Thought so.

Thanks for testing that

**Comment by idontusenumbers** [comment]
I presume this update was released but I am still experiencing this issue.

**Comment by samuelclay** [comment]
@idontusenumbers Can you submit a screenshot here?

**Comment by idontusenumbers** [comment]
Viewing "all stories" I can't swipe to see more. This is what it shows:
![SmartSelect_20191003-125712_NewsBlur](https://user-images.githubusercontent.com/1175031/67151161-311cf980-f287-11e9-8fd7-a0f83af19792.jpg)

After that I hit back and see this:
![SmartSelect_20191003-125735_NewsBlur](https://user-images.githubusercontent.com/1175031/67151165-3aa66180-f287-11e9-9a37-7a174e3dd1c3.jpg)

**Comment by idontusenumbers** [comment]
When I tap the next button, it doesn't advance but it does pop up a tool tip saying there are 359 unread stories

**Comment by sictiru** [comment]
Couldn't replicate the story traversal issue. Pushed a small change that might help with unread stories sync under some circumstances.

@idontusenumbers Are you still having the progress bar issue?

**Comment by idontusenumbers** [comment]
Seems to be working at the moment. Feel free to close the bug as obsolete or resolved =)
