### ISSUE TITLE
Articles Being Incorrectly Auto-Purged...?

### ISSUE THREAD

**Issue by tonyduckles** [samuelclay/NewsBlur#120]
I'm seeing a strange problem on my self-hosted install of Newsblur: only the newest 100 articles from any given feed are sticking around in the back-end database. Or at least that's what I seems like:
* For high-traffic feeds, after letting them sit for a few days, they're all pegged at 100 unread items. If I view the feed in All + Newest mode, the list ends after 100 articles.
* For mid-traffic feeds, even though the unread count isn't at 100, I'm still only able to see 100 articles total in All + Newest mode.

I definitely don't see this behavior on http://dev.newsblur.com/. So, that makes me think it's some kind of problem with my config/settings.  I didn't see anything obvious in the `settings.py` or `local_settings.py` files.  And I didn't see any obvious settings anywhere in the back-end MySQL database.

A few more details, in case they're relevant:
* My install is following the "circular" branch from Github.
* I used `./manage.py loaddata config/fixtures/bootstrap.json` during the install process to bootstrap my DB.
* I have a crontab entry that is running `manage.py refresh_feeds --force` every 15 minutes. I also have other crontab entries for running `manage.py collect_stats` and `... collect_feedback` every 15 minutes.

Any ideas on what's going on here? Is there some setting/tunable that I'm overlooking?

Thanks!

**Comment by samuelclay** [comment]
There is now a preference you can change on local installs.
