### ISSUE TITLE
iOS: Show hidden stories

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1201]
We have this button on the web but it should also be on mobile. Problem is figuring out where to place it. For now, put it in the story titles view menu. It should be hidden if there are no hidden stories. Don't bother with the unread count.

Boolean for whether to show the menu item is that if the feed has a non-zero 'ng' attribute (complement to 'ps' and 'nt').

**Comment by Dejal** [comment]
(I'll leave this open pending an icon; please close it if you want to just go with the current one.)

**Comment by samuelclay** [comment]
Icon is perfect, thanks.

**Comment by samuelclay** [comment]
Oh wait, the Show Changes text is sitting 2-3px higher than the date.
