### ISSUE TITLE
iOS: Story is blank on load

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1211]
Hitting the story changes button fixes it.

![Simulator Screen Shot - iPhone Xs - 2019-06-24 at 18 53 11](https://user-images.githubusercontent.com/44229/60063318-620e6880-96b1-11e9-9363-748a0fc67e61.png)

**Comment by Dejal** [comment]
I noticed this a while ago, and have investigated a little. It's a very sporadic issue. Most likely to happen on first launch, and will sort itself out after the first couple of stories, when it does happen.
