### ISSUE TITLE
Android: Story saved on Android and unsaved on Web still shows up as saved on Android

### ISSUE THREAD

**Issue by iexos** [samuelclay/NewsBlur#1212]
This has been a problem for a long time now, the way to reproduce is:

* save a story on android
* unsave it on web
* open saved stories on android
-> story still shows up in saved stories list on android
So apparently the App knows that some stories got unsaved, but are still wrongly retained in the actual list.

However, the counter has been reduced appropriately so there will be more stories in the saved story view than the number in the overview screen. Every time I unsave a story on Web that I saved before on Android, I have to unsave on Android again. This problem reoccurs after reinstalling (even though the current wrongly saved stories disappear).

**Comment by sictiru** [comment]
Fixed via https://github.com/samuelclay/NewsBlur/issues/1367
