### ISSUE TITLE
iOS: SFSafariViewController uses UIModalPresentationPageSheet

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1214]
In https://github.com/samuelclay/NewsBlur/commit/9ffb727d70290acfd45b9033ccaf018d480f95f2, the Safari View Controller was switched to display as a sheet rather than full-screen.  This makes poor use of iPad screen real estate.

Per https://github.com/samuelclay/NewsBlur/issues/1137#issuecomment-509865471, this may have been to work around another issue.  I've never had issues with the prior behavior (on released versions of iOS), FWIW.

**Comment by nriley** [comment]
Dug into this a bit more and figured out the issue you fixed was #1154. Looks like this was to work around an iOS bug; wonder if it's still there and if so, if we can just limit it to a 12ʺ iPad where a sheet would be less of a big deal.

**Comment by Dejal** [comment]
I have re-investigated this, and I can't reproduce it anymore (using the steps that did cause it before). So it looks like Apple have fixed their bug.

I've commented out the `UIModalPresentationPageSheet` change (just in case the issue recurs).
