### ISSUE TITLE
iOS: v9 wonky behavior

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1215]
There's a few issues here: https://forum.newsblur.com/t/since-latest-update-ios-ui-a-little-wonky/7711

Most importantly is that stories are being marked as read when returning to the app that are not intended. I've noticed some wonkiness too when returning to the app. Let's figure out how to at the very minimum not mark a story as read that isn't intended.

**Comment by nriley** [comment]
I’m noticing one small issue with this change - the back button in the story list is now black rather than getting themed in the white theme. Switching themes will resolve the issue.

**Comment by Dejal** [comment]
Hmm, I can't reproduce that. Can you provide repro steps?

**Comment by nriley** [comment]
I can't reproduce this any more either. Maybe it had to do with the version of Xcode/SDK I used to build; this time was 11b4 and last time was 10.2.1. Both are on iOS 12.3.1; still can't get NewsBlur to build and run on iOS 13 without crashing.

**Comment by samuelclay** [comment]
Looks like there are still iPad issues. See the thread: https://forum.newsblur.com/t/since-latest-update-ios-ui-a-little-wonky/7711/2

**Comment by alexott** [comment]
I have the same issue on iPad since last update - when you start application anew most of things is ok, although feed list isn't always updated. When you go out of application, and enter again - I see a white space instead of feed list - the only way to fix it is to close application explicitly, and start again.
