### ISSUE TITLE
iOS: Returning to iPad results in incorrect layout

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1216]
See repro here: https://forum.newsblur.com/t/weird-graphics-ipados-13-beta2/7714

**Comment by nriley** [comment]
I'm also seeing a (new) issue where after restoring, the NewsBlur layout is correct but tapping on stories doesn't do anything. See [video](https://sabi.net/temp/newsblur-unresponsive-story-taps.mov) for an example.
