### ISSUE TITLE
iOS: incorrect layout and tapping on stories does nothing after restore

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1219]
I originally posted this on #1216 but the changes that closed that issue do not seem to have resolved this one.

After restoring the IOS app directly into the stories view, it seems to restore into a hybrid of the feeds/all stories and folder stories view. Tapping on stories on either side does nothing other than gray them out.

You can see this in a [screen recording](https://sabi.net/temp/newsblur-unresponsive-story-taps.mov) from the previous version of NewsBlur but the current Git version (27d2384cf15d36768eb940047c002a9494da612b) does the same thing.

**Comment by samuelclay** [comment]
Yes I've noticed this too when returning to the app
