### ISSUE TITLE
Android: Image feeds not loading

### ISSUE THREAD

**Issue by caleb-allen** [samuelclay/NewsBlur#1222]
Possibly related to #1126 

Multiple user reports of image-only feeds failing to load:

> I'm having trouble with image only feeds. I'm getting "Sorry, the story's
text couldn't be extracted" in text mode and just broken picture with story
mode

> when I read a feed of the
xkcd comic, the comic does not come up no matter what I do. I always have
to view the original page.

**Comment by samuelclay** [comment]
Yeah this is a long standing issue and one that I've experienced myself as well.

**Comment by samuelclay** [comment]
Another recent thread:

> Still an issue today. In a normal browser it all shows properly so I really suspect something in the android app. Sometimes the switch to story / text does work, but not on all entries in the blog.
>
> The well-ordering principle direct link entry shows fine after toggling text/story, but switching to landscape or portrait removes the image again. Reproducably.
>
> Does that help you reproduce it too?
>
> My android is v9, on a Nokia 7 plus, patched to p1 from August the 1st.

**Comment by samuelclay** [comment]
I still don't see XKCD images

**Comment by caleb-allen** [comment]
Hm. But when you switch back to the text view it works?

Could you check out #1246 to see if a bigger margin fixes the issue on that first load?

If that doesn't help then the issue you're seeing probably isn't affected by the css padding.

**Comment by caleb-allen** [comment]
Also, if it doesn't work, could you give me the webview version you're on?

Should be `WebView implementation` in developer settings

**Comment by giganteous** [comment]
Hey! Didn't know this existed. I reported this on the forum, thanks for forwarding it here. 

My phone runs Android9, Webview version Chrome 77.0.3865.92, I can't opt for the "Android system webview" it is disabled for my user.

I have 2 image feeds that have this problem:
* xkcd (the feed you find when searching for it), _some_ articles never show, some after switching.
* http://www.karindaan.nl/beeldblog/feed/, switching doesn't help at all.

Both "worked in the past", I really do know that's not exact science. The web newsblur works fine. I sadly don't own another phone to test this.

Hope this helps. If you need more assistance: I'd be delighted.

**Comment by samuelclay** [comment]
Hey @giganteous, I believe this is now fixed. If you want to go above and beyond, download and install Android Studio and then download this repo. If you open the [Android repo](https://github.com/samuelclay/NewsBlur/tree/master/clients/android) you'll be able to run the app directly on your device. Fun way to change settings to whatever you want, as well.
