### ISSUE TITLE
iOS: sharing crashes after a few seconds

### ISSUE THREAD

**Issue by acdha** [samuelclay/NewsBlur#1231]
If you start to share a page on nytimes.com, talkingpointsmemo.com or a few other sites the sharing dialog disappears after about 5 seconds. I’m not sure what those sites have running but it even happens in the Brave browser with JavaScript disabled.

**Comment by acdha** [comment]
While sharing https://www.nytimes.com/interactive/2019/12/19/opinion/location-tracking-cell-phone.html I noticed that it also doesn't seem to crash on the interactives, which might be a clue what whatever the page is doing to cause the crash — I've been assuming that this is related to some sort of analytics or tracker script (which must not be in the blocklist for Firefox Focus) because all of the sites where I notice it on are media properties.

**Comment by samuelclay** [comment]
Yeah I'd like to get this fixed, we just launched it this year.

**Comment by Dejal** [comment]
To be clear, you are saying that when viewing a web page in the Brave browser, with the "Block Script" option enabled, then use the "Share with..." function and choose the NewsBlur sharing extension, it disappears after a few seconds?

I have tried to reproduce that (with New York Times, Talking Points Memo, and others, in both Brave and Safari), but the NewsBlur sharing extension has worked reliably.

Looking at the code, I can't see anything that could cause it to run out of memory or other issues (extensions are very memory constrained, so that seemed the most likely possibility).

Can either of you provide some examples of pages (and on which browsers) that exhibit the issue? A screen recording showing it could help, too.

**Comment by acdha** [comment]
In Brave, Firefox, or Chrome it crashes almost immediately. In Safari it _usually_ crashes after a second. For example, just now I opened Safari and clicked on the first story on nytimes.com (https://www.nytimes.com/2019/12/21/world/asia/north-korea-missile-test-trump-kim.html) and used the sharing extension. It loaded and disappeared about a second later.

**Comment by acdha** [comment]
The second time, following the link directly, it did not crash in Safari.

**Comment by samuelclay** [comment]
Can you provide a screenshot of right before it crashes?

**Comment by acdha** [comment]
I can’t get a screenshot before it crashes unless you mean before I open the sharing extension at all: it closes quickly. 

I did notice it failed in the iOS *app* trying to share a story from someone else’s blurblog (https://mareino.newsblur.com/).

**Comment by Dejal** [comment]
A [screen recording](https://support.apple.com/en-us/HT207935) could be helpful.

**Comment by acdha** [comment]
@github prevents attacking these directly but the behavior is identical in both Safari and Firefox, latest versions of everything:

https://www.dropbox.com/s/bglq962v3gd33ci/RPReplay_Final1577494511.MP4?dl=0
https://www.dropbox.com/s/rxer0op8hqyxmv7/RPReplay_Final1577494571.MP4?dl=0

**Comment by acdha** [comment]
Here’s another URL where it crashes in Safari, Firefox, etc.:

https://www.bloomberg.com/news/articles/2020-01-11/japan-s-population-crisis-is-pushing-more-women-into-poverty?srnd=premium-asia

**Comment by Dejal** [comment]
Thanks. Does it crash every time with that Bloomberg article, or sporadically?  When I tried it, it crashed once, but I couldn't get it to happen again, despite trying for some time. This is the most frustrating kind of issue; almost impossible to reproduce.

Looking at the code, I can't see any obvious points of failure. The share extension only gets called twice before displaying the share panel; once to ask if the item applies, which doesn't do anything complex, and again to optionally add extra UI, which doesn't do anything at all. 

The most likely cause is running out of memory, but the NewsBlur share extension doesn't allocate anything in those calls. So if that is the cause, it's at the OS level, which seems strange.

Another thing to try: go to a page that fails like the above, and try accessing other share extensions (e.g. if you use it, Slack uses a very basic share extension like NewsBlur's). Do they work?

**Comment by acdha** [comment]
It tends to be consistent when it happens but it’s definitely not 100%. I was wondering whether there was some issue with pages getting background timers or network activity since it’s mostly on big media sites infested with trackers (although I do use Mozilla’s content blocker), but I’ve never seen it on nytimes.com/interactive/ pages even though it’s routine elsewhere on their site. 

NewsBlur does seem to be most commonly affected  but I have seen it (rarely) with Tweetbot or Pinner. Interestingly, no change moving from an iPhone 6S to 11.

**Comment by samuelclay** [comment]
Ok I just tried to share a story from the NYT app and it shared a blank story with no content (but the permalink worked. The title morphed from the actual story title "Gone from Grocery Shelves, Now There's a Mad Dash to Find Them" to "The Coronavirus Outbreak" which is the series title. I do blame the NYT app, but when I send to Mail, I get the right title.

**Comment by acdha** [comment]
I've noticed that happening in the browser, too — the share works but only includes the title and URL while other apps see the entire page.
