### ISSUE TITLE
Backend: Improve story proxy ("Imperfect proxy due to http over https")

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1242]
Feed/XML URL: https://steamcommunity.com/games/943140/rss/
Website URL: https://steamcommunity.com/games/943140

Both are HTTPS, but when I try to view any stories in the feed using the Story view I get the error "Imperfect proxy due to http over https".

Funnily enough, some elements of the site will actually load, but nothing relating to the actual story.

I get this error on all the Steam rss feeds I've tested.

**Comment by samuelclay** [comment]
This is no longer a concern as the site is now https-only.
