### ISSUE TITLE
Android: Open story in incognito and change Copy to clipboard action to only hold URL

### ISSUE THREAD

**Issue by ehcloninger** [samuelclay/NewsBlur#1245]
One of my feeds has started using JS to scramble the page contents and sticking an overlay ad begging visitors to pay. I've found I can combat this practice by opening the link in incognito/private mode or by pasting the link into a browser with outline.com. Could this process be integrated directly into Newsblur on Android?

As an alternative, the "Send to" action for "Copy to Clipboard" should only copy the URL, not the text of the headline. At least with that I can paste directly into the outline.com site in my browser without having to paste into some text editor first.

**Comment by samuelclay** [comment]
@caleb-allen Is this a possibility as a preference? On iOS it's not.

**Comment by samuelclay** [comment]
Agreed on Copy to Clipboard should only keep the URL.

**Comment by sictiru** [comment]
Currently there is no path to open a story programmatically in incognito mode from inside the app. 
When the `Copy to clipboard` action is used, the entire sent payload is copied.

There are two ways of sending a story from the context menu.
`Send link to...` - payload = title + url
`Send story to...` - payload = title + url + story content

An idea would be to change the `Send link to...` payload just to the story's url.
Another one would be to create a parent `Send to >` in the context menu with 3 children like `Sent story link ...` (url), `Send story brief...` (title +url) and `Send story content...` (title + url + content)

@samuelclay Do you have a preference or suggestion?

![Screenshot_20210228-155911](https://user-images.githubusercontent.com/13900221/109440897-91c65580-79e8-11eb-9f7c-90bc66b9f976.jpg)

**Comment by samuelclay** [comment]
Let's have the Story Link option and the url + title + content option. Folks who want url + title are probably using a service that uses oEmbed meta tags to automatically display a url preview. I know SMS and Slack are both great at this.
