### ISSUE TITLE
iOS: Mac Catalyst edition

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1247]
Now that iOS 13 and macOS Catalina introduces the ability to build iOS apps for macOS, via Catalyst, there may be customer demand for a Mac edition of NewsBlur.

I've turned on the checkbox to build under Catalyst in a local branch, as an experiment, but there are a number of issues preventing successful building of a Mac app:

- The most significant is the reliance on `UIWebView`. That is not supported in Catalyst, requiring using `WKWebView` instead. That isn't a simple transition, though: the web view is used extensively in NewsBlur, with JavaScript interactions and such, which would require many changes. It should be feasible, though. And may have to be done in due course even for the iOS app, since `UIWebView` has been discouraged since iOS 8, and is now formally deprecated as of iOS 13, in addition to being unavailable for Catalyst.

- There's an error related to using the `AddressBook` framework, but that doesn't seem to be used, so can be removed.

- There are many deprecation warnings, but those shouldn't be too hard to fix (and again will need to be addressed in due course).

Beyond those, of course, the app would need many changes to work well as a Mac app, including adding a menubar, probably some layout changes, and other UI tweaks.

But I think it could a a popular option for many people. Something to consider. Let me know if you want me to explore further.

**Comment by samuelclay** [comment]
Oh I remember attempting to transition to WKWebView a long time ago and it was not fun. I ultimately abandoned that branch.

That said, I would love to see this. NewsBlur was originally developed to replace NNW, a Mac app.

**Comment by Dejal** [comment]
NetNewsWire has a [new lease on life now](https://github.com/brentsimmons/NetNewsWire). But I'm sure Brent would welcome other Mac newsreaders.

Yeah, transitioning to `WKWebView` will be a fair bit of work, but I'm confident that it is feasible, useful for Catalyst, and ultimately probably required for a future iOS version.

Okay, I will begin work on that in the next month or two, depending on other priorities that come up in the meantime.

**Comment by Dejal** [comment]
A partial list of issues I've noticed, that I'll work on in the coming months, as time allows:

- The story web view isn’t rendering the CSS correctly.
- The font size is a bit small; might want to embiggen everything a few points.
- When I first resized the window, a white box appeared.  Gone after relaunch, but should fix.
- Probably will want to add three-pane support; useful for iOS too (see issue #817).
- Should make the sidebar wider.
- Should allow the user to resize the split panes, either using a proper split view, or (more likely) adding custom support for dragging the dividers.
- Should show model views (e.g. Organize Sites) as separate windows.
- Need to redo the preferences into a more Mac-like window, with popups instead of push items, etc.
- Add more menu commands for appropriate functions.
- A bunch of deprecation warnings that may or may not need to be fixed (lots of them, but most the same).
- Add a circular app icon.

**Comment by samuelclay** [comment]
On the three-pane, I would love to rethink how NewsBlur iOS app has the panes. Today it's not great, but it works. I would be happy to move to something a bit more like sliding doors (ala Reeder), although that would make the dashboard river harder to show.

**Comment by Dejal** [comment]
Work on the three pane option (and much more) is underway; see #817 for more info.

**Comment by samuelclay** [comment]
Looking good! Stories aren't tappable right now, but using the keyboard shortcut fixed that. Also, the login screen needs adjustment (ugh, such an old view too).

**Comment by samuelclay** [comment]
For Catalyst, let's reintroduce story content previews, story date, and author, as well as larger fonts.
<img width="1512" alt="Screen Shot 2022-01-26 at 11 52 38 AM" src="https://user-images.githubusercontent.com/44229/151209185-1bbe9de0-8835-4e76-ac92-5da0a33f2969.png">

**Comment by samuelclay** [comment]
I take that back, I prefer the extra story titles. But that's for the widget (#1334). 

Let's widen the story titles a bit. Looks like they widen on their own at ~2000px.


<img width="2081" alt="Screen Shot 2022-01-27 at 10 18 54 AM" src="https://user-images.githubusercontent.com/44229/151388438-3c32f541-80fe-4d36-9893-e92ed19ddd06.png">

<img width="2095" alt="Screen Shot 2022-01-27 at 10 18 57 AM" src="https://user-images.githubusercontent.com/44229/151388431-82083eb6-7fc8-4e19-8275-3bf050732e4e.png">

Also, let's add a max-width to images of 1200px or something.

**Comment by Dejal** [comment]
The Catalyst branch and Mac app are not ready for release yet. This is on hold until more required changes are done.

**Comment by samuelclay** [comment]
Should I still be merging in catalyst into testflight?

**Comment by Dejal** [comment]
No, merge Dejal to TestFlight.

**Comment by Dejal** [comment]
I've resumed work on the macOS edition of NewsBlur, in the Catalyst branch. The NewsBlur Alpha app for macOS is available via internal-only TestFlight.

There's still a bunch of refinements to do (so don't bother reporting issues yet), but it's in a usable shape already:

![Screenshot 2023-10-05 at 14 42 46](https://github.com/samuelclay/NewsBlur/assets/1318849/22998073-dd8f-47d2-95ff-5e16ebe713c1)

**Comment by samuelclay** [comment]
It's really great! What happened to the widget? I want to see it in my widget dashboard on macos.

**Comment by Dejal** [comment]
As I recall, the widget isn't included in the Alpha build, for some technical reason I forget right now (maybe related to the bundle identifier or something). I'll take another look at that when next working on it.

**Comment by Dejal** [comment]
More progress, with the user profile in the window body like on web, and work on menus. I spent a fair bit of time struggling to get the navigation bars to behave; they appear to be implemented outside the scope of the app with Catalyst, using separate windows for each button. And clicking on one disabled the menus. A bit of a mess. But I've found a solution, using Mac-native toolbars, and have started implementing that. I'll finish that next time.

![Screenshot 2024-01-05 at 21 55 29](https://github.com/samuelclay/NewsBlur/assets/1318849/659fe571-141c-4a23-a496-a84acadfe2c2)

**Comment by Dejal** [comment]
I think the app is almost ready for release now. Just a few issues left. You can begin to report issues or request tweaks now if you wish.

![Screenshot 2024-01-19 at 21 43 28](https://github.com/samuelclay/NewsBlur/assets/1318849/aa48ae81-09d9-489a-9cfa-2d4ada1dca12)

**Comment by samuelclay** [comment]
Are you sure you want me to report issues? There's some quality of life issues in the Grid view on Catalyst. I suggest taking a look at how that's transitioning between stories. 

Also, the scroll is much slower than I would expect from a native app. Isn't there a faster scroll option for story titles and the story detail?

**Comment by Dejal** [comment]
Yes, you're welcome to report issues. I'm aware of some, but you may have other priorities.

I'll take a look at the Grid view, and the scrolling performance, though it's basically using the same code as on iOS, with the Catalyst translation layer to work on macOS, so there may be some performance impact. Still, I might be able to do something. Any performance improvement would probably also benefit the iOS app.

**Comment by Dejal** [comment]
I've addressed all known issues now, so unless you have some specific issues, I think it is ready for public TestFlight feedback. Let me know if you want me to produce a public TestFlight build (it's currently internal-only).

![Screenshot 2024-02-09 at 20 59 59](https://github.com/samuelclay/NewsBlur/assets/1318849/2dd721b4-5433-4977-ac34-664496d0ea76)

**Comment by Dejal** [comment]
I've finished my polishing; I don't have anything more on my list to do on this. Ready for a public TestFlight? Rather than making the NB Alpha app TestFlight public, we could merge into the Dejal branch, and do a main app TestFlight from there. Let me know if you want me to prepare that.

**Comment by samuelclay** [comment]
Nicely done. I've got some show stoppers that we need to fix before putting out a public beta. And sorry about the delay, I've been deep on server maintenance and transition for the past month, which you might have noticed from the flurry of commits. But we're now on dedicated hardware and it's much faster!

* Let's widen the folders and feed titles to match the width of the view they're in, reducing the side margins to 0
<img width="1295" alt="Screenshot 2024-03-09 at 7 53 05 AM" src="https://github.com/samuelclay/NewsBlur/assets/44229/4ad33223-d47f-43b0-8aaf-71115c8fa025">
* Interactively swiping with two fingers on the feed list shows this overlapping story detail behavior 

https://github.com/samuelclay/NewsBlur/assets/44229/9dddc160-7129-4058-af5f-1233dc54aa2f

* After 5 minutes or so, returning back to the app while a story is loaded and the story is entirely blank. Usually happens on the second story and not the first
<img width="1275" alt="Screenshot 2024-03-09 at 8 39 22 AM" src="https://github.com/samuelclay/NewsBlur/assets/44229/b7eed4d7-2d45-4cde-9c97-27ab4e7910d3">

**Comment by samuelclay** [comment]
* Training also isn't styled yet
<img width="1275" alt="Screenshot 2024-03-09 at 3 49 35 PM" src="https://github.com/samuelclay/NewsBlur/assets/44229/05c14021-33ec-494b-af63-20ec3b55d0af">

**Comment by samuelclay** [comment]
* And when macOS went to dark mode (which should automatically switch the theme!), I got this:
<img width="1275" alt="Screenshot 2024-03-09 at 7 40 01 PM" src="https://github.com/samuelclay/NewsBlur/assets/44229/f2273924-c9d8-42b4-aaec-73fc015bb993">

**Comment by samuelclay** [comment]
* Clicking on story titles in the widget doesn't open stories in the app
<img width="448" alt="Screenshot 2024-03-11 at 1 48 25 PM" src="https://github.com/samuelclay/NewsBlur/assets/44229/59cce094-1ec2-40ad-8107-bc86a8711c04">

* Notifications aren't showing up on macOS. Anything I need to do on the server to get this working?

**Comment by samuelclay** [comment]
* Sharing a story gave a (null) name:
<img width="1289" alt="Screenshot 2024-03-23 at 4 26 32 PM" src="https://github.com/samuelclay/NewsBlur/assets/44229/b5727bd7-f32e-40e4-9716-cdb935694c51">

**Comment by Dejal** [comment]
I've addressed some of those issues. The training one was a challenge; it appears that Catalyst doesn't support web views in sheets. So I took that as an opportunity to do something I've wanted to do for a while: make the trainer a native view. I rewrote it as a SwiftUI view. 

Here's the feed trainer:

![Screenshot 2024-04-04 at 19 44 58](https://github.com/samuelclay/NewsBlur/assets/1318849/210382f1-4bfe-43df-9afe-1a61a971eca8)

And the story trainer:

![Screenshot 2024-04-04 at 19 44 31](https://github.com/samuelclay/NewsBlur/assets/1318849/a47822f5-5bf4-495c-b3f5-05fa30f24be3)

Notice in the Story Title section, instead of selecting text and choosing a menu item to train words, I implemented an innovative approach where you tap words to add them to a neutral trainer (which can be cleared to start again). Then tap it to toggle to like or dislike, at which point it is saved (and another phrase can be started if desired).

I hope you like this new & improved edition of the trainer.

**Comment by samuelclay** [comment]
This is looking nearly ready to go. One issue I found is that when I return to the app after 30 minutes, the image previews disappear.

<img width="1289" alt="Screenshot 2024-04-16 at 11 42 39 AM" src="https://github.com/samuelclay/NewsBlur/assets/44229/a7fca966-8544-4002-8a78-d93b276800b5">
<img width="1289" alt="Screenshot 2024-04-16 at 11 16 41 AM" src="https://github.com/samuelclay/NewsBlur/assets/44229/14e5cebf-081b-46ea-acc2-48c97ec2cb1b">

**Comment by Dejal** [comment]
I think the Mac app is ready for a public TestFlight. Do you have any further issues? I'll save my time in May for any more issues with it, pre-and/or-post release.

I've added an Xcode Cloud workflow to build the macOS TestFlight, and disabled the iOS one for now. So all we need to do is merge the `Catalyst` branch changes into the `Dejal` branch, and it'll run automatically. If you're ready, you can do the honors, or I can if you prefer.

**Comment by samuelclay** [comment]
Just merged `catalyst` into `dejal`. As soon as it's public, I'll tweet about it and maybe even blog about it to get folks involved in testing it.

**Comment by Dejal** [comment]
Looks like the build failed due to missing the macOS scheme (probably a merge issue). Let me know if you want me to fix that for you.

**Comment by Dejal** [comment]
I've fixed the build issues. The app is currently awaiting beta review, so should be live in TestFlight soon.

**Comment by Dejal** [comment]
And now it has been approved for TestFlight, so you can publicize it when you're ready.

**Comment by samuelclay** [comment]
Looks like we've got some feedback:

> Just getting started with it, but some basic Mac OS conventions are missing. Menu items are missing for basic commands (like next, open in browser). And since they are missing, key commands are not labeled, and not changeable. I also miss that there is no in app browser. A lot of feeds have broken story mode and reader mode to drive views, and so to read any of these, I need to open in a browser. So basically, to read every story, I need to open in browser. If so, then I might as well go use the web app, since I end up in Safari primarily.

Another user:
> I've mentioned this in the context of the iPad app, but it's also true here - I would really like if it supported all of the keyboard shortcuts that work on the web. In particular, it would be great if I could refresh the current view by pressing "R" (or by scrolling-to-refresh at the top of the current feed/folder). Thanks for continuing to develop Newsblur rather than put it in maintenance mode. I am excited to have a Mac app, but until it has parity with the web I probably won't make much use of it.

A third user:
> Can you please make the sidebar resizable? Also, it'd be nice to be able to customize the toolbar in the main content area.

Agreed with all of these points! Let's:
* Make the sidebar resizeable
* Use an in-app browser
* Keyboard shortcuts (and show them on holding command, like on ipad)
* More menu items so keyboard shortcuts can be manually added by the user

**Comment by Dejal** [comment]
I'll see what I can do. Though showing keyboard commands when holding Cmd isn't a Mac paradigm, so we shouldn't do that; you see keyboard commands by looking in the menus.

**Comment by samuelclay** [comment]
Just installed the latest TF: on iPhone, going back to the feed list, the selected feed no longer deselects (it should fade out so you know where you've just been).

**Comment by samuelclay** [comment]
I wasn't able to set a notification using the catalyst app.

<img width="1289" alt="Screenshot 2024-05-30 at 2 25 52 PM" src="https://github.com/samuelclay/NewsBlur/assets/44229/a2b80adc-2e64-4793-8529-0082cde0896d">

Here's how it works on iOS:
![IMG_5903](https://github.com/samuelclay/NewsBlur/assets/44229/a42ee4b0-bbbd-451a-b6fa-34103aecd0d1)

**Comment by Dejal** [comment]
I'm working on fixes.

Speaking of notifications, I've just created #1867 (Mac-specific notifications).

**Comment by Dejal** [comment]
Done all of the requests. TestFlight builds available. 

Note that in addition to the keyboard shortcuts via the menus, the Mac app also supports the non-modified shortcuts of the iPad app, e.g. "j" to go to the next story, "o" to open in the browser, "u" to mark unread/read, etc.

Since macOS doesn't have an overlay to show such shortcuts, perhaps you could add a help page on the website, and I could make the NewsBlur Help menu item show that? Online help is common for Mac apps, and would be a good thing.

**Comment by samuelclay** [comment]
I'm starting to rely on the app more but I'm having a few issues:

* The trainer does not work on individual stories, it freezes
* Tapping on story titles in the widget doesn't load the correct story
* Coming back to the app after 15 minutes and seeing a blank story detail

<img width="1415" alt="Screenshot 2024-06-27 at 9 44 58 AM" src="https://github.com/samuelclay/NewsBlur/assets/44229/0591c804-aa4c-46c6-a4c0-4f8653c53eea">

**Comment by Dejal** [comment]
Done some fixes. I can't reproduce the widget not loading the correct story, but I did have a recent widget fix, so that might help. If not, please show your Widget Sites view with the selected feeds, so I can try to reproduce it.

Also, as noted elsewhere, I can't do a TestFlight until you update the Apple agreements.

**Comment by samuelclay** [comment]
Agreement has been agreed

**Comment by Dejal** [comment]
Any more feedback on the Mac app? It'd be great to get this launched! I'll be available over the next week if any issues come up.

**Comment by Dejal** [comment]
Huh, my fix on June 27 didn't solve it?

**Comment by samuelclay** [comment]
Nope, I'm still seeing it just as often.

**Comment by Dejal** [comment]
I had the Mac app running in the background all day today, every hour or so bringing it to the foreground and changing feeds/stories, but every time it has shown the story on activating the app; no blank stories. I was able to reproduce the issue before my June 27 fix, but not since.

So I'll need you to re-check it, and hopefully provide more clues if it is still occurring.

**Comment by samuelclay** [comment]
Yeah I've noticed it went away so I'll chalk it up to running an older build. At this point I'll need to assembly screenshots and launch it on the mac app store, which I'll try to do in the next few days. 

I just moved to SF so I'm without furniture for the next couple weeks, so I'll be limited in what I can achieve.

**Comment by Dejal** [comment]
Yeah, likely using an older build. I'm glad it's resolved.

I'll have a new TestFlight in the next few days, so it'd make sense to wait for that.

Best of luck getting set up in SF!

**Comment by samuelclay** [comment]
As I was taking screenshots, I noticed the app doesn't switch from light to dark like the iOS app does.

<img width="1415" alt="Screenshot 2024-08-27 at 5 21 39 PM" src="https://github.com/user-attachments/assets/0e6123fb-0d99-4efe-92f3-8b18850fe7b8">

**Comment by samuelclay** [comment]
I manually changed it but we should include a way to use the system theme. This probably goes for the iOS app as well, as a fifth theme color for "Auto"

**Comment by Dejal** [comment]
Enable the Follow System Appearance option:

![Screenshot 2024-08-27 at 20 51 44](https://github.com/user-attachments/assets/70fc0a1b-47b7-45bc-a4dd-da3f9201a3c5)

**Comment by samuelclay** [comment]
Can we add "Auto" to the segmented control? I find ymself wanting to override it but not wanting to go back into preferences. I'll make this a separate ticket.

**Comment by samuelclay** [comment]
Ok, the app was rejected for the following reasons:

> Guideline 2.1 - Performance - App Completeness
> 
> We are unable to complete the review of your app because one or more of your in-app purchase products have not been submitted for review.
> 
> Next Steps
> 
> To resolve this issue, please be sure to take action and submit your in-app purchases and upload a new binary in App Store Connect so we can proceed with our review. 
> 
> Resources 
> 
> Learn more about how to [offer in-app purchases](https://developer.apple.com/help/app-store-connect/configure-in-app-purchase-settings/overview-for-configuring-in-app-purchases/) in App Store Connect Developer Help.
> 
> Guideline 3.1.2 - Business - Payments - Subscriptions
> 3.1.2(c) Subscription Information Before asking a customer to subscribe, you should clearly describe what the user will get for the price. How many issues per month? How much cloud storage? What kind of access to your service? Ensure you clearly communicate the requirements described in [Schedule 2 of the Apple Developer Program License Agreement](https://developer.apple.com/support/terms/apple-developer-program-license-agreement/#S2).
> 
> Issue Description
> 
> The submission did not include all the required information for apps offering auto-renewable subscriptions. Apps offering auto-renewable subscriptions must include all of the following required information in the binary:
> 
> - Title of auto-renewing subscription, which may be the same as the in-app purchase product name
> - Length of subscription
> - Price of subscription, and price per unit if appropriate
> - Functional links to the privacy policy and Terms of Use (EULA)
> 
> The app metadata must also include functional links to the privacy policy and Terms of Use (EULA).
> 
> Next Steps
> 
> Update the app's metadata to include the following required information:
> 
> - A functional link to the Terms of Use (EULA). If you are using the [standard Apple Terms of Use (EULA)](https://www.apple.com/legal/internet-services/itunes/dev/stdeula/), include a link to the Terms of Use in the App Description. If you are using a custom EULA, [add it in App Store Connect](https://developer.apple.com/help/app-store-connect/manage-app-information/provide-a-custom-license-agreement).
> 
> 
> Resources
> 
> Review [Schedule 2 of the Apple Developer Program License Agreement](https://developer.apple.com/programs/apple-developer-program-license-agreement/#S2).
> 
> Guideline 4 - Design
> 
> We noticed an issue with your app's user interface that contributes to a lower-quality user experience than App Store users expect.
> 
> Specifically, we found that when the user closes the main application window there is no menu item to re-open it.
> 
> Next Steps
> 
> It would be appropriate for the app to implement a Window menu that lists the main window so it can be reopened, or provide similar functionality in another menu item. 
> 
> Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed.
> 
> Resources
> 
> - To learn more about App Store design requirements, see [App Review Guideline 4 - Design](https://developer.apple.com/app-store/review/guidelines/#design).
> - Learn more about [designing for macOS](https://developer.apple.com/design/human-interface-guidelines/platforms/designing-for-macos/) in the Human Interface Guidelines.
> 
> Support
> 
> - Reply to this message in your preferred language if you need assistance. If you need additional support, use the [Contact Us module](https://developer.apple.com/contact/topic/#!/topic/select).
> - Consult with fellow developers and Apple engineers on the [Apple Developer Forums](https://developer.apple.com/forums/).
> - Help improve the review process or identify a need for clarity in our policies by [suggesting guideline changes](https://developer.apple.com/contact/app-store/?topic=guideline).

So basically we need to support in app purchases and make it so the app can be re-opened on close. I agree with the re-open on close feature, I was missing that. As for the in app purchases, they won't let us punt on that.

**Comment by Dejal** [comment]
The main window can not be closed. The Close menu item and window button are disabled. So you might need to ask for clarification if they didn't notice that, or were able to somehow close the window.

**Comment by samuelclay** [comment]
Can you make it so that the app can be closed and then re-opened? Upon re-opening, it refreshes the feed list and loads the all site stories.

**Comment by Dejal** [comment]
I've just experimented with allowing closing the window and re-opening it. I don't think that is feasible for NewsBlur at this stage, as it doesn't really support multiple "scenes", i.e. opening another window. Adding that support would require major refactoring.

I'll next experiment with quitting the app when the window is closed. Catalyst doesn't make that easy, but it might be possible.

I previously thought that preventing closing would be better, to avoid accidentally closing (you can always quit and re-launch).

**Comment by Dejal** [comment]
Is there an API for that, or a standalone web page that I can send the user to, to delete the account?

**Comment by samuelclay** [comment]
There's both, but let's use this webpage: https://www.newsblur.com/profile/delete_account

**Comment by Dejal** [comment]
It isn't possible to add a button to the Settings window on macOS; it is managed by the Catalyst system using the Settings bundle. More concerning, Sequoia seems to have broken the Settings window; it doesn't appear anymore. I'm investigating.

So I'll have to add the delete account option elsewhere. Could be in the File menu below "Logout NewsBlur". Or could add it to the confirmation alert for logout — have "Cancel", "Logout", and "Delete Account" buttons. The latter would log out then show the delete account page. (Would be good to log out when deleting the account anyway.) What would you prefer?

**Comment by Dejal** [comment]
I decided that the latter suggestion was best, so implemented that. And fixed the Settings issue with Sequoia. TestFlight build incoming....

**Comment by samuelclay** [comment]
I've been using the macOS app a ton and it's been a great experience. One change I'd like to see is to match the up-to-date experience from the web. We have a configurable dashboard on the web that has real-time updated "widgets". Could we make a new "Dashboard" top level folder, same as on the web, with the story titles in groups matching the web? I publish those lists on `/reader/feeds/`:
```
"dashboard_rivers": [
    {
        "river_id": "river:",
        "river_side": "left",
        "river_order": 0
    },
    {
        "river_id": "river:infrequent",
        "river_side": "left",
        "river_order": 1
    },
    {
        "river_id": "river:global",
        "river_side": "left",
        "river_order": 2
    }
],
```

They should show 5 stories in the standard story titles format, and they should reload every 5 minutes (add a random 1-5 minutes per request so they don't all refresh together at once, some people can have dozens of rivers). I'd like to see this on both iPad and macOS, so I can leave the screen open and watch the news come in.

Bonus points for left vs right lists. And extra bonus points for single column, double column, and two horizontal columns (left "column" on top row, right "column" on bottom row).

**Comment by Dejal** [comment]
That's an intriguing idea. Though this really should be a new issue, since it's only tangentially related to the Mac app; as you say, it'd be beneficial on the iPad app too.

I've added #1899.

**Comment by samuelclay** [comment]
It's approved! I'll blog about this tomorrow or early next week. Congrats, it's a terrific release and I'm very hungry for #1899 because not only will that get its own blog post but it'll help the mac app become a more present part of people's day.

**Comment by Dejal** [comment]
Yay! I'm sure lots of people will be thrilled by a native Mac edition of NewsBlur. Very exciting to get it out there.

I will be available next week for any urgent fixes (please add as new issues), or otherwise working on #1899.
