### ISSUE TITLE
Adding a twitter feed is confusing

### ISSUE THREAD

**Issue by malaclypse2** [samuelclay/NewsBlur#1251]
When attempting to add a twitter URL to my feeds, I get a helpful-looking error message that says "Your Twitter connection isn't setup. Go to Manage - Friends and reconnect Twitter."  

Unfortunately, when I look over on the right hand side of the page, under "Manage" I don't see anything that looks like a "Friends" link. I have a series of links that read: Preferences / Followers / Blurblog Profile / Account / Import Site / Goodies & Apps / Notifications / Email Newsletters / Tips and Tricks / Keyboard / Organize Sites / Mute Sites / Trainer / Mark all as Read.

I did poke around in several of the likely-looking links (Preferences, Followers, Account and Import Sites, IIRC), but didn't find anything that looked like it would set me up to read something from twitter. I did see some twitter-related stuff under "Followers", but it didn't look like what I needed (since I don't have any friends or followers on twitter).

**Comment by samuelclay** [comment]
I've corrected the messaging so it says the full name of the dialog. It should be a link to automatically setup, ideally.
