### ISSUE TITLE
Android: Offer a re-sync mechanism

### ISSUE THREAD

**Issue by novoid** [samuelclay/NewsBlur#1253]
Hi!

Android v9.0.1 here on (1) OnePlus 5 (OxygenOS 9.0.8; patchlevel August 2019) and (2) Android 6 tablet.

I'd love to see a settings function that allows me to purge my local status and **re-syncs from the web service**.

**Reason/Background:**

Currently, I'm using an Android tablet and my mobile with the NewsBlur app. I've got multiple situations where I added and removed the "saved"-flag where the "other" device did not get the removal. This ended up in having the funny situation that my mobile shows 0 saved articles in the overview. However, when I enter the saved articles menu, I see dozens of saved articles. These saved articles are not listed as saved on the web page nor on the tablet.

The only thing I can do now is manually removing the synced-flag on these articles whenever I reach 0 saved articles on the other interfaces. I'd love to get rid of this manual sync if possible.

From other RSS aggregator apps I know this "reset from server" functionality which usually cleaned up these accumulated sync-messes. 

I know that the requested feature is a workaround to clean up the bug of being able to end up with this falsely saved articles. So far, I don't think that it's easy to reproduce and debug this issue from my point of view. I'd be glad to help, if I get directions.

Thanks!

**Comment by samuelclay** [comment]
Yeah we have this on iOS and it's sometimes handy. Just a purge offline cache button. On iOS it's in Preferences, which is where it should live here.

**Comment by sictiru** [comment]
> Yeah we have this on iOS and it's sometimes handy. Just a purge offline cache button. On iOS it's in Preferences, which is where it should live here.

Is this the `Delete offline stories...` option on iOS under Preferences? Is it a full storage reset (excluding non feed user preferences) or just stories + images?
