### ISSUE TITLE
All Site Stories - AJAX Error 400

### ISSUE THREAD

**Issue by ShreeMandadi** [samuelclay/NewsBlur#126]
On Navigation to All Site Stories, The AJAX call is created with a list of all feeds on the URL, and the length exceeds 4KB..

![2013-03-29_08-24-42](https://f.cloud.github.com/assets/28439/317903/25a2edc0-9885-11e2-9d54-0dc139c0b975.jpg)

Same Navigation on non-dev site shows a feed_ids_in_folder function not defined

**Comment by samuelclay** [comment]
Fixed this in the HAProxy config file.
