### ISSUE TITLE
Parsing: NewsBlur cannot parse its own RSS feed

### ISSUE THREAD

**Issue by michel-slm** [samuelclay/NewsBlur#1261]
Adding https://blog.newsblur.com/rss to my feeds, it never shows any stories despite Feed Validator saying the feed is valid but contain some interoperability issues:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.newsblur.com%2Frss

**Comment by samuelclay** [comment]
Do you have the feed trained? Right-click on the feed and open the intelligence trainer. Could be that it's thumbed down.

**Comment by samuelclay** [comment]
Also the newsblur blog is on tumblr and that should probably change.
