### ISSUE TITLE
iOS: Tapping Safari button doesn't do anything for Macrumors stories

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1263]
From a user email:

Hi, I noticed this behavior while reading the MacRumors feed. I tapped the title of the YouTube embed to open the YouTube.com URL in Safari as one often does:

![image0](https://user-images.githubusercontent.com/44229/68997629-86dcc580-0876-11ea-8aae-8246271f5e6d.png)

Instead, it opened like this, and when I tapped the Safari button in the upper right, I got this error:

![image1](https://user-images.githubusercontent.com/44229/68998125-28b2e100-087c-11ea-94c1-81b75dbbf39e.png)

Unfortunately, I can’t remember how this used to work, but I am expecting to ultimately open the YouTube video’s page in the Safari app.

**Comment by Dejal** [comment]
That story isn't appearing in my MacRumors feed. I suspect the embed was damaged, and the story pulled.

Other MacRumors stories with embedded YouTube videos do play inline correctly.

So I'm going to close this as a one-off feed issue. If you can reproduce it, or find other examples, please re-open it with that info.
