### ISSUE TITLE
iOS: Clearing offline stories doesn't work

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1266]
I'm trying to test the new offline Text feature and the clear offline stories button looks like it's working, but when I go back to pull-to-refresh, it acts as if the stories are already downloaded.

**Comment by Dejal** [comment]
Yeah, despite the button title, clearing offline stories actually was just deleting the cached images off disk (if any).  I've now changed it to also clear the stories, text, and image info from the database, as you'd expect.
