### ISSUE TITLE
iOS: Dark theme keeps turning itself off

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1268]
Looks like this is still happening in the latest build, too. I turn on dark mode, switch out of the app, come back in, and it's light themed.

**Comment by Dejal** [comment]
That's because it is following the system appearance. If you disable that preference, it'll stick with what you use.

I agree this is confusing. We might want to hide the theme segmented controls when follow system appearance is enabled.

**Comment by samuelclay** [comment]
Let's make not following the system preference the default then. If people want it to follow the system, they should have to go into NewsBlur preferences or change it manually in the app.

**Comment by Dejal** [comment]
Hmm, I don't like that. I think people would expect it to follow the system appearance by default, with the option (if they notice it) to use a different appearance.

How about this: follow system by default, but if someone changes the theme via a menu or gesture, automatically turn off the follow system preference, so their choice sticks.

**Comment by samuelclay** [comment]
Love it, great compromise.
