### ISSUE TITLE
Backend/API: add a story image thumbnail endpoint

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1269]
This is a new issue to split out the request for a story image thumbnail endpoint, for use with the iOS widget (#1162):

> Okay, @samuelclay, can you please add that endpoint to take a story hash and desired size, and return the first image (if any) scaled to the requested size. Either use the smaller dimension as the size (and I'll aspect fill to cut off the extra), or have the server do that and return as a square image.

I notice issue #1241, which could also be related.

You wrote:

> https://github.com/willnorris/imageproxy looks promising as a replacement to camo, so I'll start there and try to get that deployed

**Comment by Dejal** [comment]
Something to consider: the story image endpoint could also cache images, so multiple users requesting the same image gets it faster. And as an extra incentive for you: the iOS and Android apps, and perhaps the website, could also use the story image endpoint to speed up performance of populating the feed details. Rather than having the apps fetch the image from each site, they can ask the NewsBlur server for them, just like they do for feed icons.

Of course, would still need the full-size images when displaying the stories, so it may not be beneficial to load the feed detail thumbnails separately, but it could be worthwhile.

**Comment by samuelclay** [comment]
Deployed. Check for the thumbnail urls in each story under the new `secure_image_thumbnails` key, a dict similar to `secure_image_urls`. I made the images 200 pixels square but you can either change that in the url or let me know and I'll update the url.
