### ISSUE TITLE
iOS: replace UIWebView with WKWebView

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1270]
This was mentioned as part of the Mac Catalyst idea (#1247), but now has a fixed deadline, so I'm adding a separate issue for it.

[Apple announced on December 23, 2019](https://developer.apple.com/news/?id=12232019b):

> If your app still embeds web content using the deprecated UIWebView API, we strongly encourage you to update to WKWebView as soon as possible for improved security and reliability. WKWebView ensures that compromised web content doesn’t affect the rest of an app by limiting web processing to the app’s web view. And it’s supported in iOS and macOS, and by Mac Catalyst.
> 
> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

So we need to complete this within the next year. I'm giving it a `critical` priority since it has a deadline, and will take some time, though we have several months to complete it.

**Comment by samuelclay** [comment]
Yep, it's time. Got the warning from Apple today:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "NewsBlur" 10.0.2 (112). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

**Comment by Dejal** [comment]
All `UIWebView` references have been removed or replaced with `WKWebView` now.  All seems well in my testing.

So feel free to merge this into `Master` when you're ready.

**Comment by Dejal** [comment]
Unless you have any objections, I'll merge the [`wkwebkit`](https://github.com/samuelclay/NewsBlur/tree/wkwebkit) branch into [`dejal`](https://github.com/samuelclay/NewsBlur/tree/dejal) tomorrow.

**Comment by samuelclay** [comment]
Sounds good to me

**Comment by Dejal** [comment]
Done. The [`wkwebkit`](https://github.com/samuelclay/NewsBlur/tree/wkwebkit) branch is no longer needed. You can delete it if you wish.
