### ISSUE TITLE
Add "black" theme on iOS

### ISSUE THREAD

**Issue by Limero** [samuelclay/NewsBlur#1273]
The "black" theme in the Android app is my favorite. I really miss it in the iOS app. Can it be added?

**Comment by samuelclay** [comment]
@Dejal what do you think? Would just changing the background of the story content to pure black do the trick? Do you want all the UI to be black as well? I like having only 4 themes, but I'm not sure how much grey is used over black, so maybe we can blackly grey and blackest-of-blacks the black theme?

**Comment by Dejal** [comment]
Yeah, I think it'd be reasonable to make both of the dark themes darker, to have the darkest one use pure black backgrounds.

Personally I think a dark grey like now is easier on the eyes (and I use dark mode on all of my devices), but I know that many people want the darkest of darks.

**Comment by samuelclay** [comment]
Let's slightly darken the light grey and then blacken the dark.

**Comment by Limero** [comment]
It looks better now on the feed list, but the reader view, stories view (when opening a feed) and all headers are still gray, compared to Android where it's all black.
I think completely black mode is preferred now when we have OLED screens on new iPhones.

**Comment by Dejal** [comment]
Can you provide screenshots of the Android edition.  I'm pretty happy with the colors now, but that might provide inspiration of further tweaks.

**Comment by Limero** [comment]
Sure!
![Screenshot_20200223-220135_NewsBlur](https://user-images.githubusercontent.com/639787/75120072-bd518a00-5688-11ea-93cf-1e27b6e704cc.png)
![Screenshot_20200223-220224_NewsBlur](https://user-images.githubusercontent.com/639787/75120074-bdea2080-5688-11ea-8800-9c29d729898d.png)
![Screenshot_20200223-220309_NewsBlur](https://user-images.githubusercontent.com/639787/75120075-be82b700-5688-11ea-94dc-51274ead7ee5.png)
