### ISSUE TITLE
Android: Some images never load on Android

### ISSUE THREAD

**Issue by arantius** [samuelclay/NewsBlur#1274]
E.g. this repro: https://gist.githubusercontent.com/arantius/888ae0fc3eca4fc42eac8cc546caf690/raw/53daebb69e6ef281765a4e06743b6e5e38424e01/dhd.xml

If i add this as a feed, the image always shows broken in the Android app.  If I long press and choose open image, it always works.  In the web reader, it always works.

**Comment by sictiru** [comment]
The image from that feed doesn't load because starting from Android API 28 all traffic must be under HTTPS. The image loads if I set [usesCleartextTraffic](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic) flag on the application level but it's not recommended.

**Comment by samuelclay** [comment]
NewsBlur now has an http-to-https proxy for images. Check the story for the `secure_image_urls` dict, which lets you do a string replacement on those image urls. Note, only do this for http:// image urls and not https:// image urls.

**Comment by sictiru** [comment]
@samuelclay I assume `story.story_content` is generated on the back end and I'd need to parse it and replace the data on the front end. If that is true, could we replace the http:// image urls with https:// image urls at creation? Otherwise I'll continue with `secure_image_urls`

**Comment by samuelclay** [comment]
Yeah we need to replace it on the client-side because only "official" apps can use the secure image urls. The third-party apps will continue to use the original URLs.
