### ISSUE TITLE
[Request] Multiple instances of the same feed

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1275]
I'd really like to be able to add the same feed multiple times, but they would behave like like separate feeds and therefore let me have different intelligence training on them. This is especially handy for sites that tend to bunch up all their diverse content into a single feed.

This could probably also be optimized share feed fetching, since they would be sharing the feed url.

**Comment by samuelclay** [comment]
An interesting request but I'm afraid it would clutter up the UI to have some duplicate feeds be true duplicates (as they are now) and some be different. If you really want this to happen and you can code, you can develop a feed proxy that provides different urls. Pretty trivial to build and if you don't know how to do it you could hire somebody on Upwork or Fiverr to do it for you for less than $50.
