### ISSUE TITLE
[Bug] Embedded videos in Kickstarter feeds are broken

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1280]
Videos in kickstarter feeds are broken. As you can see in the picture below, a video will be split up into a static image from the video, and an animated gif of black bars going up and down, like it's visualizing audio.

Example RSS feed: https://www.kickstarter.com/projects/jardar/seablip-a-pirate-adventure/posts.atom
Link to the story in the picture: https://www.kickstarter.com/projects/jardar/seablip-a-pirate-adventure/posts/2745561

![2020-02-04 19 24 52 www newsblur com 281f917547a2](https://user-images.githubusercontent.com/7159527/73775059-75c09800-4785-11ea-909a-aff16a05bb40.png)

**Comment by samuelclay** [comment]
Ok so I took a look and it looks like the code from RSS is fine but the video itself is missing.

https://v.kickstarter.com/1581618001_250889b75f98c991cc6ff0e8285dc9679a80cb00/assets/027/947/653/b2c88c4c6f637b41aedf5402b5a8a971_h264_high.mp4
