### ISSUE TITLE
iPad: Widget issues

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1281]
Two issues, both in this screenshot. One is the single line for the titles, and the other is the layout issue I've seen other people refer to on iPad.

![IMG_0D1E14C1E125-1](https://user-images.githubusercontent.com/44229/73793170-d3e47f80-4773-11ea-9236-a0ec970e7f6a.jpeg)
![IMG_FE3EDAD10A5D-1](https://user-images.githubusercontent.com/44229/73793172-d5ae4300-4773-11ea-85f4-9ab1bcf622ed.jpeg)

**Comment by Dejal** [comment]
I can't reproduce the layout issue. That isn't widget-specific, though; if you can figure out a way to repro it, you can add a new issue.
