### ISSUE TITLE
Android: Add folder

### ISSUE THREAD

**Issue by mxmilkiib** [samuelclay/NewsBlur#1282]
I'm somewhat confused as I cannot find the method of creating folders in the Android interface.

If I hold down on a feed I get the option to "Choose folders", but here is only the top level tickbox available there.

**Comment by mxmilkb** [comment]
From further forum searches, I don't think this exists as a feature as of yet on Android. Could it be possible?

**Comment by samuelclay** [comment]
You're right. I believe this was slated to launch a few years ago and then I have no idea what happened to it. And I can't find the ticket, so this will be it.

Let's add the ability to add a folder when adding a feed. Just make a new dialog once the feed address is entered (or the autocomplete is chosen) and show a folder chooser, with Top Level, + Add Folder, and then all folder names.
