### ISSUE TITLE
Only latest 10 feeds?

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1286]
Hi,
 I am using the latest version of Newsblur on my host, and some feeds only show up the latest 10 articles?
Is there some kind of setting to change this? The weird thing is, that this is only real for some sources, not all.
Thanks

**Comment by yardenac** [comment]
FYI I asked about this a while back on the forums and never got a response https://forum.newsblur.com/t/the-dreaded-ten-ie-aggressively-deleting-feed-item/7171

**Comment by ttimasdf** [comment]
Add this line to your local_settings.py

```py
OVERRIDE_STORY_COUNT_MAX = 1000
```

There are several mechanisms in the codes to save server resources on feeds that are not so popular, which may cause frustrations on self-hosted instances. The one related to this issue:

https://github.com/samuelclay/NewsBlur/blob/ff4eac73bb7f4c8ea1078818f7a77f9e32e56054/apps/rss_feeds/models.py#L1518-L1525

I'm not the developer so you have to found the rest by yourself :p

**Comment by samuelclay** [comment]
Yep, that's correct @ttimasdf, if you change that settings flag you'll have a higher number of stories.

Here's the relevant code:

https://github.com/samuelclay/NewsBlur/blob/master/apps/rss_feeds/models.py#L1482-L1527
