### ISSUE TITLE
iOS: Menu control for marking stories as read on scroll

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1287]
This is for the story list view. Put it in the menu somewhere, just a toggle or switch.

**Comment by samuelclay** [comment]
Oh I didn't mean feed-specific, just in the story list view, since i found I wanted to turn it on and off. But this is fine, too, so long as it's in the menu.

**Comment by Dejal** [comment]
It uses the global preference as the default, and can be overridden on a feed-by-feed basis.  Could be useful for specific feeds.

**Comment by samuelclay** [comment]
Add a preference for "Override on a per-feed/folder basis" (or whatever fits) so it also becomes the discoverable behavior, since if I turn it on for one feed and it's not on for the other, I'm going to think it's broken, but if there are 2 settings (global setting and allow override setting) then it's clearer.
