### ISSUE TITLE
iOS: add folder from move folder popover

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1294]
This move folder popover list should have a Add Folder above the top level just for adding new top level folders. How we allow new sub folders I’m not sure yet but top level is the vast majority of folders so let’s start there. Oh and it opens a single input dialog.

**Comment by samuelclay** [comment]
Why is "Infrequent" showing up as a folder to move to?

**Comment by Dejal** [comment]
It was like that before my changes. Probably because it was added relatively recently, and not explicitly excluded. But I agree should be.
