### ISSUE TITLE
''Connection to the site is not fully secure" site status is shown when logged into the newsblur account on desktop.

### ISSUE THREAD

**Issue by ShockRocky** [samuelclay/NewsBlur#1295]
screenshot :- 
![newsblur 3](https://user-images.githubusercontent.com/46404268/78473645-e8d39400-775f-11ea-895b-0d66f06629bf.jpg)

Even though the site uses https, it seems the images are not encrypted. Is this a bug, as newsblur uses a https proxy for images on the site. From the website :- 

Aug 16, 2019 | Every image on NewsBlur is now behind an https proxy to protect your privacy.
-- | --

It does not show initially when the home page of the RSS feed is displayed, it is only when I select the individual folders, is when the error shows up.

I even made sure all of the sources are use https too, so I don't think it's a source problem.

Browser and OS details :- 

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --

OS | Windows 10 OS Version 1909 (Build 18363.720)

**Comment by samuelclay** [comment]
I just turned on https-only support. I then turned it off temporarily to help some API clients time to push out updates, but I plan to turn it back in next week. Thanks for writing this up!
