### ISSUE TITLE
iOS: Saved searches

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1298]
On web but not iOS or Android. Basically just a special case feed that runs a search query on a feed or folder. Take a look at `saved_search.js` (https://github.com/samuelclay/NewsBlur/blob/master/media/js/newsblur/models/saved_searches.js) to see what the feed id structure is and what the titles of the feed should be. And the saved searches should be listed in the original /reader/feeds call.

**Comment by Dejal** [comment]
I added a couple of saved searches on the website, then fetched the `/reader/feeds` in the app, but it does not include the searches.

Tomorrow I'll do some spelunking in the web code to see if I can find it, but if you can either point to it if available, or add it to `/reader/feeds`, that'd be helpful.

**Comment by Dejal** [comment]
Okay, I see the problem. The iOS app calls `/reader/feeds` with the parameter `flat=true`. The server code calls a [`load_feeds_flat(request)`](https://github.com/samuelclay/NewsBlur/blob/ff4eac73bb7f4c8ea1078818f7a77f9e32e56054/apps/reader/views.py#L347) function, which doesn't output the `saved_searches` properties, unlike the non-flat function.

Can you please add `saved_searches` to the `load_feeds_flat()` result.

I'll put this on hold until that's available.

**Comment by samuelclay** [comment]
> Can you please add saved_searches to the load_feeds_flat() result.

Deployed.

**Comment by Dejal** [comment]
Work on this is underway, but I've run out of time to finish it this month.

Is there an API to add new saved searches, and delete existing ones? A quick look at the [API page](https://newsblur.com/api) didn't reveal them, though they may be undocumented. If there aren't, and you can add them, I could support those functions too. You know that if people can see their searches, they'll want to add or delete them.

**Comment by samuelclay** [comment]
Deployed both endpoints in the API docs. 

https://newsblur.com/api#/reader/save_search
