### ISSUE TITLE
Android: Saved searches

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1299]
On web but not iOS or Android. Basically just a special case feed that runs a search query on a feed or folder. Take a look at `saved_search.js` (https://github.com/samuelclay/NewsBlur/blob/master/media/js/newsblur/models/saved_searches.js) to see what the feed id structure is and what the titles of the feed should be. And the saved searches should be listed in the original /reader/feeds call.

**Comment by sictiru** [comment]
@samuelclay I'm looking to see if saved searches need extra data in the payload for the apps since feed_address might not be very useful. The commit above can only display individual feed saved searches and I'm still working with the web implementation to see all its functionality.

**Comment by samuelclay** [comment]
Folders are the other half of saved searches. Should just match `folder_name`.

**Comment by sictiru** [comment]
@samuelclay I see web has a way of deleting entries from saved searches list. Is there a call I can use for that?

**Comment by samuelclay** [comment]
Yep, here's the details in the API: 

http://nb.local.com/api#/reader/save_search
