### ISSUE TITLE
iOS: App refreshes when returning from another app

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1304]
Using Newsblur on my iPad, I often click links or images to view in Safari. After being done with Safari, I then want to return to Newsblur. I click "Done" in in-app Safari or the Newsblur button in the top left corner when using regular Safari. More often than not, when returning to Newsblur the app will refresh and start syncing stories, completely throwing me out of the story I am reading and showing me the default "All Stories" view.

It also happens sometimes, when I return to Newsblur after watching a video in Youtube.

I've also tried changing the preference "Restore position" to "Never", but that doesn't seem to do anything.

This is extremely infuriating, especially when reading a story, that has multiple links/images I want to view in the browser. Because I have to go through the process of locating the story again and again, because the Newsblur app can't seem to not refresh itself.

**Comment by samuelclay** [comment]
It's weird, I've had this happen to me as well, but it's not consistent. What's happening is that the iPad is running out of memory, so some other process on the device is causing the NEwsBlur app to be taken down by iOS. 

The best we can do is continue to keep NewsBlur's memory footprint as low as possible. We just looked at this and determined there's no way we can fix this, as the memory pressure is coming from outside the app.

Which iPad is it, I'm curious? Mine is 4 years old, and I guess that's enough to make it feel old.

**Comment by Splike** [comment]
@samuelclay, It's a brand new iPad pro 11" 2020 model with 6GB of ram. I highly doubt it's coming from something external, as the app refresh happens consistently.

I'd be happy to help test the issue, as it's making using newsblur on ipad a daunting task for me.

**Comment by Splike** [comment]
I updated to iPadOS 13.5 today.

First I cleared all apps from RAM. Opened Newsblur and clicked a 10 minute YouTube video from a YouTube feed. After watching it in the Youtube app, I swipe the home bar to return to Newsblur and the app refreshes and returns me to the "All stories" page.

I really think this issue should be re-opened, as I'm certain it's not an external factor eating up all the RAM, causing the refresh.

Newsblur on the iPad is basically unusable at the moment because of this, as most of the RSS flow requires opening other apps and returning to quickly open the next story.

This especially sucks for me, as it's one of the primary reasons I bought an iPad in the first place.

**Comment by samuelclay** [comment]
I agree, and this happens to me as well. Not sure how to fix it though...

**Comment by Dejal** [comment]
I just checked the state restoration mechanism, and it is working properly. So please turn on the preference to restore the position.

I also tested doing other things on my iPad Pro, though couldn't get NewsBlur out of memory. More experiments are needed there.

However, I did find an issue where the app could be prematurely killed, due to not correctly ending a background task. That has been fixed.

I'll leave this open for now, and do more experiments, though I don't know if I'll be able to do more.

**Comment by Splike** [comment]
I've turned on the state restoration mechanism and saw instant improvement. I've previously fiddled with it, but didn't find it working at that time.

I do however feel like the experience could be improved. After returning from another app, the list will flash because of the refresh, removing all unread items except of course the one I was looking at last.

The selection of the story is also removed, making me have to click it again to get the selection-coloration.

Would it be possible not to refresh the feed? Or maybe only refresh it after being in another app for a set number of hours?

I'd much rather prefer it didn't automatically refresh and just had a manual refresh button next to the "Read all stories" button at the top. Additionally, the inclusion of "Pull to Refresh" would also be a great fit for the app.

**Comment by Dejal** [comment]
I'm glad you found an improvement.  You can configure a time interval for state restoration in the preferences.

It may be possible to make it work better, though the state restoration was kinda shoehorned into the app, since the architecture wasn't designed with that in mind (since it didn't exist when originally written).

Note that the app does support pull-to-refresh.  Try it.

**Comment by Splike** [comment]
I'll look forward to the possibility of having it be way smoother.

Regarding the pull to refresh, it's present in the main view with all the feeds, but not when viewing a specific feed.

**Comment by samuelclay** [comment]
That's because there is no pull-to-refresh in the feed detail. I suppose we could add it...

**Comment by Splike** [comment]
Since enabling the state restoration, I'm experiencing intermittent issues of being thrown out of my feed and having my ongoing story marked as read, when returning from another app.
Sometimes it works, other times it doesn't.

Also, since the feed refreshes when returning from another app, I will sometimes be shown the first story instead of the one I was on, just because it's further down and hasn't loaded yet.

**Comment by Dejal** [comment]
The work for the Catalyst edition will improve this; see #817 for more info. So I'll close this.
