### ISSUE TITLE
Email Newletters : Wrong Title with Github notifications

### ISSUE THREAD

**Issue by macjl** [samuelclay/NewsBlur#1305]
Hello,

I've set up GitHub to send notifcation e-mail to the 'Email Newsletter' adress of my Newsblur.
I'm receiving all notification, but the title seems wrong :
![2020-04-20 15_54_22-(3) NewsBlur](https://user-images.githubusercontent.com/19387619/79759671-4569ae00-831f-11ea-82cd-eb00c7bc248a.jpg)

As you can see in this print screen, the Title is 'DanielSergienko', as the mail is from 'macjl'. Is this normal? I 've noticed the title is random, but with a name that posted a message recently.

**Comment by samuelclay** [comment]
Can you post the original email? Ideally showing all header fields (which Apple Mail and Gmail can both do). I'm pulling `subject` parameter out of the email:

https://github.com/samuelclay/NewsBlur/blob/master/apps/newsletters/models.py#L76

**Comment by samuelclay** [comment]
I'm going to close this issue but feel free to reply and I'll get to the bottom of it!
