### ISSUE TITLE
iOS: Add preference for showing status bar in full screen mode

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1306]
Pretty straight forward, although I'm not sure it's trivial to implement.

Discussion at https://forum.newsblur.com/t/add-a-preference-to-show-status-bar-on-fullscreen-view-on-ios/7792/3.

**Comment by Dejal** [comment]
You could also point out that they can just left-edge-swipe to go back; don't need to scroll to the top.

Also the full-screen behavior can be disabled in the story menu.

But yeah, showing the status bar while hiding the navigation bar would be a reasonable option, and should be feasible.

**Comment by samuelclay** [comment]
It looks like the status bar now shows up early when swiping back from the story detail view.

**Comment by samuelclay** [comment]
Can we get rid of the shadow and instead make the status bar a solid color to match the theme?

**Comment by Dejal** [comment]
Aww, I liked the fadeout. But sure.

**Comment by samuelclay** [comment]
I admit the shadow was nice when it was over text, but it degraded images too much.

**Comment by samuelclay** [comment]
A few changes for the status bar now in stories:

* Can we add the feed gradient underneath the status bar? 
* This change has made swiping between stories harder because the next story is now scrolled down by the height of the toolbar.
* The status bar often has no background and/or is the wrong color. 
* The story traversal buttons (next/previous/text) now slide down to the bottom of the screen every time I go back into newsblur.

**Comment by samuelclay** [comment]
I'm getting these missing publisher stories

![IMG_B0C9E24B3067-1](https://user-images.githubusercontent.com/44229/82955599-3361d780-9f7d-11ea-95a1-db51f4c825e7.jpeg)
