### ISSUE TITLE
After some months selfhosting, the database performance degrades

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1307]
Hi!

I am using Newsblur now for around over a year, and on different hosts.
And everytime I install and run Newsblur I can see the following behaviour.
At first, the applications runs very fast and my around ~40-50 feeds coming in fast.
But over the time, it seems the database getting more and more "full" (even though all rss items are marked read) - and so the demand on the systems core and ram raise against the sky :-|

Is there any parameter which gets rid of the database old items (like 2 months old - even read - items get deleted from database)?
I think that would help a lot!

Thanks

**Comment by xanthos84** [comment]
As it seems like the dev is not responding,
is someone else able to came up with some kind of "hack" to delete older items in database after some timeframe?
like some query which removes all feed items which are older than 2 months?

**Comment by samuelclay** [comment]
Hi, you can more aggressively archive stories by changing the `story_cutoff` values in https://github.com/samuelclay/NewsBlur/blob/master/apps/rss_feeds/models.py#L1482-L1527
