### ISSUE TITLE
signup not possible - recaptcha wrong after new installation

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1308]
How can I enter the correct recaptcha API keys? settings.py ? and how?
Thanks

**Comment by JasonGhent** [comment]
Form submit from `GET /account/signup` page was not respecting the `ENFORCE_SIGNUP_CAPTCHA` flag for me. Signing up from the signup widget at `GET /` worked for me on latest using docker-compose and the default local_settings.py.template.

**Comment by samuelclay** [comment]
This will be addressed in #1316, but yeah you just need to signup on the homepage.
