### ISSUE TITLE
iOS: Embedded YouTube videos lack fullscreen support.

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1311]
On the web, embedded YouTube videos in both YouTube feeds and other feeds have the option to go fullscreen. This is sadly not the case when viewing feeds on the iPad.

**Comment by Splike** [comment]
Leaving the Newsblur iOS app to watch a video is not at all a pleasant experience, as I've described here: #1304

Also, from what I can tell, embedded videos contain none of the usual YouTube ads.

**Comment by samuelclay** [comment]
I agree, let's see if there's an easy fix for this.

**Comment by Dejal** [comment]
Unfortunately not.  I spent some time experimenting with `WKWebKit` configurations and even overriding the story HTML to change the YouTube `iframe` parameters, without any success. I think it is a Google restriction on embedded videos, limiting it to known browsers.

I'll close this; if anyone has any new information about feasibility, feel free to re-open.

**Comment by Splike** [comment]
@Dejal, Have you seen (this)[https://stackoverflow.com/questions/27404370/embed-youtube-video-in-ios-without-auto-fullscreen]?

**Comment by Dejal** [comment]
Yes, I tried manipulating the HTML to change the parameters, among other things, without success. I might take another look, in case I think of something else.

**Comment by Splike** [comment]
Until then, a temporary solution could be to let us collapse the stories/feed pane. Samuel recently added a button on the web to do this, and it would be a great benefit on iOS, because then an embedded video should in theory expand to take up most of the screen.

**Comment by Dejal** [comment]
A big enhancement to support three-pane view is in the works (#817); that might support hiding other panes when viewing stories, depending on how the UI ends up.

Another option could be a preference to disable inline video playback, which might force it to play them full-screen.
