### ISSUE TITLE
Android: Feed opens the Spotify app and shouldn't

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1315]
From a user email. This feed is causing the Spotify app to open. Let's prevent that from happening except on user interaction.

https://www.vice.com/en_us/article/akw4vk/best-new-music-february-2020

**Comment by sictiru** [comment]
Found a similar article https://www.vice.com/en_us/article/889mk3/24-essential-albums-you-might-have-missed-in-2020 with an embedded Spotify playlist.

From my tests Spotify doesn't open without the user's intent. Setting the app to automatically open all supported links (phone settings) don't change the behavior either.
