### ISSUE TITLE
iOS: Display muted sites in "All" feeds view like on Android

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1325]
Below is a screencap of how Android displays muted feeds when "All" is selected for the feed view.

![2020-06-09 10 38 43](https://user-images.githubusercontent.com/7159527/84126400-242f5f00-aa3e-11ea-9389-8c63ca8ad6f1.jpg)

According to #824, this will be coming to the web as well. This just leaves iOS for coherency.

**Comment by Dejal** [comment]
Hmm. If I add `&include_inactive=true` to the `/reader/feeds` call (i.e. `/reader/feeds?flat=true&update_counts=false&include_inactive=true`), the `feeds` property in the response has a message `Don't include include_inactive=true if you want active feeds.`

Am I missing something? It appears the only way to get the inactive feeds is to do two `/reader/feeds` calls: one to get the active feeds, one to get the inactive ones. I'd rather avoid that overhead.

Any chance you could change the output to have `&include_inactive=true` still output the active `feeds`, in addition to the `inactive_feeds`?

If you want to keep the option of omitting active when getting inactive, perhaps support a new `&include_active=false` option to control whether or not to populate `feeds` (and assume `true` if that parameter isn't specified, to avoid breaking things).

**Comment by samuelclay** [comment]
Looking at the commit that added it (bb2557377fb1eabe0b8ba1867ed5379d7a137dff), I'm not sure why I separated them out. Android doesn't even use the flat feeds, so I'll change it so both are available... done.
