### ISSUE TITLE
iOS: Feed detail menu needs a submenu

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1328]
There's too many options in the feed detail menu. Let's move the following to a "Manage this site" menu. Use the folder icon from "Move to another Folder":

* Delete this site
* Move to another folder
* Rename this site
* Mute this site

**Comment by samuelclay** [comment]
"Delete this site" is showing up on individual story menus

**Comment by Dejal** [comment]
It's supposed to. That was added via #1262.

**Comment by samuelclay** [comment]
You're right! Not sure I agree with that decision but it makes sense as you're able to delete feeds while reading a story on the web because you can see both panes.
