### ISSUE TITLE
"Next unread" in "global shared stories" jumps to next unread in my feeds, not in the shared stories

### ISSUE THREAD

**Issue by fwenzel** [samuelclay/NewsBlur#133]
STR:
* Click on global shared stories, read a few, then jump back to the top, read story.
* Hit "n" to go to the first unread story in the "global shared" category
* Note that it actually takes you to the first unread story in your *subscribed feeds* instead, not in the global shared category.

As far as I can tell, there's no way to jump to the first unread globally shared item, and I can't see why.

**Comment by samuelclay** [comment]
Global Shared Stories are just different. They've always been odd, since the way I make it work is you are effectively loading the popular's account's All Shared Stories river feed but with your own read stories subbing in. It's a hack and it's not perfect.
