### ISSUE TITLE
Android: Auto theme for OS-level dark mode

### ISSUE THREAD

**Issue by snarfed** [samuelclay/NewsBlur#1335]
Android added an OS-level dark mode a while back, and many apps now follow that setting instead of or in addition to their own. This is obviously convenient since it collapses n toggles (one per app) to just one. Any chance you all could add an option for NewsBlur to follow the OS-level setting too?

I've loved the service and app forever, btw. Thanks for all your hard work over the years!

**Comment by samuelclay** [comment]
Sure, let's add a theme called "Auto" which follows the OS theme.
