### ISSUE TITLE
iOS: Style newsletters for dark mode

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1336]
This is a quick issue but one that I fixed on the web and think should apply to iOS. In dark mode, newsletters should be coerced into dark mode, flipping background colors dark and text colors lights.

Here's the code I used to do it on the web. Note that I had to add a NB-newsletter class to the story. These styles shouldn't apply to anything but newsletters.

https://github.com/samuelclay/NewsBlur/blob/master/media/css/darkmode.css#L1172-L1188

**Comment by Dejal** [comment]
I added the newsletter CSS to the two dark mode story CSS, though they don't seem to have any effect.

Do I need to modify the story HTML in some way, to add the `NB-newsletter` class? Surely that should be done server-side?
