### ISSUE TITLE
can someone draw an architecture graph for the project on large scale?

### ISSUE THREAD

**Issue by hpsoar** [samuelclay/NewsBlur#134]
Hi, I'm new to this, and have been getting familiar with it for days, and approximately got to know, how feeds are periodically updated, and how the client fetch feeds from server(local).

If someone can draw an graph about the main modules and how they interact with each other, it would be easier for novice to work with it.

and it should be easier and more accurate for a veteran to do this.

thanks！

**Comment by samuelclay** [comment]
The README now covers this with detail. It's essentially web, db, and task servers, with 4 dibs: postgres/mysql, mongo, redis, and elasticsearch.
