### ISSUE TITLE
Android: Twitter images don't load

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1345]
See https://forum.newsblur.com/t/twitter-images-dont-load-on-android/8248. We've solved this a few ways before but I'd be interested to hear if there's anything we can do and if you can even reproduce the bug.

**Comment by sictiru** [comment]
@samuelclay Based on the provided screen shot I assume the user would like to see `pic.twitter.com/cUNxdMazum` loaded as part of the content. I couldn't find the same story but a similar one would show the image in the `story` mode but it would not be visible for `text` mode. Android behaves the same as Web.

story: `Giga Berlin <a href="https://t.co/UXQMUVTWXf">pic.twitter.com/UXQMUVTWXf</a>`
text: `<img src="https://imageproxy.newsblur.com/sc,sZIWDqqGUItchn4lgRzlOUuLoMcKgBG3wKWU6lmhAphg=/https://img.ibxk.com.br/2020/07/15/15083353345011.jpg" />`

Any suggestions for course of action?

**Comment by samuelclay** [comment]
So what are our options? Sounds to me like the Text view isn't showing the image because the url is malformed?

**Comment by sictiru** [comment]
I assume the text mode story content is generated on our backend? Would there be an option to make an exception for twitter related content and send back an img tag instead of the reference one?

**Comment by sictiru** [comment]
Http urls are swapped with https urls during the story deserialization if the story content contains unsure http links. 
Closing but feel free to reopen on new reports.
