### ISSUE TITLE
Relative image URLs are wrongly resolved when feed domain is different with story URL

### ISSUE THREAD

**Issue by ttimasdf** [samuelclay/NewsBlur#1349]
The use case:

I use Huginn to generate some feeds of my own. RSS address registered in Newsblur is something like `https://huginn.example.com/users/1/web_requests/14/balabala.xml` and the articles are of cource located in another domain. e.g. https://anquan.baidu.com/article/1098. The article contains some `img` tag with relative URL path like `&lt;img src="/upload/ue/image/20190611/1560247617514999.jpg" alt="8.jpg"&gt;`, and Newsblur wrongly concat the URL path with feed address, into `https://huginn.example.com/upload/ue/image/20190611/1560247617514999.jpg`

I located the bug here (at least I thought).

The URI is passed in through

https://github.com/samuelclay/NewsBlur/blob/325a6d26e1b7624fa671fd724501e2ab50f6cce7/utils/feed_fetcher.py#L149-L152

And read at here

https://github.com/samuelclay/NewsBlur/blob/325a6d26e1b7624fa671fd724501e2ab50f6cce7/utils/feedparser.py#L3933-L3936

And finally cause bug at here

https://github.com/samuelclay/NewsBlur/blob/325a6d26e1b7624fa671fd724501e2ab50f6cce7/utils/feedparser.py#L2320-L2321

**Comment by ttimasdf** [comment]
I've made a patch and I thought it works, at least solve my requirements and doesn't change behaviors that much. I'll send a PR later

**Comment by samuelclay** [comment]
Feedparser is actually a vendorized dependency that I change a single line of allowed attributes (to allow for video embeds). If you want to change how feedparser handles absolute urls, let me know if there's a setting I can use (and can then use to absolutize urls later on). 

But to me it feels like the burden to fix the URLs is on Huginn, as it has the correct relative url and changes its meaning without absolutizing those urls. I'm going to close this ticket as I believe the patch should be upstream, but happy to fix it if there's anything I can do.

**Comment by ttimasdf** [comment]
XML/HTML processing is a mess that I'd rather not to handle it by myself 😅 Huginn is not good at manipulating data at large scale (e.g. find and replace lists or URLs) without scripting.

This is the changes I made to feedparser to correct the behavior. despite the logging part only two lines are essential (setting `self.basestack` parts).

I propose to fix this issue in feedparser because it's resolving URL based on a wrong assumption, that the relative URLs inside RSS items are under the same domain as feed URL. The following change makes feedparser resolve the URL (set the `self.baseuri`) based on the URL inside the first `<link>` tag of RSS feed data (the "website address" of a feed), and it will solve most of the problems without changing too much codes.

```patch
diff --git a/utils/feedparser.py b/utils/feedparser.py
index c577f216c..633924ff8 100644
--- a/utils/feedparser.py
+++ b/utils/feedparser.py
@@ -155,6 +155,11 @@ except ImportError:
         from StringIO import StringIO as _StringIO

 # ---------- optional modules (feedparser will work without these, but with reduced functionality) ----------
+try:
+    from utils import log
+except Exception:
+    import logging
+    log = logging.getLogger("feedparser")

 # gzip is included with most Python distributions, but may not be available if you compiled your own
 try:
@@ -1677,6 +1682,9 @@ class _FeedParserMixin:

     def _end_link(self):
         value = self.pop('link')
+        if value and self.infeed and not self.inentry and len(self.basestack) > 1:
+            log.debug("_end_link set baseuri %s => %s" % (self.basestack[-2], value))
+            self.basestack[-2] = value

     def _start_guid(self, attrsD):
         self.guidislink = (attrsD.get('ispermalink', 'true') == 'true')
@@ -3825,6 +3833,7 @@ def parse(url_file_stream_or_string, etag=None, modified=None, agent=None, refer

     :return: A :class:`FeedParserDict`.
     '''
+    log.debug("parse params %s %s %s %s %s %s %s %s" % (url_file_stream_or_string[:100], etag, modified, agent, referrer, handlers, request_headers, response_headers))

     if handlers is None:
         handlers = []
```

**Comment by samuelclay** [comment]
If you can write a test case for this (not the logging but the indeed/inentry/basestack section), propose it to the feedparser team: https://github.com/kurtmckee/feedparser
