### ISSUE TITLE
Android: API 29 Update

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1353]
https://developer.android.com/about/versions/10/behavior-changes-all

**Comment by sictiru** [comment]
[Update commit reference](https://github.com/samuelclay/NewsBlur/commit/b02e404fc9dfb182a508261d2bbee589da6504d0)

@samuelclay Moving to API 29, Preferences are deprecated and there is an AndroidX replacement. I've made the migration but reverted because it requires AppCompat/Material as a theme. Currently the project is using a very old theme style and instead of patching a change just for the Settings page, I'd recommend we do it globally as a separate task. I expect bumps like this to happen more frequent if we need the current theme style. 
This would also be a prerequisite for any future broader UI style changes in the Android project. After the migration, there will be certain UI element that will have a different appearance (top app bar and alert dialogs mainly) but overall it would look the same.

**Comment by samuelclay** [comment]
We have beta 5 in the beta channel. When do you think we should promote it to a full release? After the API 29 update? We need to have the API 29 update done before November IIRC.

**Comment by sictiru** [comment]
I'd make another beta release with the API 29 update included and let it run for one week before going full release. There shouldn't be any issues with this update but with Android's fragmentation I had surprises in the past on some devices when updating the API version.

**Comment by samuelclay** [comment]
Ok v10.1b6 has been released.
