### ISSUE TITLE
Twitter: add the full names on top of the screen names

### ISSUE THREAD

**Issue by rndprt** [samuelclay/NewsBlur#1354]
Following a twitter account creates a feed called 'screen_name on Twitter'. Each tweet is then showed as a story, with the screen name of the author given as author. The issue is that the screen names are not always very explicit, especially for retweets.

The question is to add the full name of the author in the story_author field, for example: `Nilay Patel (@reckless)` instead of only `reckless`.

**Comment by samuelclay** [comment]
Terrific idea. Just deployed. Notice that it won't repeat the screen name if it matches the names. Thanks for the idea!

<img width="557" alt="Screen Shot 2020-08-25 at Aug 25 8 38 06 PM" src="https://user-images.githubusercontent.com/44229/91241479-f68bb500-e712-11ea-9ec5-a0198b68a7a6.png">
