### ISSUE TITLE
Android: Add in app review API

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1364]
https://developer.android.com/guide/playcore/in-app-review

Show the rating dialog after a user swipes back to the feed list from the story list.

**Comment by sictiru** [comment]
@samuelclay I'll need your help to finish testing the in app review dialog. Looking to do so via the [Internal test track in Play Store](https://developer.android.com/guide/playcore/in-app-review/test#internal-test-track)

**Comment by samuelclay** [comment]
Ok, v10.1b7 is released to the Internal Test Track. Let me know how that goes and I'll promote it to the beta track. Also, do you think we're ready for a general release? Things are feeling pretty good now.

**Comment by sictiru** [comment]
@samuelclay Yes I believe v10.1.b6 can be promoted to production.

**Comment by sictiru** [comment]
Testing was a success.

**Comment by samuelclay** [comment]
Ok, deploying v10.1b7 to production as v10.1.
