### ISSUE TITLE
Android: Unsaving a story not working

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1367]
From a user email: 

> When I unsaved a article on laptop or iPad, it still appears in Saved folder in Android. This bug has existed for at least 6 months.

Not sure what's happening, since when I went to reproduce it I could unsave a recently saved story fine. Maybe try reproducing it yourself and inspecting the code paths?

**Comment by sictiru** [comment]
Tried to reproduce by combining story save/unsave actions between Web, iOS and Android, but without any success. The only thing that comes to mind is that the local db is not synced in real time between devices but after a local refresh it always applied the save/unsave action in my tests.
