### ISSUE TITLE
iOS: block quotes on dark mode show wrong color

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1368]
See screenshot

![2BD675F3-5AD8-4E05-AD51-DE7C4BD8A8C3](https://user-images.githubusercontent.com/44229/93475396-8c57d180-f8c6-11ea-8540-2d4a0edac7d9.png)

**Comment by Dejal** [comment]
Fixed. If you want any other issues fixed/changed now, rather than after the three-pane stuff, please mark them as `Critical`, or add a comment indicating priority. Otherwise, I will be prioritizing that project.
