### ISSUE TITLE
iOS: In full screen mode, tapping on the story content hides the feed bar

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1371]
The feed bar should stay visible. While we're here, it would also be nice if the feed bar could stay pinned to the top but then scroll with the story content when dragged down. Similar to how the story traversal buttons are pinned to the bottom but then scroll with the story content when dragged up. So yes, this issue is a two-fer.

**Comment by Dejal** [comment]
I will be making changes to the implementation of the fullscreen feature as part of the big Catalyst-related project, so unless this is really bothersome, I'd prefer to defer this until after that.

**Comment by samuelclay** [comment]
Sounds good to me, we can close this issue then.

**Comment by Dejal** [comment]
Old issue, no longer applicable.
