### ISSUE TITLE
iOS: Can no longer tap on title of YouTube video to open in YouTube app

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1375]
Previously if I had subscribed to a YouTube feed in NewsBlur I could tap on the title of the YouTube video to open it in the YouTube app. Now I have to tap, hold and choose “Open Link” to get this to happen.

**Comment by samuelclay** [comment]
Tapping on a YT title opens the in app browser for me. Did it ever open in the YT app?

**Comment by nriley** [comment]
In previous NewsBlur iOS versions (for years), tapping the title of the video opened the YouTube app (not the in-app browser). You can still do this if you tap and hold and choose 'open link', but now single-tapping does nothing. Tapping the icon of the channel does open the channel in the in-app browser.

This could have been a coincidental change on the YouTube side, not necessarily something that changed in the iOS app.

**Comment by Dejal** [comment]
NewsBlur doesn't have any visibility into how taps on a YouTube `IFRAME` is handled; that's something handled by YouTube. So I'll close this.
