### ISSUE TITLE
Android: Why use image proxy for all images?

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1380]
A very curious issue was raised by a user here: https://forum.newsblur.com/t/android-broken-images-served-through-image-proxy/8373

It looks like if you subscribe to the feed at http://feeds.feedburner.com/SlickdealsnetFP all of the images are broken on Android. It looks like the rewriting image urls to use the secure image proxy is causing the issue. I should fix the image proxy, but I'm also left wondering why Android chooses to use the image proxy for everything? The image proxy should only be used on the web for images that are http. 

On Android you can load http images just fine. So let's do that and not use the image proxy at all.

**Comment by sictiru** [comment]
Android doesn't play well with http on API 28+. Modified code from https://github.com/samuelclay/NewsBlur/issues/1274 to correctly handle http and https urls within the same content
