### ISSUE TITLE
Android: Upgrading to premium unmutes all muted feeds

### ISSUE THREAD

**Issue by whispy** [samuelclay/NewsBlur#1384]
(Apologies for lack of information, on my phone)

Steps To Reproduce:
1. Have 65/64 feeds (not sure if required)
2. Upgrade to Premium

Expected Result: Muted feeds would stay muted

Actual Result: All feeds unmuted.

**Comment by sictiru** [comment]
@whispy I tried to reproduce the bug but I need your help to understand it better.
Assuming you were redirected to the Mute Sites screen:
Did you click "Upgrade" on the modal, without interacting further with the Mute Sites screen?

If instead you clicked "OK" on the modal:
Was the "Reset to popular sites" button used?
Were actions taken via the overflow menu? (the vertical 3 dots)

**Comment by whispy** [comment]
@sictiru I don't remember the exact sequence of events. I think it was:
1. Add one too many sites
2. Be taken to Mute Sites screen
3. Upgrade from the Mute Sites screen
4. (Don't recall but don't think I interacted with any Mute Sites screen actions)
5. All sites were unmuted

I know that was vague. I wasn't paying too much attention when it happened.

Do you have some debug accounts I could try to reproduce with? Maybe 2-3 accounts with 64/64 feeds, and then I try walking through my process. Or any other suggestions as to how I could walk through it?

**Comment by whispy** [comment]
@sictiru I don't remember the exact sequence of events. I think it was:
1. Add one too many sites
2. Be taken to Mute Sites screen
3. Upgrade from the Mute Sites screen
4. (Don't recall but don't think I interacted with any Mute Sites screen actions)
5. All sites were unmuted

I know that was vague. I wasn't paying too much attention when it happened.

Do you have some debug accounts I could try to reproduce with? Maybe 2-3 accounts with 64/64 feeds, and then I try walking through my process. Or any other suggestions as to how I could walk through it?

**Comment by samuelclay** [comment]
This is the fault of the backend. It's known behavior and somewhat expected as free accounts only have 64 feeds they can be subscribed to while the rest are muted. Upgrading re-enables all of your feeds. So that's what's happening. I don't like the idea of having two different muting mechanisms, so the tradeoff is that going from free to premium enables all feeds, which is expected.
