### ISSUE TITLE
Android: In-App Browser Improvements

### ISSUE THREAD

**Issue by whispy** [samuelclay/NewsBlur#1385]
Pulling this comment out from the original in-app browser thread to highlight some improvements that could be made:

> @samuelclay it's working great so far! There are just 3 areas that could be improved:
> 
> 1. I think the back button should unwind links instead of going directly back to story. But, that's personal preference.
> 2. User should be able to copy the URL of the currently viewed page (e.g. if they navigate several links deep past the story and want to extract the URL for archiving or sharing)
> 3. User should be able to tap-and-hold to copy inline links.

_Originally posted by @whispy in https://github.com/samuelclay/NewsBlur/issues/1319#issuecomment-699493677_

**Comment by whispy** [comment]
4. Do not refresh page when decide is rotated.

**Comment by samuelclay** [comment]
On (1), there should be a way to unwind links as well as return to the story. On iOS that's achieved with a separate back/forward browser chrome toolbar a the bottom of the screen and a normal view back button at top that takes you back to the story.

We should absolutely support (2).

I checked and the behavior for (3) is that long-pressing a link shows the share link menu, which includes copy.

(4) is long-standing and will take a lot of developer time to fix. I'd love to support it though! I'll separate that one out.

**Comment by samuelclay** [comment]
Just checked and it looks like scroll position is restored when rotating, which is a pretty good way of addressing the issue.

**Comment by whispy** [comment]
@samuelclay 

For (1), are you saying this method should already exist on Android? I don't see it at all on 10.1.1.

(2) - nice, looking forward to it!

(3) - that is not the behavuor I see. When long-pressing, the device will do a short pulse vibrate after pressing for ~1 second. However, no share menu displays. I can provide a screen recording, if you'd like.

(4) - scroll position is restored in extracted Newsblur content, but not in-app browser content. In fact, if I am 3 pages deep in the in-app browser and rotate my device, it brings me back to the 1st page.

If relevant, I currently have Android System Webview 87.0.4280.66 installed.

**Comment by samuelclay** [comment]
#1390

**Comment by samuelclay** [comment]
Ok added #1390 to capture (4). 

Please upload a video to capture (3).

**Comment by whispy** [comment]
Here's a screen recording capturing (4):
https://www.dropbox.com/s/9jcc5enkdq2bzsp/InShot_20201205_180306164.mp4?dl=0

Please let me know if I can provide more info. Thanks!

**Comment by samuelclay** [comment]
Just tested this on my Pixel 2 and long press is now working on the in app browser.
