### ISSUE TITLE
Reset intelligence trainer on unsubscribed feeds

### ISSUE THREAD

**Issue by teddybradford** [samuelclay/NewsBlur#1388]
Sometimes I'll add a feed, use some intelligence training filters on it, then later delete the feed. My expectation is that when deleting the feed, the filters would get deleted too, however, when I re-add the feed it seems those filters are still applied.
If there is a long time between deleting and re-adding a feed (say, a few months or a year) it's not always clear that there are filters applied to the feed, which creates some confusion.

It would be nice to either 1) delete filters when deleting a feed, or 2) have an option to delete filters from unsubscribed feeds.

**Comment by samuelclay** [comment]
I'm partial to (2) but honestly I think a dialog just for removing training along with a site is overkill. I don't think training should be deleted though. It's easy enough to delete training and you can use the Intelligence Trainer on a site and see all of the training in a single screen.

**Comment by teddybradford** [comment]
That’s fair. Perhaps there could be some indicator/warning shown when re-adding a feed that has existing filters? There have been a few times when I’ve re-added feeds after long periods of time and forgotten they had filters, so a reminder to make sure the filters are still relevant would be helpful.

**Comment by samuelclay** [comment]
Might make more sense to mute the feed instead of deleting it, if you think you might be resubscribing to it.
