### ISSUE TITLE
Android: Gesture navigation for "back" is also interpreted as a normal left swipe

### ISSUE THREAD

**Issue by novoid** [samuelclay/NewsBlur#1396]
Hi,

After [switching from OnePlus 5 (Android 9; virtual button navigation) to Pixel 4a](https://karl-voit.at/2020/11/15/pixel4a-migration) (Android 11, latest OS patch level) with _gesture navigation enabled_, I noticed within my NewsBlur v10.2.0 an issue that is a nasty one:

When I am within a feed and I do the gesture navigation for "back" (swiping to the left with crossing the display border - I prefer the right border), **NewsBlur _sometimes_ additionally(!) interprets the "back" action as a normal left swipe** which is mapped to "Save this story" at my current setup.

I noticed that behavior by finding articles in my list of "saved articles" which were clearly not "saved" by myself.

The bad thing is that the user doesn't recognize the mis-interpreted swipe action because the intended (back) action is executed as normal. Furthermore, the app executes the "left swipe" action many times when the "back" action is executed. This has different implications, depending on the current "left swipe" action mapped within NewsBlur.

**My expectation** would be that when the users does a "back" action, no "left swipe" action is executed within NewsBlur.

**Comment by sictiru** [comment]
@novoid Replicating with an OnePlus 6T and a Pixel 3a, both with navigation gestures enabled, was unsuccessful. 
The OS will either intercept the "back" action, or the left swipe is received within NewsBlur, saving the story. 

It would be helpful if you could record an instance of the issue with the tap pointer enabled from the developer settings. The one that shows where you're touching the screen.

Meanwhile I'm keeping left swipe mapped to "save story: action on my phone (using the right screen edge too) for the next month to keep an eye on it.

**Comment by novoid** [comment]
@sictiru Thanks for your reply.
I've done a screencast that shows the issue: from five left-swipe-actions, two are also mis-interpreted as a "save" action.

I tried to upload to imgur but got rejected. Then I tried to upload it here but it exceeds the limit of 10MB. So I provide you the link via my personal web space but I'll remove the video as soon as you've seen it: [Screencast video](https://Karl-Voit.at/temp/2021-01-11T19.05.23_screencast_NewsBlur_2-out-of-5.mp4)

As you can see, it does not "work" all the time. I've got the impression that "save"-action is more "sensible" compared to "mark as unread" action. At least I was not able to replicate this behavior for a screencast with the "mark as unread" action mapped to the left-swipe. This would be funny somehow so I'm unsure if this is a wrong impression of mine.

It is worth mentioning that I do use a rather thick smartphone case. Maybe it does "cover up" the border a bit. However, I would have guessed that _even in this case_, the "wrong action" would not be followed by the back action. Both at the same time are unusual IMHO.

**Comment by sictiru** [comment]
@novoid Thanks for the video, it was very helpful to see exactly what's going on. After many, many swipes I could replicate it and find a solution that I think solves the issue. Take a look once it hits beta/production and let me know how it goes.
