### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [samuelclay/NewsBlur#1397]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by samuelclay** [comment]
We don't maintain the F-Droid repo, but if there's somebody who does, screenshots are available in 

https://github.com/samuelclay/NewsBlur/tree/master/media/img/android

**Comment by shuvashish76** [comment]
@IzzySoft request to provide fastlane metadata from PlayStore & merge with F-Droid.
