### ISSUE TITLE
Add default styling to newsletters

### ISSUE THREAD

**Issue by ktosiek** [samuelclay/NewsBlur#1406]
Currently Robin Rendle's newsletters renders badly when opened in a new tab: pictures are wider than the browser, and often even the screen. For example https://www.newsblur.com/newsletters/story/7706944:609ca4 has 3024px wide `<img/>`s.

Maybe it would make sense to have some very basic default styling for stand-alone newsletter articles? I'm thinking about things like `body { max-width: 90ch; margin: auto; }`, to handle very wide screens, or `img { max-width: 100%; }` to make sure images don't "jump out" of the viewport.

**Comment by samuelclay** [comment]
Hey, can you post a screenshot of this? I can't see that newsletter story due to privacy settings but if you don't feel comfortable sharing it here feel free to email me at samuel@newsblur.com.

**Comment by samuelclay** [comment]
By the way, NewsBlur already does quite a bit of shapeshifting to get newsletters to fit correctly into the news reader experience. I already have to do some gymnastics to get the images to fit best in most cases.
