### ISSUE TITLE
Feature Request: Gemini Support

### ISSUE THREAD

**Issue by ecliptik** [samuelclay/NewsBlur#1407]
This is a request to add support for the [Gemini Protocol](https://gemini.circumlunar.space), which is a newer Internet protocol more lightweight than http and require TLS.

Gemini sites have the ability to [serve an XML feed similar to RSS](https://tildegit.org/solderpunk/gemfeed), and the request is for Newsblur to understand `gemini://` and read in a feed similar to an `http://` site.

An example feed is here: gemini://rawtext.club/~ecliptik/_posts/feed.xml

**Comment by samuelclay** [comment]
This is a neat project. Between gopher and http but so far it's pretty tiny. I'm going to punt on this and honestly if you want NewsBlur to support a new protocol, make the change upstream in the feedparser repo.

**Comment by kholbekj** [comment]
Just want to comment here (as I also thought this would be a great feature), that feedparser rejected such an idea https://github.com/kurtmckee/feedparser/issues/266 based on the fact that this is doable with existing dependencies. I'm not deep enough in this to make a contribution, but just in case you ever reconsider :)

**Comment by sjehuda** [comment]
Parsing Gemini Feed.

```py
from urllib.parse import urljoin

class Gemini:

    def gemini_feed(uri: str, content: str) -> dict:
        feed = []
        for line in content.split('\n'):
            if line.startswith('=>'):
                line_split = line.split()
                entry = {
                    # 'content' : 'Content and summary would require download.',
                    'date' : line_split[2],
                    'link' : urljoin(uri, line_split[1]),
                    # 'summary' : 'First line after title should probably be summary.',
                    'title' : ' '.join(line_split[3:]) if len(line_split) > 3 else 'No title'
                    }
                feed.append(entry)
        return feed
```

It appears that `urljoin` does not work properly for Gemini URI scheme, albeit it does work with Gopher URI scheme.

---


Download from Gemini.

```py
import Agunua

class Gemini

    def download(uri: str) -> dict:
        data = Agunua.GeminiUri(uri, get_content=True, maxsize=5000000)
        if data.network_success and data.status_code == '20':
            result = {
                'charset': data.charset,
                'content': data.payload,
                'content_length': data.size,
                'content_type': data.mediatype,
                'error': None,
                'message': data.error,
                'original_url': uri,
                'status_code': data.status_code,
                'response_url': data.url}
            return result
```

**Comment by sjehuda** [comment]
(Off topic) This comment will be deleted.

@ecliptik Please see gemini://woodpeckersnest.space/~schapps/tutorial/2024-11-23-html-custom-syndication-feed.gmi

For your HTML site https://www.ecliptik.com/
