### ISSUE TITLE
Initial river of news view shows "select a story to read"

### ISSUE THREAD

**Issue by jgbishop** [samuelclay/NewsBlur#1409]
A few days ago, the "river of news" view stopped initializing properly when first visiting NewsBlur. All I see when I initially visit the site (or when I press Ctrl+E to "open everything") is the "Select a story to read" blank page. If I navigate to the next or previous story (with J or K), the page updates to show the items in my feeds.

I'm using Chrome 88.0.4324.150, which is the latest (as of this writing) on Windows 10. Here are some of my preferences, if it helps:

* Default folder is "All Site Stories"
* Default feed layout is "Full"
* Default feed view is "Feed"
* Default story order is "Oldest / Unread Only"

**Comment by jgbishop** [comment]
This may be unrelated, but I see these console messages as I navigate:

    ["Hijacking view setting", 6124077, " --> ", 6124077, "feed"]

**Comment by samuelclay** [comment]
Is this still an issue? By the way, do you notice the problem on beta.newsbur.com?

**Comment by jgbishop** [comment]
I no longer see this issue.
