### ISSUE TITLE
broken favicons on docker_django3.1

### ISSUE THREAD

**Issue by robsee** [samuelclay/NewsBlur#1413]
docker-compose.yml  for favicons needs to be changed from MONGO_PORT=29019 to MONGODB_PORT=29019

**Comment by jmath1** [comment]
added to the dashboard3 branch

**Comment by robsee** [comment]
Is dashboard3 the branch I should be using, or is docker_django3.1 the right one

**Comment by samuelclay** [comment]
You'll want to use dashboard3, which is downstream of docker_django3.1. If you run it you'll notice quite a few UI refinements that have yet to launch on newsblur.com.
