### ISSUE TITLE
Backend: Refinements to README for Docker builds

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1414]
This email came in from a developer who is on the `dashboard3` branch and is attempting to run `make nb` and have everything work. Let's resolve these issues in the README for others to use.

> I was able to get the Docker container up but not quite running. 
>
> The new container install instructions weren't clear if any changes needed to be made to the docker-compose file (like for the hostname/domain name)? In the Readme you mention 
"make nb and then navigate to: https://nb.local.com"
> 
> Is that all that is required? Or should I be substituting my hostname in? For this release do I need to preload the JSON data file, or run a makemigration/migrate first? And is that literally the address to use? (if so, maybe I have a DNS issue)
>
>I was getting some haproxy bind errors because I am running some servers (PiHole and NextCloud) on other ports and wanted to change the ports for the NewsBlur server (say to use 8080 instead of 80 and 8443 instead of 443).

**Comment by jmath1** [comment]
I believe the problem is that you need to update /etc/hosts to have `127.0.0.1 nb.local.com`. I'm updating the README now. If you want to use port 8443 and 8080 instead of 443 and 80, just change the line in the docker-compose file to `8443:443` and `8080:80` instead of `443:443` and `80:80`.

**Comment by dougleclair** [comment]
> 
> 
> I believe the problem is that you need to update /etc/hosts to have `127.0.0.1 nb.local.com`. I'm updating the README now. If you want to use port 8443 and 8080 instead of 443 and 80, just change the line in the docker-compose file to `8443:443` and `8080:80` instead of `443:443` and `80:80`.

Thank you for the advice,  jmath1! I tried rebuilding the Docker container and adding in the host name to the /etc/hosts file. I confirmed that the host pings fine but for some reason the container doesn't seem to respond to requests on either of those ports (by host name or IP), I can only get to the web server on port 8000. For the port settings I assume you mean changing the settings for haproxy in the docker compose file.

I noticed when I did the initial make nb I got the error:

ERROR: Service 'haproxy' failed to build: COPY failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder543758631/docker/haproxy/haproxy.dev.conf: no such file or directory

I tried copying haproxy.cfg to haproxy.conf, and haproxy.dev.cfg to haproxy.dev.conf and the make completes without any errors but I am not sure if that is the problem, and do any modifications need to be made in those configs? Thanks again!

**Comment by jmath1** [comment]
we have been making changes in this branch and if you are trying to use docker/haproxy/haproxy.dev.conf then it is likely that you need to do a `git pull` because that file was recently renamed and there may be other changes that you are missing as well. Also, did you make the ssh keys? I see that the makefile doesnt automatically build keys with the `make nb` command although it was intended to do so. I will update it now in the dashboard3 branch

**Comment by dougleclair** [comment]
> 
> 
> you need to do a `git pull` because that file was recently renamed and there may be other changes that you are missing as well. Also, did you make the ssh keys? I see that the makefile doesnt automatically build keys with the `make nb` command although it was intended to do so. I will update it now in the dashboard3 branch

Thank you for the reply! I did a pull yesterday and the make worked without error, 
I noticed the certificate issue:

[[ -d config/certificates ]] && echo "keys exist" || rm -r config/certificates
/bin/sh: 1: [[: not found
rm: cannot remove 'config/certificates': No such file or directory
make: [Makefile:15: nb] Error 1 (ignored)

I already have an SSL cert from LetsEncrypt, should I use that or is there another command I should run to generate one?

**Comment by jmath1** [comment]
I just made some commits that fix that issue moments before your comment. please pull and you should see it.

**Comment by dougleclair** [comment]
Thank you! Although the new version generated an SSL certificate without any problems, this error still is showing up right before:

[[ -d config/certificates ]] && echo "keys exist" || make keys
/bin/sh: 1: [[: not found

After it completes, if I check netstat there is still nothing listening on the configured ports. And https://nb.local.com is inaccessible. I can only get to port 8000, but not to SSL or web ports set for haproxy even though it is set correctly in the hosts file.

**Comment by jmath1** [comment]
can you tell me which containers are up and running? if there are any that are down, please share the logs.... in regard to your `/bin/sh: 1: [[: not found` issue, this is designed for bash and you are using shell when you execute the Makefile. You can probably get that error to go away by adding `/bin/bash` to the beginning of the line that line that is causing that error.

**Comment by jmath1** [comment]
also please share the output of the `make nb` command if you see anything that might be helpful there

**Comment by dougleclair** [comment]
Here are the running containers:

CONTAINER ID        IMAGE                       COMMAND                   CREATED             STATUS              PORTS                                                              NAMES
c8f34a0d059d        nginx:1.19.6                "/docker-entrypoint.…"    46 seconds ago      Up 44 seconds       80/tcp, 0.0.0.                             0:81->81/tcp            nginx
98d6bf060ada        newsblur/newsblur_python3   "bash -c 'if [[ -z \"…"   47 seconds ago      Up 45 seconds       8000/tcp                                                           newsblur_web
dc6918d292a7        newsblur/newsblur_node      "docker-entrypoint.s…"    52 seconds ago      Up 48 seconds       0.0.0.0:3030->                             3030/tcp                node_favicons
d82c21068dc2        newsblur/newsblur_node      "docker-entrypoint.s…"    56 seconds ago      Up 50 seconds       0.0.0.0:8888->                             8888/tcp                node_websocket
a6c80311a60d        mongo:3.6                   "docker-entrypoint.s…"    56 seconds ago      Up 47 seconds       27017/tcp, 0.0                             .0.0:29019->29019/tcp   db_mongo
b7149847488d        newsblur/newsblur_node      "docker-entrypoint.s…"    56 seconds ago      Up 49 seconds       0.0.0.0:4040->                             4040/tcp                node_original_text
fb2917ebfda8        newsblur/newsblur_python3   "bash -c 'python /sr…"    56 seconds ago      Up 48 seconds       0.0.0.0:5579->                             5579/tcp                monitor
27c0201efb26        redis:3.2.6                 "docker-entrypoint.s…"    56 seconds ago      Up 48 seconds       6379/tcp, 0.0.                             0.0:6579->6579/tcp      redis
aa7c5fd5a139        elasticsearch:2.4.4         "/docker-entrypoint.…"    56 seconds ago      Up 50 seconds       0.0.0.0:9200->                             9200/tcp, 9300/tcp      elasticsearch
aca8afa1bb81        postgres:13.1               "docker-entrypoint.s…"    56 seconds ago      Up 51 seconds       0.0.0.0:5434->                             5432/tcp                postgres
5d9e45bda40d        newsblur/newsblur_node      "docker-entrypoint.s…"    56 seconds ago      Up 52 seconds       0.0.0.0:3060->                             3060/tcp                node_original_page

The stopped containers are:


CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                     PORTS               NAMES
f0900fef2183        newsblur-dashboard3_haproxy   "/docker-entrypoint.…"   6 minutes ago       Exited (1) 6 minutes ago                       haproxy
c2ba7a679b7c        newsblur/newsblur_python3     "celery worker -A ne…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd_search_indexer
4da2d556dc78        newsblur/newsblur_python3     "celery worker -A ne…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd
e69112ddb2bd        newsblur/newsblur_python3     "bash -c 'mkdir -p d…"   6 minutes ago       Exited (2) 6 minutes ago                       celerybeat
777a1527d923        newsblur/newsblur_python3     "celery worker -A ne…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd_search_indexer_tasker
6d9e0d2abcee        newsblur/newsblur_python3     "celery worker -A ne…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd_news
632dddbe9a00        newsblur/newsblur_python3     "celery worker -A ne…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd_beat
8876390fa933        newsblur/newsblur_python3     "celery worker -A ne…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd_beat_feeds
9d6a61b67c35        newsblur/newsblur_python3     "bash -c 'celery wor…"   6 minutes ago       Exited (2) 6 minutes ago                       celeryd_work_queue
7c09ad60806d        newsblur                      "gunicorn --bind 0.0…"   3 days ago          Exited (3) 3 days ago                          distracted_montalcini

So for some reason haproxy and the celery containers are not coming up. How can I pull the logs?

I do get this error on make nb:

2 moderate severity vulnerabilities
Some issues need review, and may require choosing a different dependency.

if i run npm audit I get:

npm audit
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

Thanks again! :)

**Comment by dougleclair** [comment]
Some log info:

[2021-02-21 19:29:22 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2021-02-21 19:29:22 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2021-02-21 19:29:22 +0000] [6] [INFO] Using worker: sync
[2021-02-21 19:29:22 +0000] [9] [INFO] Booting worker with pid: 9
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:41]  ---> GET / {}
[Feb 21 19:29:41]  ---> [FF    ] [0.06s] [AnonymousUser] Loading welcome
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:42]  ---> GET /reader/feeds {'v': '2', 'update_counts': 'false'}
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:43]  ---> POST /reader/save_dashboard_river {'river_id': 'river:', 'river_side': 'left', 'river_order': '0'}
[Feb 21 19:29:43]  ---> [FF    ] [0.00s] [AnonymousUser] Saving dashboard river: river: (left 0)
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:43]  ---> POST /reader/save_dashboard_river {'river_id': 'river:infrequent', 'river_side': 'left', 'river_order': '1'}
[Feb 21 19:29:43]  ---> [FF    ] [0.00s] [AnonymousUser] Saving dashboard river: river:infrequent (left 1)
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:43]  ---> POST /reader/save_dashboard_river {'river_id': 'river:global', 'river_side': 'left', 'river_order': '2'}
[Feb 21 19:29:43]  ---> [FF    ] [0.00s] [AnonymousUser] Saving dashboard river: river:global (left 2)

**Comment by dougleclair** [comment]
Got the haproxy container up and running. Had to change the domain in docker/data.json from

"domain": "docker.newsblur.com",

to:

"domain": "nb.local.com",

The celery containers are still showing as exited and while the home page is coming up now, I still can't log in.

**Comment by samuelclay** [comment]
Are you sure you're running the latest `dashboard3`? The gunicorn version is not correct. You have v20 but I had to downgrade to v19 (specifically `gunicorn==19.7.1`) due to some issues the gunicorn team is working through.

**Comment by dougleclair** [comment]
> 
> 
> Are you sure you're running the latest `dashboard3`? The gunicorn version is not correct. You have v20 but I had to downgrade to v19 (specifically `gunicorn==19.7.1`) due to some issues the gunicorn team is working through.

I am pretty sure I have the current version, I downloaded the zip file from the main tree. Is there something else I could try?

**Comment by jmath1** [comment]
it looks like you arent using the latest newsblur/newsblur_node image. Please remove your current image with `docker image rm newsblur/newsblur_node --force` and try bringing it up again. This is causing nginx to fail which is causing haproxy to fail.
