### ISSUE TITLE
Docker: Unable to identify subdomain for request warning

### ISSUE THREAD

**Issue by dougleclair** [samuelclay/NewsBlur#1416]
I am able to get Dashboard3 up and partially running on Ubuntu 20.04 LTS. But I am receiving the following error: "The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request" and for some reason the haproxy and celery containers exit and won't stay up.

Here are the running containers:

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
c8f34a0d059d nginx:1.19.6 "/docker-entrypoint.…" 46 seconds ago Up 44 seconds 80/tcp, 0.0.0. 0:81->81/tcp nginx
98d6bf060ada newsblur/newsblur_python3 "bash -c 'if [[ -z "…" 47 seconds ago Up 45 seconds 8000/tcp newsblur_web
dc6918d292a7 newsblur/newsblur_node "docker-entrypoint.s…" 52 seconds ago Up 48 seconds 0.0.0.0:3030-> 3030/tcp node_favicons
d82c21068dc2 newsblur/newsblur_node "docker-entrypoint.s…" 56 seconds ago Up 50 seconds 0.0.0.0:8888-> 8888/tcp node_websocket
a6c80311a60d mongo:3.6 "docker-entrypoint.s…" 56 seconds ago Up 47 seconds 27017/tcp, 0.0 .0.0:29019->29019/tcp db_mongo
b7149847488d newsblur/newsblur_node "docker-entrypoint.s…" 56 seconds ago Up 49 seconds 0.0.0.0:4040-> 4040/tcp node_original_text
fb2917ebfda8 newsblur/newsblur_python3 "bash -c 'python /sr…" 56 seconds ago Up 48 seconds 0.0.0.0:5579-> 5579/tcp monitor
27c0201efb26 redis:3.2.6 "docker-entrypoint.s…" 56 seconds ago Up 48 seconds 6379/tcp, 0.0. 0.0:6579->6579/tcp redis
aa7c5fd5a139 elasticsearch:2.4.4 "/docker-entrypoint.…" 56 seconds ago Up 50 seconds 0.0.0.0:9200-> 9200/tcp, 9300/tcp elasticsearch
aca8afa1bb81 postgres:13.1 "docker-entrypoint.s…" 56 seconds ago Up 51 seconds 0.0.0.0:5434-> 5432/tcp postgres
5d9e45bda40d newsblur/newsblur_node "docker-entrypoint.s…" 56 seconds ago Up 52 seconds 0.0.0.0:3060-> 3060/tcp node_original_page

The stopped containers are:

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f0900fef2183 newsblur-dashboard3_haproxy "/docker-entrypoint.…" 6 minutes ago Exited (1) 6 minutes ago haproxy
c2ba7a679b7c newsblur/newsblur_python3 "celery worker -A ne…" 6 minutes ago Exited (2) 6 minutes ago celeryd_search_indexer
4da2d556dc78 newsblur/newsblur_python3 "celery worker -A ne…" 6 minutes ago Exited (2) 6 minutes ago celeryd
e69112ddb2bd newsblur/newsblur_python3 "bash -c 'mkdir -p d…" 6 minutes ago Exited (2) 6 minutes ago celerybeat
777a1527d923 newsblur/newsblur_python3 "celery worker -A ne…" 6 minutes ago Exited (2) 6 minutes ago celeryd_search_indexer_tasker
6d9e0d2abcee newsblur/newsblur_python3 "celery worker -A ne…" 6 minutes ago Exited (2) 6 minutes ago celeryd_news
632dddbe9a00 newsblur/newsblur_python3 "celery worker -A ne…" 6 minutes ago Exited (2) 6 minutes ago celeryd_beat
8876390fa933 newsblur/newsblur_python3 "celery worker -A ne…" 6 minutes ago Exited (2) 6 minutes ago celeryd_beat_feeds
9d6a61b67c35 newsblur/newsblur_python3 "bash -c 'celery wor…" 6 minutes ago Exited (2) 6 minutes ago celeryd_work_queue
7c09ad60806d newsblur "gunicorn --bind 0.0…" 3 days ago Exited (3) 3 days ago distracted_montalcini

Some log info:

[2021-02-21 19:29:22 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2021-02-21 19:29:22 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2021-02-21 19:29:22 +0000] [6] [INFO] Using worker: sync
[2021-02-21 19:29:22 +0000] [9] [INFO] Booting worker with pid: 9
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:41] ---> GET / {}
[Feb 21 19:29:41] ---> [FF ] [0.06s] [AnonymousUser] Loading welcome
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:42] ---> GET /reader/feeds {'v': '2', 'update_counts': 'false'}
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:43] ---> POST /reader/save_dashboard_river {'river_id': 'river:', 'river_side': 'left', 'river_order': '0'}
[Feb 21 19:29:43] ---> [FF ] [0.00s] [AnonymousUser] Saving dashboard river: river: (left 0)
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:43] ---> POST /reader/save_dashboard_river {'river_id': 'river:infrequent', 'river_side': 'left', 'river_order': '1'}
[Feb 21 19:29:43] ---> [FF ] [0.00s] [AnonymousUser] Saving dashboard river: river:infrequent (left 1)
The host 192.168.1.116:81 does not belong to the domain nb.local.com, unable to identify the subdomain for this request
[Feb 21 19:29:43] ---> POST /reader/save_dashboard_river {'river_id': 'river:global', 'river_side': 'left', 'river_order': '2'}
[Feb 21 19:29:43] ---> [FF ] [0.00s] [AnonymousUser] Saving dashboard river: river:global (left 2)

Thank you in advance! :)

**Comment by samuelclay** [comment]
Try again now. You'll want to delete your volumes and containers, but we've updated docker-compose.yml quite a bit.

**Comment by samuelclay** [comment]
Mind you, I believe you'll still get this warning. The issue is that we haven't figured out how to get the `subdomains` library to recognize the original hostname through the proxies.

**Comment by samuelclay** [comment]
I believe now that we moved to localhost, everything should work as expected.
