### ISSUE TITLE
iOS Catalyst: panes display in wrong place on resumption

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1419]
![57F181A3-BA35-4524-A7E5-A2C8AB916DAF_1_105_c](https://user-images.githubusercontent.com/68303/109438629-d0640c00-79f8-11eb-90a5-ec7265309c6d.jpeg)

**Comment by Dejal** [comment]
I can't reproduce this one. Can you?

**Comment by nriley** [comment]
I'm not seeing this issue on resume since the update but a potentially related one? The stories display like an elevator stuck between floors. I wonder if again this is dependent on the screen size of my iPad?

![IMG_0313](https://user-images.githubusercontent.com/68303/112727045-e0d3ad80-8ef6-11eb-877c-5fd4d001d37c.png)

**Comment by nriley** [comment]
#1475 is the same issue; as it's newer will close this one.
