### ISSUE TITLE
iOS Catalyst: incomplete theme changing

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1421]
This persists even when switching between articles in a feed. Switching to another feed causes the appearance to update, *except* for the story navigation buttons at the bottom, which still retain the appearance from the prior theme.

![IMG_0300](https://user-images.githubusercontent.com/68303/109438834-abbc6400-79f9-11eb-9db6-8f231e9db2ed.png)

![IMG_0301](https://user-images.githubusercontent.com/68303/109438877-ee7e3c00-79f9-11eb-9f7f-006ce582a233.png)

**Comment by Dejal** [comment]
Sorry, accidentally bumped the Close button.

**Comment by nriley** [comment]
This looks much better now, thanks! The one thing that looks terrible (particularly with the removal of ALL CAPS) is a shadow persisting under the heading when switching (see "All Stories"). Also, I'm not sure if the inconsistent colors along the top in the dark theme are intended? Some are a sepia color, some are gray.

![IMG_0314](https://user-images.githubusercontent.com/68303/112726955-630fa200-8ef6-11eb-9a06-9690ca4e5b3b.png)

**Comment by nriley** [comment]
Thanks, seems to be working better. One last thing I noticed is that the status bar text is sometimes not changing color appropriately. Unfortunately I can't seem to reproduce this but the screenshot below is real…

![image](https://user-images.githubusercontent.com/68303/112757553-391eb400-8fb8-11eb-9ffc-d14cc3bff00b.png)
