### ISSUE TITLE
iOS Catalyst: full width images are offset to the right

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1422]
Looks like the images have the correct width but they have an unintended left margin.

A couple examples are in #1421.

**Comment by Dejal** [comment]
This seems to be fixed based on recent changes; if you can still repro, please re-open with more info.

**Comment by nriley** [comment]
This is trivially reproducible for me on every single full-bleed image on my 10.5ʺ iPad Pro. I haven't ever been able to get it to *not* happen. Please let me know what else you need!

**Comment by Dejal** [comment]
Trying on various device sizes in the Simulator, the images seem to be mostly either correctly full-width, or hard against the left margin.

I think this might be a CSS thing, not something the app does. I've experimented a bit, but can't figure out how to improve it yet.

**Comment by nriley** [comment]
Should have mentioned (on a real device) that it only occurs in landscape orientation with the sidebar visible. If I rotate to portrait, the image is correctly full-width. If I hide the sidebar, the image ends up against the left margin.

**Comment by nriley** [comment]
Wondering if this bug and #1419 could be related. When I went back into the app this time after the above experimentation, I was able to see the entire width in landscape mode with the sidebar visible, *but* the entire web view appeared zoomed out.

![IMG_0320](https://user-images.githubusercontent.com/68303/112744892-f6d28400-8f71-11eb-8a7d-2cd621131dfe.png)

When I went to the next story, it was offset as in #1419 (but still zoomed out):

![IMG_0321](https://user-images.githubusercontent.com/68303/112744897-fd60fb80-8f71-11eb-97a5-b283344622ab.png)

**Comment by nriley** [comment]
I connected to my iPad with the Xcode view debugger (all the view bounding boxes look fine) and Safari web debugger and think I agree with you that this is CSS related. The erroneous (?) definition seems to be "margin-left: -30px !important"; when I uncheck this, everything magically works, as it no longer shadows the iPad size-specific "margin-left: -90px !important" below it.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/68303/112758063-75531400-8fba-11eb-976a-f0e1b833c8d8.png">
![IMG_0323](https://user-images.githubusercontent.com/68303/112758160-d67ae780-8fba-11eb-9e24-2d3aec3815db.png)

**Comment by Dejal** [comment]
This should be better now, based on recent changes. Reopen with more info if not.
