### ISSUE TITLE
iOS Catalyst: loss of functionality with tapping and holding on images

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1425]
The current release version displays a popover which allows you to zoom an image, view alt text or save an image.

![IMG_0302](https://user-images.githubusercontent.com/68303/109439311-d3143080-79fb-11eb-92e8-24df447e9dc5.jpeg)

The catalyst branch does nothing useful other than allowing you to drag the image.

It might make sense to build off the standard functionality if you can — it does everything except for allowing you to "view and zoom", which honestly I rarely use.

![IMG_0303](https://user-images.githubusercontent.com/68303/109439315-d7404e00-79fb-11eb-9618-901a6326758e.jpeg)

**Comment by samuelclay** [comment]
I would love to get rid of View & Zoom anyway because honestly we should have a feature where you can pinch an image and it zooms automatically in its own view controller using a view transition. I'll write that up now.

**Comment by Dejal** [comment]
That image zoom idea sounds great. For now, I've just added a long-press gesture recognizer to restore the old menu; we can do the enhancement later.

**Comment by nriley** [comment]
The long press seems to require a *really* long press (nearly 2 seconds) compared to the previous one. Also sometimes the menu also appears, which is not ideal.
![IMG_0312](https://user-images.githubusercontent.com/68303/112726709-3eff9100-8ef5-11eb-8cc1-3d9e9e486585.png)
