### ISSUE TITLE
Bug: Docker Install With Out IP

### ISSUE THREAD

**Issue by zero77** [samuelclay/NewsBlur#1433]
I am trying to install newsblur docker image but, after i pull and then run the image, It starts with out an ip.
OS: Debian
Docker version 20.10.5, build 55c4c88

`sudo docker volume create newsblur_data`
`sudo docker pull newsblur/newsblur_python3`
`sudo docker run -d -p 8000:8000 --name newsblur --restart always -v /var/run/docker.sock:/var/run/docker.sock -v newsblur_data:/data newsblur/newsblur_python3`

`CONTAINER ID   IMAGE                       COMMAND     CREATED         STATUS                          PORTS     NAMES`
`aee35f29d56a   newsblur/newsblur_python3   "python3"   7 minutes ago   Restarting (0) 37 seconds ago             newsblur`

`sudo docker inspect aee35f29d56a`
[
    {
        "Id": "aee35f29d56a68d7e795c597732cb1f53fd46509ac72c6571d42b86fec99e1b3",
        "Created": "2021-03-15T15:03:08.834338609Z",
        "Path": "python3",
        "Args": [],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-03-15T15:10:57.812866037Z",
            "FinishedAt": "2021-03-15T15:10:57.872853186Z"
        },
        "Image": "sha256:7b0024897aa073fd5620feac771bc9abc35f6e074a2645fad91c80f347aed0d0",
        "ResolvConfPath": "/var/lib/docker/containers/aee35f29d56a68d7e795c597732cb1f53fd46509ac72c6571d42b86fec99e1b3/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/aee35f29d56a68d7e795c597732cb1f53fd46509ac72c6571d42b86fec99e1b3/hostname",
        "HostsPath": "/var/lib/docker/containers/aee35f29d56a68d7e795c597732cb1f53fd46509ac72c6571d42b86fec99e1b3/hosts",
        "LogPath": "/var/lib/docker/containers/aee35f29d56a68d7e795c597732cb1f53fd46509ac72c6571d42b86fec99e1b3/aee35f29d56a68d7e795c597732cb1f53fd46509ac72c6571d42b86fec99e1b3-json.log",
        "Name": "/newsblur",
        "RestartCount": 17,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "newsblur_data:/data"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ece52e36ec837e370bd23c1247c50821fb4263c18c3688f853fd0cfe73518505-init/diff:/var/lib/docker/overlay2/28177cc8b494bed2fe9515be91ae876658dbec73757fd30c03e7e6810d94bb4b/diff:/var/lib/docker/overlay2/729e1a189912bf62b7335455cd8174742bf36626b479e3c5a9b93e57b7c3b9b5/diff:/var/lib/docker/overlay2/a3685ab29c42ad6afe9ea72f714264f111681af2df44004fa02452882c7dd0b0/diff:/var/lib/docker/overlay2/af49040253db120b2ca10c300cbfbf783d365bedf88aed5884b9b22ffa840ea0/diff:/var/lib/docker/overlay2/b4ceb6f36239cf5f918ec149c3f4da0a5f725a4fe1c626c8190fddff3c982cdf/diff:/var/lib/docker/overlay2/089daa885276b294945521a129fa2e52d82ea6f00dd28d9abf4d59761462511c/diff:/var/lib/docker/overlay2/864db4719467d0b18ffe7758d18301c030655008b4f5d8e0a49502d9bc545753/diff:/var/lib/docker/overlay2/13e6496caa6c59149a1968b48ee869411c585b6870838e52a82f4dc2b9f2237e/diff:/var/lib/docker/overlay2/e72202ca7c6d1cdd1a8608af207f27a49d9a56248993ccd6b6111442bead174b/diff",
                "MergedDir": "/var/lib/docker/overlay2/ece52e36ec837e370bd23c1247c50821fb4263c18c3688f853fd0cfe73518505/merged",
                "UpperDir": "/var/lib/docker/overlay2/ece52e36ec837e370bd23c1247c50821fb4263c18c3688f853fd0cfe73518505/diff",
                "WorkDir": "/var/lib/docker/overlay2/ece52e36ec837e370bd23c1247c50821fb4263c18c3688f853fd0cfe73518505/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "newsblur_data",
                "Source": "/var/lib/docker/volumes/newsblur_data/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "aee35f29d56a",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.2",
                "PYTHON_PIP_VERSION=21.0.1",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/b60e2320d9e8d02348525bd74e871e466afdf77c/get-pip.py",
                "PYTHON_GET_PIP_SHA256=c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565",
                "PYTHONPATH=/srv/newsblur"
            ],
            "Cmd": [
                "python3"
            ],
            "Image": "newsblur/newsblur_python3",
            "Volumes": null,
            "WorkingDir": "/srv/newsblur",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d8ea4f2ff815cd152f8cdfb21cd0f91d602e555641d1f8ed8643905ab04de446",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/d8ea4f2ff815",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "a80926ac0bece8c982df998ef0df779be6ae86982850e8c20a6876fe12721746",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by robsee** [comment]
I don't think it is designed to run from a single docker container. Using the dashboard3 branch (which I think is the recommended way to go right now) there are many separate containers that together make up the app. Check out the docker-compose file in that branch.

**Comment by samuelclay** [comment]
I'd like to see the `docker logs newsblur_web -n30` output to see why its failing, but my guess is that you don't have the repo in that volume. 

The best way to setup NewsBlur is to use the Makefile and the command `make nb`. That should set everything up, including the volumes.

**Comment by samuelclay** [comment]
By the way, I'm thrilled you're using it this way as we're just about to launch it. If you encounter any bugs with the docker-compose and `make nb` commands, let me know and I'll get to work on it.
