### ISSUE TITLE
Feed has no original page. (404) on dashboard3

### ISSUE THREAD

**Issue by robsee** [samuelclay/NewsBlur#1434]
Hi,

  On dashboard3, all of my feeds are showing and error on the original page view, and say "Feed has no original page. (404)." I've looked through the code to try and identify the issue, but have been unable to find it. Can you point me in the direction of which component I should be looking at to track this down ? Thanks.

**Comment by samuelclay** [comment]
Thanks for reporting this! This is now fixed. Good catch on both this and the imageproxy.
