### ISSUE TITLE
Preferences option missing text on beta site

### ISSUE THREAD

**Issue by jgbishop** [samuelclay/NewsBlur#1436]
The first option in the dropdown for the **Default Folder** preference doesn't have any text on the beta site (see screenshot below).

![Screenshot 2021-03-18 203742](https://user-images.githubusercontent.com/4210087/111715267-dac03b80-8829-11eb-96e5-fdbe5f9d3a2f.png)

**Comment by samuelclay** [comment]
Thanks for reporting this! Turns out it was related to the changes I made to the dashboard folder selector. Now fixed.
