### ISSUE TITLE
Android: Share button text broken

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1437]
See screenshot. Once this is fixed I'll ship out v10.3.
![Screenshot_20210322-140125](https://user-images.githubusercontent.com/44229/112036857-7ea23380-8b17-11eb-81c6-bf0bfae60970.png)

**Comment by sictiru** [comment]
@samuelclay This seems a bit odd. The share button doesn't reference that string resource. 
The string is used only after the user clicks on the share button to render the share dialog title. 

![ezgif com-resize](https://user-images.githubusercontent.com/13900221/112495163-df608480-8d40-11eb-9350-5861f92a854c.jpg)
![ezgif com-resize(1)](https://user-images.githubusercontent.com/13900221/112496175-c1475400-8d41-11eb-8286-978f319e7828.jpg)
