### ISSUE TITLE
Android: Displaying large images without downsampling

### ISSUE THREAD

**Issue by struggggle** [samuelclay/NewsBlur#1438]
Hi,

I found that when I clicked `SAVED STORIES` and opened the news list of the below page, the speed of displaying the images in the right of the news list is slow.

![image](https://user-images.githubusercontent.com/19150666/112162081-ad5aff80-8c26-11eb-9a53-214f85496dfe.png)

I checked the source code and hooked the execution of newsBlur. I found that in the code below, the displayed images are decoded directly without downsampling:

![image](https://user-images.githubusercontent.com/19150666/112163197-c31cf480-8c27-11eb-8fb2-d8756ef0277a.png)

The location of the source code:
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/util/UIUtils.java#L127

Although the code implementation has considered image downsampling, in the actual execution, the variable `maxDim`  is assigned with a value of `2147483647`:
which caused the variable `decodeOpts.inSampleSize` is assigned with 1.

I collected the execution trace and found that the resolution of many decoded images is bigger than 800\*800.
For example, the resolution of the displayed image below is 1200\*1186.

![image](https://user-images.githubusercontent.com/19150666/112163860-63731900-8c28-11eb-903c-89eef3e86a8e.png)

However, the size of the widgets used to display these images is 315*315, which means we can downsample the displayed image so as to save time consumption in image decoding.

I think what I found may be an important reason why the speed of image displaying on this page is slow.

Hoping what I found will help to improve newsBlur's runtime performance.

Thanks.

**Comment by samuelclay** [comment]
Thanks for writing this up! @sictiru, is this an easy enough fix?

**Comment by sictiru** [comment]
@struggggle thanks for the detailed description.
Images are now downsampled based on the image view height. In case of any real lazy view measurement the images are limited to 800px which I think is plenty for thumbnails and icons.
