### ISSUE TITLE
[WebSub] hub.verify_token is deprecated

### ISSUE THREAD

**Issue by da2x** [samuelclay/NewsBlur#1440]
Requiring hubs to return the `hub.verify_token` parameter makes Newsblur incompatible with [WebSub](https://www.w3.org/TR/websub/) and the now deprecated [PubSubHubbub 0.4](https://pubsubhubbub.github.io/PubSubHubbub/pubsubhubbub-core-0.4.html) specification. Only Newsblur, InoReader, and ~~BazQux~~ send this parameter (at least to my hub.)

It was an optional parameter in PubSubHubbub version 0.3, but it was removed in 0.4. It was determined that it didn’t serve any purpose not already addressed by the `hub.callback` parameter.

**Comment by samuelclay** [comment]
I believe this is now fixed. Can you verify? I've moved the backend to Python 3 and this should be rolled into that.
