### ISSUE TITLE
Android: After browsing a lot of images, image displaying becomes slow

### ISSUE THREAD

**Issue by struggggle** [samuelclay/NewsBlur#1441]
Hi, 
I opened the news list and swiped it to browse more news.

After I swiped several times and browsed dozens of news, I found that the speed of image displaying became much slower than before.

![image](https://user-images.githubusercontent.com/19150666/112656520-725a0580-8e8c-11eb-8dd4-b4ed0cb84047.png)

I checked the source code of NewsBlur and found that in the following code, the image cache can be optimized to improve performance.

![image](https://user-images.githubusercontent.com/19150666/112656632-8dc51080-8e8c-11eb-8e99-7d37aeee3ad6.png)

Code location:
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/util/ImageLoader.java#L52

![image](https://user-images.githubusercontent.com/19150666/112656748-a7feee80-8e8c-11eb-8fcb-74e898ecd644.png)

Code location:
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/util/MemoryCache.java#L44

In the implementation, the image cache is set to a value of `Runtime.getRuntime().maxMemory()/6`,
When the image cache is full, every time decoding a thumbnail image and adding the decoded image to the image cache, the image cache will remove one or more images that have a similar memory size of the added image.
This will make the image cache always full and cause NewsBlur's the memory consumption is always high, which would affect the performance of NewsBlur.

Maybe removing more images when the image cache is full or setting a reasonable size of the image cache can mitigate the memory bloat of NewsBlur.

Thanks.

**Comment by bryceco** [comment]
It’s clever that you use LinkedHashMap to track the oldest items, however when a cache hit occurs you need to move the item to the end of the list. Also, adding a time stamp to each item would allow checkSize to prune items older than 24 hours or so.

**Comment by samuelclay** [comment]
I believe @sictiru just launched a fix for how big those image thumbnails are, so it should take care of this problem, at least ameliorating it.

By the way, that fix is on the beta channel as v10.3.0. I'll release it publicly in a week's time.

**Comment by sictiru** [comment]
I'm considering replacing the custom `ImageLoader` with `Glide`. Quick tests show a ~30% memory usage decrease.
Also will deep dive into the `ImageLoader` to see if similar gains can be attained.

**Comment by sictiru** [comment]
@struggggle Are you still seeing slowness on image displaying in the recent versions?

**Comment by sictiru** [comment]
Feel free to reopen ticket if there are issues loading or displaying images lately.
