### ISSUE TITLE
iOS Catalyst: UI Updates

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1442]
This latest beta is incredible! It's ready to roll on TestFlight. I'm wondering how hard it would be to make these changes beforehand. I'd like to update the font, sizes, icons, and a bit of styling all over the app to match the upcoming redesign at beta.newsblur.com.

* App font is now Whitney everywhere. I've found that the equivalent size is one px higher. So 14px Helvetica is 15px Whitney.
* A few folder icons are updated
* A tiny bit of extra vertical space for feeds for easier tapability
* Story titles have a bit more breathing room as well
* No more uppercase everything. Folder names, menu items, share buttons should all be "Sentence case".
* Use icons instead of numbers in the menu "Title | 1 | 2 | 3" /media/img/reader/content_preview_{small,medium,large}.png

<img width="264" alt="Screen Shot 2021-03-26 at Mar 26 2 02 23 PM" src="https://user-images.githubusercontent.com/44229/112674113-ed470000-8e3b-11eb-9ec1-9613e0d899f0.png">

<img width="379" alt="Screen Shot 2021-03-26 at Mar 26 2 03 20 PM" src="https://user-images.githubusercontent.com/44229/112674224-09e33800-8e3c-11eb-9be5-31695310ba0d.png">

<img width="335" alt="Screen Shot 2021-03-26 at Mar 26 2 01 25 PM" src="https://user-images.githubusercontent.com/44229/112674009-c8eb2380-8e3b-11eb-9fc1-fb843581f0ad.png">

<img width="383" alt="Screen Shot 2021-03-26 at Mar 26 3 10 45 PM" src="https://user-images.githubusercontent.com/44229/112681739-81699500-8e45-11eb-95fc-4c89fbc09817.png">

**Comment by Dejal** [comment]
Done. If I've missed any icons, please identify them, preferably by path, or at least by name.

**Comment by samuelclay** [comment]
Amazingly quick turnaround! Few notes:

* Is it just me or are the story titles font sizes a step (s->m, m->l) bigger than the story detail font size? I was at Medium on both and it felt like the story text went smaller.
* The descenders on folder titles are cut off. `g` and `p` etc
* In story titles, the story content preview should be one font size smaller than the title
* "Book" vs "Medium": I don't know why but the website's Medium is a bit bolder than the apps. I only use two weights and they should be the same between app and web, but I should look into why
* In story titles, on the small image preview, there should be a bit more space to the left of the image
* Times should use the new format. "10:00am" instead of "10:00 AM"
* Times should now match the color of author in story titles
* Share/Train/Save buttons need Sentence case
* The feed gradient title should be a nudge taller (2-4px)

**Comment by Dejal** [comment]
I'll see what I can do later today.

**Comment by nriley** [comment]
@samuelclay — an issue with using "am" rather than "AM" is that it's not a standard localized time format on iOS. Do you want NewsBlur to stop using standard time formats for this?

**Comment by Dejal** [comment]
Yes, I'm inclined to decline the time format change. It uses the system date format, and should continue to do so (e.g. I use 24 hour time).

**Comment by samuelclay** [comment]
Sure, I'm fine with that

**Comment by Dejal** [comment]
Try that on for size.
