### ISSUE TITLE
Android: UI Updates

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1443]
Similar to the iOS app, I'd like to update the font, sizes, icons, and a bit of styling all over the app to match the upcoming redesign at beta.newsblur.com.

* App font is now Whitney everywhere. I've found that the equivalent size is one px higher. So 14px Helvetica is 15px Whitney.
* A few folder icons are updated
* A tiny bit of extra vertical space for feeds for easier tapability
* Story titles have a bit more breathing room as well
* No more uppercase everything. Folder names, menu items, share buttons should all be "Sentence case".

<img width="264" alt="Screen Shot 2021-03-26 at Mar 26 2 02 23 PM" src="https://user-images.githubusercontent.com/44229/112674113-ed470000-8e3b-11eb-9ec1-9613e0d899f0.png">

<img width="379" alt="Screen Shot 2021-03-26 at Mar 26 2 03 20 PM" src="https://user-images.githubusercontent.com/44229/112674224-09e33800-8e3c-11eb-9be5-31695310ba0d.png">

<img width="335" alt="Screen Shot 2021-03-26 at Mar 26 2 01 25 PM" src="https://user-images.githubusercontent.com/44229/112674009-c8eb2380-8e3b-11eb-9fc1-fb843581f0ad.png">

<img width="383" alt="Screen Shot 2021-03-26 at Mar 26 3 10 45 PM" src="https://user-images.githubusercontent.com/44229/112681739-81699500-8e45-11eb-95fc-4c89fbc09817.png">

**Comment by sictiru** [comment]
@samuelclay Users have a few options to change the font for the story reading view only and the global app font is the Android default. I'm planning on making `Whitney` the default global app font and remove the `Whitney` font option in `Preferences`.
Let me know if you had something else in mind for the font changes.

**Comment by sictiru** [comment]
The new default font and a few other tweaks really make the content more readable and easier on the eye! I'm looking forward to see this in production.

The UI updates are ready for review.

**Comment by samuelclay** [comment]
Terrific! I'll be putting this out on the beta channel later today.

**Comment by samuelclay** [comment]
I think the last change to be made here is to normal case the story traversal buttons (next/story/text).

**Comment by samuelclay** [comment]
Also, can you change the Share and Save buttons at the bottom of every story to match the web. They should be lighter and be a lighter color than the story traversal buttons (so that they dont blend with each other when overlapping)

<img width="630" alt="Screen Shot 2021-05-04 at May 4 4 09 59 PM" src="https://user-images.githubusercontent.com/44229/117063725-3750ba80-acf3-11eb-9e2b-d348c595c5e5.png">
