### ISSUE TITLE
iOS: Add to "Saved Stories" with share extension

### ISSUE THREAD

**Issue by garymh** [samuelclay/NewsBlur#1445]
I'm loving the addition of https://github.com/samuelclay/NewsBlur/issues/1097 for my browser, but unfortunately it doesn't seem to work for me on iOS... is it possible to add that functionality to the share extension?

**Comment by samuelclay** [comment]
Yep, I agree, we should be able to save stories from the iOS share extension. @Dejal, whenever you get to this, take a look at the browser extension to see the differences. `templates/api/bookmarklet.js` will be helpful.

**Comment by samuelclay** [comment]
Oops, I re-created in #1515. Let's switch to that one.
