### ISSUE TITLE
Android: The speed of entering the login screen is slow

### ISSUE THREAD

**Issue by struggggle** [samuelclay/NewsBlur#1450]
Hi,

When I opened Newsblur in an Android device of OnePlus 6T, Android 9.0
I found that I can enter the following login screen immediately.

![image](https://user-images.githubusercontent.com/19150666/114264049-3e99e680-9a1b-11eb-916f-0a1bd400081a.png)

However, when I opened Newsblur in another Android device of Mi Note 3, Android 8.0
I found that the speed of entering the login screen became much slower and following pages will appear before entering the login screen

![image](https://user-images.githubusercontent.com/19150666/114264074-5f623c00-9a1b-11eb-9889-ea611b1f2ca5.png)

![image](https://user-images.githubusercontent.com/19150666/114264078-67ba7700-9a1b-11eb-8ccf-4b1fb2412472.png)

I hooked NewsBlur and found that a 840\*840 image was decoded in the UI thread, which would be the reason why the speed become slow in Mi Note 3.
Below is the 840\*840 image:

![image](https://user-images.githubusercontent.com/19150666/114264115-9d5f6000-9a1b-11eb-9452-9fd4d1a43fc7.png)

Below is the stack trace obtained by calling Thread.currentThread().getStackTrace() after the image was decoded:
(each line contains "class name", "method name", and "line number"):

''
android.graphics.BitmapFactory;decodeStream;-1
android.graphics.BitmapFactory;decodeResourceStream;538
android.graphics.drawable.Drawable;createFromResourceStream;1195
android.content.res.ResourcesImpl;loadDrawableForCookie;812
android.content.res.ResourcesImpl;loadDrawable;630
android.content.res.Resources;loadDrawable;886
android.content.res.TypedArray;getDrawableForDensity;953
android.content.res.TypedArray;getDrawable;928
android.content.res.XResources$XTypedArray;getDrawable;1363
android.widget.ImageView;<init>;188
android.widget.ImageView;<init>;171
androidx.appcompat.widget.AppCompatImageView;<init>;72
androidx.appcompat.widget.AppCompatImageView;<init>;68
androidx.appcompat.app.AppCompatViewInflater;createImageView;187
androidx.appcompat.app.AppCompatViewInflater;createView;107
androidx.appcompat.app.AppCompatDelegateImpl;createView;1407
androidx.appcompat.app.AppCompatDelegateImpl;onCreateView;1457
android.view.LayoutInflater;createViewFromTag;772
android.view.LayoutInflater;createViewFromTag;730
android.view.LayoutInflater;rInflate;863
android.view.LayoutInflater;rInflateChildren;824
android.view.LayoutInflater;rInflate;866
android.view.LayoutInflater;rInflateChildren;824
android.view.LayoutInflater;inflate;515
de.robv.android.xposed.XposedBridge;invokeOriginalMethodNative;-2
de.robv.android.xposed.XposedBridge;handleHookedMethod;361
android.view.LayoutInflater;inflate;-1
android.view.LayoutInflater;inflate;423
com.newsblur.databinding.ActivityMainBinding;inflate;115
com.newsblur.databinding.ActivityMainBinding;inflate;109
com.newsblur.activity.Main;onCreate;59
android.app.Activity;performCreate;7009
android.app.Activity;performCreate;7000
android.app.Instrumentation;callActivityOnCreate;1214
android.app.ActivityThread;performLaunchActivity;2731
android.app.ActivityThread;handleLaunchActivity;2856
android.app.ActivityThread;-wrap11;0
android.app.ActivityThread$H;handleMessage;1589
android.os.Handler;dispatchMessage;106
android.os.Looper;loop;164
android.app.ActivityThread;main;6494
java.lang.reflect.Method;invoke;-2
com.android.internal.os.RuntimeInit$MethodAndArgsCaller;run;438
com.android.internal.os.ZygoteInit;main;807
''

Below are the created image data in NewsBlur after image decoding (obtained by hooking NewsBlur) :

![image](https://user-images.githubusercontent.com/19150666/114264130-b405b700-9a1b-11eb-8415-afdfe15aff05.png)

Data description:  “840, 840" is the width and hight of an image.

From the obtained image data, I also found that the 840\* 840 image is repeated decoded in the UI thread.

Android suggests that the process of decoding large images should not be executed in the main UI thread. 
https://stuff.mit.edu/afs/sipb/project/android/docs/training/displaying-bitmaps/process-bitmap.html

Maybe the process of decoding the 840\*840 image should be moved to a background thread.
At the same time, the image should not be decoded repeatedly.

Thanks.

**Comment by sictiru** [comment]
@struggggle There were updates on the initial screen loading in Oct 2021 as part of the Android 12 upgrade. More startup improvements will be merged soon from another initiative.
I'm closing this ticket but feel free to reopen if the issue persists.
