### ISSUE TITLE
Android: Send link on v10.3.0 only sends URL without a headline

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1452]
A user emailed today:

> Hi!
> 
> Sorry to bother you with this, but the functionality of the 'Send
link' function seems to have been altered as of the latest released
version of the NewsBlur Android app.
> 
> The functionality used to pick the headline of the article and the URL
(the "link") and put them one after another on one line.
> 
> This was perfect for sending links to people in a compact fashion, and
it had worked as such for years.
> 
> However, this seems to have changed as of the latest Android app version:
> 
> Upon using the 'Send link' function to send the link to a Gmail
message (on an Android phone), the headline is on one line and the URL
is on another line. Upon sending the link to a Hangouts chat, only the
URL gets transmitted to the chat.
> 
> Would it be possible to bring back the functionality as it used to be?
(i.e. first the headline and then the URL, all on the very same row)
> 
> There seems to be very little reason in sending any links anymore
since the headline used to give the URL a "context" which now is
missing.

Do you remember why we changed this? Would it be wise to change it back?

**Comment by sictiru** [comment]
@samuelclay Yes there was a recent change on the "Send link to..." option for stories and details can be found at https://github.com/samuelclay/NewsBlur/issues/1245
I agree with your comment on the issue but also open to revert the change if users expect a different experience.
