### ISSUE TITLE
Android: Scrollbars on Story Views

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1454]
**Issue**
"Recent update of the Android app no longer shows the scrollbar when reading a story, even when scrolling up or down, making it hard to get an idea of the length of a story.

Noticed with 10.3.0, unsure about the version it worked in, but was correct within the last week.

If this is intentional, it would be nice to get a config to re-enable this, and even go further and always have scrollbars visible."

**Expectation**
Scrollbars should be visible on story views

**Comment by samuelclay** [comment]
Deployed to the Play Store as 10.3.1.
