### ISSUE TITLE
iOS: Inconsistent behavior with titles on bottom on iPad

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1456]
When I upgraded to the TestFlight beta on my iPad, the story list switched to being displayed on the bottom. But unlike the prior version, I can no longer drag the splitter to the bottom of the screen to switch to stories on the left.

![image](https://user-images.githubusercontent.com/68303/116111354-91fb6e00-a684-11eb-8380-d98a9396f1f5.png)

Also, the 'full screen' button (top left of the screen, circled) does not do anything in this mode.  I can show the feed list by swiping from the left side of the screen, but I do not think this gesture is particularly discoverable; would recommend that this nonfunctional button be replaced by one that shows the story list.

I can switch to titles on the left with "Story titles layout" in Preferences, which I think is also not terribly discoverable, but after I do so, it causes some layout issues when I try to swipe in from the left with a "phantom column" as below:

![E2E7428F-C892-463D-BA39-995159AD060A_1_105_c](https://user-images.githubusercontent.com/68303/116111144-5b255800-a684-11eb-8fea-9ac30895a8c4.jpeg)

**Comment by samuelclay** [comment]
This is looking good now.
