### ISSUE TITLE
Android: Add image preview and content preview options to story titles list menu

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1458]
To match web and iOS. We already have both options, although the Show Content Preview option is a boolean and should now be: title only, small (2 line, current default), medium (4 lines, make this the new default), large (6 lines).

![IMG_BB4C8436D5E1-1](https://user-images.githubusercontent.com/44229/116112173-52815180-a685-11eb-9157-e2cadc8d2e21.jpeg)
<img width="546" alt="Screen Shot 2021-04-26 at Apr 26 11 51 59 AM" src="https://user-images.githubusercontent.com/44229/116112717-d20f2080-a685-11eb-980e-4767064493ec.png">

**Comment by samuelclay** [comment]
Add the Mark read on scroll option to that menu as well.

**Comment by sictiru** [comment]
The Android menu has fewer options compared to web & iOS plus some of them are only present under `Preferences`. I will surface the Mark read on scroll, Image Thumbnail and Content Preview options here as well.

**Comment by samuelclay** [comment]
This is great! One issue I've noticed is that the 6 line preview doesn't end up working because the content is truncated too early.

**Comment by sictiru** [comment]
Story short content length was doubled in the parser to cover even stories with no thumbnail when 6 line of content preview are required.

**Comment by samuelclay** [comment]
For the image preview, let's also add left-hand images, in both large and small. So that's 5 states. Since Android doesn't use icons in menus, use No image preview, Left-hand small, Left-hand large, Right-hand large, Right-hand small

<img width="382" alt="Screen Shot 2021-05-05 at May 5 1 11 28 PM" src="https://user-images.githubusercontent.com/44229/117181687-82c2a180-ada3-11eb-8cea-ffd8a520d608.png">

**Comment by samuelclay** [comment]
Alternatively you can do what we do on the web, which is elongate the image, using css to properly constrain it.

<img width="421" alt="Screen Shot 2021-05-10 at May 10 3 25 42 PM" src="https://user-images.githubusercontent.com/44229/117713781-17624080-b1a4-11eb-9019-54411eb1bd57.png">

**Comment by samuelclay** [comment]
Also, please update to the higher resolution unread dots. They live under `/media/icons/circular/g_icn_focus.png` and unread and hidden.

**Comment by sictiru** [comment]
Am I looking in the right place ? https://github.com/samuelclay/NewsBlur/tree/master/media/img/icons/circular These icons are the same as the ones in the project.

The story thumbnails dimensions can vary greatly and I'm still working through a few way of efficiently adding rounded corners to the small thumbnail views.

**Comment by samuelclay** [comment]
You're right, I guess it's time to redraw them.

**Comment by samuelclay** [comment]
Rounded previews are looking great. Let's not have a ragged left when image previews are on the left. Let's just keep empty space.

![Screenshot (May 17, 2021 4_19_22 PM)](https://user-images.githubusercontent.com/44229/118551620-e1850500-b72b-11eb-81b1-3b157e163db1.png)

![IMG_5B62A0CF0DFA-1](https://user-images.githubusercontent.com/44229/118552004-59ebc600-b72c-11eb-9982-7feb592998bd.jpeg)

**Comment by samuelclay** [comment]
Also, some images are rounded and some aren't. Screenshot above shows that happening.

**Comment by samuelclay** [comment]
Oh, while I'm comparing screenshots, take off forced uppercase on the author.

**Comment by sictiru** [comment]
@samuelclay The last commit disabled image memory cache but still uses file caching. This was necessary to address the issue where some images are rounded and some aren't. The rounded corners are applied at the time of the image decoding and it's being cached in memory with or without corners. When a user changes between large and small thumbnail, the image is used from the cached memory directly, reusing the previous image decoded state. 

I'm thinking about removing the memory caching all together or refactoring/replacing the image loader at a deeper level because of the new usage of rounded corners throughout the app. There is already an issue opened for the memory image caching https://github.com/samuelclay/NewsBlur/issues/1441 and will need to spend more time on the problem.

**Comment by sictiru** [comment]
The image memory caching was restored and a full image caching refactor will be done in a separate issue.
