### ISSUE TITLE
iOS: Add button on iPad to make story titles list sticky

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1464]
Basically this button (on the top right of the story titles list view) would configure the app is look like the old 2 column layout. Not everybody wants a full screen story.

**Comment by samuelclay** [comment]
This one's for @mihaip

**Comment by samuelclay** [comment]
Just realized we have the full screen button in the top left of the story detail view. That would be fine to also show on Portrait mode on iPad.

**Comment by Dejal** [comment]
I added **Auto**, **Tile**, **Displace** and **Overlay** options to the feed detail menu, with a nice animated transition.

We should replace those text titles with suitable icons; preferably you can provide them, or I could come up with something.

Auto will let iPadOS decide what to use (it uses Tile in landscape, Overlay in portrait), the others can override that.

**Comment by Dejal** [comment]
_Probably shouldn't have closed that; you can re-open once you provide the icons, or request me to make some._

**Comment by samuelclay** [comment]
These are wild and there's quite a bit of overlap. Honestly, I feel like we could remove the menu item and instead just switch between two with a couple full screen buttons. The way you did it with the button on the top left of the feed list is pretty good but maybe that's non-discoverable? It feels like these 4 options are really 2 options in disguise: story titles present or hidden/swipable, feed titles present or hidden/swipable.

We should noodle on this feature. Do you see a way to remove it and switch to a couple buttons to hide/show the feed titles and story titles? I'm thinking a pin on both would do the trick.

**Comment by Dejal** [comment]
There are subtle differences. Tile makes them all fit (which really only works in landscape on big iPads); Displace pushes the story off to the right, and hides the feeds when showing the story (which works better for smaller iPads). Overlay keeps the story fullscreen and slides the others over the top (which works best for portrait orientation). Auto uses the best choice for each of those situations.

The button in the top-left is an iPadOS standard feature; see Notes, Mail, etc.

If you want to remove options, we could just stick with Auto like before, and perhaps put these options in the preferences for people who want to override the OS.

**Comment by samuelclay** [comment]
Do we declare Auto or is that built in? I find that I want to switch between Displace and Overlay mode (basically a full screen button). But I like Tile and for certain setups that's preferred. But we don't need to offer Tile unless it's an iPad in landscape. But if I had to choose one, it'd be Displace.

**Comment by samuelclay** [comment]
By the way, it looks like there's still the 20px line at the bottom of the story content pane that we used to use for story titles on bottom. But I can't get it to work. Have we removed that (which is fine) and if so, can we remove that bar?

**Comment by Dejal** [comment]
Auto and the other modes are all built-in options.

Not sure what you mean by the line?

**Comment by samuelclay** [comment]
Here's a screenshot of the line:

![IMG_0168](https://user-images.githubusercontent.com/44229/119725344-d3c33400-be3d-11eb-8d2e-72849070efab.PNG)

**Comment by samuelclay** [comment]
I'm happy with the menu, so long as it comes with #1490. And the story content view being ~20px too small should be a separate ticket. I'll open that now.
