### ISSUE TITLE
iOS: Stories aren't always rendering

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1466]
Got a substantial number of bug reports today on stories not rendering. I experience this too, although intermittently.

> Multiple views of a read story sometimes don’t render. Sometimes (very frequently) if the list view for a site has read items enabled and you tap into an item, navigate back to the list view, and then tap into the same story again the story text will not render. This is usually repeatable if you swipe back and tap into the same story again. Tapping into a different story from the one you were previously looking at works fine and after doing that you can view the original story again too.

![screenshot_01](https://user-images.githubusercontent.com/44229/116249142-81a5ca80-a73a-11eb-9129-9578070f6057.jpg)

Here's another:

> Some sites, like MacRumors here, show a blank page instead of the content. Sometimes toggling between the Text and Story modes help but not always.

 ![original-2](https://user-images.githubusercontent.com/44229/116249227-984c2180-a73a-11eb-9cb6-63de0b442339.jpg)

**Comment by samuelclay** [comment]
Here's a recent thread about this issue: https://forum.newsblur.com/t/ios-first-two-items-in-folder-load-empty-body/8665

Seems to be a race condition on load. Can we inject some slow-downs in the JS or image rendering to see if we can force a repro of this issue?

**Comment by Dejal** [comment]
Leaving this open for now; that change may or may not help. If I experience it again, I'll experiment some more. Let me know if anyone experiences it after using this change.
