### ISSUE TITLE
Android: New font options are difficult to read

### ISSUE THREAD

**Issue by whispy** [samuelclay/NewsBlur#1468]
App version 11.0b1

I find each of the new font options provided in the new beta to be difficult to read for longform content. The new "Default" option is highly legible for titles and labels, but **not** readable for body text. (I have also tried the other listed options, like Noto Sans and so on, with little improvement.)

Can you please add back in the previous default font as a selectable option? I found that one to be optimally readable for both longform and title/label content.

Thanks! I do appreciate the overall polish in this beta!

**Comment by samuelclay** [comment]
I believe we're using the wrong Whitney on Android. There's Whitney SSm (ScreenSmart) which is what the web uses for text, and Whitney A/B, which is used for titles. @sictiru, can you confirm which we're using? The font files for SSm are in clients/ios/Resources/fonts.

**Comment by samuelclay** [comment]
Yeah, I see that it's WhitneySSm-Book. We should also have Bold in there, as the native bold applied to Book is nowhere near as good.

@whispy Can you post a screenshot?

**Comment by sictiru** [comment]
@samuelclay WhitneySSm-Semibold was added in parallel to WhitneySSm-Book. I opted for the Semi Bold because Bold was too strong next to Book. I'll change it to Bold if you think otherwise.
Also let me know if we should support the standard Android Roboto font again.

**Comment by sictiru** [comment]
Bold
![android bold](https://user-images.githubusercontent.com/13900221/116494054-e5241b00-a854-11eb-900e-ab0c60fce3e5.jpg)

Semi bold
![android semi bold](https://user-images.githubusercontent.com/13900221/116494058-e6edde80-a854-11eb-8c84-f0cd87e6adf8.jpg)

**Comment by whispy** [comment]
Here's a screenshot with the font set to default: 
![Screenshot_NewsBlur_20210428-224003](https://user-images.githubusercontent.com/2874975/116496293-b9b02900-a872-11eb-889c-0db5a2b82abd.png)

I would absolutely like it if the previous default font (Android Roboto?) were added back as an option, @sictiru.

**Comment by samuelclay** [comment]
I thought Roboto was an option, but yeah let's add it back in for stories. The story titles shouldn't have a font option, though. We don't have one on the web or iOS, so Whitney for story titles and feed titles is the NewsBlur look.

**Comment by samuelclay** [comment]
Agreed on Semi Bold. That's also what we're using on the web.

**Comment by whispy** [comment]
> I thought Roboto was an option, but yeah let's add it back in for stories. The story titles shouldn't have a font option, though. We don't have one on the web or iOS, so Whitney for story titles and feed titles is the NewsBlur look.

Keeping a consistent identity makes sense. Thanks for adding back in Roboto as a story option!
