### ISSUE TITLE
Android: Full bleed images

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1471]
iOS has had this and I just launched it on the web. It's always a bit tricky to implement, but the relevant CSS changes can be found in this commit: b4ade7afc08b4366543d7b182a357248551f7ae2

Part of how full bleed images work is that on page load, we check every image after it loads and see if its width is greater than 320px and its height is greater than 50px, and if so add a "NB-large-image". If not, add a "NB-small-image". The JS code for this lives in media/js/newsblur/views/story_detail_view.js:watch_images_load:L132. You'll need the imagesLoaded library, which is at media/js/vendor/imagesLoaded-4.1.0.js.

So there's three states here: unloaded but loading, large, and small. We do this differently between the web and iOS. On iOS, images are kept at their natural size (NB-small-image doesn't do anything, it's mainly to see that an image is small instead of large when debugging) and then grown to full bleed when loaded. On web, we do it the opposite and assume images are large (therefore NB-large-image doesn't do anything) and add NB-small-image when it's small (javascript exposes this as `this.naturalWidth`). Therefore on the web images will look great on load but will shrink when small. On iOS, images will pop larger after loading.

I believe the web version is better because I notice it less. And when an image fixes itself, it's not a big deal, just as much as an image enlarging itself. So if the cost is the same either way, better to assume the image is large.

**Comment by sictiru** [comment]
@Dejal could you provide more context into how is this implemented on iOS and what is the high level flow on your side?

**Comment by Dejal** [comment]
@sictiru This wasn't something I added. It just uses Javascript and CSS as Sam describes; no native code. The app loads the page HTML, which includes `storyDetailView.js`, which in turn calls a `loadImages()` Javascript function to set the CSS for the images.

**Comment by samuelclay** [comment]
Take a look at 5295b8d19062370b741bb77e6a2210d6c9956583 to see how I made it work on iOS. Basically negative-margin and a width of calc(100% + 2*margin). That seems to work well in CSS3.

**Comment by samuelclay** [comment]
I see the commit but images aren't full bleed yet. Is it only under certain conditions?

**Comment by sictiru** [comment]
@samuelclay Could you attach a screenshot with a full bleed image example from iOS? I don't have access to an iPhone until next week and the fix here might be a quick CSS change after the last commit.

**Comment by samuelclay** [comment]
Sure, here's a screenshot from the "Betabeat" publisher:

![IMG_78240EFAEDA9-1](https://user-images.githubusercontent.com/44229/123996071-f399ca80-d99c-11eb-9710-636fec8dcb52.jpeg)

**Comment by sictiru** [comment]
Looks like a deeper dive is required into the CSS file to make this happen.
