### ISSUE TITLE
iOS: On iPad landscape, the third column is offset

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1475]
From TestFlight feedback:

![original-4](https://user-images.githubusercontent.com/44229/117200658-b8728500-adb9-11eb-92b9-faccb61f01e8.jpg)

**Comment by Dejal** [comment]
I still can't reproduce this. I'll keep trying, but if you can provide any reliable steps to repro, that'll help.

**Comment by Dejal** [comment]
Since I can't repro this, and haven't seen any recent reports, I'm going to close it. Feel free to re-open if you see it, especially if you can provide steps to repro.
