### ISSUE TITLE
Android: Taller image previews

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1482]
This is to make the story title image thumbnail match the height of the story. See this screenshot from the web. 

Note that the CSS to achieve this is:

```
.NB-story-title .NB-storytitles-story-image {
    position: absolute;
    right: 0;
    width: 86px;
    height: 100%;
    background-size: 40%, cover;
    background-position: 50% 50%, 50% 30%;
    background-repeat: no-repeat;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

<img width="1470" alt="Screen Shot 2021-05-17 at May 17 4 41 00 PM" src="https://user-images.githubusercontent.com/44229/118553793-ca93e200-b72e-11eb-935c-b7ee6f18aecd.png">

**Comment by samuelclay** [comment]
I'm taking screenshots now and this would be appreciated as the next priority.

**Comment by sictiru** [comment]
@samuelclay This should be ready for screenshots. 
I'm continuing the work on images to cleanup and simplify the code and move away from rounding image corners on decoding, which will be committed under the same task for context.

**Comment by samuelclay** [comment]
Lovely!

![redesign-ios-android](https://user-images.githubusercontent.com/44229/123999293-5b054980-d9a0-11eb-9a7d-4fd610a1a779.png)

**Comment by samuelclay** [comment]
Let's move up the top alignment of the image to be inline with the favicon

**Comment by samuelclay** [comment]
And add a bit more rounding
