### ISSUE TITLE
iOS: On Tile mode, swiping every other story is prevented (see video)

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1485]
I'm using the same amount of force every time, but the story won't advance,

https://user-images.githubusercontent.com/44229/118561927-ccaf6e00-b739-11eb-8921-539701a8a3dd.MP4

**Comment by Dejal** [comment]
That's a strange one. The paging mechanism is unchanged from how it's worked for years, but I do confirm that it seems a bit more finicky in portrait tile mode.

The way the paging works (as you implemented it) is it changes pages when scrolling at least halfway across the page.
