### ISSUE TITLE
iOS: Add 2/3/fullscreen columns menu to Feed List Menu

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1490]
Right now it's only in the Story Titles Menu. It'd be nice if it's also in the Feed List Menu.

I also updated the icons and names for it, so it now shows 2 and 3 columns and uses Full Screen for Overlay. Does that seem correct?

We may want to think about making it more discoverable. Perhaps splitting Style from Settings, similar to how we do it on the web. Instead of having it be another menu, we'll stick with the single popover, but with a more obvious separation between settings and style.

**Comment by Dejal** [comment]
I've added the split mode control to the feeds menu. Which was justification to finally replace that menu with a standard `MenuViewController`-based one, eliminating a bunch of code.

Yes, I like the icons, and Full Screen makes sense too. You could use a single wide rectangle to represent that as an icon, if desired (i.e. 1 column).

I have moved the split mode control after the reading settings, followed by the feed detail & story orientation controls, then the feed detail controls. That grouping and order makes more sense, I think.
