### ISSUE TITLE
iPad: No scroll bounce at the bottom of a story

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1491]
Only see it on iPad. When I scroll down on a story, there's no scroll bounce. There is when I scroll to the top.

**Comment by Dejal** [comment]
Weird; it only happens when showing two columns. When using the three column mode, it works fine, but if you hide the feeds list, it stops bouncing. Which is strange, since showing or hiding the feeds list and/or feed detail doesn't change the story view.

**Comment by samuelclay** [comment]
Let's also make two column mode the default (instead of Auto). Full screen is easy enough to tap into, and people who want a stretched 3 column will have to know where to find it.
