### ISSUE TITLE
Unable to Mark Stories as Unread

### ISSUE THREAD

**Issue by jgbishop** [samuelclay/NewsBlur#1502]
I have one particular feed that is behaving strangely. The feed URL is: https://www.ncbirdingtrail.org/feed/

I added this feed (which is new to me) to my account, and all the pre-existing stories were marked as read. I typically browse in the river of news mode, showing only unread only, sorted oldest to newest. As a result, it appeared as if this feed had no stories to view.

I changed my view to show all stories, and I am able to see the stories in the feed just fine. However, if I try to mark any of the stories as unread (by pressing `[U]`), they immediately get marked as read again. See the screenshot below for what's happening. I'm using the latest version of Chrome, and I did a force refresh of the site (Ctrl + F5) to flush anything that might have been cached).

![animation](https://user-images.githubusercontent.com/4210087/122643985-bc940100-d0e0-11eb-9c2a-663bfc29ade6.gif)

**Comment by jgbishop** [comment]
I should also mention that this is the only feed that is behaving this way for me. All other feeds are working as I would expect them to.

**Comment by samuelclay** [comment]
Note that the story is from May 10th, which is more than 30 days old. NewsBlur only allows for 30 days of unreads.

**Comment by jgbishop** [comment]
I didn't realize about that limit. Does that even apply to paid accounts?

**Comment by samuelclay** [comment]
The limit is 14 days for free accounts and 30 days for paid subscribers.

**Comment by jgbishop** [comment]
Ok, thanks for the info! Keep up the great work.
