### ISSUE TITLE
Web: Limit full-bleed images on desktop

### ISSUE THREAD

**Issue by jgbishop** [samuelclay/NewsBlur#1507]
The new full-bleed image feature is neat, but there are a number of cases where it makes things look awful. Below are a few examples of single-panel comic strips that look quite pixelated with this new feature (and one screenshot showing one such comic image at its native size).

I could imagine a few possibilities for improving this experience:

1. The full-bleed state could only activate for images above some (configurable?) width (e.g. if the image is larger than 1000 pixels, stretch it).
2. Constrain full-bleed width to some multiple of the original image size (i.e. only allow the image to grow to 2x its original width).
3. Allow the **story width** option to be feed-specific, not global. I'd love for some sites (comic strip feeds) to be constrained to 700px, but other sites (photo blogs, for example) I might want to span the whole screen.

I realize everyone may not browse the web at full-screen, but I do, and this new feature makes some images simply too big.

**Note:** View these attachments at full size to get a sense of how pixelated the images end up being.

![full_bleed](https://user-images.githubusercontent.com/4210087/124277400-ff0f0200-db12-11eb-8d5c-1476edd2513d.jpg)
![regular_size](https://user-images.githubusercontent.com/4210087/124277407-01715c00-db13-11eb-9a40-6f4bfa072803.jpg)
![full_bleed_2](https://user-images.githubusercontent.com/4210087/124277418-033b1f80-db13-11eb-8d93-24bbb096911b.jpg)

**Comment by samuelclay** [comment]
Fixed in f780c070c, now deployed.
