### ISSUE TITLE
Android: Sharesheet to share content from other apps with NewsBlur

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1516]
We should support both sharing stories publicly and save stories privately, with saved story tags. This is a rewrite of #384. Since we launched on both the web and iOS, Android should have the ability to inject content from other apps.

**Comment by samuelclay** [comment]
This feature will give users the ability to Save a story or Share a story from another app. Think of this as the bookmarklet but for Android. A user invokes it while in their browser and want to share/save to newsblur without leaving the app.

**Comment by satmandu** [comment]
I recall asking for exactly this some years ago. Hooray!

**Comment by sictiru** [comment]
The API documentation states that `/social/share_story` requires a `story_id` and a `feed_id`. The story url can be used as the `story_id` but what would be the best way to fetch the `feed_id` and `story_hash`, the latter being necessary for `/reader/mark_story_hash_as_starred`?

**Comment by sictiru** [comment]
Using `/api/save_story/` doesn't seem to work. It returns 200 for both auth and non auth users, with the response content being a HTML page.

Sharing a story to one's blurblog works as expected with `/api/share_story/` and the UI will be similar to iOS.

**Comment by samuelclay** [comment]
What's the content of that HTML page? Also, looking at `apps/api/views.py#save_story` it looks like it requires a POST. Just double checking. But that endpoint only returns JSON, so I'm wondering what you're seeing.

**Comment by sictiru** [comment]
@samuelclay
[save story response.zip](https://github.com/samuelclay/NewsBlur/files/8149662/save.story.response.zip)

**Comment by samuelclay** [comment]
Looks like I neglected to hook the URL up correctly. Try now, should be working.
