### ISSUE TITLE
"feed has no original page" on certain sites

### ISSUE THREAD

**Issue by ssweeny** [samuelclay/NewsBlur#1519]
With feeds on certain sites, in particular the New York Times and Washington Post I see a `feed has no original page (404)` error in the "Statistics" listing and I see a ! next to the "Original" button when showing those feeds.

Reading/browsing seems to work, and in most cases the content of the articles is fetch-able with the "Text" button, but I'm curious whether the feeds themselves are not produced correctly or there is some error on Newsblur's side (a la #1434)

Some example feeds which show this behavior:
https://rss.nytimes.com/services/xml/rss/nyt/US.xml
http://feeds.washingtonpost.com/rss/national

**Comment by samuelclay** [comment]
Thanks for pointing this out. Those are both in the explicitly banned url list, which you can see here:

https://github.com/samuelclay/NewsBlur/blob/master/apps/rss_feeds/page_importer.py#L32-L43

I changed the logs to say that the 404 is because NewsBlur is banned.

**Comment by samuelclay** [comment]
Note this is just for the Original view. Feed, Text, and Story view continue to work.
