### ISSUE TITLE
Android: App crashes when opening a specific story

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1525]
Here's the thread: https://forum.newsblur.com/t/android-app-crashes/8908

Here's the site: https://www.newsblur.com/site/6270708/brave-browser

Story title is BAT Roadmap v2

**Comment by alexandru** [comment]
Hello,

Was this deployed?

It was still reproducible on stable & beta today. I then figured that it may be a caching issue, so I cleared the cache & data, and now it seems to be working.

**Comment by samuelclay** [comment]
Yep, this should be released to general availability as of yesterday.
