### ISSUE TITLE
iOS: Sites should load immediately using offline cache, before new sites come in

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1534]
The app used to do this, so I'm not sure when it changed. But right now the app can take 5-10 seconds to load my feeds. It used to load a stale cached version of my feeds and then pop in the new feeds as they came in. This allowed me to read feeds immediately, even if the unread counts would change in a bit.

**Comment by Dejal** [comment]
It does do that. Maybe you've disabled offline stories in your preferences?

Please check your settings, and if you're sure there is an issue, provide a screen recording to show me what you experience.

**Comment by samuelclay** [comment]
Here's a video. This happens multiple times a day. But if I force-quit it and relaunch, everything comes in as it should, cached feeds, cached icons, and cached avatar.


https://user-images.githubusercontent.com/44229/131706030-a42019c8-b85e-412f-8571-17839f7aa9c3.MP4

**Comment by samuelclay** [comment]
I believe this is also the cause for notifications not working. I've found that notifications work flawlessly if I load sites first, then force quit the app. But if I wait another hour (or even less), then my cached account/feeds are gone and notifications go nowhere.

**Comment by Dejal** [comment]
This is a tricky one to diagnose. I've tried to reproduce it, but haven't managed yet. Of course, when running in the debugger is even harder, since running the app from Xcode is like the force quit situation.

**Comment by samuelclay** [comment]
Closing for now, I haven't seen it happen for a while.
