### ISSUE TITLE
Docker: Cannot login when website is accessed from other machine in LAN (not localhost)

### ISSUE THREAD

**Issue by louis-pre** [samuelclay/NewsBlur#1537]
Hello, 

I am trying to setup a self-hosted Newsblur instance on my Ubuntu 20 server (using docker) and I am having some difficulties. 

I am using the Makefile commands and while the installation works as expected when accessed from the server itself (accessing it through localhost), it does not behave the same when accessed from another computer on the same LAN.
On that other computer, I can load the homepage but the authentication has no effect (it redirects back to the homepage). 

My educated guess is that the session cookie is set for the domain localhost and is therefore useless when Newsblur is accessed through its host's LAN IP.
I have attempted to replace localhost by the LAN IP in `docker/local_settings.py` and `config/fixtures/bootstrap.json` without success, the cookie is still set for localhost.

I would love to have your input on what are the correct steps to take to enable access with a domain other than localhost. 

Thank you!

**Comment by louis-pre** [comment]
Update: 
I have managed to update the website's domain setting by updating `newsblur_web/docker_local_settings.py` too.
I am not sure if I am still missing something but it seems like it's working now so I will close this issue. 

Unrelated but could be helpful for anyone trying to self-host NewsBlur behind a reverse-proxy: 
NewsBlur only accepts a hardcoded list of subdomains (defined in `apps/reader/views.py`), I was stuck in an endless redirect loop until I started using one of the authorized subdomains.

**Comment by samcro1967** [comment]
I am also stuck in the login loop when trying to access via something other than localhost.  Here is what I tried:

```
updated NEWSBLUR_URL and SESSION_COOKIE_DOMAIN in docker/local_settings.py to IP address
updated DOMAIN in config/fixtures/bootstrap.json. to IP address
updated NEWSBLUR_URL and SESSION_COOKIE_DOMAIN in newsblur_web/docker_local_settings.py to IP address
docker exec -it newsblur_web bash
python3 manage.py makemigrations
python3 manage.py migrate
make rebuild
make nb

Entering username and password just redirects me back to the login page, unless I access NB via localhost.  I see in the logs below it recognizes I am trying to login, but then it appears to be redirected to / and goes back to AnonymousUser Loading Welcome.  

```
newsblur_web        | [Oct 31 12:05:11]  ---> POST /reader/login {'csrfmiddlewaretoken': ['qdVqBhW0w2naq3I0zqRxTwASU3UD06L0z7KxGwjrWGyc6cZ1ffwgE5hKFdFmqa93'], 'login...[22 bytes]...ys'], 'login-password': ['password'], 'login-add': [''], 'submit': ['log in'], 'next': ['/']}
newsblur_web        | [Oct 31 12:05:12]  ---> [------] [username*] Login
newsblur_web        | [Oct 31 12:05:12]  ---> [0.15s] DB times: sql: 0.0060s mongo: 0.00000s redis: 0.000274s
newsblur_web        | [Oct 31 12:05:12]  ---> GET /
newsblur_web        | [Oct 31 12:05:12]  ---> [Chrome] [0.01s] [AnonymousUser] Loading welcome
newsblur_web        | [Oct 31 12:05:12]  ---> [0.15s] DB times: sql: 0.0020s mongo: 0.00142s redis: 0.000152s
newsblur_web        | [Oct 31 12:05:12]  ---> GET /reader/feeds {'v': ['2'], 'update_counts': ['false']}
newsblur_web        | [Oct 31 12:05:12]  ---> [0.01s] DB times: sql: 0.0020s mongo: 0.00000s redis: 0.000262s
```

Is there another step I am missing?

**Comment by samuelclay** [comment]
I'm pretty sure that it can't be an IP address and must be a name instead. I always made it `nb.local.com` and added that domain to my `/etc/hosts` file locally.
