### ISSUE TITLE
node container cannot find module '@sentry/node'

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1543]
the node container is constantly restarting complaining about not finding @sentry/node like in this comment:

https://github.com/samuelclay/NewsBlur/issues/1444#issuecomment-810679265

i'm trying to build this on macos catalina (10.15.7) and had a similar error, and based on your response to that comment, i tried `npm install` in the node dir and got the following error:

npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/@postlight/mercury-parser/browser-request@github:postlight/browser-request#feat-add-headers-to-response" as it does not contain a package.json file.

is it me or does that not look right?

i tried to `npm install @postlight/mercury-parser` and aside from a bunch of deprecated warnings, i got the following error:

Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/luxiouronimo/.npm/_cacache/index-v5/b8/65'tus

i own that directory and it is writable, but the "tus" after the 2nd apostrophe looks out of place; perhaps this is a result of the first error..?

`npm install @sentry/node` results in:

npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/@postlight/mercury-parser/browser-request@github:postlight/browser-request#feat-add-headers-to-response" as it does not contain a package.json file.

**Comment by luxiouronimo** [comment]
this is no longer an issue

**Comment by samuelclay** [comment]
Glad that worked out? Was it the updated dependencies or did something local on your machine change?

**Comment by luxiouronimo** [comment]
the updated dependencies fixed this issue, tho i encountered another (seemingly related) one..:  [#1553](https://github.com/samuelclay/NewsBlur/issues/1553)

**Comment by Neutrino3316** [comment]
I experience the same problem. I use the latest master branch (714f31a) and run `make nb`, the error logs showes this:
```
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '@sentry/node'
Require stack:
- /srv/newsblur.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/srv/newsblur.js:5:12)
    at Object.<anonymous> (/srv/newsblur.js:74:4)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/srv/newsblur.js' ]
}
```

Is there any dependencies changed? What was the commit id when you successfully built last time?  @​luxiouronimo :pray:​

**Comment by luxiouronimo** [comment]
it didn't successfully build, it resulted in a different error than this one

based on the history further up i'd say it was commit 8ce2557

**Comment by samuelclay** [comment]
Let me know if you're still having any issues. We refactored this a bit recently in November and I believe it works better. I tested it on my new M1 Pro to try to iron out the kinks.

**Comment by luxiouronimo** [comment]
adding "sleep 60;" where you suggested over in #1558 lets it make without fail, and i am able to reach it at localhost!

thank you kindly!
