### ISSUE TITLE
Android: Not being able to login (self-hosted & official website)

### ISSUE THREAD

**Issue by nicolasshu** [samuelclay/NewsBlur#1546]
Hi,
I have not been able to login to the Android app. I have tried a self-hosted environment as well as your official website, and yet still, every time I try to login via the application, I obtain the following:

"Logging in... Retrieving feeds..."

And then I receive the: 
"There was a problem logging in to NewsBlur"

I tried to do a little of my homework, but I'm not sure how to check the logs. I ran it on an Android Studio on a Manjaro distribution, and from there, I was able to access the official server, not my self-hosted instance, and then I tried the official server again, and it didn't work anymore. I tried to check #1439 and #1356, but none of them seemed to work. I went on F-Droid and tried installing the v10.3, but that did not work either. So yeah, the only instance I was able to get it working was on an Android Emulator via Android Studio, and only to the official server (once). I have a Pixel 3a running an Android 11 with the Kernel 4.9.248-gc4689af91bc5-ab7425221.

I also have tried to use the beta version of NewsBlur on the Play Store after I have cleared my cache from the Play Store app and Webview app. Perhaps it's also important to note that, on my self-hosted instance, it is behind a HTTP protocol, and not a HTTPS. Not sure if that makes any difference. *shrug in confusion*

Do you have any tips? Thanks!

**Comment by nicolasshu** [comment]
Oh so here is something that I found out. When you have a fresh install (e.g. a new Android system [I had to wipe my tablet earlier in the night]), you will be able to connect to the official server without a problem. I was able to login twicetto tthe oofficial sserver.

**Comment by nicolasshu** [comment]
Sorry, I was typing on my phone and it closed the issue. Continuing... 
But the moment you try to connect to a personal server, it will not allow you to, and will leave a cookie of some sort behind, which will not allow you to login to the official server. I can't pinpoint the cause of it, but I figured I'd report thos symptom. When I went and cleared the data/cache, it allowed me to login to the official servers. 
Do you know why amI then not being able to get on the personal server?

**Comment by sictiru** [comment]
@nicolasshu Your self-hosted environment didn't work because starting from Android 9 (API 28) all traffic must be via HTTPS.

Once a custom server url is set there is no way to remove it unless the app storage is manually cleared. I'll make changes on the login step to handle custom server urls.
