### ISSUE TITLE
Android: Crash on Samsung Fold 3

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1550]
As reported in the forums: https://forum.newsblur.com/t/got-a-new-phone-newsblur-app-doesnt-work/9000/2

**Comment by sictiru** [comment]
Crash was linked and fixed in https://github.com/samuelclay/NewsBlur/issues/1546.

**Comment by sictiru** [comment]
https://forum.newsblur.com/t/app-crashes-in-android/9009
