### ISSUE TITLE
iOS: Custom domain crashes app on start

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1552]
Using a selfhosted version of Newsblur,
and after entering the custom URL,
and restarting the app,
entering the user + password click on login -> crash
reopen app -> login + password required again.

**Comment by samcro1967** [comment]
I am self hosting also.  The iOS app crashed for me on the first launch.  After running a second time and updating the custom domain URL, I just get a blank screen and it says offline.  I am able to access the URL fine from Safari.

**Comment by samuelclay** [comment]
Are you using the TestFlight version or App Store version? TestFlight should work for custom domains, but it's possible I'm misremembering and we just fixed that on Android and not iOS.

**Comment by xanthos84** [comment]
App Store Version.
Where to get the TestFlight Version?

**Comment by samuelclay** [comment]
Here's the TestFlight invite: http://testflight.apple.com/join/hYk9WU3f

**Comment by xanthos84** [comment]
thanks! app crashing. sent a log direct from the crash report.

Samuel Clay ***@***.***> schrieb am Mi. 8. Dez. 2021 um 20:23:

**Comment by xanthos84** [comment]
btw 10.0.1 is not crashing,
it started with 10.1



Samuel Clay ***@***.***> schrieb am Mi. 8. Dez. 2021 um 20:23:

**Comment by samuelclay** [comment]
I wonder if this is due to an invalid certificate. Can you try without https for your custom domain? HAProxy might be redirecting you, though, in which case well have to figure out what to do with it.

**Comment by samuelclay** [comment]
Got the crash report. I'll note that you're on iOS 14, so would you be able to run this on iOS 15 and see if it's still an issue?
<img width="670" alt="Screen Shot 2021-12-08 at Dec 8 3 01 11 PM" src="https://user-images.githubusercontent.com/44229/145276104-58fe441f-6ef7-4707-9219-2b8406317bb3.png">

**Comment by xanthos84** [comment]
I got my own reverse proxy solution, so no HAProxy - and working ssl
certificate.
My server is only hosting on https.
And as said, 10.0.1 version works fine. from 10.1 it crashes.
cheers

Am Mi., 8. Dez. 2021 um 20:58 Uhr schrieb Samuel Clay <
***@***.***>:

**Comment by samuelclay** [comment]
Mind sharing the domain so I can try it out? Feel free to email it: samuel@newsblur.com

**Comment by xanthos84** [comment]
Well, I am not upgrading my  IPad to 15 anytime soon.
So if 14.3 is not supported, I will stay on newsblur 10.0.1 ..

Am Mi., 8. Dez. 2021 um 21:01 Uhr schrieb Samuel Clay <
***@***.***>:

**Comment by samuelclay** [comment]
Looks like the issue happens after the feed list is loaded, which makes me think something is going on with what the data looks like.

```

Last Exception Backtrace:
0   CoreFoundation                	0x19f83686c __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1b47a5c50 objc_exception_throw + 60 (objc-exception.mm:565)
2   CoreFoundation                	0x19f73d95c -[NSObject(NSObject) doesNotRecognizeSelector:] + 144 (NSObject.m:146)
3   CoreFoundation                	0x19f839438 ___forwarding___ + 1444 (NSForwarding.m:3597)
4   CoreFoundation                	0x19f83b740 _CF_forwarding_prep_0 + 96
5   NewsBlur                      	0x10218ea10 __49-[FeedsObjCViewController finishLoadingFeedList:]_block_invoke_2 + 1228 (FeedsObjCViewController.m:604)
6   NewsBlur                      	0x1022a9520 __46-[FMDatabaseQueue beginTransaction:withBlock:]_block_invoke + 204 (FMDatabaseQueue.m:125)
7   libdispatch.dylib             	0x19f42adb0 _dispatch_client_callout + 20 (object.m:559)
8   libdispatch.dylib             	0x19f439428 _dispatch_lane_barrier_sync_invoke_and_complete + 60 (queue.c:998)
9   NewsBlur                      	0x1022a9424 -[FMDatabaseQueue beginTransaction:withBlock:] + 204 (FMDatabaseQueue.m:114)
10  NewsBlur                      	0x1022a9660 -[FMDatabaseQueue inTransaction:] + 80 (FMDatabaseQueue.m:143)
11  NewsBlur                      	0x10218e454 __49-[FeedsObjCViewController finishLoadingFeedList:]_block_invoke + 224 (FeedsObjCViewController.m:583)
12  libdispatch.dylib             	0x19f42924c _dispatch_call_block_and_release + 32 (init.c:1454)
13  libdispatch.dylib             	0x19f42adb0 _dispatch_client_callout + 20 (object.m:559)
14  libdispatch.dylib             	0x19f42dddc _dispatch_queue_override_invoke + 692 (inline_internal.h:2548)
15  libdispatch.dylib             	0x19f43b93c _dispatch_root_queue_drain + 356 (inline_internal.h:2589)
16  libdispatch.dylib             	0x19f43c120 _dispatch_worker_thread2 + 116 (queue.c:6777)
17  libsystem_pthread.dylib       	0x1ea2d77c8 _pthread_wqthread + 216 (pthread.c:2219)
18  libsystem_pthread.dylib       	0x1ea2de75c start_wqthread + 8

```

**Comment by xanthos84** [comment]
just sent you a crash report from my iphone which is on the newest ios.
same crash after login on my feed server.


Am Mi., 8. Dez. 2021 um 21:05 Uhr schrieb Samuel Clay <
***@***.***>:

**Comment by xanthos84** [comment]
this issue is still happening with newest version just released (11.1)
on iPadOS 15.2

**Comment by samuelclay** [comment]
I wonder what the data looks like that it's crashing on. Are you able to use Xcode? If not, can you send latest crash details?

**Comment by xanthos84** [comment]
> 

it would make more sense if you would just connect to my server,
i can send you the details by mail!

**Comment by samuelclay** [comment]
Oh that'd be great! Yeah I asked for it earlier but I forgot to follow up. Send it by email or share here. samuel@newsblur.com. I'll send it over to @dejal to take a look.

**Comment by samuelclay** [comment]
Looks like you're using some custom reverse proxy in front of newsblur (openresty) so I'm afraid it's out of our hands. 

If you want to fix this, get Xcode and run it and see what's causing the crash. But because it's for a custom config, we don't have the resources to do custom work.
