### ISSUE TITLE
Host key verification failed. fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1553]
error/failure when doing a "make nb" on macos 10.15.7

here's the end of the debug.log:

3875 verbose stack Error: exited with error code: 128
3875 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
3875 verbose stack     at ChildProcess.emit (events.js:182:13)
3875 verbose stack     at maybeClose (internal/child_process.js:962:16)
3875 verbose stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
3875 verbose stack     at Socket.emit (events.js:182:13)
3875 verbose stack     at Pipe._handle.close (net.js:610:12)
3876 verbose cwd /Users/luxiouronimo/Documents/NewsBlur/node
3877 verbose Darwin 19.6.0
3878 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3879 verbose node v10.14.2
3880 verbose npm  v6.9.0
3881 error Error while executing:
3881 error /usr/bin/git ls-remote -h -t ssh://git@github.com/postlight/difflib.js.git
3881 error
3881 error Host key verification failed.
3881 error fatal: Could not read from remote repository.
3881 error
3881 error Please make sure you have the correct access rights
3881 error and the repository exists.
3881 error
3881 error exited with error code: 128
3882 verbose exit [ 1, true ]

**Comment by samuelclay** [comment]
What happens when you install https://github.com/postlight/mercury-parser directly:

`npm install @postlight/mercury-parser`

**Comment by luxiouronimo** [comment]
**after fresh git clone, make nb:**

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/postlight/difflib.js.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luxiouronimo/.npm/_logs/2021-10-06T13_53_02_905Z-debug.log


**npm install @postlight/mercury-parser**

that appears to have worked, despite claims of package.json not existing:

npm WARN saveError ENOENT: no such file or directory, open '/Users/luxiouronimo/Documents/NewsBlur/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @postlight/mercury-parser@2.2.1 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
npm WARN enoent ENOENT: no such file or directory, open '/Users/luxiouronimo/Documents/NewsBlur/package.json'
npm WARN NewsBlur No description
npm WARN NewsBlur No repository field.
npm WARN NewsBlur No README data
npm WARN NewsBlur No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: http-headers@3.0.2 (node_modules/@postlight/mercury-parser/node_modules/http-headers):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined

+ @postlight/mercury-parser@2.2.1
added 165 packages from 246 contributors and audited 165 packages in 8.938s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details


**make nb:**

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/postlight/difflib.js.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luxiouronimo/.npm/_logs/2021-10-06T14_00_41_003Z-debug.log

**Comment by Neutrino3316** [comment]
> **after fresh git clone, make nb:**
> 
> npm ERR! Error while executing: npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/postlight/difflib.js.git npm ERR! npm ERR! Host key verification failed. npm ERR! fatal: Could not read from remote repository. npm ERR! npm ERR! Please make sure you have the correct access rights npm ERR! and the repository exists. npm ERR! npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /Users/luxiouronimo/.npm/_logs/2021-10-06T13_53_02_905Z-debug.log
> 
> **npm install @postlight/mercury-parser**
> 
> that appears to have worked, despite claims of package.json not existing:
> 
> npm WARN saveError ENOENT: no such file or directory, open '/Users/luxiouronimo/Documents/NewsBlur/package.json' npm notice created a lockfile as package-lock.json. You should commit this file. npm WARN @postlight/mercury-parser@2.2.1 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions. npm WARN enoent ENOENT: no such file or directory, open '/Users/luxiouronimo/Documents/NewsBlur/package.json' npm WARN NewsBlur No description npm WARN NewsBlur No repository field. npm WARN NewsBlur No README data npm WARN NewsBlur No license field. npm WARN optional SKIPPING OPTIONAL DEPENDENCY: http-headers@3.0.2 (node_modules/@postlight/mercury-parser/node_modules/http-headers): npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
> 
> * @postlight/mercury-parser@2.2.1
>   added 165 packages from 246 contributors and audited 165 packages in 8.938s
>   found 2 vulnerabilities (1 low, 1 moderate)
>   run `npm audit fix` to fix them, or `npm audit` for details
> 
> **make nb:**
> 
> npm ERR! Error while executing: npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/postlight/difflib.js.git npm ERR! npm ERR! Host key verification failed. npm ERR! fatal: Could not read from remote repository. npm ERR! npm ERR! Please make sure you have the correct access rights npm ERR! and the repository exists. npm ERR! npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /Users/luxiouronimo/.npm/_logs/2021-10-06T14_00_41_003Z-debug.log

How about manually execute `npm install postlight/difflib` ? Maybe this will work @luxiouronimo

**Comment by luxiouronimo** [comment]
oki this is no longer an issue; it now builds past that part, and i'm having a different issue noted in #1558
