### ISSUE TITLE
Intelligence Trainer: Universal custom "Titles and Phrases"

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1555]
**Is your feature request related to a problem? Please describe.**
Currently "Intelligence Trainer" filters are based upon single sites. For example, I wanna see  "_India_" title related to all articles from sites, there is no option to add custom Titles and Phrases #1554 as a whole.

**Describe the solution you'd like**
- Universal custom "Titles and Phrases" for all your Newsblur feeds
- Universal custom "Titles and Phrases" based on user preferred folders/sub-folders

**Comment by samuelclay** [comment]
A feature like this would work well for the upcoming NewsBlur Pro. Closing in favor of #1576.
