### ISSUE TITLE
iOS: Recently muted site unread count still shows up in total count

### ISSUE THREAD

**Issue by Mastermjr** [samuelclay/NewsBlur#1561]
Not sure if this is the correct place, but I've found an issue with the ios app (or possibly a feature?) 
When I mute a site on the web application in my browser, the total unread articles is updated to remove the number from that unread site (I've done this on feeds that gather too many articles, but still are nice to have if I want to read one day). 

However in ios they still appear in the total unreads, and this is quite frustrating as it doubles/triples my number of unread articles and discourages me from reading. 

I understand this may not be the best place to post or that this issue is difficult to fix. 
If so let me know how I can help. 

## To test: 
add a site
mute the site
total unreads should not reflect the count from the unreads for the muted site

**Comment by samuelclay** [comment]
You're right, we should be checking if a muted site has an unread count. @Dejal, I tested this by muting a site on the web and then pulling to refresh on iOS. The web count was right but iOS was not.

Now, I have a few hundred muted sites and they aren't being counted. So I believe the total count should check a feed's is_active status.

**Comment by Mastermjr** [comment]
Great Thanks All!! Excited to see the update! I really am appreciating the app!

**Comment by samuelclay** [comment]
This is out on TestFlight now, so you can use it immediately. I'm hoping to push out a full update within a week or two as we iron out the few remaining bugs.
