### ISSUE TITLE
Docker image - Youtube not working

### ISSUE THREAD

**Issue by samcro1967** [samuelclay/NewsBlur#1563]
Youtube feed get added as untitled and show no articles.  Tried several links and get the same result for all.  Tested the one below in another app and it displays as expected.

https://www.youtube.com/feeds/videos.xml?channel_id=UCZNhwA1B5YqiY1nLzmM0ZRg

**Comment by samuelclay** [comment]
To make YouTube feeds work on your local installation, you'll need to register for a YouTube API key, which you can override in docker_local_settings.py under `YOUTUBE_API_KEY`.
