### ISSUE TITLE
iOS: Show Changes button broken

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1567]
Looks like it broke recently. Try a Twitter feed like https://twitter.com/bicyclelobby which constantly had like count changes. 

![image](https://user-images.githubusercontent.com/44229/141460744-e7d32fbc-25f6-4faa-9eaa-a399d9a2cfbb.png)

**Comment by Dejal** [comment]
The `/rss_feeds/story_changes` API request is getting a 405 status code error: `Request failed: method not allowed (405)`. So the issue seems to be server-side.

**Comment by samuelclay** [comment]
Are you POSTing to /rss_feeds/story_changes? It looks like it's expecting a GET request with the story_hash.
