### ISSUE TITLE
iOS: iPad feed list layout issues on launch

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1571]
Neither the dark status bar nor the "double spacing" happened with the previous TestFlight beta.

![IMG_0474](https://user-images.githubusercontent.com/68303/143512643-c798e687-6cdf-4824-9c2d-1af7cde09136.png)

**Comment by Dejal** [comment]
Yeah, I noticed those too. Seems to be things iOS 15 introduced. Annoying when they mess with the metrics or behaviors.

**Comment by nriley** [comment]
Now you mention it, I'm remembering where I saw that in a WWDC video. Answer seems to be in many places including this one: https://stackoverflow.com/questions/68155090/extra-padding-above-table-view-headers-in-ios-15 — hopefully that'll work.

**Comment by Dejal** [comment]
Yep, already fixed, but thanks. The status bar is proving a bit trickier, but getting there.

**Comment by nriley** [comment]
Looks good on both counts, thanks!

(I also got my NewsBlur iOS build environment up and running again on my new MBP today so I can actually test things prior to TestFlight again… of course this happened about a minute before you posted it to TestFlight.)
