### ISSUE TITLE
Android: Images are decoded without checking image size

### ISSUE THREAD

**Issue by sunshinelwj** [samuelclay/NewsBlur#1573]
When loading an image, Google suggests us to resize the image before decoding them, so as to save memory resource.
https://developer.android.com/topic/performance/graphics/load-bitmap.html

However, in the code below, images are decoded by decodeByteArray() directly without checking image size:
com.newsblur.activity.FeedSearchAdapter.java onBindViewHolder()
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/activity/FeedSearchResultAdapter.kt#L30

Are these images all of small size and do not need to be resized? 

Also, onBindViewHolder() is performed in the UI thread, which means image decoding is performed in the UI thread. Because image decoding is of high time consumption, you can perform these operations in worker threads (e.g., via AsyncTask).

In addition, Google suggests us to cache the bitmaps that can be reused, so as to keep a fluid and fast-loading UI.
https://developer.android.com/topic/performance/graphics/cache-bitmap.html

onBindViewHolder() are frequently invoked and this means that there will be many bitmap objects being created if we not define a cache to store them. For performance considerations, maybe you can define memory cache to store the bitmap objects. Then app can reuse them instead of creating new bitmap objects continuously.

**Comment by samuelclay** [comment]
What's the feeling on priority here? How much of a performance hit or extra space are we using for this? Will end users notice and how?

**Comment by sictiru** [comment]
The favicon image is sent down in base64 encoding and it's decoded on the main thread without caching. This piece of code is celebrating its 10 year anniversary soon.
The impact to the end user would be very low if noticeable on current hardware.

@samuelclay if you want to send `favicon_url` to `/rss_feeds/feed_autocomplete` I'll make a separate ticket to update that. Until that happens the current favicon loading will be upgraded.

**Comment by samuelclay** [comment]
You can create a favicon url using this url template:

`/rss_feeds/icon/<feed_id>`
