### ISSUE TITLE
iOS: Support link in feed list settings menu

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1578]
Similar to how we have it on Android, there should be a simple way to get support from the iOS app. Let's link people to the support forum. Call it "Support forum" and put it above Logout.

**Comment by Dejal** [comment]
I used the world icon; if you'd like a different one, please provide.

<img width="275" alt="Support Forum" src="https://user-images.githubusercontent.com/1318849/146862945-7b199935-f912-4a22-89a0-6c00b1141a7c.png">
