### ISSUE TITLE
site root ("/") via subdomain redirects to lan ip, paths such as /folder/everything remain at the subdomain

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1580]
heya, sorry to be a pest, but i've done a buncha testing and can't fix this through other means..

i'm running the newsblur instance on an old mac mini via docker.. i have a reverse proxy elsewhere on a lan vm that for all intents and purposes works fine..

when i try and reach the root of https://nb.(subdomain).(mydomain).com it redirects to my lan ip: https://10.0.0.26

when i go to this (and other paths) directly:
https://nb.(subdomain).(mydomain).com/folder/everything it appears to load successfully and remain at that subdomain|url

is the root "/" route handled differently or something?

i tried this without the reverse proxy, and instead it redirected to localhost.. i've seen mentions of "you'll want to change the Site.objects.all()[0] entry in the shell", and while i can confirm that it incorrectly lists "<Site: localhost>", i can't find any info as to how to remedy that.. i do however think this is a different issue; one that is related to my default user profile icon trying to pull from localhost and instead showing a broken image.. i can file a separate issue if needed; there are others that i'm hoping this OP issue might help..

**Comment by samuelclay** [comment]
No need to feel like a pest. In fact, this is the opposite, I'm thrilled you're taking the time to get it right. I'll answer these tickets as often as they're made. I'm also getting back from 5 months of paternity leave (and now 2 weeks of winter vacation), so I'm a bit behind, but we'll get it working right.

As for changing the Site instance, that's really only handling emails and the occasional image. It's not doing the subdomain redirect. And yes, you're correct in that the homepage is handled differently. Let's take a look:

https://github.com/samuelclay/NewsBlur/blob/master/apps/reader/views.py#L90-L110

Well it looks like Site makes an appearance on line 104. So try changing that and seeing if it works.
