### ISSUE TITLE
I'm trying to export a list of the stories in my feeds, but I can't figure out how to log into the API in the first place.

### ISSUE THREAD

**Issue by NylaTheWolf** [samuelclay/NewsBlur#1582]
I've recently gotten into RSS and I started using Newsblur. And I've…kind of bitten off more than I can chew.

I subscribed to some feeds that post wayyyyy too often and it’s super overwhelming. Before I unsubscribe or use that intelligence trainer feature Newsblur has, I want to get a list of all the entries that are already there so I don’t miss anything I’d actually be interested in. I'm assuming this will I'm guessing this is something I can do through the API, but before asking here I wanted to see if anything the Newsblur API page lists would work.

I've tried the following:

```
curl --request POST --user "<username>:<password>" http://newsblur.com/api/login'

{"code": -1, "errors": {"username": ["Please enter a username."]}, "result": "ok", "authenticated": false}
```

When I didn't include the password, it prompted me for the password. I've tried pasting it, I've tried typing it out, neither worked.
```
curl --request POST --user "<username>" http://newsblur.com/api/login

Enter host password for user '<username>':
{"code": -1, "errors": {"username": ["Please enter a username."]}, "result": "ok", "authenticated": false}
```

I was told I needed to work with my cookies. I've tried exporting my cookies but to no avail.

```
curl -X POST --cookie-jar session.newsblur --data "username=NylaTheWolf" --data "password=<password>" https://www.newsblur.com/api/login 

{"code": 1, "errors": null, "result": "ok", "authenticated": true, "user_id": 625613}
```

```
curl POST -b "C:\Users\Nyla Smokeyface\Downloads\newsblur_cookies.txt" https://www.newsblur.com/api/login 

{"code": -1, "errors": {"method": "Invalid method. Use POST. You used GET"}, "result": "ok", "authenticated": true, "user_id": 625613}
```

So...I'm completely lost here. I haven't really used curl before so I don't know if it's something super obvious and I'm sorry if this is a dumb question, but I have no idea how to work with this API.

**Comment by samuelclay** [comment]
If you're interested, we built an Organizer that shows your RSS feeds in various orders and groupings and allows you to mass-delete subscriptions that are chatty or dead.

As for the `--user` flag, that's for HTTP Basic Auth. 

On your last attempt, the `-X` got dropped so it wasn't sent as a POST request. Try it again, you've almost got it!
