### ISSUE TITLE
iOS: sharing to Micro.blog or Micropub

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1585]
Apparently [this was requested in the NewsBlur forums years ago](https://forum.newsblur.com/t/sharing-to-micro-blog/6762), but it recently came up again in [a discussion on Micro.blog](https://micro.blog/issimonwoods/12307202), a service I use. So I thought I could look into supporting it.

We have the story sharing panel in the app, with buttons to share to Twitter and Facebook. I could add a third button to share to Micro.blog, or perhaps to Micropub. It'd display a web view to authenticate, similar to Facebook etc. I had a quick look, and found some code to help with posting.

**Comment by samuelclay** [comment]
The whole sharing feature needs to be redone with more OAuth to support Evernote, Pocket, etc. So you can share out the link to those services with a single tap without leaving the app. It'll be supported server side. But I feel like this ticket is addressed by the Share sheet and by #811.
