### ISSUE TITLE
iOS: Share text lost if switching back and forth into app

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1587]
See this forum thread with repro steps: https://forum.newsblur.com/t/my-text-gets-lost-if-i-leave-and-return-to-the-app-before-sharing/8890. From the user:

What happens:

* I click “share” and write some text
* I leave NewsBlur and switch to another app (e.g., go to Safari to look something up)
* I return to NewsBlur, but it’s no longer on the “Share this story” screen with the large text box containing all the text I had been typing. It’s instead showing the article view, but with the keyboard from the share screen still displayed on the bottom half of the screen.
* because the keyboard is still displayed, I can’t actually scroll back down to click the “share” button again until I get rid of the keyboard
* when I leave the article and come back to it, the keyboard disappears and the button becomes accessible, but when I click “share” again, the text box is now empty and everything I wrote has been lost.

**Comment by Dejal** [comment]
I can't reproduce this on iPhone, but could on iPad. The fix might help iPhone too.
