### ISSUE TITLE
iOS: Feed/story title doesn't show active highlight until tap-off

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1589]
The active highlight should show on the beginning of the tap gesture, not the end.

**Comment by Dejal** [comment]
No, it should be at the end, as starting a tap could be a long press, which shows the mark read menu. Don't necessarily want to select the feed before showing the menu.

**Comment by samuelclay** [comment]
How about having the active highlight show on tapBegin but have the select feed called on tapEnd? Guiding this is that the UI should feel responsive. It doesn't if a highlight doesn't show on tap.
