### ISSUE TITLE
Android: Add compact/comfortable control to feed list

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1590]
Similar to the new compact/comfortable setting on the web and on iOS from #1540.

**Comment by sictiru** [comment]
@samuelclay Please provide feedback on spacing between the two settings.
The options can be found under `Preferences` to minimize the entries in the feed list context menu but let me know if you disagree.

**Comment by samuelclay** [comment]
I'm having trouble finding it in Preferences (latest on sictiru branch). Also, after thinking about it, I'd like it on the feed list and story list menu as "Spacing > Compact/Comfortable" using the drill down context menus we're using for things like Theme. It needs immediate feedback so users can tell the difference, so it needs to hover over the feed/story titles.

On iOS and web it's an inline control but on Android, until we build inline controls, we can use the drill down menus.

![4995DC94-CE98-4627-AA8A-27296E03598A](https://user-images.githubusercontent.com/44229/165116664-850fa59f-a208-4e2d-974a-44e9a65a2896.png)
<img width="793" alt="Screen Shot 2022-04-25 at 11 01 45 AM" src="https://user-images.githubusercontent.com/44229/165116677-95783394-246d-4600-ae60-fd9fc49174b7.png">

**Comment by sictiru** [comment]
Should be under Preferences under the Feed section. I'll add it to the story list view and also in the context menus.

**Comment by sictiru** [comment]
@samuelclay Let me know if the spacing needs tweaking before releasing.

**Comment by samuelclay** [comment]
I can't find this feature, and I'm looking in the feed title list menu and story title list menu.

**Comment by sictiru** [comment]
It's under `Spacing` for both feed title list and `story title list`. The spacing between the two lists can be configured individually just like on iOS.

**Comment by sictiru** [comment]
Latest changes on the matter were addressed [in the redesign](https://github.com/samuelclay/NewsBlur/issues/1694)
