### ISSUE TITLE
iOS: Custom domains crash the app

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1591]
In trying to reproduce #1515, I set my custom domain to staging.newsblur.com and it looks like the old default server continued to be used. I then force quit the app and on launch it crashes.

**Comment by samuelclay** [comment]
Of course when I attach a debugger I can't reproduce it.

**Comment by samuelclay** [comment]
Oh, it's possible it's because I used http and not https!

**Comment by Dejal** [comment]
The URL is cached, so a force quit is required. I could add logic to check if the URL was changed, and clear the cached value, but that seems an uncommon situation, and changing server mid-session seems like it might have unexpected side effects.

If you enter just `staging.newsblur.com` it defaults to `http://staging.newsblur.com`; if you enter `https://staging.newsblur.com` it'll use that. I could change that to default to `https://` if you like; most servers nowadays support that.

I didn't experience a crash with either URL, but the `http://` one did seem to have difficulty loading.

If you don't want any changes, we can close this.

**Comment by xanthos84** [comment]
sorry to say but the new (and old) app 11.1 on ipados 15.2 still crashing with custom server….
