### ISSUE TITLE
celery container unable to write to logs (Permission issue)

### ISSUE THREAD

**Issue by Linecutterx** [samuelclay/NewsBlur#1593]
The docker-compose.yml feeds the celery container with the ID of the current user, but the newsblur.log is owned by root/root. Logging therefore fails (which seems to freeze processing as far as I can tell).

Changing the log's ownership to the current user fixes the error.

**Comment by samuelclay** [comment]
The newsblur log shouldn't be owned by root. The Makefile shows that `make nb` runs with `CURRENT_UID`:

https://github.com/samuelclay/NewsBlur/blob/master/Makefile#L24

Does `docker inspect newsblur_web` show a different user? Are you running with sudo?

**Comment by samuelclay** [comment]
Oh, I see now that we didn't have the `user: "${CURRENT_UID}:${CURRENT_GID}"` line on anything but celery. I changed that but you may see unintended consequences of changing the user on everything. Might have to perform a `chown -R $(id -u):$(id -g) /srv/newsblur/*`
