### ISSUE TITLE
iOS: Auto-select first story

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1599]
On iPad, we are now showing the first story but not marking the story as read. I think the behavior we have now is not the right behavior, as it shows a story, you read it, then you swipe to the next story, and the first story isn't read. I don't think there's a good way to let the user mark the story as read by default but then have a way to unread it. And that made me realize that the unread should be manual, and that's basically a "auto-select first story" feature.

So this ticket is about making that auto-select first story the default, and then turning off this story loader without marking as read feature.

**Comment by Dejal** [comment]
I'm not entirely sure what you want here, but it sounds related to #1500, so please re-read the comments on that and add a comment there on what you want, and change its priority if desired. I'll close this as a duplicate.
