### ISSUE TITLE
Android: Preference for marking story as read only after time or manually

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1600]
Same as #1596.

* New preference (matches the web): 

<img width="668" alt="Screen Shot 2022-01-25 at 11 48 06 AM" src="https://user-images.githubusercontent.com/44229/151021367-de548a49-3352-44af-8c81-3317e1e1a556.png">

* Manual means a new "Mark story read" button, basically the same button as the Share/Save/Train buttons, but full width, above those three. 
* Hitting that button changes the text to "Read" and a slightly dimmer text color.
* Tapping it again marks unread, and restores text to "Mark story read"

And we should also do the timer, so if you remain on a story for more than X seconds, it auto-marks as read. Nifty!

**Comment by sictiru** [comment]
@samuelclay In case you cut a new release this week, this feature is only available with `Immediately` and `Manual` options on the `sictiru` branch. 
To implement the timer I need to know the lifecycle of the view visible to the user and with the existing adapter that looks infeasible without other problems. I'm starting to rewrite/update this core piece and it will probably need a beta test.

**Comment by samuelclay** [comment]
Can you change the mark read button to be the same width as the three buttons below?
![Screenshot (Mar 8, 2022 11_39_57 AM)](https://user-images.githubusercontent.com/44229/157283947-f34b4696-b663-42a2-9c5f-a83765c07919.png)

**Comment by samuelclay** [comment]
As soon as you do that, I'll cut a release and add it to the blog

**Comment by sictiru** [comment]
@samuelclay You can give it another try.

**Comment by samuelclay** [comment]
<img width="930" alt="Screen Shot 2022-03-22 at 10 21 07 AM" src="https://user-images.githubusercontent.com/44229/159503569-4e278fc2-a395-49bc-8544-ad08c7ace9f6.png">
<img width="894" alt="Screen Shot 2022-03-22 at 10 21 11 AM" src="https://user-images.githubusercontent.com/44229/159503572-d5f7a57f-ae03-40aa-b554-1cc9404fcd92.png">

**Comment by samuelclay** [comment]
Looks good but the unread indicator gif is a bit larger than it should be. Check the web for the right height-to-text and margin ratio.

**Comment by samuelclay** [comment]
Also, would it be possible to show the read story title and only show the unread indicator if a user marks the story as unread (or has the new timer or manual mode). We do this on iOS and on the web and it's easier on the eyes not to see every single story transition from unread to read. You should only see the transition in special cases.

**Comment by sictiru** [comment]
It looks like I need to get creative to make that behavior happen.
