### ISSUE TITLE
Android: "Title only" should show full story title

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1606]
See this thread: 

https://forum.newsblur.com/t/android-show-full-story-title-instead-of-cutting-it-off/9169

Basically there should be a way for titles to not be cut off, and I think if a user is willing to turn off story previews, they should get the full title. At least ~6 lines max (unlike the 2 max we have now).

**Comment by VlaK0r** [comment]
> I think if a user is willing to turn off story previews
But I don't want to turn off.

**Comment by samuelclay** [comment]
Only so tall a story can get. I suspect we might want to experiment with a max of 3 lines for story titles by default then.

**Comment by VlaK0r** [comment]
Sorry I misunderstood you

**Comment by VlaK0r** [comment]
Please make a maximum of 6 in any variation. And about the preview, everyone will choose what is best for him, 6 or "Title only"

**Comment by VlaK0r** [comment]
Usually you read the title, and you will be guided by it whether you will read the full content or not.

**Comment by VlaK0r** [comment]
> I suspect we might want to experiment with a max of 3 lines for story titles by default then.

3 is not enough, 6 is just right

**Comment by VlaK0r** [comment]
And even better to do as in the web version. Automatically increase the number of lines depending on the length of the title.

**Comment by sictiru** [comment]
@samuelclay What is the final request here? 
- Wrap the title text to max 6 lines when the content preview is disable?
- Create a separate settings for title max lines?
- Increase default max story title lines to 3.

Currently the app will show 3 lines of text for the story title if the text size is > M.

I'd set the default max story to 3 lines and to 6 lines when the content preview if disable.

**Comment by VlaK0r** [comment]
> 

Automatically increase the number of lines depending on the length of the title?

**Comment by samuelclay** [comment]
> I'd set the default max story to 3 lines and to 6 lines when the content preview if disable.

Agreed
