### ISSUE TITLE
Android v11.2: Randomly collapses all folders close when opening the app

### ISSUE THREAD

**Issue by mystic-githuber** [samuelclay/NewsBlur#1610]
Since update 11.2 Newsblur on android (f-droid) seems to collapse all folders close when opening the app. This behaviour is random.

**Comment by VlaK0r** [comment]
Yes, I noticed the same

**Comment by sictiru** [comment]
Does this behavior happen only on installs from F-Droid?
When you say the behavior is random, is that between app cold starts or warm starts?

**Comment by VlaK0r** [comment]
> Does this behavior happen only on installs from F-Droid?
> When you say the behavior is random, is that between app cold starts or warm starts?

I don't understand what you mean.
This happens randomly.
App installed from google store

**Comment by mystic-githuber** [comment]
It happens when the app is already logged into my account. Not sure what you mean by cold and warm starts?

I usually download form F-droid and the above user got it from the play store so it seems to be an Android issue.

**Comment by VlaK0r** [comment]
It all started after the transition to android 12

**Comment by mystic-githuber** [comment]
I am on android 11 and this problem is there.

**Comment by manderson23** [comment]
I see this too. By cold vs warm starts you mean app opened vs switching to app from another?

**Comment by daradib** [comment]
I've experienced this starting with 11.2 (F-Droid), but also on 11.2.2 (Play). It happens seemingly randomly both during cold starts (e.g., force stopped and launched) and warm starts (e.g., backed out and relaunched).

Have the changes through 11.2.2 (201) been pushed to this repo? `clients/android/NewsBlur/build.gradle` is still at 11.2 (199).

**Comment by sictiru** [comment]
11.2.2 has been pushed to the repo but it might not be on the master branch.
I haven't experienced this bug yet during my daily usage and there shouldn't be changes in this part of the app but I will have to look deeper into it.

**Comment by manderson23** [comment]
Often for me it is collapsed when the app opens but when the sync completes this triggers the folders to open.

**Comment by samuelclay** [comment]
I'm seeing 5 conflicts when merging master and sictiru. @sictiru would you mind merging master in?

**Comment by sictiru** [comment]
Master has been merged.

**Comment by samuelclay** [comment]
I'm not sure why but I'm still having trouble merging master into sictiru branch. There's even more conflicts now. I pulled both, not sure why I'm seeing this.

**Comment by sictiru** [comment]
@samuelclay Master was re-merged and sictiru was pushed to main repo. Let me know if that works.

**Comment by sictiru** [comment]
Can this issue still be observed on the latest 11.3.0 version?

**Comment by sictiru** [comment]
In case there are instances of randomly collapsing folders after v 11.3.0 feel free to reopen.

**Comment by manderson23** [comment]
I still see this regularly on 11.3.0

**Comment by sictiru** [comment]
Fixed in NewsBlur v12.0. Please reopen if necessary.
