### ISSUE TITLE
what to do when >>> Site.objects.all()[0] shows <Site: localhost>

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1611]
heya i'm fixing my errors relating to using a custom domain, and in the README under "Using a custom domain", you mention:

`You can also confirm that there is a domain name mismatch in the database by running make shell & typing Site.objects.all()[0] to show the domain that NewsBlur is expecting.`

myne does indeed incorrectly show <Site: localhost>

how do i fix this?

- newsblur_web/docker_local_settings.ph has the subdomain set for NEWSBLUR_URL and SESSION_COOKIE_DOMAIN
- config/fixtures/bootstrap.json has the subdomain set as the domain

i suspect this is related to why my default profile pic is a broken image that is trying to load from localhost..

**Comment by samuelclay** [comment]
Well, if you changed `bootstrap.json`, that will only work if your blow away your DB. Now that the DB is populated and you make not want to delete it, here's how to edit it:

```
>>> site = Site.objects.all()[0]
>>> site.domain
'localhost'
>>> site.domain = 'nb.local.com'
>>> site.save()
```
