### ISSUE TITLE
disable sign ups & user management

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1613]
is there a way to disable sign ups?

also, is there a way to manage (view/delete) users?

**Comment by samuelclay** [comment]
You can manage users using the admin interface, at https://localhost/admin/.

As for disabling sign ups, the only built in way to do that is it kick users over to the payment form and not run the new user queue, which will keep new users in purgatory.

After looking through the code, it seems we ripped it out. So I suggest jusst throwing an `assert False` into the `apps/reader/forms.py` code so new user registration doesn't work and instead throws an exception.

**Comment by luxiouronimo** [comment]
hmm, regarding the /admin/ (Django administration) login; i am authenticated (as my only user thus far), but i am not authorized to access this page.. i am apparently not a staff account?

**Comment by samuelclay** [comment]
Ah-ha, you'll want to change the `is_staff` flag on your account:

```
>>> u = User.objects.get(username='samuel')
>>> u.is_staff = True
>>> u.save()
```

**Comment by luxiouronimo** [comment]
progress; after setting is_staff = True, i can login to the /admin/ (Site administration) area, but i "don't have permission to view or edit anything."

Recent actions is empty, and My Actions has "None available"

**Comment by samuelclay** [comment]
Apparently Django changed it to `is_superuser`, as per https://stackoverflow.com/questions/33556515/django-admin-you-dont-have-permission-to-edit-anything.

**Comment by luxiouronimo** [comment]
alrighty, that gives me a bunch of functionality..

however, the page is lacking any style or images, and it appears that none of the /media/admin assets (css/js/svg) are loading; they're all 404's..

**Comment by samuelclay** [comment]
Try `make collectstatic`, that should collect the admin assets.

**Comment by mbhkoay** [comment]
Where do we do the is_staff or is_superuser? 

> Ah-ha, you'll want to change the `is_staff` flag on your account:
> 
> ```
> >>> u = User.objects.get(username='samuel')
> >>> u.is_staff = True
> >>> u.save()
> ```

**Comment by VlaK0r** [comment]
> Where do we do the is_staff or is_superuser?
> 
> > Ah-ha, you'll want to change the `is_staff` flag on your account:
> > ```
> > >>> u = User.objects.get(username='samuel')
> > >>> u.is_staff = True
> > >>> u.save()
> > ```

I support the question.
Can I explain in more detail how to do this, please.

**Comment by VlaK0r** [comment]
> progress; after setting is_staff = True, i can login to the /admin/ (Site administration) area, but i "don't have permission to view or edit anything."

Hello!
Please tell me how did you do it?

**Comment by luxiouronimo** [comment]
the stuff shown here with `>>>` at the beginning of the line is done in the python/django(?) shell. in the NewsBlur dir, type `make shell` and you can then enter the commands above (without the `>>>`)
