### ISSUE TITLE
self hosted docker not running flawless

### ISSUE THREAD

**Issue by trooper91** [samuelclay/NewsBlur#1617]
Hey there,
i am trying to set up a self hosted of NewsBlur service as described in the README.md

For my setup i have Debian 11 with the newest versions of docker and docker-compose. Running `make nb` works with sudo without any errors and the containers seem to be running ok. I wrote seem because after i go to the website i am not able to scroll neither i can click anything. Also it looks very strange.
![image](https://user-images.githubusercontent.com/16492918/152069749-2f5a34be-d128-4e36-9b6d-38b05b1e2a78.png)

Running the tests gives only an error about duplicates which should not cause such a problem in my opinion.
Did i miss something? I would be very grateful for any help.

**Comment by samuelclay** [comment]
Try running `make collectstatic` and let me know if that fixes it.

**Comment by trooper91** [comment]
After running `make collectstatic` and rerunning `make nb` (both with sudo) it works. Thank you :)
But there are some errors after the first command:

```
[user@user-virtualbox NewsBlur]$ sudo make collectstatic
[sudo] password for user: 
rm -fr static
docker run --rm -v /home/user/newsblur/NewsBlur:/srv/newsblur newsblur/newsblur_deploy
Unable to find image 'newsblur/newsblur_deploy:latest' locally
latest: Pulling from newsblur/newsblur_deploy
a2abf6c4d29d: Already exists 
27003db43ed4: Pull complete 
eba080ca5a70: Pull complete 
00ceeca3d803: Pull complete 
8980b900ecd2: Pull complete 
b8e067772b91: Pull complete 
c4d7baa4a72e: Pull complete 
e1d902ce900c: Pull complete 
dfe47dec8bb0: Pull complete 
3ca8c3bfea5e: Pull complete 
f815d3caedef: Pull complete 
121ebbf81b1f: Pull complete 
f1b223b190d1: Pull complete 
84bbc47ff882: Pull complete 
ccb4acd91eb3: Pull complete 
930942556022: Pull complete 
4d8d40d43e7d: Pull complete 
cc5a2798468a: Pull complete 
1d92b46c922d: Pull complete 
Digest: sha256:566e7998f585e0f558c87096d02769ecdc4e37334397edc92e57cbb3264a26ab
Status: Downloaded newer image for newsblur/newsblur_deploy:latest
Traceback (most recent call last):
  File "/srv/newsblur/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 132, in collect
    for original_path, processed_path, processed in processor:
  File "/usr/local/lib/python3.9/site-packages/pipeline/storage.py", line 37, in post_process
    packager.pack_javascripts(package)
  File "/usr/local/lib/python3.9/site-packages/pipeline/packager.py", line 122, in pack_javascripts
    return self.pack(package, self.compressor.compress_js, js_compressed, templates=package.templates, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipeline/packager.py", line 116, in pack
    content = compress(paths, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipeline/compressors/__init__.py", line 66, in compress_js
    js = getattr(compressor(verbose=self.verbose), 'compress_js')(js)
  File "/usr/local/lib/python3.9/site-packages/pipeline/compressors/closure.py", line 8, in compress_js
    return self.execute_command(command, js)
  File "/usr/local/lib/python3.9/site-packages/pipeline/compressors/__init__.py", line 250, in execute_command
    raise CompressorError(stderr)
pipeline.exceptions.CompressorError: b'Error: Unable to access jarfile node_modules/google-closure-compiler-java/compiler.jar\n'
make: [Makefile:24: collectstatic] Error 1 (ignored)
```

**Comment by samuelclay** [comment]
I wouldn't sweat it, you shouldn't have to run collectstatic anyway. Check that you have DEBUG_ASSETS turned to True, which will also let you debug the JS/CSS. It's a bit slower, but it's what works best for standalones.

**Comment by grgghrn** [comment]
I just ran into this exact same issue as well in ubuntu 20.04 under wsl2 in Windows 11.  The underlying error seemed to be that underscore hadn't been included anywhere and it was trying to call “_.memoize” from reader_utils.js.
  
This definitely did the trick, thank you!

Is this something that would need to be run to incorporate update too - or should just the 'make nb' work after git pulling to get latest changes?

**Comment by samuelclay** [comment]
The `make collectstatic` command needs to be run every time new JS/CSS comes down. But really you should never have to run it and instead just ensure `DEBUG_ASSETS` is set to True. That way all of the JS/CSS is served as individual files directly from the source. It takes an extra 1-2s to load the website, but it's guaranteed to be latest.

Also, I just fixed the issue above as we now use `/usr/local/bin/compiler.jar`. Let me know how that works.

**Comment by trooper91** [comment]
Sorry to reopen it. DEBUG_ASSETS is set to True (or maybe i miss the part where it is False). Even if there is a registered user shown i'm not able to login as the user i've created.

**Comment by samuelclay** [comment]
Tell me more about what you're seeing, even posting a screenshot. And don't forget to look in the web inspector to see what's going on. And type `make alllogs` to see what docker is seeing.
