### ISSUE TITLE
Android: Story view disappears on split screen

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1618]
Self-explanatory

https://user-images.githubusercontent.com/48226312/151745405-734b36aa-6d26-45b1-9c61-6296b168bffb.mp4

App version: `v11.2.2 (201)`

**Comment by sictiru** [comment]
This one was interesting to debug. When the multi window mode is activated, the app is told that it's not visible on the screen.

**Comment by samuelclay** [comment]
Neat, I'll launch this as 11.2.3 as soon as master is merged in

**Comment by sictiru** [comment]
@samuelclay master has been merged in.
`sictiru` branch contains a fix for https://github.com/samuelclay/NewsBlur/issues/1628 too
