### ISSUE TITLE
iOS: River from widget only loads a few stories and then shows the story titles end bar

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1621]
I believe this is due to how the river calls the backend. There is a story list cache that NewsBlur keeps on the backend for about an hour for each river call. But you have to call every parameter the same except for `page` in order for the cache to match. When it doesn't match, then we get a story titles end bar. 

Honestly, I think it's just the feed list we pass to the river that needs to be the same. NewsBlur uses a hash of the list of feed ids to identify the story list cache key. 

Two options:

1) Transfer the stories from the widget for instant load, and then page through the river as though starting from the first story, and tossing new stories that come in that match the already displayed stories. And that means stories may appear slightly out of date order. That's ok.
2) I believe right now we're transferring the stories and then continuing to page? Fewer network calls, but can easily break the feed cache in the river.

**Comment by Dejal** [comment]
The widget and main app load the stories independently. The widget uses the new `/reader/river_stories_widget` endpoint, passing only the feed IDs specified in the widget preferences, and only stores the few properties it needs (title, date, etc). In most cases, the feeds loaded by the widget will be a subset of all the feeds, so server-side caching based on the set of feed IDs won't help.

When the main app is opened, it fetches the stories like any normal launch, and finds the story from the widget, using the story hash.

So it would be a massive job to transfer the story data from the widget to the main app and insert them in the river.

**Comment by Dejal** [comment]
Given the above, we can probably close this now. Or change the priority to attempt a more drastic optimization in the future.

**Comment by samuelclay** [comment]
Agreed, we'll see if this is an issue and I'll re-open.
