### ISSUE TITLE
Android: Add 'share' as action on notifications

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1626]
Actions for Button1/2/3
- Mark Read
- Save
- Share
- none/disable
---

![Screenshot_2022-02-12-00-47-05](https://user-images.githubusercontent.com/48226312/153655450-830d4d8a-93e0-45da-af5a-bb54f34d66d0.jpeg)
![Screenshot_2022-02-12_00-10-31_1](https://user-images.githubusercontent.com/48226312/153655489-fdaeacfd-a172-4a0c-8d6d-42f8a34f8d5a.png)

screenshots source: [QKSMS](https://github.com/moezbhatti/qksms)

---

Currently we've only SAVE & MARK READ options which are fixed buttons.
This Feature will give users bit more freedom/control through notifications.

**Comment by samuelclay** [comment]
I'm not entirely sure what you're asking for here. Can you offer a bit of clarity? I'd be happy to think about adding controls somewhere.

**Comment by shuvashish76** [comment]
![image](https://user-images.githubusercontent.com/48226312/155675331-3d5612ab-dbfc-4a71-b17a-448fad422c30.png)

> Currently we've only SAVE & MARK READ options which are fixed buttons.

check screenshot. (no1 & no2)

---
FR for controlling what these buttons should do.
Add this feature to Settings > Notifications > Actions

Options for action buttons:

`Button 1`
 - Mark Read
 - Save
 - Share
 - none/disable

`Button 2`
 - Mark Read
 - Save
 - Share
 - none/disable

`Button 3`
 - Mark Read
 - Save
 - Share
 - none/disable

**Comment by samuelclay** [comment]
We can add Share, but I see no reason to add configuration for order.

**Comment by samuelclay** [comment]
Launching as v12.1.0.
