### ISSUE TITLE
Android: Import/Export option

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1627]
Add import/export `.opml` files option for android app.

It's possible to import/export `.opml` file by logging in browser but I don't think most ppl would like to login browser just for this feature. Plus this is a very common feature in almost all android RSS reader apps.

ThankYou🙏🏿

**Comment by samuelclay** [comment]
Agreed, this would be a welcome feature. Easy to implement too, just kick the user over to the `/import/opml_export` endpoint.

**Comment by samuelclay** [comment]
Here's the relevant JS code for uploading:

https://github.com/samuelclay/NewsBlur/blob/master/media/js/newsblur/reader/reader_intro.js#L540-L603

And the upload url is `/import/opml_export`.

**Comment by shuvashish76** [comment]
Also if you think from from new users prospective this is very important feature before shifting to Newsblur. Just import `.opml` file from your existing RSS reader app/service & try Newsblur.

Do consider this feature for next update.

**Comment by samuelclay** [comment]
Agreed, this is a great next feature to build for Android. The backend is ready, just send over the opml and either wait for it to process or you'll get a message back about it being in a queue and the user will be emailed. 

The code from `reader_intro.js` shows what to look for in the response:

```
                    if (data.payload.delayed) {
                        NEWSBLUR.reader.flags.delayed_import = true;
                        self.count_feeds({fake_count: data.payload.feed_count});
                        $('.NB-intro-import-delayed', self.$modal).show();
                        $('.NB-intro-import-restart', self.$modal).hide();
                        $('.NB-intro-import-message', self.$modal).hide();
                    } else if (data.code < 0) {
                        $('.NB-intro-import-delayed', self.$modal).hide();
                        $('.NB-intro-import-restart', self.$modal).show();
                        $('.NB-intro-import-message', self.$modal).addClass('NB-error').show().text(data.message);
                    } else {
                        $('.NB-intro-import-message', self.$modal).text("All done!").removeClass('NB-error').show();
                        $('.NB-intro-import-delayed', self.$modal).hide();
                        $('.NB-intro-import-restart', self.$modal).show();
                    }
```

**Comment by sictiru** [comment]
@samuelclay Can you share an example JSON payload that contains an opml file which the server will accept?
Currently I'm getting the XML file from `import/opml_export`, converting it to JSON and sending it up but I'm missing something.

**Comment by samuelclay** [comment]
Why convert to JSON? Looks like opml_upload looks for the `file` parameter (under `apps/feed_import/views.py`). I don't believe clients are sending JSON over, just the XML file.

**Comment by sictiru** [comment]
Misread that as the request type but it's actually the response type.
Feature is ready for review under the main context menu as `Import/Export...`
