### ISSUE TITLE
Android: Allow Intelligence trainer & Insta-fetch stories to muted sites

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1635]
Self-explanatory.

Newsblur web version supports both Intelligence trainer & Insta-fetch stories for muted sites but you don't get such options on Android when you long click on any muted site/feed.

Intelligence trainer & Insta-fetch stories for muted sites is a very useful & free feature if you do not want a site/feed as your regular feed but you only check their headlines/important new articles occasionally.

**Comment by samuelclay** [comment]
Sure, hey @sictiru, why do muted sites not have a context menu?

**Comment by shuvashish76** [comment]
> why do muted sites not have a context menu?

Agree, I just mentioned Intelligence trainer & Insta-fetch stories for my own necessity but it would be nice to have other options for muted sites. For example choose folders, delete feed, rename feed, list style etc... all these options are disabled for muted sites. To delete/rename a muted site you've to un-mute the site 1st.🤷🏿‍♂️
We should support all those options for muted sites as well cause we already support them in web version.

1. When long click any site

![Screenshot_2022-03-05-06-12-36](https://user-images.githubusercontent.com/48226312/156860105-49b5c5f3-aad7-4889-8e6e-a41cdc242a2c.jpeg)

For muted sites - _Un-mute feed_

2. When you open the site & click on 3dot menu from top-right-cornor

![Screenshot_2022-03-05-06-13-01](https://user-images.githubusercontent.com/48226312/156860091-edb6b6f3-b780-4123-bea5-b44571a793d0.jpeg)

Currently both these menu/options disabled for muted sites...

**Comment by sictiru** [comment]
Context menus for muted feeds were intentionally disabled in 2017.

**Comment by samuelclay** [comment]
Without going back into the github ticket archive, I'm going to assume we're maybe going to see a crash based on one of those menu items. So keep that in mind in case a crash happens on a feed a user may not immediately know has been muted because they're in the All Sites view.

**Comment by sictiru** [comment]
@shuvashish76 The ticket was closed because Intelligence trainer & Insta-fetch stories for muted sites were enabled for mutes feeds and it's available on the latest version. Please reopen if you find it otherwise or you're having issues with it.
