### ISSUE TITLE
API: Marking Article Unstarred Twice Results in 500 Error.

### ISSUE THREAD

**Issue by jbrayton** [samuelclay/NewsBlur#1636]
If I mark an article unstarred twice, I via the API, I get a 500 error.

For example:

```
curl -i -H "Authorization: Bearer [redacted]" -d "story%5Fhash=5982259:c49fe4" https://www.newsblur.com/reader/mark_story_hash_as_starred

(returns a 200)


curl -i -H "Authorization: Bearer [redacted]" -d "story%5Fhash=5982259:c49fe4" https://www.newsblur.com/reader/mark_story_hash_as_unstarred

(returns a 200)


curl -i -H "Authorization: Bearer [redacted]" -d "story%5Fhash=5982259:c49fe4" https://www.newsblur.com/reader/mark_story_hash_as_unstarred

HTTP/1.1 500 Internal Server Error
server: gunicorn/20.0.4
date: Sun, 27 Feb 2022 17:11:14 GMT
content-type: text/html; charset=utf-8
vary: Authorization, Cookie, Accept-Encoding
x-gunicorn-server: app-django6
x-mr-burns: I'll keep it short and sweet - Family. Religion. Friendship. These are the three demons you must slay if you wish to succeed in business.
content-length: 2363
strict-transport-security: max-age=0; includeSubDomains

(html)
```

This may seem harmless, but if an article gets unstarred from elsewhere before the client becomes aware of it, it creates a condition where the client thinks it needs to retry because of server issues.

I believe this just started happening within the past week or two. Starring an article that is already starred appears to work as expected.

**Comment by samuelclay** [comment]
Sorry, I just broke this when adding the ability to send batch `story_hash` ids for starring, unstarred, and unreading (similar to how reading by story hash already has the ability to batch many stories in a POST list). Fixed now!
