### ISSUE TITLE
Android: Add notifications dialog

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1638]
![image](https://user-images.githubusercontent.com/48226312/156394481-acebd067-6e7c-4f49-b531-791f05dada52.png)

Just like the web version add option to control notification for Android app.

---

We do support such option for individual sites
![image](https://user-images.githubusercontent.com/48226312/156397546-6dd0a51b-49f9-4f39-88aa-e7ff14ef7972.png)

But currently we don't view them as whole which makes tough to find enabled - Focus/Unread (notifications) sites manually.

FR: Show all notification enabled sites for android as a whole & control individual notification enabled sites for either "Focus mode" or "Unread mode" from there.

**Comment by samuelclay** [comment]
I was just thinking the same thing when I worked on your other notification ticket. We should absolutely have a centralized dialog for notifications on Android, just as we do on iOS and Web.

**Comment by samuelclay** [comment]
This looks ready to launch as part of v12.1.0. What do you say?

**Comment by sictiru** [comment]
@samuelclay Ready for v12.1.0

**Comment by samuelclay** [comment]
Launched as v12.1.0 today.
