### ISSUE TITLE
iOS: folder highlight does not deactivate upon return

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1641]
It should fade out like feeds. Right now it doesn't fade out or even deactivate. https://user-images.githubusercontent.com/44229/157031173-3bcb9260-4a5d-45f9-bc0f-4f1aa47aa21a.MOV

**Comment by Dejal** [comment]
I can't get that video to load. The folders are always deactivating for me on iPhone. I've added fading.
