### ISSUE TITLE
Android: Keyboard shortcuts for external keyboards

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1644]
We added this on iOS (thanks to @nriley) and a user just requested it for Android. Let's try to capture as many keyboard shortcuts from the web we can. And here's screenshots of the mappings on ipad:

**Comment by samuelclay** [comment]
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-03-11 at 17 21 02](https://user-images.githubusercontent.com/44229/157980447-fb864c32-4df4-4a77-845c-c607643a7a7a.png)
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-03-11 at 17 20 55](https://user-images.githubusercontent.com/44229/157980455-dd930f59-210e-45f2-abec-0fee757be607.png)

**Comment by sictiru** [comment]
@samuelclay How can the keyboard shortcut options be viewed in iOS like in the photos above? 
While checking the shortcuts in iOS I noticed that some of them are not working. These are Page Down, Page Up, Dashboard, Share This Story, Scroll to Comments(should it scroll to the bottom if there are no comments or just no op?).

**Comment by sictiru** [comment]
The keyboard shortcuts menu option appeared on the web so I'll add it there on Android when an external keyboard is connected. The Alt key is used as the command for now.

**Comment by samuelclay** [comment]
You can see the keyboard shortcuts on an iPad by holding the Command button. But hitting '?' should also work, although I think that only works on the web.

**Comment by samuelclay** [comment]
I don't know which keyboard meta key should be used, but use your judgement. I'm fine with whatever, so long as it's discoverable.

**Comment by sictiru** [comment]
Added the option key as a way to discover the keyboard shortcuts, alongside the menu button that is available once an external keyboard is connected.
