### ISSUE TITLE
Delete Saved & Read stories with "Erase Yourself"

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1645]
NewsBlur should remove all Saved & Read stories when you "Erase Yourself".

Currently it just remove all sites which is expected as you click on "DELETE ALL OF MY SITES" but when someone tries to erase himself I assume he wants to remove all his traces including Read & Saved stories. (of course without deleting his account)

This should show on your NewsBlur > ACTIVITIES as a message that you Erased yourself.

![image](https://user-images.githubusercontent.com/48226312/158006138-b2f7495e-ef9a-4fd3-a083-31a65b5a1121.png)

**Comment by samuelclay** [comment]
I understand where this is coming from but I don't agree with either scenario. For saved stories, the user should have more granular options than just all or nothing. There's a more granular saved story deleter immediately next to this, so it's moot anyway. We don't need deleting your data to only be a one stop process, apart from account deletion.

For Read stories, those are actions and not subscriptions/stories, so they are stored just as activities and interactions are stored. If you really want to delete them, you've gotta delete the account. I can facilitate keeping premium status in between or I can perform one-off requests.

As for an activity message, I do like that, but is this really something that happens so often as it warrant a note? Besides, if OPMl is immediately uploaded, then that alone will show.

**Comment by shuvashish76** [comment]
Agreed 👍🏿
Usually devs close issues they don't like (or if doesn't match project vision) without comments _(or short comments like "No", "No thanks" etc.)_ So, thankyou for the detailed explanation.
