### ISSUE TITLE
Newsblur with Traefik reverse proxy

### ISSUE THREAD

**Issue by grigio** [samuelclay/NewsBlur#1650]
Is possible to run with it via docker compose ?

**Comment by samuelclay** [comment]
Sure, I don't see why not. I assume traefik is running on port 80/443? You'll have to move haproxy in docker-compose.yml to another set of ports, and the rest should be fine. nginx is using port 81, if that matters. They're all in there, ready for the changing.

Let me know how that goes! Everything should work fine, but who knows what exotic configuration we're about to explore.
