### ISSUE TITLE
Backend: Missing JS files referenced by file glob (ex: `backbone-*.js`)

### ISSUE THREAD

**Issue by grigio** [samuelclay/NewsBlur#1653]
The website do not run fine i get several errors in Chome console

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

![Screenshot from 2022-03-15 10-05-37](https://user-images.githubusercontent.com/8074/158343630-3f38c603-8915-4a4e-8275-ac0273b26ba7.png)

**Comment by samuelclay** [comment]
That 403 is for the fonts file, which isn't all that concerning. More importantly is why are you seeing odd javascript errors? Those make it look like certain JS files aren't being loaded. Can you show me the Network tab with a full list of every JS file that was attempted.

<img width="1439" alt="Screen Shot 2022-03-15 at 1 43 13 PM" src="https://user-images.githubusercontent.com/44229/158439084-a09a784d-6ce5-4260-b158-8ed5aaee5d99.png">

**Comment by jschulman** [comment]
I'm having the same issue here.  Fresh Ubuntu 20 install, Docker 20.10.13.

Network shows all files are loading fine.  Here is the console debug which shows the javascript errors:

![Screen Shot 2022-03-21 at 8 04 09 AM](https://user-images.githubusercontent.com/1237472/159267136-2107cc09-b195-4aef-8bdc-8dd9d122f401.png)

**Comment by samuelclay** [comment]
Thank you for posting that @jschulman! It has the smoking gun.

It looks like the `backbone-*.js` entries in assets.yml are not being read and thereby not included.

**Comment by samuelclay** [comment]
Well here's a problem. It works on my machine, so I have no idea why file globs are being ignored. 

The code beings in [assets.yml](https://github.com/samuelclay/NewsBlur/blob/master/newsblur_web/assets.yml), where those `backbone-*.js` references live. They are read in [settings.py#L804-L819](https://github.com/samuelclay/NewsBlur/blob/master/newsblur_web/settings.py#L804-L819), and then sent to django-pipeline, which has [glob support](https://django-pipeline.readthedocs.io/en/latest/configuration.html). 

So I'm at a loss. Any ideas or log entries anywhere with the missing files?

**Comment by jschulman** [comment]
File exists:

```
root@nb:/srv/newsblur/media/js/vendor# ls -la
total 3360
drwxr-xr-x 2 root root   4096 Mar 21 02:32 .
drwxr-xr-x 5 root root   4096 Mar 21 02:32 ..
-rwxr-xr-x 1 root root  32703 Mar 21 02:32 audio.js
-rw-r--r-- 1 root root  59497 Mar 21 02:32 backbone-1.0.0.js
```

checked the nginx log files and it's not requesting the file.

files are listed in assets.yml.

any other suggestions to try?

**Comment by samuelclay** [comment]
Try this, delete the `static/` directory after running `make collectstatic` and see if the site still loads. It *should* and if it doesn't, can you tell me if you're changing `settings.DEBUG` or `settings.DEBUG_ASSETS` in local_settings.py or docker_local_settings.py?

**Comment by jschulman** [comment]
I cleaned up the docker_local_settings.py because there are duplicate DEBUGs.  I wasn't sure if it takes the first or last as it parses it.  This is where I ended up:

```
DEBUG = False
DEBUG_ASSETS = True
```

**Comment by samuelclay** [comment]
You'll want both DEBUG and DEBUG_ASSETS set to True. Try that and delete `static/` and let me know if that works.

**Comment by kkretsch** [comment]
Doing a fresh install on a new ubuntu vserver I fall into the same problem. The initial web page seemed buggy.
Running just the `make collectstatic` seems to help a lot.

**Comment by samuelclay** [comment]
@kkretsch When you type `make shell` and then `>>> settings.DEBUG`, is it True or False? Also check `settings.DEBUG_ASSETS`. They should both be set to True and if they are False, then `make collectstatic` will make a difference. But if they are True, then those static assets won't be served. And they shouldn't be.
