### ISSUE TITLE
iPad: Story is missing or offset on iPad 11"

### ISSUE THREAD

**Issue by Sembiance** [samuelclay/NewsBlur#1658]
I've encountered 4 issues running `NewsBlur 11.1` on `iOS 15.3.1` on an `iPad Pro 11-inch (2nd generation)`.

A video of the 4 issues is here: https://www.youtube.com/watch?v=mQ29LVC4Wvg

1. When entering a category and clicking on the first story, it's always blank:
![screenshot_2022-03-22_07:45:51](https://user-images.githubusercontent.com/81436/159474950-e891df98-be37-4dae-902f-724f5a8fd26a.png)

2. When clicking the next story, there is a gap at the top of the story showing the previous story:
![screenshot_2022-03-22_07:46:02](https://user-images.githubusercontent.com/81436/159475106-06cb8778-0ed8-4d26-8da8-a3f3fc62a002.png)

3. When clicking a story and opening an external browser then going back to the app, clicking the next story fails to show it and instead scrolls just kinda half way:
![screenshot_2022-03-22_07:46:27](https://user-images.githubusercontent.com/81436/159475292-6610ac9e-f22b-42ce-a27a-51a4ebb1e8e3.png)

4. Not shown in video, but when logging in for the first time, the text color of the username and password fields are invisible. Probably just black text on a black background, probably need to detect if a dark theme is being used and make sure to set the text color to something bright. I've actually typed in text to the username and password fields in this screenshot:
![IMG_0300](https://user-images.githubusercontent.com/81436/159476263-183531f8-3f95-4aa4-8c57-dae53fbdbcd3.PNG)

If you turn on `Scroll horizontally` then the first issue above goes away, but the same scrolling problem happens when leaving the app and coming back and picking the next story, but now it's on the left side:
![IMG_0302](https://user-images.githubusercontent.com/81436/159477892-9745b155-3ba7-4300-9c64-e1563f398506.PNG)

These issues happen always, every time.

I uninstalled and reinstalled the app, same issues.

Been a paying customer now for 10 years, since 2011, quite happy with Newsblur. Hopefully these issues can be resolved. Let me know if you need additional information.

**Comment by Sembiance** [comment]
![IMG_0303](https://user-images.githubusercontent.com/81436/159502322-6bb5dd9a-017d-410d-b1f7-22c8cbe04290.PNG)
![IMG_0304](https://user-images.githubusercontent.com/81436/159502350-507aa522-8aa5-4d23-8698-43f95f0f27fe.PNG)

**Comment by samuelclay** [comment]
Splitting out the fourth issue in #1675. This ticket is now just for the offset story.
