### ISSUE TITLE
River of news on folder sometimes showing all items unread?

### ISSUE THREAD

**Issue by lance0428** [samuelclay/NewsBlur#166]
In my example here I am clicking on 'Deal Sites' folder to get river of news for all sub-feeds.  As you can see there is no story counts for any of the sub-feeds.  Yet it shows stories as unread in the content panel.  I don't see this for all my folders so not sure what is special about this one.  The Android and iOS app are doing the same thing so it must be on back end.

![FolderRiverOfNewsShowingAllUnread](https://f.cloud.github.com/assets/3937210/366039/79c5026a-a26e-11e2-8302-8db842ed94eb.png)

**Comment by samuelclay** [comment]
Whoops, was probably a temporary issue. Works now!
