### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by AndrewJDR** [samuelclay/NewsBlur#1661]
I tried to self host newsblur on an ARM server, and it appears to work other than the imageproxy service, which prints an error `exec user process caused: exec format error`.

Is ARM support blocked by https://github.com/willnorris/imageproxy/issues/296 ?

Thanks!

**Comment by AndrewJDR** [comment]
Update: I was able to get this going by just building the imageproxy docker image myself.

**Comment by samuelclay** [comment]
I didn't want to build it myself because that's basically like an older practice of vendorizing code just to fix a bug, only to find the vendorized code stays stagnant and never gets updated. I figure it'll happen eventually, and imageproxy can be emulated as x86 on arm-only servers.

**Comment by willnorris** [comment]
I hadn't actually realized that NewsBlur was using imageproxy, or that this was a blocking issue for anything.  The good news is that ARM support was added for the pre-built imageproxy docker image a few months ago in https://github.com/willnorris/imageproxy/commit/a6f541de1b37f9d8bdde5d092c8fe8bbab542b10

**Comment by samuelclay** [comment]
You rock, thanks for following up on this!
