### ISSUE TITLE
iPad: Theme change doesn't update toolbar

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1663]
I noticed this on iPhone as well. Can we do a thorough theme change check around the app and address the few text shadow and title color theme updates that aren't reliably happening?

![image](https://user-images.githubusercontent.com/44229/160407820-d1566417-3c82-45af-b922-5f4ae90a416b.jpeg)

**Comment by Dejal** [comment]
I'll keep trying, but so far I haven't been able to get the theme change to exhibit that behavior. Can you reproduce it? If so, how?
