### ISSUE TITLE
iOS: New preference for notifications: Open in All Site Stories vs Open in Feed

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1668]
I often find myself wanting to read the rest of a feed while reading the river. I suppose that's a slightly different issue, but for notifications, I also find myself wanting to jump directly to the feed and not to the all site stories river.

Let's add a preference for this, defaulting to All Site Stories.

**Comment by Dejal** [comment]
I recently changed notifications to open just the feed, to speed up loading. I think that should be the default, though there could be some merit in allowing using All Site Stories instead.

**Comment by Dejal** [comment]
Actually, I just tried to implement this, and it often timed out before finding the story in All Site Stories, when an older story. I think the experience would be sub-par, even if it did find it. So I'll just leave it using the feed, which works much better, and is what you really wanted anyway.

**Comment by samuelclay** [comment]
You know, just a thought, we could include a `include_story_hash=123:abc123` when requesting stories and then you'll get 6+1 stories back, ensuring the one you want is there.

**Comment by samuelclay** [comment]
Lovely, submitted a pretty detailed list to the App Store as v11.2:

  Building on the redesigned iPad layout, this release has new preferences as well as fixes for issues we heard from your generous feedback.
  
  A nice feature we added is a new preference for which folder to automatically open when opening NewsBlur, so you can start the app right where you want to be. You can combine this with the preference to auto-open the first unread story, and you can open the app directly to what you want to read.
  
  A substantial number of issues were fixed: 
  - Returning to the app should no longer cause a story to be offset
  - The feed bar no longer intermittently disappears
  - An odd 1px white border found at the bottom the story list was removed
  - The full screen button now works when story titles are on the top/bottom on iPad
  - Toggling fullscreen now preserves your position in a story
  - Stories are no longer cut off when in iPad multi-app mode
  - Loading notifications and having them open the story in a timely manner should now be more reliable
  - A number of issues were found and fixed around state restoration when returning back to the app
  - No longer losing story position on interactive edge swipe that gets canceled early
  - The “when opening a site” preference on iPad now shows the first story by default
