### ISSUE TITLE
Android: Weird rendering artifact on Cyrillic text

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1670]
From a user, here's an example story: https://trim-c.livejournal.com/4572445.html

![Screenshot_20220327-115654_NewsBlur](https://user-images.githubusercontent.com/44229/163592805-640989d7-37b0-4253-89cf-950ec3025a08.jpg)
2

**Comment by sictiru** [comment]
Another similar report https://forum.newsblur.com/t/garbled-text-with-one-particular-feed-on-android/9714

**Comment by sictiru** [comment]
Couldn't replicate on the latest build. Tried both physical devices and emulators.
Used https://trim-c.livejournal.com/data/rss/ to access the feed.

![Screenshot_2023-02-12-09-21-33-013](https://user-images.githubusercontent.com/13900221/218326680-53e7d932-d1d6-4a90-a645-85d7155cf543.jpg)

**Comment by samuelclay** [comment]
From the user on the forum thread:
> I cannot reproduce it with the old version of the app either. I ma now travelling and on very slownconnection, it might be a race issue, will try again in March from home.q
