### ISSUE TITLE
Feature Request: Modify Schedule to fetch feeds

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1673]
Hi,

for selfhosted newsblur instances it would be nice to adjust the schedule how often the feeds are being fetched.
Thank you!

**Comment by samuelclay** [comment]
You are free to adjust the settings for when feeds are fetched as part of https://github.com/samuelclay/NewsBlur/blob/master/apps/rss_feeds/models.py#L2119-L2215. You can simply as a `2 * minutes` to extend the schedule, or vice-versa.

And if you switch to the upcoming `pro` branch, you can turn on pro subscribers and that will automatically have your feeds fetched every 5 minutes.
