### ISSUE TITLE
iOS: Feed title headers disappears on scroll up

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1676]
See video. I want to hit these fit and finish issues to address the need to be more polished. 

https://user-images.githubusercontent.com/44229/165505188-3c2d6e3d-ac89-4245-bd21-ad8ff73cd82a.MOV

**Comment by Dejal** [comment]
I can't reproduce this with the latest Dejal branch. I also tried it with the iPhone SE simulator to see if it was a notch-less issue. I'm pretty sure I fixed it recently. Can you repro with the Dejal branch? Any clues, if so?

**Comment by samuelclay** [comment]
Looking good!
