### ISSUE TITLE
Android: Standardize menus

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1678]
Story order shows up as a modal but most of the others show up as a second level menu. Let's move them to second level menus so they're consistent. 

Also, we really need to figure out how to show what those setting are set to. "Story order..." doesn't say much, but "Newest first >" does. 

"List style..." shouldn't have the ellipses, nor should Notifications. Use the ellipses to denote a modal dialog. 

Let's fix all of the context menu to normalize to what we have elsewhere and standardized to each other.

![Screenshot (May 2, 2022 9_51_54 AM)](https://user-images.githubusercontent.com/44229/166245806-72a77af8-1364-4689-bd16-00d57fd6d019.png)

**Comment by sictiru** [comment]
Available in NewsBlur v12.0
