### ISSUE TITLE
Android: Too large of a header on the feed titles view

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1679]
I'm on a Kindle Fire and the header is too tall.

![Screenshot (May 2, 2022 9_51_12 AM)](https://user-images.githubusercontent.com/44229/166245914-7e310af0-ff57-4034-937f-f0fe90f84994.png)

**Comment by sictiru** [comment]
The size of the action bar is dynamic based on the screen density and landscape/portrait mode. The action bar is going to be fixed at 48dp for all screen configs.

**Comment by sictiru** [comment]
Fixed in NewsBlur v12.0
