### ISSUE TITLE
iOS: notifications don't work

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1680]
See this video. In fact, I noticed even when not clicking on notifications and instead just opening the app led to a number of unnecessary River loads. We need to audit these loads and get this flow correct. 

https://user-images.githubusercontent.com/44229/166662392-8dc155ca-921e-4ab1-aa07-42d884cd3766.MOV

**Comment by samuelclay** [comment]
Let me ask, since I have this issue, how are you testing notifications on your devices? I assume you have some chatty feeds that you have pushing to iOS, but when you have a custom build, not from the App Store or TestFlight, you won't receive notifications because the certificate doesn't match. 

Do you have a way to generate notifications or would it be worthwhile to build one?

**Comment by Dejal** [comment]
When I need to test notifications, I install the TestFlight or release build on my iPhone, let it accumulate some chatty feeds, then do a development build running on my iPhone. And hope I solve the problem before I run out of accumulated notifications (I had two left when I was done last night). If I run out, or when I'm done, I switch back to the TestFlight build to get more.

A bit of a hassle, but rare enough that it's probably not worth trying to make them work with development builds.

**Comment by samuelclay** [comment]
Might have something to do with my "Open All Stories on load" setting. 

https://user-images.githubusercontent.com/44229/167647303-0c2a8bc8-58a7-4dff-89fb-45fd41fb1cd1.mp4
