### ISSUE TITLE
iOS: 2022 Redesign

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1693]
It's time for this year's design changes. There's a good number of them.

You can see the redesign on beta.newsblur.com.

* Story titles changed the most
  * There's now a lot more margin and spacing between title, content, and date/author
  * Author moved from inline with title to next to date, losing color differences
  * Read stories are now bold, so unread and read story titles take the same space
  * Unread indicator and feed favicon switched positions
* All new icons. 100% SVGs, all found under `media/icons/nouns/*` on the `pro` branch
* Missing favicon icon also replaced (world.png -> world.svg)
* Almost all uppercase is now in regular, sentence case. Exceptions can and should be made, but buttons and such are now "Sentence case".
* Feed title background colors are slightly different to match each other better
* All feed favicons now have a border radius
* Blurblogs move to below a user's own feeds
* All menu icons (site menu, feed menu, folder menu, story menu) were replaced
* New icons in Feed Options popover (top style menu)
* Difference between Comfortable / Compact was further emphasized
* Borders between feeds, folders, and story titles were removed and deemphasized
* Story content header has fewer borders and more space
* Feed header bar no longer has borders, just the gradient
* Story action buttons at the bottom of each story are slightly different too
* Highlighted feeds have a border radius and margin to them now
* An iOS specific change: Titles should now be variable height. Right now we kinda have a static height that's a bit variable depending on the length of the title. But the spacing around the title should be normalized. And bring the unread indicator up to the top line of the story title to match the web.

I uploaded a whole bunch of screenshots of the before and after from the web for convenience, but realized it would be easier for you to just switch back and forth between beta.newsblur.com and www.newsblur.com. That should help guide the relative changes since it won't be a 1-for-1 with mobile.

**Comment by Dejal** [comment]
Done, except for updating the icons. Xcode can only handle PNG, JPG, or PDF for icons, not SVG.

I think the "nouns" icons were available as PNGs too? Can you provide those?

Another alternative could be to adopt Apple's SF Symbols (their modern approach), which probably have symbols similar enough to the ones on the website.

Let me know if you want any other tweaks.

**Comment by samuelclay** [comment]
I believe SVGs are supported since iOS 13: https://www.willowtreeapps.com/craft/what-svg-support-means-for-your-ios-app-graphics. The colors are in CSS, but we should be able to 

There's many other visual tweaks I'd like to do for iOS to have it match the web. 

 * Folders no longer have gradients, should match the color of "All Site Stories" on the web
 * More space between story title and story content
 * Comfortable/Compact should be on story titles menu as well and should have an effect on those story titles. Check the web for relative spacing. Also note the difference between reading by folder and reading by feed. Looks like feed story titles are more compact that folder story titles.
 * Note the font colors on story content, date, and author. It's lighter on the web than iOS
 * No more top/bottom borders on feed favicon top line on story detail
 * More space on story content view's story title header
 * Can we add a scale transformation to selected story titles like on the web? 
 *

**Comment by samuelclay** [comment]
Take a look at the differences between these two screenshots:

<img width="1007" alt="Screen Shot 2022-07-11 at 11 04 27 AM" src="https://user-images.githubusercontent.com/44229/178295707-034311bf-c495-4def-af84-20d657aad823.png">

![IMG_8E8E4DD18455-1](https://user-images.githubusercontent.com/44229/178295724-8281cc59-d77a-4b42-a7b6-9d6b170387dc.jpeg)

Also note the white status bar text.

**Comment by samuelclay** [comment]
Notes on the three main views:

Feed list
 * Dark areas next to second-level folders, pictured
 * Folders should have a background color, same as web
 * Folder icon color should be tinted. The color is embedded in the SVG, is there a way to use that?
 * World icon is similarly tinted
 

![IMG_0251](https://user-images.githubusercontent.com/44229/180815336-2fd559ba-a929-4c27-95cf-25dbf29ffafe.PNG)

<img width="1500" alt="Screen Shot 2022-07-25 at 11 18 15 AM" src="https://user-images.githubusercontent.com/44229/180814374-c12b8b5c-645a-4c5d-a08b-9931ba082319.png">

Story list
 * It looks like the space below a short story title has been removed, but I'm still seeing it a bit. Also, I think the story content preview is being extended on short story titles. I'd like to cap it at 2/4/6 lines and make the story title shorter instead. This is more noticeable on the 2 line preview
 * Bug in highlighting, was able to highlight multiple stories
 * Can we add an animation transition to story selecting or something so the story title doesn't jump? On web we just scale the button, which may work similarly here
 * More margin above top line and below date line, match the web in Comfortable. Right now it's fine for Compact
 * The Notifications icon in the story titles menu has a huge scale
 * Is there a difference between Compact and Comfortable on this story titles list?
 * Let's not reload the feed when switching between compact and comfortable and instead just redraw the story titles.Also, don't close the menu either, similar to how the line height and font size controls work. Also change the font size on story titles to not close the menu.


![IMG_0252](https://user-images.githubusercontent.com/44229/180818226-3f8583da-20dc-4b1f-93ad-34a17377ac12.PNG)

Story content
 * Lighten the dividing line between story titles and story content to match the web
 * Share/Save/Train buttons need border/box conversion and new icons
 * Training dialog should use Normal case and new icons/styling
 * New saved icon

<img width="710" alt="Screen Shot 2022-07-25 at 11 54 10 AM" src="https://user-images.githubusercontent.com/44229/180821704-bcc5f6f7-74c0-4c0e-a51e-dabc6f1cfbb8.png">

**Comment by samuelclay** [comment]
Scrolling is so smooth now, it's amazing. Thanks for getting to the bottom of that!

**Comment by Dejal** [comment]
> Can we add an animation transition to story selecting or something so the story title doesn't jump? On web we just scale the button, which may work similarly here

Not sure what you mean by this? What jumping?

**Comment by Dejal** [comment]
> Can we add an animation transition to story selecting or something so the story title doesn't jump? On web we just scale the button, which may work similarly here

Not sure what you mean by this? What jumping?

**Comment by samuelclay** [comment]
This looks solid! Hardly any notes, so we're nearly there. I neglected to bring my iPad, so it'll be until next week that I can review on an iPad, but I'll wait for the next round of notes.

Feed list:
 * The icon for Focus is filled in when it should be a circle and ring
 * Saved icon should be solid, not outline

Story titles list:
 * When I switch themes in the story detail view, upon returning I see the wrong feed title font color and shadow, as screenshotted below
 * Compare the web to iOS in these two screenshots: 
   * Add a bit more space, ~2px each, between the image and the favicon, and then the favicon and title/content
   * Bump the story title font size up by 1px (across all font sizes)
   * Where are the story thumbnails for your feed and the Core77 feed? [Pairs with this thread](https://forum.newsblur.com/t/some-thumbnails-are-not-showing-up-in-ios-app/9454/3). Made a new ticket #1723.

![IMG_2732](https://user-images.githubusercontent.com/44229/182877559-770e2d2f-117c-495f-a016-44f4f992cb27.PNG)

Story content:
 * Icons cutoff on the story buttons at the bottom. Also, I think it looks better on Android:

![IMG_2731](https://user-images.githubusercontent.com/44229/182880016-5c9c604d-8e08-4dd5-ac10-1db5bc37d439.PNG)
![Screenshot (Aug 4, 2022 11_05_26 AM)](https://user-images.githubusercontent.com/44229/182881573-839253c2-b5a6-482a-acd9-ce81d300ae36.png)

**Comment by Dejal** [comment]
I can’t figure out how to add spacing between the text and icon (or however else you want to modify the layout); CSS is more your thing, can you help?

Probably something in here in [storyDetailView.css](https://github.com/samuelclay/NewsBlur/blob/1258e88dd086528d16175fc7a1377e2438d206ec/clients/ios/static/storyDetailView.css):

```
.NB-button.NB-share-button div { 
    padding: 8px 0px 8px;
    border-radius: 2px;
    text-align: center;
}

.NB-button.NB-share-button .NB-icon {
    background: url("share@2x.png") no-repeat 0 0;
    background-size: 16px;
    width: 25px;
    display: inline-block;
    height: 18px;
    margin: 0 2px 0 12px;
    vertical-align: text-bottom;
    opacity: .7;
}
```

**Comment by samuelclay** [comment]
Few more notes:

Feed titles list:
* Can we apply a blur filter to the feed folder titles? I find it a bit weird to have text hide underneath a straight white line, and we're done with borders, so that can't be a fix either.
* Replace the toolbar notifications icon with the new dialog-notifications.svg (without the inner shadow)

Story titles list:
* The folder icon color should match (see screenshot)
* Can we change the two toolbar icons to use the new icons?  settings.svg and mark-read.svg
* In the Daring Fireball screenshot, a  story title is too close to the story content
* The focus unread icon is incorrect (pictured in screenshot)
* Horizontally center the favicon and the unread icon to each other

![IMG_2741](https://user-images.githubusercontent.com/44229/183091568-a72ed52d-4622-416f-88f0-62c4b8eb432d.PNG)

![IMG_115EB352DD74-1](https://user-images.githubusercontent.com/44229/183091583-5b1b49ed-a3ec-49dd-bffe-449d32d4d2f5.jpeg)

Story detail:
* I adjusted the share buttons

Misc:
* Title case for "Interactions / Activities" segmented control in the notifications popover.
* Take the borders out of the training dialog. See the web for header styling.

**Comment by samuelclay** [comment]
Compact is also showing too close between title and content preview

![image](https://user-images.githubusercontent.com/44229/183246362-0b6302f0-4960-422b-9867-ec79cf57248f.png)

**Comment by samuelclay** [comment]
Let's also expand titles to max three lines from two. 

![image](https://user-images.githubusercontent.com/44229/183414227-4be1ffbb-be3d-4519-b7f1-e388f5e0636f.png)

**Comment by Dejal** [comment]
> Can we apply a blur filter to the feed folder titles? I find it a bit weird to have text hide underneath a straight white line, and we're done with borders, so that can't be a fix either.

I've tried, but can't figure out how to do that. I could change the background color (for all folders, not just when floating). But take a look at apps like Reminders; the headings behave the same way. So I think it's okay.

**Comment by samuelclay** [comment]
* Still too much space below titles in river view
* Reduce space above title in feed view (not river view)

Both of these can be seen in these two screenshots. Please try to match relative spacing with the web.

![IMG_2767](https://user-images.githubusercontent.com/44229/185420743-ef9d51ad-5790-4d9e-bddc-0098f41dd1c4.PNG)
![IMG_2766](https://user-images.githubusercontent.com/44229/185420754-5f71130c-7f70-46fe-87e6-f0f37b678a5f.PNG)

**Comment by samuelclay** [comment]
Few changes left:

* Can we change the icons in light grey to not be black? Ideally the lighter color in the dark theme, but is this an easy adjustment?
* Large world icon in Add Site
* Incorrect colors in Interactions popover in light grey
* Remove "Delete this site" from the story detail menu
* Left align the profile photo with the folder icons and search bar. Similarly right align the interactions icon

I think we're ready to launch after these changes!
