### ISSUE TITLE
iOS: crash on opening notifications

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1699]
A user reported the issue, their username is in this thread:

https://forum.newsblur.com/t/crash-on-opening-ios-notifications/9370/2

I suggest doing a login_as and waiting for those notifications to roll in.

**Comment by Dejal** [comment]
I switched my iPhone to that account a couple of weeks ago, and am using the release version, but haven't received any notifications since then. Maybe the server knows it isn't really my account, or something?

**Comment by samuelclay** [comment]
You should receive notifications. The notifications are sent to multiple iOS devices, anything that gives an APNS token, which  is specific to the device. You might have to kickstart it by turning on an ios notification on some feed that doesnt have it yet.

**Comment by Dejal** [comment]
That didn't seem to help. I've just turned on notifications for a couple more sites, to see if that kicks it.

**Comment by Dejal** [comment]
I haven't received any notifications since signing in as the user. Despite iOS notifications being on for some feeds that have new content. Is it keyed to a device or something? I don't know how to diagnose this issue.

**Comment by samuelclay** [comment]
You'll only receive notifications on an App Store build. The Xcode build requires a different set of keys on the server and while I once implemented it, I haven't used it in a while and it's probably stale for one reason or another. 

Try installing the App Store version, accumulate notifications, and then open them on your own build.

**Comment by Dejal** [comment]
I am running the App Store edition. And yet....

**Comment by samuelclay** [comment]
It hasn't crashed on me in a long time, so may be time to close this ticket.
