### ISSUE TITLE
iOS: Add Tag context menu attached to Add Tags button on already saved stories is too short 

### ISSUE THREAD

**Issue by NylaTheWolf** [samuelclay/NewsBlur#1700]
When saving a story on iOS and adding a tag, the context menu that appears is far too small and hard to use. It's near impossible to navigate if you're adding a tag to a story you already saved. You have to drag your finger in a precise spot in order to scroll through the menu. It doesn't seem like the gray box is a search box, so you can't use that to get to the tag you want to use quicker. This bug makes it extremely hard to use Newsblur on my iPhone.

The menu that appears when hitting the "Save" button:

![](https://i.imgur.com/ZwvzWzu.png)

The menu that appears when hitting "Add tag" to an article that's already saved:

![](https://i.imgur.com/YvUcutA.png)

**Comment by samuelclay** [comment]
Great job on the writeup and screenshots, this can be easily fixed.
