### ISSUE TITLE
Android: Folders start closed then pop open

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1703]
From a user's email:

> In the past couple(?) months, including immediately before I sent this report, Newsblur will sometimes start with the folders closed. I always want them open, so I can see my feed list, which is how it used to work for me.

> I do have v11.3.1, but I'm still seeing the issue.  I force-closed NewsBlur to get a proper test, reopened it, and all the folders were closed.
> 
> For what it's worth, I opened it a minute later, without any force-closing first, and saw that the folders were initially closed but they quickly popped open without any action on my part.  Another force close saw them already open.  A third left them closed.  I can't figure out any pattern.

Can we make it so the folders are open/closed when they are initially drawn?

**Comment by samuelclay** [comment]
> If there's a call being made to open all the folders after feed counts come in, maybe there are times when the app doesn't refresh feeds, so no call comes in, so the folders stay closed?  I assume it stores a timestamp of last refresh, or something similar, so that it doesn't auto-refresh too often regardless of how often the app is started.

**Comment by sictiru** [comment]
Issue initially reported in https://github.com/samuelclay/NewsBlur/issues/1610

**Comment by sictiru** [comment]
Fixed in NewsBlur v12.0
