### ISSUE TITLE
Android: Crash Reporter

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1707]
Can we add our own custom crash reporter as mentioned by AppManager dev here: https://github.com/MuntashirAkon/AppManager/issues/289#issuecomment-782571555

> [_After the first crash I got this system message: “NewsBlur closed because this app has a bug. Try clearing the app's cache first, and then reopen the app.” On later crashes I got: “NewsBlur closed because this app has a bug. Try updating this app after its developer provides a fix for this error.”_](https://github.com/samuelclay/NewsBlur/issues/1651#issuecomment-1150164407)

Instead of these type of message users would directly see the crash logs & option to send them through mail or copy to clipboard with their comments.

AppManager consider [ACRA](https://www.appbrain.com/stats/libraries/details/acra/acra) as Tracker since it phone home by default.

**Comment by sictiru** [comment]
The message you got for that crash seems like custom OEM implementation, unlike the default Android crash dialog.
The option for a user to send crash logs and feedback is available in the main context menu under `Send app feedback` -> `Email a bug report`. 

@samuelclay how is the crash reporting on iOS?

**Comment by samuelclay** [comment]
If there's a prebaked crash reporter solution built into Android, I'd love to use it. We get crash reports in the Play Store, is that not all of them?

As for iOS, we only have crash reports on TestFlight (beta channel), but that's been instrumental in finding bugs. @Dejal, is there a crash reporter on iOS that we could use for prod? I know we used to use one but it was bloated and caused it's own issues so we had to remove it from the iOS app.

**Comment by Dejal** [comment]
Apple provides aggregated crash reports in App Store Connect and Xcode. For both TestFlight and App Store releases.

There are third-party solutions, if you don't mind including unknown spyware, for example [Sentry.io](https://sentry.io/for/ios/) is one I've heard of before. But Apple's is sufficient.

**Comment by sictiru** [comment]
The Play Store crash reports contain all of the crashes and most rely on it in favor of adding a 3rd party crash report. The only problem is that it has very limited notification settings in case some issues arise, compared to a 3rd party integration.
