### ISSUE TITLE
NewsBlur experienced an error (after git pull & make nb)

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1709]
i tried to update my newsblur docker on macos; there were no errors during a `git pull` & subsequent `make nb`, however after doing so, accessing the newsblur instance in a browser results in:

```
NewsBlur experienced an error
The error has been logged and will be fixed soon so you won't have to see this message again.
```

**Comment by samuelclay** [comment]
What do you see in `make log` and `make alllogs`?

**Comment by samuelclay** [comment]
You can also perform `docker logs -n 100 newsblur_web` which is probably what we really need to see.

**Comment by luxiouronimo** [comment]
aha; thank u for the troubleshooting tips; i wasn't sure where to start..

the docker logs showed something about a css file, so i did a `make collectstatic` and things seem fine now, i can access my newsbin in a browser

thx again

**Comment by Sevichecc** [comment]
I have the same problem, but `make collectstatic` doesn't work for me
the error logs comes with 
```
ValueError: Missing staticfiles manifest entry for 'css/reader/reader.css'
```

**Comment by samuelclay** [comment]
This should now be fixed now that `make collectstatic` is part of the `make nb` routine.
