### ISSUE TITLE
iPad: XKCD alt text

### ISSUE THREAD

**Issue by iangilman** [samuelclay/NewsBlur#171]
The web comic http://xkcd.com/ (as well as other web comics) include alt text, so you can hover over the comic with your mouse and see a second joke/commentary; it's an integral part of the comic reading experience. Of course there's no mouse hover on the iPad. Google Reader's iPad-optimized web version solves this by adding "show alt text" at the bottom of the story. It would be good to have this in the NewsBlur iPad app as well!

**Comment by samuelclay** [comment]
Hooray, this launched sometime 2014.

**Comment by iangilman** [comment]
:+1:
