### ISSUE TITLE
Web: no images in magazine and other views

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1710]
heya, from a previous newsblur update, i don't have images in some views (tho i do have 'em in the full article view)..

they stopped appearing some time ago, and around that time i think i saw something about one of the image-related docker things being for arm, whereas i'm on an intel macos.. i can't find that label now tho..

i thot things looked a little extra spacious, and then remembered i ignored this issue when i first noticed it..

**Comment by luxiouronimo** [comment]
hmm, i thot there was some extra space to the right of the dates on the list view, but that's on the case now.. regardless, here's the magazine view; no broken images, just a big space where the images should be..:
![Screen Shot 2022-07-05 at 12 34 16 AM](https://user-images.githubusercontent.com/1970784/177275285-4fb4cd82-f790-4f71-855b-93ccaf6953e9.png)

there's a div with an inline style that contains a background-image declaration, and that url does point to a valid image:
![Screen Shot 2022-07-05 at 12 39 29 AM](https://user-images.githubusercontent.com/1970784/177276041-9261e89c-2322-4137-8dbb-e9da9d443fdf.png)

i'm using macos/safari, and i can't test in firefox because i can't remember how i was able to login with safari, and haven't been able to login from any other browser or device..

**Comment by samuelclay** [comment]
Here's what I'm seeing:

<img width="1637" alt="Screen Shot 2022-07-05 at 10 59 44 AM" src="https://user-images.githubusercontent.com/44229/177358209-4a4d9c0a-5ee3-4866-a246-5cecb9f068c1.png">

Seems something is going on with your network requests. Do you see any network errors?

**Comment by samuelclay** [comment]
Whoops, here it is in magazine view...
<img width="1637" alt="Screen Shot 2022-07-05 at 11 02 33 AM" src="https://user-images.githubusercontent.com/44229/177358570-cf51b896-1152-48bd-a2a7-7c99602b32f8.png">

**Comment by luxiouronimo** [comment]
only errors for the default_profile_photo.png (could not connect to the server), a fonts.css from cloud.typography.com (403 forbidden), and a socket.io.js.map (404 not found)..

**Comment by luxiouronimo** [comment]
hmm i think it's a css issue; the resulting problematic styles i think are 
`display: none;`
`height: 0;`
`right: -84px;`

when i override these with the following sloppy values, the image appears
`display: block;`
`height: 100px;`
`right: 0;`

these values aren't ideal, but they do demonstrate that the images are loading, just inhibited from appearing by the css..

no images:
![Screen Shot 2022-07-06 at 6 37 13 PM](https://user-images.githubusercontent.com/1970784/177672146-617a37bf-38f5-43de-940d-52c791bba2e4.png)

hacked to be visible:
![Screen Shot 2022-07-06 at 6 42 20 PM](https://user-images.githubusercontent.com/1970784/177672181-9b8e6ed1-4c62-4ef8-b726-4f144cf503cc.png)

**Comment by samuelclay** [comment]
I believe you have image previews turned off. Here's where you'll find it.
<img width="966" alt="Screen Shot 2022-07-07 at 10 09 37 AM" src="https://user-images.githubusercontent.com/44229/177794413-1d8aded9-277e-458d-8fb2-9dc07a1afd1e.png">

**Comment by luxiouronimo** [comment]
wow, that was indeed it; i guess i thot something was broken cuz of the big empty space when there's previews are set to 'no image', but selecting another option does indeed show the images..

plz excuse my ignorance
