### ISSUE TITLE
Self hosted on old computer, elastic search using lots of cpu

### ISSUE THREAD

**Issue by alexjp** [samuelclay/NewsBlur#1712]
Hi,

Thanks for newsblur, I have only been testing it for a few days, but seems really awesome!

I am testing it on an old laptop that I have for "self hostings", and elastic search seems to pop up every 30 seconds and cause massive cpu usage!

Is there a way to, without disabling elastic search, but to relax the schedule? I haven't even used the search functionality, so I don't care if "search is very up to date".

Thanks again !

**Comment by samuelclay** [comment]
It's kind of all or nothing. You can certainly turn off elasticsearch and other than the feed fetchers complaining in the logs, it'll work fine. There's some fine tuning we could be doing, but I don't see ES popping up often enough to have it high on the priority list of latency issues.

**Comment by alexjp** [comment]
thanks @samuelclay for the reply, and sorry for my own late reply.

I managed to disable ES and not have any error logs by removing it from several functions ( python is not my primary language, but I have some experience in python ).

Maybe there is something misconfigured on my end, but ES was popping up all the time and making the cpu almost always at 100% (which , granted, its an old computer). But without ES, it runs fine without ever reaching 100% cpu (or even 50% usage).

If it is a "all or nothing", and search being of course important, I understand and keep this issue closed.

Thank you for your time, and thank you for newsblur, its just **awesome** !

**Comment by VlaK0r** [comment]
> It's kind of all or nothing. You can certainly turn off elasticsearch and other than the feed fetchers complaining in the logs, it'll work fine. There's some fine tuning we could be doing, but I don't see ES popping up often enough to have it high on the priority list of latency issues.

Hello!
I also faced this problem.
I stopped the container, everything seems to be working.
Please tell me what this service is responsible for and what are the consequences of disabling it?
