### ISSUE TITLE
CSS files not found

### ISSUE THREAD

**Issue by Sevichecc** [samuelclay/NewsBlur#1715]
I had change the haproxy port to 83:80 and 444:443 in `docker-compose.yml` as below:
```  
ports:
      - 83:80
      - 444:443
```
after `make nb`, the web page show as 
```
NewsBlur experienced an error
The error has been logged and will be fixed soon so you won't have to see this message again.
```
as this issue mention #1709 , I have tried `make collectstatic`, it works, the content shows up, but I got a lot of  404 in console
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/91365763/178280092-7c26227b-aef0-4e7b-8180-74dabce79bfa.png">

and it seems nothing wrong in logs……

**Comment by samuelclay** [comment]
I probably need to add this command to make nb, but try `make collectstatic`

**Comment by samuelclay** [comment]
Whats the full url of one of those 404s?

**Comment by Sevichecc** [comment]
> Whats the full url of one of those 404s?

such as `http://myip:8000/media/css/pages/welcome.css`

**Comment by samuelclay** [comment]
NewsBlur can run on any port you want, but you'll have to configure docker-compose.yml to suit. Also, I just pushed a build out that fixes the CSS files not found issue.
