### ISSUE TITLE
iOS: Nested folder bug

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1718]
See this thread: https://forum.newsblur.com/t/ipad-nested-folder-weirdness/9484

**Comment by Dejal** [comment]
Including multiple levels of nested folders:

<img width="671" alt="Expanded" src="https://user-images.githubusercontent.com/1318849/182527320-bbf6e8c2-0732-4ff3-8cd9-7c6ff25c708f.png">

<img width="668" alt="Collapsed" src="https://user-images.githubusercontent.com/1318849/182527330-8bc87f44-5351-4c22-9030-8b88fc012366.png">
