### ISSUE TITLE
Feature Request: Configurable S3 hostname

### ISSUE THREAD

**Issue by jmarler** [samuelclay/NewsBlur#172]
There are a large number of competitor S3 services out there now, and you can even host your own S3 object container service.  Currently, NewsBlur has uses the default Amazon S3 hostname.  Many of these services use the S3 API and can be used as drop-in replacement's for Amazon's service.

I would like to request that a couple new configuration options be added:

S3_HOSTNAME
S3_PORT

This could be set to Amazon's by default, but can be customized if needed.

The boto library does allow for setting a custom host and port, as well as proxy if necessary when creating the S3Connection instance.

**Comment by samuelclay** [comment]
Would be happy to accept a pull request on this.
