### ISSUE TITLE
Cutoff stories 500

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1724]
hi,
trying to get more than 500 stories on my feeds.
OVERRIDE_STORY_COUNT_MAX = 1000
in local settings files does not do anything anymore?

Can you please help what to edit?
Thanks!

**Comment by xanthos84** [comment]
after some complete fresh build up it works now.. dont know what was wrong before

**Comment by VlaK0r** [comment]
> after some complete fresh build up it works now.. dont know what was wrong before

Hello!
Please tell me, how did you do it?

**Comment by samuelclay** [comment]
Just type `make nb` to restart everything

**Comment by VlaK0r** [comment]
> Just type `make nb` to restart everything

![image](https://github.com/samuelclay/NewsBlur/assets/77666575/142efc95-c9c9-49d2-ab40-4d2fb016028e)
![image](https://github.com/samuelclay/NewsBlur/assets/77666575/22257d1e-6aba-4676-8ce3-fe2326fc93f1)

It doesn't help.
Please tell me, what am I doing wrong?

**Comment by VlaK0r** [comment]
> Just type `make nb` to restart everything

![image](https://github.com/samuelclay/NewsBlur/assets/77666575/ff66199b-594d-4109-9d27-d64964176d7a)

I tried all three methods.
None of them gave any result.
