### ISSUE TITLE
Web: Bug Using "Next Unread" When Viewing Updated Feed

### ISSUE THREAD

**Issue by DavidTPate** [samuelclay/NewsBlur#173]
Issue: When viewing a feed that has had new Unread items added to it (to the top of the stack) and clicking the "Next Unread" button what happens is that it traverses the list downwards to try and find the unread item never actually getting to the top of the list.

Expected Result: When viewing a feed that has been updated with Unread items and no more unread items exist lower in the stack than is currently being viewed it automatically goes to the top of the stack to show the newest unread item.

Quick Example, I have the following items in my feed (bold are unread, normal are read)
* **Cookies Are Awesome**
* **Try Our New Cookie Bowls**
* Bacon is Amazing

Once I have opened this feed and viewed all of the unread items my list is then transformed to this:
* Cookies Are Awesome
* Try Our New Cookie Bowls *(My browser is currently viewing this item)*
* Bacon is Amazing

Then my feed is automatically updated with a new item, to be:
* **I Like Turtles**
* Cookies Are Awesome
* Try Our New Cookie Bowls *(My browser is still currently viewing this item)*
* Bacon is Amazing

With this new unread item above the item holding focus currently and I hit "Next Unread" the read items in the list are then traversed and I never get up to the new **I Like Turtles** post.

**Note:** I have only been able to reproduce this when viewing posts then navigating in other tabs, marking an item as read to try and reproduce it doesn't allow me to reproduce it. What it looks like is happening to me is that when I am scrolled down outside of the buffer for the post list it doesn't get updated with the new items.

**Comment by samuelclay** [comment]
I changed this some time ago to reload the current feed when searching for a next unread. This case should now be handled gracefully.
