### ISSUE TITLE
docker: db_redis restarting

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1730]
heya i did a `git pull` and `make nb`, and now "NewsBlur experienced an error" when logging in..

i check things in docker, and the db_redis is constantly restarting, saying:

```
*** FATAL CONFIG FILE ERROR (Redis 6.2.6) ***
Reading the configuration file, at line 626
>>> 'repl-diskless-sync-max-replicas 0'
Bad directive or wrong number of arguments
```

**Comment by samuelclay** [comment]
I upgraded to redis 7. docker-compose shows `redis:latest`, so maybe we need to add a 'docker pull redis:latest`? Try that and see if it helps.

**Comment by luxiouronimo** [comment]
aha, `docker pull redis:latest` and then `make nb` seems to have done it; thank u thank u ^_^
