### ISSUE TITLE
Android: Typing in url to add dialog shows folder dialog

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1731]
From a user email:

> When I start typing a URL in the "Add Feed" screen, it pops up the folder selection dialog prematurely, in the middle of typing. I then have to press back, continue typing, and repeat this until I've managed to type the entire URL.

**Comment by sictiru** [comment]
This happened when the query was recognized as an URL and it tried to add it immediately. 
Adding a feed by URL was added as an option to the results list when applicable.

**Comment by samuelclay** [comment]
Launching with v12.1.0.
