### ISSUE TITLE
Android: New preference to load next feed on mark read

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1733]
From this thread: https://forum.newsblur.com/t/option-to-open-the-next-site-or-folder-after-marking-all-as-read-on-mobile/9608. Works on feeds and folders, and loads the next feed or folder. Defaults to off.

This exists on the web in case you'd like to see it in action and see it's wraparound behavior.

**Comment by VlaK0r** [comment]
I suggested it back in March 2019
https://forum.newsblur.com/t/a-button-to-open-the-next-feed/9239
