### ISSUE TITLE
iOS: support for iOS and iPadOS 16, and Xcode 14

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1734]
Please note that the iOS app project now requires Xcode 14 or later.

I have updated the project for Swift 5.7, and for compatibility with iOS and iPadOS 16.

I don't think there are any iOS 16 improvements that we need to adopt in NewsBlur at this stage. Things like lock-screen widgets aren't that useful for this app.

_(This issue is assigned to both of us to give you a heads-up; feel free to close it once you've updated.)_

**Comment by samuelclay** [comment]
Working fine for me, and I'm running Xcode 14.0.2.
