### ISSUE TITLE
iPhone: Misaligned top layout

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1735]
See screenshot. It's both the activities icon and the avatar icon.

![IMG_3062](https://user-images.githubusercontent.com/44229/192292185-7c57a85c-bb39-4c69-a9db-8203269a3b49.PNG)

**Comment by samuelclay** [comment]
Also, I know this should be its own ticket, but in the above screenshot, can we get the word "Focus" to fit? I keep finding myself in focus mode and not seeing why

**Comment by Dejal** [comment]
I assume you mean that you'd prefer the avatar icon to be further to the left? That isn't possible with a navigation bar title view; it won't go any further over. Similarly with the activities icon; that's where iOS wants the right bar button. (You may notice they are aligned with the Add Site and Settings icons in the bottom toolbar.)
