### ISSUE TITLE
[Self-Hosted] unable to stat SSL certificate

### ISSUE THREAD

**Issue by ottoborden** [samuelclay/NewsBlur#1736]
So trying to get NewsBlur up and running on Vultr behind Traefik. Clone the repo, run the domain change script, and `make nb`. Everything builds fine, no errors I see. Then `docker compose up` and everything starts fine except for haproxy which is failing with the below error.

I checked the NewsBlur/config/certificates directory and the only file there I see is `dhparam-2048.pem`. So maybe something did fail in the build and I missed it?

Can I generate these certs? Sorry if it's a newbie question, I'm no sysadmin, just trying to learn.

```
haproxy           | [NOTICE]   (1) : haproxy version is 2.6.6-274d1a4
haproxy           | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
haproxy           | [ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:35] : 'bind :443' in section 'frontend' : unable to stat SSL certificate from file '/srv/newsblur/config/certificates/localhost.pem' : No such file or directory.
haproxy           | [WARNING]  (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:49] : a 'monitor fail' rule placed after a 'redirect' rule will still be processed before.
haproxy           | [WARNING]  (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:50] : a 'monitor fail' rule placed after a 'redirect' rule will still be processed before.
haproxy           | [ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:129] : 'bind :1936' in section 'listen' : unable to stat SSL certificate from file '/srv/newsblur/config/certificates/localhost.pem' : No such file or directory.
haproxy           | [ALERT]    (1) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
haproxy           | [ALERT]    (1) : config : Fatal errors found in configuration.
```

**Comment by samuelclay** [comment]
How did you end up generating the certificates?

**Comment by Berzerker** [comment]
I had this issue. For me, I'm fairly certain it was because I didn't run `make nb` with as root (sudo) the first time, so it errored out when trying to create the certs. However, re-running `sudo make nb` did not properly start that process again, so it proceeded with a broken set of certs. I wasn't 100% sure how to resolve it, but I was early on so I just blasted the whole thing away, re-cloned the repo and ran `sudo make nb` the first time properly, and it worked correctly.
