### ISSUE TITLE
Axios feed not parsing

### ISSUE THREAD

**Issue by nims** [samuelclay/NewsBlur#1738]
For some reason, the Axios RSS Feed: https://api.axios.com/feed/ does not parse in any shape or form anymore. It appears to be working on other RSS sites and apps without issues.

**Comment by samuelclay** [comment]
They are serving NewsBlur a 403 Forbidden, which means that are purposefully disabling NewsBlur. I suggest reaching out to them! I have emailed them to no avail. Please try again!
