### ISSUE TITLE
Web: Some images are not show due to `Referer`

### ISSUE THREAD

**Issue by SeptemberHX** [samuelclay/NewsBlur#1739]
For example, the feed `https://rsshub.app/thepaper/featured`.

An example: `<img alt="" src="https://imagecloud.thepaper.cn/thepaper/image/220/451/797.jpg" style="width: 600px;" class="NB-small-image">`.

If I set it with `referrerpolicy="no-referrer"`, then it works fine. The image appears again.

**Comment by samuelclay** [comment]
The only way this will work is if you load it into Custom JS for your own account. Unfortunately I can't make this change for everybody because it will strip referrers from all image requests and we'd piss off a lot of publishers.
