### ISSUE TITLE
Android: Run unit tests in GA

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1741]
Add Github action script to run unit tests from the Android project.

@samuelclay I've started writing unit tests for some of the newly added code. Any concerns on running this in CI?

**Comment by samuelclay** [comment]
Let's do it! You should have Github Action run access if you commit to the `.github/workflows/` directory.

**Comment by sictiru** [comment]
@samuelclay Just a FYI that I'm reorganizing the Android project files to be better suited for Android Studio. Since the project was started before Android Studio existed, there were a lot of workarounds needed for adding tests, modules and other things. The git history on files will be retained.
PR https://github.com/sictiru/NewsBlur/pull/16
