### ISSUE TITLE
iOS: Marking all stories as read leaves a white row

### ISSUE THREAD

**Issue by adeftu** [samuelclay/NewsBlur#1750]
After I marked all stories as read for a site, the row becomes white and stands out on the main feed. 

Version: 12.0.1 iOS

![image](https://user-images.githubusercontent.com/13695993/200830499-4eb0e145-639e-4ecd-9f56-8e2253fa0e86.jpeg)

**Comment by samuelclay** [comment]
Thanks for reporting this!

**Comment by Dejal** [comment]
I can't reproduce this. Marking as read from the feed detail, via the context menu, or swiping does not do that for me. Can you clarify how to repro this?

**Comment by adeftu** [comment]
https://user-images.githubusercontent.com/13695993/200968072-0a09a883-1372-4c9f-8d51-5808c962ebae.MOV
