### ISSUE TITLE
iOS: No image setting broken

### ISSUE THREAD

**Issue by kinueng** [samuelclay/NewsBlur#1752]
# Issue
The `No image` configuration is not working anymore after upgrading to NewsBlur version 12.0.1.

I have tried switching between the `No image` and the various positioning of the images settings, but the problem persists. Below is a screenshot of the panel I have been interacting with to disable images.

# Environment Information
Operating Systems:
iOS and iPadOS

NewsBlur version:
iPadOS v12.0.1
iOS v12.0.1

# Screenshot of issue on iPadOS:
![image](https://user-images.githubusercontent.com/31117513/200905019-131a87bd-a47e-402b-807f-77d45b70e0b2.png)

**Comment by Sembiance** [comment]
I was also just about to submit a bug for this same issue. iPad, latest version, no matter what I try, I can'get the images to turn off. I can move their location, but not hide them like they used to do.
![version](https://user-images.githubusercontent.com/81436/201207706-093f6cbe-ea76-45d3-b463-567d5ce00be3.jpg)
![images](https://user-images.githubusercontent.com/81436/201207727-07eb98d9-6f7f-4914-a8a6-85d99d8c545d.jpg)
![pref](https://user-images.githubusercontent.com/81436/201207733-a8f85c4f-7e4f-49ef-9f70-5739f5e23339.jpg)

**Comment by kinueng** [comment]
This is likely a dupe of https://github.com/samuelclay/NewsBlur/issues/1746
