### ISSUE TITLE
Android: Update project to target SDK 33/Android 13

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1753]
The most important change that needs to be made is supporting the new runtime permissions for sending notifications.
https://developer.android.com/develop/ui/views/notifications/notification-permission

**Comment by sictiru** [comment]
@samuelclay As part of this update, I'll be merging app startup benchmarks which enabled experimenting with [Baseline Profiles](https://developer.android.com/topic/performance/baselineprofiles/overview). Initial tests are promising and show up to 20% reduction in cold startup times. 
The user journey used to generate the baseline profile stops at the folder/feed list but I think I'll extend it until feed reading. This will increase the APK size ~10kb but the app should perform faster out of the box with this ahead of time optimization.

**Comment by samuelclay** [comment]
Hey that's neat! Should this go through beta channel first?

**Comment by sictiru** [comment]
I've been using it for a few weeks but we can put it through beta first. The branch should be ready in a few days once I close some other work.

**Comment by sictiru** [comment]
@samuelclay The `sictiru` branch is ready to be released to the beta channels.

**Comment by samuelclay** [comment]
Deployed to the beta channel as v13.0.0b1.
