### ISSUE TITLE
Android: Article rendering

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1754]
Check article rendering issue reported for the “inside” network: Inside AI, inside streaming, inside tech, etc.
https://forum.newsblur.com/t/android-article-rendering/9705

**Comment by sictiru** [comment]
@samuelclay I think this rendering issue is caused by escaped HTML tags within a story's content
` <p>Beth is a writer and editor at &lt;a href="http://Inside.com" rel="nofollow"&gt;Inside.com&lt;/a&gt; covering artificial intelligence and daily technology news. You can reach her at &lt;a href="mailto:Beth.Duckett@inside.com"&gt;Beth.Duckett@inside.com&lt;/a&gt;.</p>
`

is rendered by the web view as
`<p>Beth is a writer and editor at <a href="http://Inside.com" rel="nofollow">Inside.com</a> covering artificial intelligence and daily technology news. You can reach her at <a href="mailto:Beth.Duckett@inside.com">Beth.Duckett@inside.com</a>.</p>
`

Do you have an idea of what we could do here?

**Comment by samuelclay** [comment]
I asked but we need the feed
