### ISSUE TITLE
iOS: Split builds for development

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1755]
We just released version 12 (actually v12.0.3 was just submitted. I don't know what happened to 12.0.2 but oh well) and I realized I spent half the time since the last release earlier this year with a dev build where I couldn't receive notifications. So I'd like to see if we can make another build of NewsBlur, maybe with a blue tinted icon, so I can test changes but still have the App Store build to verify user requests, etc.

**Comment by Dejal** [comment]
I've added a new target to the project, called **NewsBlur Dev**. You can build it by choosing the **NewsBlur Dev** scheme in the toolbar:

<img width="520" alt="NewsBlur Dev" src="https://user-images.githubusercontent.com/1318849/203687912-f14c5cae-ef32-4ccb-9425-39714fae9925.png">

It will build a separate edition of the app, with its own app identifier, settings, and a blue icon.

Just make sure to switch back to the regular build scheme before producing a TestFlight or App Store release.

**Comment by Dejal** [comment]
I strongly recommend when merging the `dejal` branch into `master` that you just replace the `NewsBlur.xcodeproj/project.pbxproj` file without attempting to merge it; you'll just need to update the version and build numbers afterwards.
