### ISSUE TITLE
Android: newsletter dialog

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1756]
Basically copy the dialog from the web. We really just need the email address easily copied, so make that front and center and single tap to copy directly to the clipboard. 

https://forum.newsblur.com/t/android-app-access-email-newsletter-forward-address/9713/2

**Comment by sictiru** [comment]
@samuelclay Could you point me in the right direction to retrieve/generate the token necessary for email forwarding?

**Comment by samuelclay** [comment]
Use the `secret_token` from the /reader/feeds endpoint. Here's how `reader_newsletters.js` puts it together:

```
        var email = NEWSBLUR.Globals.username + "-" + NEWSBLUR.Globals.secret_token + "@newsletters.newsblur.com";
```

**Comment by sictiru** [comment]
@samuelclay `/reader/feeds` doesn't return `secret_token` in its response payload. Is there a filter in place for mobile/Android or something of sorts?

**Comment by samuelclay** [comment]
Looks like it's under `share_ext_token` in https://github.com/samuelclay/NewsBlur/blob/master/apps/reader/views.py#L489

**Comment by samuelclay** [comment]
I'm adding share_ext_token but it should also be in user.profile.secret_token.
