### ISSUE TITLE
Right-to-left posts are shown left-to-right

### ISSUE THREAD

**Issue by amire80** [samuelclay/NewsBlur#176]
If a post is written in a right-to-left language, such as Arabic or Hebrew, NewsBlur still shows it at left-to-right.

It should identify the direction of the post and of the title and show them accordingly.

**Comment by samuelclay** [comment]
I believe there is a CSS stylesheet floating around that fixes this. But it requires a lot more work than just alignment. This is a big investment and I don't know if it can be prioritized.
