### ISSUE TITLE
newsblur_web NewsBlur experienced an error

### ISSUE THREAD

**Issue by famaTV** [samuelclay/NewsBlur#1761]
Hello friends!

Could you please help? I am receiving this error message when trying to open the main web page

NewsBlur experienced an error
The error has been logged and will be fixed soon so you won't have to see this message again.
Return to NewsBlur

I cloned the repository and then I have used the make nb to build all docker services. No errors during installation. The only changes I did in the source files were updating the "docker compose" statements to "docker-compose" inside Makefile as it's a legacy command and creates errors. Also, I used different ports because they are used by other dockers as below:

haproxy 4080:80 and 4443:443
newsblur_web 8086:8000
ngix 82:81

![image](https://user-images.githubusercontent.com/6208778/203401535-8386bf28-7f92-4242-9f85-b868520ab457.png)
![image](https://user-images.githubusercontent.com/6208778/203401576-769e2704-fc9a-4b09-9007-705b59d4d3e4.png)
![image](https://user-images.githubusercontent.com/6208778/203401733-07b1d6ec-a7ee-4d5c-8973-a035553d678a.png)

Thank you in advance,

**Comment by famaTV** [comment]
Update:

I tried the above with a virtual machine. The only difference between both setups is that I didn't change anything in the yml file. I just updated the Makefile file (added a '-' between every docker and compose statement).

The issue for me is I already have portainer which is set on port 8000 and I have existing ngix manager which sets on port 80 and 81 and 443 which could break the NB setup. 

![image](https://user-images.githubusercontent.com/6208778/203714775-4ccc8d75-0aea-4e0d-8156-a746389b6c78.png)
![image](https://user-images.githubusercontent.com/6208778/203714986-9714120c-e73e-4721-ad70-a7642b912f57.png)

Your advice is truly appreciated.

**Comment by samuelclay** [comment]
My advice is to check the logs and see if there's anything in there. Specifically `docker logs newsblur_web` and see why you're getting that error page. It's probably some DB server can't be accessed due to a hostname or possibly a port. You might have to change the public ports in a few docker.conf files.
