### ISSUE TITLE
Backend: searching for site to add not returning any matches

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1763]
In the iOS app or website, if I try adding a site, no matches are returned for my search terms. For example:

`https://www.newsblur.com/rss_feeds/feed_autocomplete?term=apple&v=2`

Returns:

```
{
    authenticated = 1;
    feeds =     (
    );
    result = ok;
    term = apple;
    "user_id" = 375710;
}
```

This isn't just an iOS issue; the website also isn't working as expected:

<img width="423" alt="Screenshot 2022-11-25 at 14 38 59" src="https://user-images.githubusercontent.com/1318849/204053499-633cbf1e-7524-4e99-ba72-7eea7b68c20b.png">

<img width="417" alt="Screenshot 2022-11-25 at 14 39 23" src="https://user-images.githubusercontent.com/1318849/204053546-5100d683-f2c5-42e0-9385-52ef2e194b8a.png">

**Comment by Dejal** [comment]
Even a valid RSS URL is failing, e.g. 

`https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml`

<img width="408" alt="Screenshot 2022-11-25 at 15 02 19" src="https://user-images.githubusercontent.com/1318849/204055076-a23b7a91-627b-4f07-a99f-78334e1c7041.png">

(Also that error message isn't very readable in dark mode.)

**Comment by samuelclay** [comment]
Phew, finally fixed this
