### ISSUE TITLE
web: rogue rss feed kopalniawiedzy.pl

### ISSUE THREAD

**Issue by Peter774** [samuelclay/NewsBlur#1766]
Check this feed: https://kopalniawiedzy.pl/wiadomosci.rss
It works fine under android client.
But selecting it under web interface confuses browser and page https://kopalniawiedzy.pl/ is shown instead of newsblur web-ui.

**Comment by samuelclay** [comment]
You'll need to select the feed or text view. Right click the feed before you open it, go to settings, and change the view there. The Original view and Story view for that feed have iframe busters that our iframe buster buster can't defend against.
