### ISSUE TITLE
is it safe to prune docker images?

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1767]
it seems i've been running newsblur docker for almost 2 years; while doing some system maintenance i saw several 'Unused' and 'Unused (dangling)' docker images..

i also discovered the `docker system prune -a` command, and wonder if it's safe to run, or if there's some method of clearing out the old stuff..

**Comment by luxiouronimo** [comment]
it seems safe to run a `docker image prune` to remove dangling images, i'm not sure about `docker image prune -a` tho

**Comment by samuelclay** [comment]
Yep, it's great to get rid of the older images, esp. if you've been upgrading regularly.

**Comment by luxiouronimo** [comment]
awesome, thanks!
