### ISSUE TITLE
local (lan) rss' aren't working

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1768]
heya i just discovered git-web and would like to add a repository's rss feed to my newsblur, but i'm getting the error:
`This address does not point to an RSS feed or a website with an RSS feed.`
despite the url appearing to point to an rss feed..
is this perhaps because it uses standard browser authentication asking for a username and password?

**Comment by steanne** [comment]
this is already possible, just needs the appropriate formatting.

https://forum.newsblur.com/t/handling-of-passworded-paywalled-rss-feeds/5022/2

**Comment by luxiouronimo** [comment]
hmm, i guess there's something else afoot; i get the same error with the username & password..

i validated the feed with the W3C feed validation service, and it indicates that it is a valid RSS feed, so i dunno what's going on..

i guess i'll close this since i can't ask you to setup git-web and troubleshoot it

**Comment by samuelclay** [comment]
What's the url for git web? I couldn't find it but I'd be happy to try and get it working!

**Comment by luxiouronimo** [comment]
i can't share the repo of the relevant project, so i created a repo in a similar fashion and a limited user for you…

this is the url with username and password for the rss:
https://public-test:qlgUNOE4hVtEZMM@dev.dsub.net/git/gitweb.cgi?p=public-test.git;a=rss

and this is the web url, wherein u'll find the rss link in the bottom right:
https://dev.dsub.net/git/gitweb.cgi?p=public-test.git;a=summary

username: public-test
password: qlgUNOE4hVtEZMM

**Comment by luxiouronimo** [comment]
hmm, after updating to a newer version of gitweb and that still not working, i tried another local website with rss and that doesn't work either, so i think it's an issue relating to my lan and not gitweb specific..

any reason newsblur wouldn't be able to access websites on my lan? they're reachable from the host machine i run docker/newsblur on; is there something about the docker network settings that would inhibit this? i'd expect it to be using the network settings (dns, etc) of the docker host machine..?

**Comment by samuelclay** [comment]
You could do it be IP, or have your DNS be local and take care of the domains. But I don't know if there's anything NB can easily do here.

**Comment by luxiouronimo** [comment]
i think this might have to do with the docker host bridge networking somethingerrather; i saw something in this realm and had the thought, but haven't been able to dig further into that..

i can't do it with ip cuz it's a virtual (apache) host at that ip that needs the hostname supplied..
