### ISSUE TITLE
Option for email other than mailgun

### ISSUE THREAD

**Issue by Berzerker** [samuelclay/NewsBlur#1770]
Maybe I'm blind or something, but it seems like there's no option for a free-tier anymore with Mailgun. Are there any alternatives I can use instead that the system supports? I couldn't seem to find anything from the documentation that exists.

Apologies if I missed it.

**Comment by samuelclay** [comment]
You can just substitute in your gmail settings and it should work just fine. There's nothing special about our handling of mail, it all goes through anymail:

https://github.com/anymail/django-anymail

Change `EMAIL_BACKEND` in settings.py.
