### ISSUE TITLE
Android: Story list is shuffled when many items have the same timestamp

### ISSUE THREAD

**Issue by Philipp91** [samuelclay/NewsBlur#1776]
Sometimes when I read through the stories of some feed, when I come back to the story list, I see an animation happening that reorders a whole bunch of stories. This leads to a situation where, despite having "Mark read on scroll" enabled, there are suddenly dozens of unread stories above the scrolling fold,, but also already some unread ones below it, so I need to scroll back up to read the ones that were shuffled up there.

All the stories that got shuffled have the same timestamp. (Many news outlets that also sell print media will publish a whole chunk of articles at a scheduled time early in the morning.)

I'm not exactly sure yet what the trigger is. I navigate away from the list to read an article (sometimes in the external browser) and then I come back. So any of the following might be happening in the meantime:

1. `onStop()` and `onResume()` triggered on the Activity.
2. Entire app killed (JVM terminated) and restarted when I come back.
3. Server sync (triggered by schedule or because the local data exceeds a certain staleness).

Is there may be some unstable sort somewhere?

**Comment by samuelclay** [comment]
Do you have a feed where this happens regularly? If you can provide the newsblur.com url when you the site on the web, that would help us reproduce the issue.

**Comment by Philipp91** [comment]
https://www.nzz.ch/startseite.rss

**Comment by sictiru** [comment]
On `onResume()` the dataset is refreshed with the latest stories for that specific feed. While reading a story, if the background service brought in new stories, those should be displayed at the top of your current scroll state/index once you get back to the feed's story list.

The stories are sorted by timestamp and hash as mentioned in the comments here
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/database/DatabaseConstants.java#L444-L452

I've added NZZ to my account for further debugging.

**Comment by Philipp91** [comment]
> new stories, those should be displayed at the top of your current scroll state/index

One possibly crucial setting: I sort "Oldest first" and "Mark read on scroll".

Yesterday, I noticed a similar, possibly related phenomenon in another feed, and in a part of the feed where the entries had clearly distinct timestamps:

After returning to the list view, new unread items (that I definitely hadn't seen before) appeared above the ones I had already read and scrolled past. They were all 1+ days old, so unless that feed retroactively published a whole bunch of articles _and_ a sync that included those happened while I was away, I suspect that those were somehow hidden or shown in a different place (far below the fold) at the time when I first scrolled over that place. So I had to scroll back up and read them and scroll back down again for them to become unread.

Another related thing: Sometimes I read a feed to its end, then refresh and a couple unread items appear (not fresh ones, but sprinkled over the timeframe that I had previously scrolled over). So far, I thought this was a glitch in how items were being marked as read while I scrolled past them (i.e. some weren't marked and thus were still unread when I refresh). That could be, or it could be that those weren't shown to me in the first place and therefore were never marked as read.

----

I use the training/filtering feature quite extensively. In the aforementioned feeds, around 5% of articles are recognized as disliked. The Web UI won't show me those at all, but the Android App does show me those articles still, with a red little circle on the left. I wonder if that's intentional (or should it filter them out too? why the inconsistent UX?) and whether it could potentially mess with the sorting or as-read marking.

For instance, it could be that it tries to hide a disliked article, but due to an off-by-one error or due to the oldest-first sorting it actually ends up hiding a completely different article. Then I don't get to see that other article, so I won't mark it as read when scrolling through (but I'll mark the disliked one as read) and when I refresh/come back, the other article is surprisingly still there.

Or it could be that when an article is marked as read by scrolling that it somehow counts its position in the list and there's a misalignment in whether filtered articles are counted or not, leading to a different article being marked as read instead.

**Comment by samuelclay** [comment]
Were you able to trigger this behavior @sictiru?

**Comment by sictiru** [comment]
My daily usage involves  `All Stories` section and I have the mark on scroll option enabled. I have noticed instances where some stories were retroactively posted and/or picked up from remote and inserted in the list, creating a fragmented list of read stories. I will have to check on iOS if this behavior can be observed before I rule out the client side.

Philipp you mentioned that you're setup contains `"Oldest first", filter for "Unread only" and use "Mark read on scroll".` which I enabled for one of the feed but I have yet to see a similar behavior to what you're described. It could be that this feed is always picked up sequentially and I'll need to find another one to test.

**Comment by sictiru** [comment]
I pushed an experimental fix which ignores new stories in the story feed list until it's refreshed manually. The way it's set up it had to still take into account updated state for the existing stories in the list.

**Comment by sictiru** [comment]
The fix isn't working as expected so I'm still working on it.

**Comment by sictiru** [comment]
A fix is available in v13.2.3

**Comment by Philipp91** [comment]
Thank you! It's hard to verify this immediately, but I'll keep an eye out for the phenomenon (I've somehow gotten used to it subconsciously by now) and will report back in case it happens again; hopefully it won't.
