### ISSUE TITLE
iOS: Xcode cloud

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1782]
Let's hook up NewsBlur Dev to Xcode cloud so I can get regular branch builds on my device

**Comment by Dejal** [comment]
I see that you created a couple of workflows already. I've tweaked those, and added one for the Catalyst branch, where I'm working on the Grid view and other major changes.

It can't successfully build the NewsBlur Dev app, though, as it has a different bundle identifier than the "real" app. We could work around that by adding a new app listing in App Store Connect for `NewsBlur Dev`, with its bundle identifier of `com.newsblur.NewsBlur.dev`. 

You'd need to do that; I don't have sufficient access (or you could increase my access if you want me to do it for you). Note that this is a permanent thing; it isn't possible to remove apps from App Store Connect. But it would only be visible to us, and would enable doing Xcode Cloud and TestFlight builds; of course, we wouldn't do App Store releases of this app.

**Comment by samuelclay** [comment]
Ok, this should now be up and running! You should have just received an email about the TestFlight being ready.
