### ISSUE TITLE
Android: Put feed name and date/time on one line

### ISSUE THREAD

**Issue by Philipp91** [samuelclay/NewsBlur#1787]
At least in "Spacing: Compact" mode, the feed name and the timestamp should be put on a single line, to save vertical space:

![Screenshot_20230227_215537_NewsBlur](https://user-images.githubusercontent.com/2501211/221683628-f12c2455-839b-4644-9d2b-f35e699fec66.jpg)

Here, half of the vertical space is spent on non-content stuff. E.g. the "Golem" and "21:31" bit can both be above or below the title. In the case where there's also an author (not sure if that happens a lot, I saw it [here](https://github.com/samuelclay/NewsBlur/issues/1639#issuecomment-1059319457), but it never happens in any of my feeds) that could also be squeezed onto the same line, or simply be omitted in compact view.

**Comment by sictiru** [comment]
I see your point of view but consider feeds that have a very long title and/or thumbnails. In that case there wouldn't be room for neither the timestamp nor the author. When a large thumbnail size is used, the title only has 60% of the width of the screen to render itself.

**Comment by samuelclay** [comment]
If you really really want to, the code is open source (here) and you can change the XML file and compile your own NewsBlur Android app. I'm closing this ticket as the title + feed + date/author is as compact as we'll get on mobile. If you really, really want this to happen, post an idea on the [forum](https://forum.newsblur.com) with mocked up screenshots and see if it anybody else wants to see this built.
