### ISSUE TITLE
Android: Allow scrolling the stories list in pages

### ISSUE THREAD

**Issue by Philipp91** [samuelclay/NewsBlur#1788]
Assuming one actually reads only <5% of the stories, most of the items in the list will be scrolled over without reading. NewsBlur already partly serves this use case by auto-marking stories as read during scrolling. But this scrolling currently takes more effort than necessary. Either one needs to move the finger all the way up (basically grab the bottom-most item and drag it to the top of the screen), which requires a second hand. Or one can do many smaller scroll moves with the thumb of one hand, but then that thumb will eventually suffer from RSI. Or one can fling-scroll and catch at the right moment -- but missing the right moment means accidentally marking many stories as read, which would be bad. What's more, none of these scrolling solutions work particularly well while walking (when phone and hands aren't stable).

Possible solutions:
1. Introduce a new pagination mode where a single upwards drag/gesture scrolls a whole page (like the Page-Down key on a desktop browser). Feedly has this.
2. Add Page-Up and Page-Down buttons at the bottom of the screen, overlaying the list, analogous to the "previous story" and "next story" arrow buttons at the bottom right when viewing a story.
3. Introduce another value for the "Mark read on scroll" setting, so that there's "Leave unread", "Read on scroll" and "Click to mark read and scroll". The latter changes the behavior when tapping an item. Instead of opening the story, it will be scrolled up past the upper boundary of the screen, thereby marking it and all stories above as read. To open a story, one would long-click it.

The third proposal is a little less intuitive, but more powerful than Feedly's solution for power users: Because it's not tied to whole pages, it allows the user to interrupt their reading/skimming even halfway through the list, by simply tapping the item they just read. This is opposed to Feedly, where there's only the option to mark the whole page as read, or nothing.

**Comment by samuelclay** [comment]
Hey I love this request! I think it will take some thought about what people want. I'm not attached to this paging style but I believe other people might be! So I'm going to move this thread over to the forum so other people can comment and hopefully it can get built. Really, we just need to make decisions (with enough detail that allows us to consider all the main use cases).

I'm going to close this ticket and direct conversation over to https://forum.newsblur.com/t/scroll-stories-list-in-pages-on-ios-and-android/9993. And when it's finally time to build this after consensus is reached, we can make a new ticket with the decisions.
