### ISSUE TITLE
iOS: Notifications after log out

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1790]
Notifications are still coming in after the user has logged out

- log in
- enable notifications for some feed
- confirm notifications are coming in (and open)
- log out
- wait for notifications

On notif open, the main page is displayed for a few ms and then the login page is shown to the user

**Comment by samuelclay** [comment]
I'm OK with this as users can have multiple accounts and may want multiple sets of notifications coming in. I don't see the current system as an issue, so I'll close this ticket.
