### ISSUE TITLE
iOS: External keyboard shortcuts

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1791]
It looks like some of the iOS keyboard shortcuts do not work as expected
https://github.com/samuelclay/NewsBlur/issues/1644#issuecomment-1427126303

**Comment by samuelclay** [comment]
Sounds like some of the keyboard shortcuts are broken:

> Page Down, Page Up, Dashboard, Share This Story, Scroll to Comments(should it scroll to the bottom if there are no comments or just no op?).

**Comment by samuelclay** [comment]
We have Scroll to Comments on the web and it's a noop if there are no comments
