### ISSUE TITLE
Android: Empty Focus/Unread mode explainer

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#180]
If no feeds have unreads in Focus/unread mode, show focus explainer (see dev.newsblur.com using a new account, just click on Focus). When there are no stories in that mode, show the explainer and world icon.

Don't be afraid to create test accounts. I just ask that you preface them with `test_`.

**Comment by samuelclay** [comment]
Is this still an issue?

**Comment by dosiecki** [comment]
I fixed it so that the empty view now correctly differentiates between loading / no unreads status, but the message is still very generic.  Popping in some unformatted text snippents would be quite easy, though doing formatted stuff will take an hour or two.

**Comment by samuelclay** [comment]
Something formatted would be preferable. See what I've got on iOS and the web. Use the same image.

**Comment by dosiecki** [comment]
Done in #720.
