### ISSUE TITLE
Android: Scroll jumps on load of new items

### ISSUE THREAD

**Issue by bryankaplan** [samuelclay/NewsBlur#1800]
I've encountered this bug in the Android app for ages, and I'm finally reporting it. Sorry if it's been reported elsewhere — I looked but didn't find it.

## Summary:

Using the Android app, while scrolling through All Stories, on-screen list position occasionally jumps when new items are loaded.

## Steps to Reproduce:
1. Have many feeds from news sources that add new items frequently.
2. Go to All Stories.
3. Slowly scroll down the list. No need to click on any items.
4. Continue slowly scrolling down the list until new items are loaded at the top of the list.

## Expected Result:
No visible change. At any point in scroll, there are certain specific items on-screen. When new items are loaded at the top of the list, it should not change which specific items are on-screen.

## Actual Result:
List of items visually jumps, making you lose your place. Suddenly you're looking at completely different items than you were just a moment ago, before the new stories loaded. The items that were previously on-screen are now off-screen.

## Versions:
App Version: 12.1.1
Android Version: 12

**Comment by samuelclay** [comment]
Any chance you can record a video of this happening? If so, we can figure out a fix!

**Comment by bryankaplan** [comment]
I'd rather not for privacy reasons, but it should be very easy to reproduce.

I think the problem is that the list updates while it's open. When I click on "All Stories", I expect a stable list that's a snapshot of the moment I clicked on it. If I want it to be updated, I'll reload the list.

If the list is going to update while it's open, you need to preserve the current view when that happens. But it's hard because timestamps might put new items above and below the items currently on-screen. It would be better UX all around just not to update.

**Comment by sictiru** [comment]
Related https://github.com/samuelclay/NewsBlur/issues/1776
I'm gonna close this one as I pushed changes for that ticket.
The list shouldn't update with newer items anymore until the list is reopened again.
