### ISSUE TITLE
iOS: add interactively swipe right anywhere on the screen to return to the feed list

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1803]
In a comment on the #1720 (grid view) issue, @samuelclay requested:

> I'd like to interactively swipe right anywhere on the screen to return to the feed list. This should be an interactive gesture across the entire width of the view.

I replied:

> that is already available as an edge swipe. Which is distinct from a non-edge swipe, which changes story pages.

Since it's unrelated to the grid view, I've created this new issue. Though I'm still unclear on it; as I said, swiping from the left edge to the right will go back, and swiping right within the content will go to the previous story. So you want a swipe right within the content to continue to go to the previous story if ended before the right edge of the screen, and go back to the feed list if it reaches the right edge of the screen? I don't see how that could be interactive, since it'd be paging the stories then suddenly stop doing that and switch views? Can you show a video of another app doing this elegantly?

**Comment by samuelclay** [comment]
This is for a whole screen interactive swipe in the story list to go back to the feed list. Here's a video:


https://github.com/samuelclay/NewsBlur/assets/44229/9dc7555b-3788-4c4a-806a-4f064c0ffc70

**Comment by Dejal** [comment]
Yes, that shows an interactive swipe like the existing edge swipe (whether or not it was actually started from the edge). But that app doesn't have pages to the left and right, so is not the same situation. We need the distinction of starting the swipe from the edge of the screen to distinguish between going back and changing story pages.

Now, if we have story scrolling set to vertical instead of horizontal, we could start the swipe anywhere on the screen.

**Comment by samuelclay** [comment]
A key distinction here is that this is for going back from the story titles list to the feed list, and not from the story detail view. That view continues to have full-page horizontal swiping, which is great. This is just for the grid view.

**Comment by Dejal** [comment]
Oh, sorry, I misinterpreted the request; I thought you meant from the story view to the feed detail, not from feed detail to feeds list. I understand now; the latter has no conflict.
