### ISSUE TITLE
sudo necessary for make nb (to avoid gtimeout and security commands not found)

### ISSUE THREAD

**Issue by luxiouronimo** [samuelclay/NewsBlur#1804]
heya, i used to run newsblur/docker on macos catalina, but after attempting to update, it died, so rather than troubleshoot, i switched to ubuntu, since docker abandoned catalina some months ago.

with a fresh/minimal ubuntu desktop 22.04 install, i setup docker desktop, enabled the preference that aliases docker-compose, cloned the repo, and did a make nb.

the full output is below, but there were 2 errors i can summarize:

`/bin/bash: line 1: gtimeout: command not found`
…
`sudo: /usr/bin/security: command not found`

i tried looking into `gtimeout` for ubuntu without success, and i'm at a loss for `security`..

thx for your time & efforts, i <3 newsblur

```
~/NewsBlur$ make nb
/bin/bash: line 1: gtimeout: command not found
docker pull newsblur/newsblur_python3
Using default tag: latest
latest: Pulling from newsblur/newsblur_python3
461246efe0a7: Pull complete
e37ebf440f7f: Pull complete
d5b2724fe69a: Pull complete
7965a1bc9673: Pull complete
203fb75034a0: Pull complete
2a0e80bac787: Pull complete
aa24e1004fdb: Pull complete
f3d983fb39e6: Pull complete
cf4fc887ae44: Pull complete
6f2f3bf80c1f: Pull complete
4f4fb700ef54: Pull complete
7b97316b05ea: Pull complete
Digest: sha256:b15f208f82af7a6f8edebb4b32846dfcb47fb0d033235242937776e370d7ff48
Status: Downloaded newer image for newsblur/newsblur_python3:latest
docker.io/newsblur/newsblur_python3:latest
docker pull newsblur/newsblur_node
Using default tag: latest
latest: Pulling from newsblur/newsblur_node
81fc19181915: Pull complete
ee49ee6a23d1: Pull complete
828510924538: Pull complete
a8f58c4fcca0: Pull complete
33699d7df21e: Pull complete
923705ffa8f8: Pull complete
ae06f9217656: Pull complete
39c7f0f9ab3c: Pull complete
df076510734b: Pull complete
660aa3e3c688: Pull complete
6dd11cb4fdf2: Pull complete
356e2b746a5f: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:307471b66f895bb24ad924322b0c8cf0f6afa908fcee380aa5489615a2ad1859
Status: Downloaded newer image for newsblur/newsblur_node:latest
docker.io/newsblur/newsblur_node:latest
docker pull newsblur/newsblur_monitor
Using default tag: latest
latest: Pulling from newsblur/newsblur_monitor
214ca5fb9032: Pull complete
fa7d81b69b9a: Pull complete
53375f8c4be0: Pull complete
d0fd5ab9ec24: Pull complete
8c7a905e65a9: Pull complete
4ae63f7f9ad1: Pull complete
a95cf58cc108: Pull complete
462eca261538: Pull complete
Digest: sha256:273c3bb3f3b7afab9a5f1addd7539bb62c387b2a36c35ad2d65942f449134be9
Status: Downloaded newer image for newsblur/newsblur_monitor:latest
docker.io/newsblur/newsblur_monitor:latest
RUNWITHMAKEBUILD=True CURRENT_UID=1000 CURRENT_GID=1000 docker compose down
[[ -d config/certificates ]] && echo "keys exist" || make keys
make[1]: Entering directory '/home/<user>/NewsBlur'
/bin/bash: line 1: gtimeout: command not found
mkdir config/certificates
openssl dhparam -out config/certificates/dhparam-2048.pem 2048
Generating DH parameters, 2048 bit long safe prime
[…]
openssl req -x509 -nodes -new -sha256 -days 1024 -newkey rsa:2048 -keyout config/certificates/RootCA.key -out config/certificates/RootCA.pem -subj "/C=US/CN=Example-Root-CA"
[…]
[…]
-----
openssl x509 -outform pem -in config/certificates/RootCA.pem -out config/certificates/RootCA.crt
openssl req -new -nodes -newkey rsa:2048 -keyout config/certificates/localhost.key -out config/certificates/localhost.csr -subj "/C=US/ST=YourState/L=YourCity/O=Example-Certificates/CN=localhost"
[…]
[…]
-----
openssl x509 -req -sha256 -days 1024 -in config/certificates/localhost.csr -CA config/certificates/RootCA.pem -CAkey config/certificates/RootCA.key -CAcreateserial -out config/certificates/localhost.crt
Certificate request self-signature ok
subject=C = US, ST = YourState, L = YourCity, O = Example-Certificates, CN = localhost
cat config/certificates/localhost.crt config/certificates/localhost.key > config/certificates/localhost.pem
sudo /usr/bin/security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ./config/certificates/RootCA.crt
[sudo] password for <user>:
sudo: /usr/bin/security: command not found
make[1]: *** [Makefile:86: keys] Error 1
make[1]: Leaving directory '/home/<user>/NewsBlur'
make: *** [Makefile:21: bounce] Error 2

```

**Comment by luxiouronimo** [comment]
i guess [`security`](https://ss64.com/osx/security.html) is a macos command..

**Comment by mrcozzens** [comment]
> 

Hey @luxiouronimo,   I finally gave this install a first test myself tonight.  All default settings, and I got the same error as you.
Just to see what happened, I ran with sudo and got much further. Not full success yet, but it seems close, but I gotta repair a port conflict to see may break next :)   Not sure the ramifications if any of doing this, but I'm just giving a test anyways.  
                `sudo make nb`

My test install is on Windows WSL2-Docker. 
It's been a couple weeks, so not sure if still applicable for you etc...

**Comment by luxiouronimo** [comment]
cheers yo, i haven't reapproached it since last i did; i figure the gtimeout cmd not found is easy enough to resolve, but replacing `security` with a non-macos solution will take some digging..

are your errors one of `security` or `gtimeout`..?

**Comment by mrcozzens** [comment]
> 

I had the same errors as you. Logged look the same.  I'm saying I ran the make command again with sudo and the errors went away.

**Comment by luxiouronimo** [comment]
as someone else pointed out, these errors are no longer present when doing `sudo make nb`.

there is now a different error, but it doesn't seem to be related to `gtimeout` or `security`.

**Comment by luxiouronimo** [comment]
the subsequent error was:
```
docker exec -it newsblur_web ./manage.py migrate
 ---> Starting NewsBlur development server...
make: *** [Makefile:38: migrate] Error 137

```
which was resolved with [the advice here](https://github.com/samuelclay/NewsBlur/issues/1792#issuecomment-1507854850), which was:
`chmod 777 docker/volumes/db_mongo/`

**Comment by luxiouronimo** [comment]
are u using docker-desktop? i'm not sure if it helped, but over the course of getting this to work, i switched from docker-desktop to docker-engine..

the things noted above that fixed my issues:

- `sudo chmod 777 docker/volumes/db_mongo/`
- `sudo make nb`

and possibly:
- using docker-engine instead of docker-desktop

if none of this fixes your issues, i offer my condolences, and suggest you continue searching the issues here, or post a new issue
