### ISSUE TITLE
[android] Since update to 13.1.0 app does not work

### ISSUE THREAD

**Issue by credfeto** [samuelclay/NewsBlur#1814]
Been using the app for months with no issue, but since it updated it's stopped working. 

Initially it showed zero feeds and trying to look at anything caused it to crash.

I uninstalled and re-installed and now cannot log in - the app just exits.

Not sure how to get stack trace or anything out of it.

Android 13 / OnePlus 10

**Comment by sictiru** [comment]
@credfeto Version 13.1.1 is available for update https://play.google.com/store/apps/details?id=com.newsblur. Thanks!

**Comment by credfeto** [comment]
@sictiru Thanks for the quick fix - can confirm everything working my end :)
