### ISSUE TITLE
Android: Story reading horizontal scrolling

### ISSUE THREAD

**Issue by sictiru** [samuelclay/NewsBlur#1815]
There are instances where scrolling horizontally on a story's content doesn't page to the next story.

**Comment by bradleynbaker** [comment]
It seems random when it happens.. my favorite feed is hacker news (y combinator) and it happens there frequently.  https://news.ycombinator.com/rss
I typically will read a few posts in story mode (or text mode it truly is not clearly indicating what mode I'm in.. i.e. if it says story mode, is that the mode I'm in? Or is that the other mode to switch to??  ). But basically the mode where the entire sorry is fed in, and I don't have to go the the website to read it (which is my favorite feature).


But once it starts it happens frequently.  To advance I have to hit next.  Frustratingly the next button only appears at the top of the story and the bottom... Never while reading in the middle.  Which, during a long form article and it gets boring... Causes for quite a delay to get to the next story when the swipe horizontal doesn't work.

To clear the bug, I have to exit out of the text mode and go into the story list, the re enter the text/story mode again.

**Comment by sictiru** [comment]
@bradleynbaker The problem seems to be that the webview in which the story is loaded sometimes will contain content that blocks the horizontal scroll in the parent container.
Until the fix is pushed out there is a workaround: 
1) scroll the view container at the top of the story content, like the title, authors and tag.
2) if you scroll down the list and the top view collapses, there is still a small view with the title with the feed's background color that can handle the scrolling correctly.

**Comment by sictiru** [comment]
Available in version 13.1.2
