### ISSUE TITLE
force http instead https

### ISSUE THREAD

**Issue by ElFDA** [samuelclay/NewsBlur#1819]
Hello!
I have Caddy in front of all my services that automatically manages redirect and SSL certificates, there is a way to force NewsBlur only http and not redirect on https itself?

**Comment by samuelclay** [comment]
You'll have to play around in haproxy.docker-compose.conf:

https://github.com/samuelclay/NewsBlur/blob/ed1a2c40eb56b5cd72d4b95d05d32e08ec3c9cf6/docker/haproxy/haproxy.docker-compose.cfg#L39-L41
