### ISSUE TITLE
iPad: Story traversal buttons have wrong colors on theme change

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1823]
See this screenshot. I changed themes and the story traversal buttons didn't change. Also, see in the other screenshot, how the Next button has a checkmark instead of an arrow.

I re-launched the app to get the correct theme colors, but then the icon was wrong.

![Simulator Screenshot - iPad Pro (12 9-inch) (2nd generation) - 2023-10-06 at 08 07 33](https://github.com/samuelclay/NewsBlur/assets/44229/217388f8-24a7-4336-a7e4-3ba5d88abf60)
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-10-06 at 08 05 37](https://github.com/samuelclay/NewsBlur/assets/44229/3beb9b97-a55b-4d83-8220-40e91ae8d2f7)

**Comment by Dejal** [comment]
I can't reproduce this one. Can you? Any clues on how I can do so?

**Comment by Dejal** [comment]
Continuing my cleanup of old issues that I can't reproducing, closing this one too. Feel free to re-open if you can repro.
