### ISSUE TITLE
iOS: Next Unread button leads to spinning screen

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1827]
This is in the App Store build. See the video. There are 23 unread stories left on some future page but hitting next unread consistently shows a spinning screen. 
https://github.com/samuelclay/NewsBlur/assets/44229/761009cc-8147-4730-9132-5de8f1dd9944

**Comment by Dejal** [comment]
Wow, this was a tricky one. I could reproduce it, which always helps, but couldn't figure out what was causing it. So I spent some time doing a brute force investigation: reverting to older Git revisions (in a binary search) until I found the change that caused it: a fix for issue #1657.

Undoing that change solved it. Then I redid that in a more appropriate place. Now all good. Phew!
