### ISSUE TITLE
Change Default haproxy Port

### ISSUE THREAD

**Issue by Scags** [samuelclay/NewsBlur#1829]
Hi, is it possible to change the HTTP port that haproxy binds to? There is a policy on my work machine that prevents binding to port 80, thus the haproxy container will not start.

`Error: (HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

I first tried to change the port in [docker-compose.yml](https://github.com/samuelclay/NewsBlur/blob/b9d0ae626f7dde4a29f92ee05cd885c5bb4124fb/docker-compose.yml#L172) but doing that and trying to connect via that port gives me an ERR_SSL_PROTOCOL_ERROR.

For context, I am also deploying in Windows, where I've made slight modifications to the Makefile to get the building to work. This works on a separate machine, but when deploying on a service machine, the port-binding inability is present hence the need to change it.

Thanks.

**Comment by samuelclay** [comment]
You'll want to change it in `haproxy.docker-compose.cfg`:

https://github.com/samuelclay/NewsBlur/blob/ed1a2c40eb56b5cd72d4b95d05d32e08ec3c9cf6/docker/haproxy/haproxy.docker-compose.cfg#L34-L35

**Comment by kendofriendo** [comment]
@samuelclay 

Changing the port from 443 doesn't seem to work. I still get an error saying that port 443 is already allocated.
