### ISSUE TITLE
Android: "Go to feed" doesn't go to feed from "Global Shared Stories"

### ISSUE THREAD

**Issue by heliostatic** [samuelclay/NewsBlur#1837]
Expected: 

1. View Global Shared Stories feed
2. Click on an individual story
3. Select "Go to feed" in the triple dot menu
4. Be taken to the site feed for that story, e.g. "The Verge" feed if the story came from The Verge

Actual:

1. View Global Shared Stories feed
2. Click on an individual story
3. Select "Go to feed" in the triple dot menu
4. Header displays "The Verge - All Posts" but the actual feed is the Global Shared Stories feed

Use case: 
While viewing a story in the Global Shared Stories feed, I want to click on a story and subscribe to the individual site feed it came from.

**Comment by sictiru** [comment]
Live in v13.2.3
