### ISSUE TITLE
Android: Header bar shows user and username

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#184]
Show user profile photo at top left instead of generic user icon and newsblur logo. See iOS screenshot.

**Comment by samuelclay** [comment]
I'd like to see this next.

**Comment by dosiecki** [comment]
Not quite clear on this.  Do you want to replace the title of the app with the username of the logged-in user and the app icon with their photo, or do you want to augment the UI by displaying these two in addition?  I can't quite figure out how to shoehorn the iOS look into the Android platform style in this case.

**Comment by samuelclay** [comment]
I want it to look like the iOS app's header, with the user's avatar instead of the NewsBlur logo, their name, and total unread counts below the name.

**Comment by dosiecki** [comment]
Done in #720.
