### ISSUE TITLE
iOS: Widget has extra margin

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1842]
I believe this change happened with iOS 17, but I'm seeing an extra margin on the home screen widget.

![IMG_0029](https://github.com/samuelclay/NewsBlur/assets/44229/ee74013a-f380-4e9f-ac40-ef22d0b30a87)

**Comment by Dejal** [comment]
I've already fixed the margins in the Catalyst branch, but the fixes require iOS 17, so I don't want to retrofit that to the Dejal branch (i.e. current releases) until we can require at least that OS version. Not worth dropping previous OS support for this minor cosmetic issue, in my opinion.

The image preview follows the preference for placement.
