### ISSUE TITLE
iOS: List and Magazine views

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#1847]
Now that the **Grid** view has been completed, it wouldn't be too difficult to extend that to support the **List** and **Magazine** views. They appear to be very similar, just different layouts of the story details. That'll help maintain reasonable feature parity with the website, too.

**Comment by samuelclay** [comment]
Would love to see this!

**Comment by Fe1777** [comment]
---

## 🎨✏️👥💡 Design Phase: Sketching the Future 💡👥✏️🎨

**Objective:** Create visually appealing and functional prototypes for the List and Magazine views.

### Steps:

- **Research:** 🔍📖🤔
  - Analyze existing UI/UX patterns for similar views. 🧐
  - Gather user feedback on the current Grid view and website versions. 👂👥

- **Wireframes:** ✏️📐
  - Draft wireframes for both List and Magazine views. 📝
  - Ensure functional elements like navigation, filters, and content previews are clearly outlined. 🌐

- **Mockups:** 🎨🖌️🖼️
  - Develop detailed mockups with color schemes, typography, and iconography. 🎨✨
  - Use a design tool like Sketch, Figma, or Adobe XD. 🛠️💻

- **User Testing:** 👥🔍👍
  - Create clickable prototypes. 📲
  - Conduct user testing sessions to gather initial feedback and iterate on the design. 📝🔄

## 💻🔧🛠️ Development Phase: Bringing Ideas to Life 🌟🔗💡

**Objective:** Develop the List and Magazine views based on finalized designs and integrate them into the app.

### Steps:

- **Project Setup:** 🧰⚙️🔨
  - Create separate branches from the main codebase for List and Magazine views development. 🌳🌿

- **Component Development:** 🔧⚙️🎛️
  - Develop reusable UI components like cards, lists, and grids. 🗂️
  - Use SwiftUI or UIKit, depending on the existing project structure. 🖥️

- **Data Layer:** 📊🔄
  - Ensure data fetching and binding are efficient and optimized. 🚀
  - Update the API layer if necessary to support new data structures for the views. 🌐

- **Integration:** 🔗📲
  - Integrate the new views into the app's navigation structure. 🚦
  - Add toggle functionality between Grid, List, and Magazine views. 🔄📑📖

## 🧪✅📊 Testing Phase: Quality Assurance Adventure 🚀🔍✨

**Objective:** Ensure the new views are bug-free, performant, and provide a seamless user experience.

### Steps:

- **Unit Testing:** 🧩🔍📐
  - Write unit tests for new components and data handling logic. 🛠️
  - Use frameworks like XCTest. 📝

- **UI Testing:** 📲🖥️🔬
  - Develop UI test cases for user interactions like scrolling, clicking, and transitioning between views. 🖱️🔄
  - Use XCUITest for automated UI testing. 📱🔍🤖

- **Performance Testing:** ⏱️🚗💨
  - Test the app on various iOS devices to ensure smooth scrolling and quick load times. 📲
  - Use Instruments for performance profiling. 🎛️📊

- **Beta Testing:** 👩‍🔬👨‍🔬🚀
  - Release the app to a subset of users via TestFlight. 💌
  - Gather feedback and monitor crash logs and performance metrics. 📋🔍

## 📣📝🔄 User Feedback Phase: Listening and Improving 📈📣✨

**Objective:** Collect and analyze user feedback to make necessary adjustments and improvements.

### Steps:

- **Feedback Collection:** 📝📮🙏
  - Encourage users to provide feedback through in-app surveys or feedback forms. 📊🗣️
  - Monitor app reviews and social media for user comments. 💬🕵️‍♂️

- **Data Analysis:** 📊🔍📈
  - Analyze feedback to identify common pain points or desired features. 🧐
  - Prioritize issues based on severity and frequency of occurrence. 🚦

- **Iteration:** 🔄🖌️🚀
  - Make necessary adjustments to the views based on feedback. 🛠️📲
  - Deploy updates to address bugs and enhance the user experience. 🚀👍

## 🚀🌟📤 Deployment Phase: Going Live! 🎉🌎🚀

**Objective:** Seamlessly release the updated app to all users while ensuring stability and performance.

### Steps:

- **Final Testing:** ✅🔍📝
  - Conduct a final round of comprehensive testing, including regression tests. 🔄🗂️
  - Ensure all critical bugs are resolved. 🐞❌

- **Prepare for Release:** 🎁📲📝
  - Update app metadata, including descriptions and screenshots for the App Store. 🖼️📈
  - Write detailed release notes highlighting the new features and improvements. 📋🆕

- **Gradual Rollout:** 🌎🚦🛠️
  - Consider a phased rollout to monitor the initial reaction and catch any unforeseen issues. 🌍🔍
  - Use feature flags to control the visibility of new views if necessary. 🚩🛠️

## 🔄📊📈 Post-Launch Maintenance: Keeping the Wheels Turning 🔋🚴‍♂️✨

**Objective:** Continuously monitor the app's performance and address issues promptly.

### Steps:

- **Monitoring:** 📈📊🔍
  - Monitor app analytics and crash reports closely after the release. 📱
  - Use tools like Firebase Crashlytics or Sentry for real-time monitoring. 🎛️

- **User Support:** 🛎️👩‍💻👨‍💻
  - Provide support for users reporting issues related to the new views. 🧐🤝
  - Keep an open channel of communication for ongoing feedback. 📣📝

- **Updates:** 🔄📲✏️
  - Release timely updates to resolve identified issues and improve features. 🔧📈
  - Plan for periodic updates to keep the app fresh and engaging. 📅✨

---

### Moving Forward 🚀🔜✨

Implementing these steps ensures a structured approach to adding new List and Magazine views to your iOS app, balancing design, development, testing, and user feedback for a successful rollout. Feel free to reach out if you need further details on any specific part of the process! 🚀📞📧

**Comment by Dejal** [comment]
Done both in the **NB Alpha** app. 

I can't do a build until you [agree to the updates to the Apple Developer Agreement](https://developer.apple.com/account/?teamId=HR7P97SD72).

Note: now that the Catalyst project has been merged into the `Dejal` branch for a public TestFlight, I've renamed the `Catalyst` branch as `dejal-alpha`, since it is used for my changes for the **NB Alpha** internal-only TestFlights.

List layout:

![Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-06-26 at 21 27 31](https://github.com/samuelclay/NewsBlur/assets/1318849/a7b2389f-62d1-43dd-9a9e-8947420bd96b)

Magazine layout:

![Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-06-26 at 21 28 21](https://github.com/samuelclay/NewsBlur/assets/1318849/09d74a3e-f556-481f-90e0-6db485cae52e)

Both work on both iPad and Mac, and support the usual settings for preview image shape and placement, and content text length.

**Comment by samuelclay** [comment]
That's awesome!! Can't wait to try it out.

**Comment by Dejal** [comment]
Any feedback on the List and Magazine views? They are in the `dejal-alpha` branch, and the **NB Alpha** app on internal-only TestFlight. If no issues, we could merge into the `dejal` branch for public testing and release in the next update.

**Comment by samuelclay** [comment]
Nice work! In the magazine view, the story traversal buttons should be sticky to the bottom of the screen, but as the bottom of the story scrolls past, they should stick to the story. So basically at the bottom of the screen or the story, whichever is higher up.

**Comment by samuelclay** [comment]
Is there any way to get rid of the jump when swiping between stories in the magazine view?

**Comment by samuelclay** [comment]
The Left Split view no longer updates which story is highlighted as you swipe between stories on the right
