### ISSUE TITLE
The search is not working.

### ISSUE THREAD

**Issue by VlaK0r** [samuelclay/NewsBlur#1849]
Hello!
Thank you for your hard work.

The instance is installed on raspberrypi (Debian GNU/Linux 12 64bit / Linux 6.1.0-rpi8-rpi-v8)

The search is not working, what could be the reason?

**Comment by samuelclay** [comment]
Answered on https://forum.newsblur.com/t/search-isnt-working-on-local-raspberry-pi-install/10461/22
