### ISSUE TITLE
iOS: feed title is a bit too high

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1850]
See this screenshot. The feed title is nudged too high. ![image](https://github.com/samuelclay/NewsBlur/assets/44229/d68840ca-a924-4fb8-8447-07eb61e411a0)

**Comment by Dejal** [comment]
This doesn't seem to be an issue in the Catalyst branch?

**Comment by Dejal** [comment]
Since this doesn't seem to be an issue in the Catalyst branch, I'm closing this; feel free to re-open if you can reproduce it in the Catalyst branch (preferably along with instructions on how I can do so).

**Comment by samuelclay** [comment]
Can you release the catalyst branch (now merged into dejal) to TestFlight for iOS? I want to try it on my phone and can't remember if we setup Xcode Cloud on the dejal branch.

**Comment by Dejal** [comment]
Yes, the `NewsBlur for iOS` Xcode Cloud workflow builds the iOS app from the `Dejal` branch. I had deactivated it so it wouldn't trigger when doing Mac builds, but I've just reactivated it and done a TestFlight build.
