### ISSUE TITLE
[Enhancement] Allow linking to oneself's profile with a URI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [samuelclay/NewsBlur#1859]
[`issues/1860`](https://github.com/samuelclay/NewsBlur/issues/1860#issue-2254753426) explains the rationale.

**Comment by beedell-roke** [comment]
Closed, unless [`issues/1860`](https://github.com/samuelclay/NewsBlur/issues/1860#issue-2254753426) is undesirable.
