### ISSUE TITLE
Default browser preference on iOS not working

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1866]
See this ticket: https://forum.newsblur.com/t/default-browser-preference-in-iphone-app/10618

> For full stories that open in a browser, I want to use a different browser (Safari) from my iPhone default (Firefox - which I use for everything else). My NewsBlur preference for default browser is set to Safari, but stories open in the device default, Firefox.
> 
> NewsBlur iOS v. 13.0, in iOS 17.4.1. I don’t know if the preference overrode system settings in any earlier versions, I’ve just noticed this (apparently) problem now.

**Comment by Dejal** [comment]
I'll take a look on Monday, but I suspect this might be something that can't be fixed. From memory, opening in a non-Safari browser requires using a special URL that they support, but Safari doesn't support a special URL if Safari isn't the default browser.

If that's the case, your only option would be to use the in-app browser (which uses the Safari rendering engine).

**Comment by samuelclay** [comment]
Be sure to post that comment in the thread for the user!

**Comment by Dejal** [comment]
I've posted to the thread, and am closing this as can't fix.
