### ISSUE TITLE
Feature Request: BlueSky Support

### ISSUE THREAD

**Issue by satmandu** [samuelclay/NewsBlur#1887]
I'd love to be able to post from Newsblur to Bsky or Buffer.

Is that possible to do?

It would be nice to have an alternative to facebook...

**Comment by satmandu** [comment]
Bumping this again @samuelclay, because it would really be useful in this day and age to be able to easily share to Bluesky.

**Comment by samuelclay** [comment]
This is done but won't be launching until I launch the `discover` feature. Should be another week or two. I'm trying hard to get it out ASAP.

Here's the commit: https://github.com/samuelclay/NewsBlur/pull/1832/commits/60f980a26f35bf7e813ba3ee85d2c27a89843208

**Comment by samuelclay** [comment]
![b81f4a2860a0bb81cf796890fd72ee90c14e2e4c_2_1372x998](https://github.com/user-attachments/assets/e27e4d8f-c155-4063-a266-c60813b0c5e2)
