### ISSUE TITLE
Custom email url / domain for newsletter

### ISSUE THREAD

**Issue by mbhkoay** [samuelclay/NewsBlur#1888]
Have a newsblur instance that is self hosted, installed in a vm. 
I'm running it behind a caddy reverse proxy. 

Is it possible to change the email newsletter to my own domain?

**Comment by samuelclay** [comment]
You'll need to setup a mail forwarder like Mailgun. I spend about $250 per month forwarding emails, and I get a bulk discount. You'll probably be looking at the $35/month minimum, just to receive email newsletters.
