### ISSUE TITLE
Android: Fastlane - move folder

### ISSUE THREAD

**Issue by licaon-kter** [samuelclay/NewsBlur#1889]
https://github.com/samuelclay/NewsBlur/tree/master/clients/android/fastlane to root of repo https://github.com/samuelclay/NewsBlur so F-Droid can pick it up

ref: https://gitlab.com/-/snippets/1895688#locations

**Comment by sictiru** [comment]
@samuelclay I see you moved it intentionally to the android subfolder in https://github.com/samuelclay/NewsBlur/pull/1799#issuecomment-1599125851 
Any concerns with moving the folder to root?

**Comment by samuelclay** [comment]
I'd be OK with moving fastlane to the root folder.

**Comment by sictiru** [comment]
Live in 13.3.3
https://github.com/samuelclay/NewsBlur/releases
