### ISSUE TITLE
iOS Bug: Marking story as read/unread right after loading will mark different story

### ISSUE THREAD

**Issue by Limero** [samuelclay/NewsBlur#1898]
This is a bug that happens to me daily and I can easily replicate it. If I open the app, click a feed and too quickly mark a story as read/unread, it will mark a different story. I've not been able to replicate the same bug on Android. Potentially related to https://github.com/samuelclay/NewsBlur/issues/1876

https://github.com/user-attachments/assets/78cce804-2f34-4f4b-8d07-a20af8acc056

**Comment by samuelclay** [comment]
I've experienced this before as well. Sometimes I'll tap a story and the wrong story will open. @dejal can you audit this code and come up with ideas for why this might be happening.

**Comment by Dejal** [comment]
I wasn't able to reproduce #1876 (it has the `blocked` tag). But I'll take another look; even if I can't reproduce either issue, I may be able to add some sanity checks to make sure the right story is accessed.

**Comment by macjl** [comment]
I have same issue. It appears frequently, on iPad and iPhone.
