### ISSUE TITLE
mercury-parser was renamed

### ISSUE THREAD

**Issue by materemias** [samuelclay/NewsBlur#1905]
as stated [here](https://www.npmjs.com/package/@postlight/mercury-parser) project has been renamed to @postlight/parser. Install using @postlight/parser instead.
this makes the node image failed to build/install

**Comment by samuelclay** [comment]
This is fixed in the `discover` branch: https://github.com/samuelclay/NewsBlur/blob/discover/node/package.json#L7

I'll be merging it in soon, hopefully within the month. It's been up on staging.newsblur.com and it's working great.
