### ISSUE TITLE
Incorrect parsing of Tagesschau feed

### ISSUE THREAD

**Issue by soerenb** [samuelclay/NewsBlur#1911]
Issue #1897 was incorrectly closed as "one off". This is not a one off but is happening for several month now. It's not 100% on every article in the feed, but still a common occurrence. Still happens on latest app on recent article.
![IMG_0184](https://github.com/user-attachments/assets/b331065e-e5d7-447b-aac7-7d44e87ec590)
![IMG_0185](https://github.com/user-attachments/assets/d0a9491d-b4fc-4ed2-82bc-d9da3c036b96)

**Comment by samuelclay** [comment]
Ok, I like your persistence. But the truth is, this is out of our hands. The way to get this fixed is to submit a PR to https://github.com/postlight/parser

I searched but nobody's built anything for it yet, so it's up to you: https://github.com/search?q=Tagesschau+postlight&type=code

You can hire somebody or honestly, get GPT to write it. All you have to do is roll up your sleeves and get Postlight Parser's test suite running. If you manage to get that working on a github branch, I'll fork it and run our text fetchers on your fork (I'll bring it in to my own repo fork, but if you write that fork for Tagesschau support, I'll do the work).

**Comment by samuelclay** [comment]
Also happy to answer questions in getting that working. If you get stuck, ping me and I'll get you unstuck.

**Comment by soerenb** [comment]
Seems that postlight has been abandoned and there mercury forked off (https://github.com/jocmp/mercury-parser). And it looks like that one does have some custom support for tagesschau.de: https://github.com/jocmp/mercury-parser/pull/62.

**Comment by samuelclay** [comment]
Thank you so much for finding that! I've deployed with that new repo and it should be working. Won't work retroactively, but if you add `&force=true` to the original_text url, it'll update it (for testing).

**Comment by soerenb** [comment]
I updated the URL and so far things are looking good. Thanks for picking it up so quickly!
