### ISSUE TITLE
Android: Converts URLs to lowercase when adding them

### ISSUE THREAD

**Issue by s-cassidy** [samuelclay/NewsBlur#1912]
Since the paths in URLs can be case sensitive, this can be a problem. I have feeds that I've been able to add perfectly fine in the web version but cannot add in the Android version because it converts the URL to lowercase before trying to add it. This is clearly not desirable behaviour (however you feel about uppercase characters in URLs)

**Comment by samuelclay** [comment]
Ohh, yeah, we should not be changing the case of a URL, since urls are case sensitive.

**Comment by sictiru** [comment]
@s-cassidy It looks like the urls are not lowercased in the project when one tried to add a new feed. 
Could you provide an example of a feed that you couldn't add on Android for me to debug?

**Comment by s-cassidy** [comment]
For example https://mycrsswrd.co.uk/feed/Dyno.rss

![Screenshot_20241211-063222](https://github.com/user-attachments/assets/aee2f6a5-1541-4826-8eaa-508b3537a0f1)

**Comment by sictiru** [comment]
@s-cassidy Fixed and it's going out in the next release. I'll close the ticket once it's live.

**Comment by sictiru** [comment]
https://github.com/samuelclay/NewsBlur/releases
