### ISSUE TITLE
iOS: Opening a site does not scroll to the top

### ISSUE THREAD

**Issue by adeftu** [samuelclay/NewsBlur#1915]
Any site I open, the scroll position it’s not at the top, but is a few pixels below. This means I can’t see the title of the last post and I’d need to scroll down each time I open a site. 

https://github.com/user-attachments/assets/2f914f3e-d5d8-4fef-9c2a-54ec11a23adf

iOS: 18.1
Newsblur: 13.1.3

**Comment by samuelclay** [comment]
Whoa, that is strange. Never seen that before. Do you have a premium account? @Dejal maybe try logging in as this user and see if you can repro.

**Comment by adeftu** [comment]
> Do you have a premium account?

Nope. 

I could probably try to delete and reinstall the app and see if that helps. But let me know first if I can help debugging in the current state.

**Comment by Dejal** [comment]
Actually, not as simple as I thought; it looks like iOS 18 changed the table view behavior, as the same code behaves differently on iOS 17 vs 18. I'm out of time this week, so will resume investigating this on Monday.
