### ISSUE TITLE
Android: Reading Activity recycled on device rotation or context switch

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#199]
The current implementation of the Reading Activity and Fragment does not save state or hold enough state in the fragment to be kept for more than one instantiation.  This causes a number of ill effects when the device is rotated while reading:
- scroll position is lost
- text mode is reset
- unread counter is reset incorrectly
- pagination resets to page 1 and must fully cycle to load page N+1
- unread-only mode may re-page and skip stories

**Comment by dosiecki** [comment]
I believe this is fixed to the best of our practical ability as of 984eeb13bb46b72d7c3f32acda46d90cbf083238.  Story scroll will be saved on rotation within a reasonably margin of precision.
