### ISSUE TITLE
Android: Choose folder when adding a new site

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#202]
Add a folder chooser to add feed dialog. Also allow adding of folders.

**Comment by richardlm** [comment]
I find the inability to assign feeds to folders - either when initially adding a feed or later when I want to change categorisation - is an unnecessary and frustrating limitation.

**Comment by dosiecki** [comment]
Happy to take this on if enough folks come forward in support to bump the priority up to critical/high.

**Comment by samuelclay** [comment]
Yes, we should be doing this. You should be able to select a folder when adding a feed. Just need a drop down, defaulting to the Top Level.

**Comment by richardlm** [comment]
Good news - thanks Samuel.

**Comment by dosiecki** [comment]
Went much further and added full support for organising feeds into folders at any time in 4.6.0
