### ISSUE TITLE
Android: Layout issues with user icons in story view

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#212]
When a story has many shares and likes I see rendering issues on my phone. All the user icons are shown in one or two columns which means there is a lot scrolling to do to get to the story text.

![screenshot-1366749110291](https://f.cloud.github.com/assets/1684641/416784/2ebda262-ac56-11e2-8ca1-0f7b65ac9e23.png)
![screenshot-1366749125329](https://f.cloud.github.com/assets/1684641/416791/4e2b9906-ac56-11e2-8367-828c0912950e.png)

The user icons for likes on comments also render as a single column and overlap with comment text.

![screenshot-1366749166837](https://f.cloud.github.com/assets/1684641/416800/7c579c1c-ac56-11e2-98ee-84a583bbce8c.png)

My phone is a ZTE Blade running Cyanogenmod 7.2 (Android 2.3.x). The screen resolution is 480x800.

This isn't an issue on my HP Touchpad running Cyanogenmod 9 (Android 4.0) so I guess it is related to how the FlowLayout used for the images works with on smaller resolution screens.

**Comment by samuelclay** [comment]
Seems this is fixed now, yeah?

**Comment by dosiecki** [comment]
That code has been reworked to a degree, but I was never able to repro the issue in the first place, so it is hard to say if it has been fixed.
