### ISSUE TITLE
The story view auto redirect to the original site

### ISSUE THREAD

**Issue by bruceyou** [samuelclay/NewsBlur#233]
Using the feed http://www.ruanyifeng.com/blog/atom.xml the story view auto redirect to the original site and cannot go back to NewsBlur site even if I click on the "Go Back" button on the browser.

**Comment by samuelclay** [comment]
I would just disable 'ruanyifeng' on your local install. You can add it to page_importer.py.

**Comment by samuelclay** [comment]
Adding it to reader_utils.js would disable the Story view.
