### ISSUE TITLE
Issues with the supervisor search path for supervisord.conf 

### ISSUE THREAD

**Issue by fake-name** [samuelclay/NewsBlur#242]
The search paths for supervisord.conf seem to apparently vary by distro. Debian (and debian only) has a patch to extend the supervisor search paths to include `/etc/supervisor/supervisord.conf`

The supervisor manual ( http://supervisord.org/installing.html#creating-a-configuration-file ) actually specifies that the correct location for the conf file is `/etc/supervisord.conf`.

Furthermore, I'm not sure how supervisor found it's way onto my system (I didn't install it manually, I'm just using the fabfile), but apparently at least the version of supervisor available with ubuntu 12.04 LTS does not have the patch that includes the additional config search paths (I've verified this by looking at the supervisor sources in `dist-packages`).

As such, it seems like the location for the placement of the supervisor conf files should be moved from `/etc/supervisor/` to just `/etc/`. This will pretty much guarantee it will work on most distros.

**Comment by samuelclay** [comment]
Would be happy to accept a pull request on this.
