### ISSUE TITLE
Deleting a feed that had unread items, keeps unread count in the folder it was in.

### ISSUE THREAD

**Issue by gkatsev** [samuelclay/NewsBlur#246]
I had a feed that had 14 items left in it. The folder that the feed was in had 30 items, this included the 14 from the feed. I deleted the feed with the 14 items. The folder still said it had 30 items in it. Refreshing the page didn't help. After I finished reading the other items in the folder, I was able to use `shift-a` to mark everything as read.
When the feed was deleted, the unread count should've reflected the change in items.

**Comment by samuelclay** [comment]
I believe it does, although I have fixed a number of issues like that since 2013.
