### ISSUE TITLE
Relative URLs in <video> tags are not corrected

### ISSUE THREAD

**Issue by Anks** [samuelclay/NewsBlur#265]
I just noticed this problem when reading this feed: http://acko.net/atom.xml
The [latest post](http://acko.net/blog/why-android-hates-you) contains a `<video>`  with a relative source URL `/files/android/camera-flip.webm`

NewsBlur's web UI renders a video element, but the video points at https://www.newsblur.com/files/android/camera-flip.webm instead of http://acko.net/files/android/camera-flip.webm

**Comment by samuelclay** [comment]
Yeah, this is doing the best it can with relative URLs. They are most definitely expanded to absolute URLs, but this doesn't always work in some cases.
