### ISSUE TITLE
Duplicates in Shared Feed

### ISSUE THREAD

**Issue by heliostatic** [samuelclay/NewsBlur#303]
Duplicate items appear in shared feed group, and break navigation:
![photo 2](https://f.cloud.github.com/assets/70898/671643/db7faf0e-d861-11e2-97d6-e160315b6a62.png)
![photo 3](https://f.cloud.github.com/assets/70898/671645/ddf57584-d861-11e2-8c4f-34003bbf9780.png)

**Comment by samuelclay** [comment]
Probably doesn't happen anymore. I fixed the dupe checker sometime last year.
