### ISSUE TITLE
Serif (Georgia) font not displaying

### ISSUE THREAD

**Issue by nfvs** [samuelclay/NewsBlur#319]
Changing `Preferences > Story > Feed view font family` has no effect on the font displayed, it always shows a sans-serif font. It does change the font size, however (I'm guessing to adapt to the expected different font).

Inspect-element always reports the fonts as: `'Lucida Sans', 'Lucida Grande', Verdana, 'Helvetica Neue', Helvetica, sans-serif;`

Observed on Win7 with both Chrome and Firefox.

**Edit:** I just noticed this happens *only* when in List Mode. In Split Mode it displays correctly.

**Comment by samuelclay** [comment]
Ah-ha, this has definitely been fixed.
