### ISSUE TITLE
Whitespace issue around links

### ISSUE THREAD

**Issue by clumma** [samuelclay/NewsBlur#369]
Take a look at this blog post
http://blog.23andme.com/23andme-research/mito-mightily-disappoints-autism-researchers/

and this one
http://economicsone.com/2013/07/18/the-apple-e-book-price-fixing-case-a-teaching-moment/

Now look at them in Newsblur. Whether I use the Feed or Text view, I get weird spacing issues around the links. See the link on "unable" in the first story, for example. The Feed view wrongly shows the space before the word as part of the link. In the Text view there is no space at all before "unable".

![23andmefeed](https://f.cloud.github.com/assets/1046768/828909/7adc6f20-f0c1-11e2-956a-6f2dee6df508.png)
![23andmetext](https://f.cloud.github.com/assets/1046768/828910/7dff8624-f0c1-11e2-87a7-5c15995c66db.png)

In the second story, the link "full opinion" looks fine in Text view but has no spaces around it in Feed view. The other link (" e-book prize-fixing case") is fine in both views.

![econone](https://f.cloud.github.com/assets/1046768/828912/834e4b1a-f0c1-11e2-9a4e-1e5b1701d5ce.png)

I see this a lot on Newsblur. I haven't seen it in other RSS readers.

**Comment by samuelclay** [comment]
This was fixed I believe sometime in 2014.
