### ISSUE TITLE
Switching between List and Split modes => UI bug

### ISSUE THREAD

**Issue by cyranix** [samuelclay/NewsBlur#379]
Load up a story in a feed (tested under Feed, Text, and Story views) in Split mode. Now change to List mode and change back to Split mode.

Expected: No net effect
Actual: Article contents are smooshed into the article list.

![image](https://f.cloud.github.com/assets/161077/875611/29f17270-f8a7-11e2-898b-5dfdf0aaa760.png)

**Comment by samuelclay** [comment]
Fixed two months ago. I can't believe this lasted that long...
