### ISSUE TITLE
Android: External Intent for Social Shares

### ISSUE THREAD

**Issue by satmandu** [samuelclay/NewsBlur#384]
It should be fairly straightforward to expose an intent that consumes a URL for social sharing via the existing dialogue.

**Comment by dosiecki** [comment]
@samuelclay - looking into the design for this and the first trick will be getting the magic token to pass into `/api/share_story/`.  It looks like I could attempt to guess it based upon some metadata returned by `/reader/feeds`, but if it could officially be added to authenticated responses to the API, that would be great.

**Comment by samuelclay** [comment]
/reader/feeds *is* the official place to get the secret_token.

**Comment by dosiecki** [comment]
> /reader/feeds is the official place to get the secret_token

What is the canonical location in the response?  If I grep the output of `/reader/feeds` for my token, it shows up as a substring of a somewhat deeply nested object, but not in any way that it would be identifiable as the token, without a priori knowledge of the value.  (for instance, the `starred_counts` array has one seemingly-random member with mostly null fields except for `count` and `feed_address`, the latter of which happens to have the token embedded within it, but not with any specific key or other sort of identifier)

**Comment by samuelclay** [comment]
It's `share_ext_token` in /reader/feeds?flat=true.

**Comment by samuelclay** [comment]
There's a renewed call to ship this feature. I'd love to see it, and we just launched this feature on iOS on November: http://blog.newsblur.com/post/179624147551/the-newsblur-ios-app-also-hits-version-80

**Comment by samuelclay** [comment]
Switching to #1516.
