### ISSUE TITLE
Chrome malware warning on feed not present in site

### ISSUE THREAD

**Issue by cyranix** [samuelclay/NewsBlur#409]
I get a Big Red Malware Warning when I view a particular story in a particular feed that doesn't occur when I visit the site in question directly.

Site: http://blog.cryptographyengineering.com (story: "The Many Flaws of Dual_EC_DRBG")
Feed: https://newsblur.com/site/764868/a-few-thoughts-on-cryptographic-engineering

Malware warning indicates that **blog.port3101.org** is the culprit. When I loaded the feed in Firefox, I didn't see any requests being made to that domain (and Firefox's malware warning did not trigger).

Hopefully this is just a weird false alarm, but I thought it would be prudent to report just in case it's XSS or something.

**Comment by samuelclay** [comment]
If you're in the Original view, it's possible. Sites do have that control in NewsBlur.
