### ISSUE TITLE
iOS: Invalid Pinboard token returns "error: (null)" and there is no outside way to reset the token in the device keychain.

### ISSUE THREAD

**Issue by nelsonjchen** [samuelclay/NewsBlur#436]
https://getsatisfaction.com/newsblur/topics/ios_app_when_sending_to_pinboard_unable_to_reset_api_token?utm_content=reply_link&utm_medium=email&utm_source=reply_notification#reply_13329638

Erroneous Pinboard tokens aren't detected and don't get deleted from the iOS device keychain. This entry in the keychain persists even after application uninstallation and reinstallation. If the user inputs an invalid API key or changes their key on Pinboard, their only recourse to restore this functionality is to:

* Jailbreak the device and edit the keychain items to remove the offending database entry.
* Wipe the device and reinstall everything without using backups.
* Restore the backup to a similar iOS device and then restore that backup to the original device. This will invalidate the original device's keychain en masse.

**Comment by samuelclay** [comment]
Good thing we moved to native iOS share controls in iOS 7 in 2014. Thanks for reporting this!
