### ISSUE TITLE
Blank lines being inserted before/after <a href=""> links from feed

### ISSUE THREAD

**Issue by bslatkin** [samuelclay/NewsBlur#445]
This looks like a regression in NewsBlur to me. My guess is something that's extracting HTML from the Atom feed is inserting P tags that shouldn't be there.

These screenshots are from Chrome Version 32.0.1700.19 beta on Mac OS X 10.8.5. It looks identical in Firefox 25.0.1.

#  How it looks in NewsBlur
![screen shot 2013-12-03 at 3 58 43 pm](https://f.cloud.github.com/assets/68086/1669368/1317027a-5c77-11e3-8484-d3887244c8d3.png)

# How it looks on my website
![screen shot 2013-12-03 at 3 58 50 pm](https://f.cloud.github.com/assets/68086/1669369/1324c4e6-5c77-11e3-8356-574238ec3bea.png)

# HTML from the feed

Note this is a good looking escaping. Blogger is what powers my site

```html
<content type='html'>Compare the goals of &lt;a href=&quot;http://www.cbsnews.com/news/amazon-unveils-futuristic-plan-delivery-by-drone/&quot;&gt;Amazon&#39;s delivery drones&lt;/a&gt; to Matternet for the developing world (&lt;a href=&quot;http://www.fastcompany.com/1776951/matternet-flying-autonomous-delivery-system-developing-world&quot;&gt;article from August 2011&lt;/a&gt;):&lt;br /&gt;
&lt;br /&gt;
&lt;iframe width=&quot;640&quot; height=&quot;360&quot; src=&quot;//www.youtube.com/embed/7B3E4OOuGDk?rel=0&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;</content>
```

# Escaped HTML from the feed

Note there are no newlines

```html
Compare the goals of <a href="http://www.cbsnews.com/news/amazon-unveils-futuristic-plan-delivery-by-drone/">Amazon's delivery drones</a> to Matternet for the developing world (<a href="http://www.fastcompany.com/1776951/matternet-flying-autonomous-delivery-system-developing-world">article from August 2011</a>):<br />
<br />
<iframe width="640" height="360" src="//www.youtube.com/embed/7B3E4OOuGDk?rel=0" frameborder="0" allowfullscreen></iframe>
```

# DOM that NewsBlur renders in my browser

Note the extra P tags

```html
<div class="post-body entry-content"><p>
Compare the goals of </p><a href="http://www.cbsnews.com/news/amazon-unveils-futuristic-plan-delivery-by-drone/">Amazon's delivery drones</a><p> to Matternet for the developing world (</p><a href="http://www.fastcompany.com/1776951/matternet-flying-autonomous-delivery-system-developing-world">article from August 2011</a><p>):

</p>
</div>
```

Feed XML is here: http://www.onebigfluke.com/feeds/posts/default

**Comment by samuelclay** [comment]
This should be fixed by now.
