### ISSUE TITLE
iOS: Saved Stories blocked while app is caching feeds

### ISSUE THREAD

**Issue by fxer** [samuelclay/NewsBlur#467]
Just noticed yesterday, if you scroll to the bottom of the iOS app to access your Saved Stories you can't always click on them, if is overlaid by the "Storing past 3 hours...1 day...6 days" messages. Once the caching is finished you can click on Saved Stories like normal

![photo jan 14 8 44 11 am](https://f.cloud.github.com/assets/1500269/1912540/7510d78c-7d3b-11e3-94e0-d6d9be1493d0.png)

**Comment by samuelclay** [comment]
This is a known issue. With saved story tags, it's often only the last saved tag that is blocked, so that makes it less of an issue.
