### ISSUE TITLE
Global Shared stories not staying marked as read

### ISSUE THREAD

**Issue by vpatil** [samuelclay/NewsBlur#489]
From this thread: https://getsatisfaction.com/newsblur/topics/global_shared_stories_not_staying_marked_as_read

Symptoms:
- Stories from up to three months back (with a sliding time window) are continually redisplayed
- Multiple copies of the same story appear
- These zombie stories appear to be from feeds that you subscribe to
- New shared stories from feeds that you *don't* subscribe to work fine
- Doesn't seem to matter whether stories have been re-shared or not

**Comment by samuelclay** [comment]
This is a known issue, which is why Global Shared Stories don't have an unread count.
