### ISSUE TITLE
Android: Videos won't open full-screen

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#515]
Trying to watch a video from Adafruit.com (title: The globes that will *change the way we make music*) and I can't full screen it. I've also heard of this issue before from other users.

**Comment by dosiecki** [comment]
Took some doing, but I got this working on a majority of devices in 4ac7732a9bc6cc0846bcd9b1992794dca122f66b.  Look out for it in our next feature release.

**Comment by dosiecki** [comment]
Have tested this will all sorts of HTML5 content including videoes from all the usual places (youtube, vimeo, dailymotion, etc) and even with some embedded VR(!) and the all worked great.
