### ISSUE TITLE
Match Facebook comments from feeds to Shared stories' comments

### ISSUE THREAD

**Issue by dracoheimerich** [samuelclay/NewsBlur#556]
When the RSS feed brings back a Facebook story with comments, the comments and the original post are not structured in a "story" way. Is it possible to recognize this structure as a "share story" in newsblur to show comments as replies?

**Comment by samuelclay** [comment]
They are formatted as Facebook has requested. I retooled this sometime in 2014, not sure if it was after this request or before, but it's definitely in the style it should be in now.
