### ISSUE TITLE
Android: View Recently-Read Stories

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#561]
The web UI now provides a sweet way to go back and find stories you just read.  Should be a snap to add to the android app.

**Comment by samuelclay** [comment]
This would be great to have, and it's a lightweight feature to add.

**Comment by dosiecki** [comment]
Question about the `/reader/read_stories` API: it looks like it is sorted by last-read-time, but I can't find a property of the story element that vends that timestamp.  Can it be added?  It would make implementation more straightforward.

**Comment by samuelclay** [comment]
Yes, I can see why that would be helpful. Unfortunately, I don't store that information on the backend. I only store relative order. Got any ideas on how to fake that?

**Comment by dosiecki** [comment]
Is there wany way to start collecting it eventually?  Without the sortation key, we can't cleanly merge recents from both local and remote contexts.  I would find the feature deeply frustrating to use if it only showed one or the other.

**Comment by dosiecki** [comment]
Figured out a workaround to get things working.  This will be in the next PR (it is my most-requested feature, by far).

**Comment by dosiecki** [comment]
Implemented in #689.
