### ISSUE TITLE
Android: New Story-List Loading Indicator Bar

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#582]
Enhance the adapter for the story list view to mock an N+1th list item that is the pulsing blue load indicator.  Enable this indicator when the list is loading.

**Comment by manderson23** [comment]
From seeing this in the app now do we still need to show "Fetching fresh stories..." when the loading indicator is shown?
They are effectively duplicate indicators in this case and if the story list fills your complete view the text overlays the indicator anyway and you can't see it.

**Comment by dosiecki** [comment]
Implemented in #665.

**Comment by dosiecki** [comment]
@manderson23 Yeah, the detailed loading status is a bit over-communicated in the story list.  I want to keep it active for debug builds for sure (it is invaluable for troubleshooting), but as to whether it should stay on in Prod is more a judgement call.

**Comment by samuelclay** [comment]
Right, let's get rid of the text and just keep the pulsing bar. I'm going to go in and change the timing, size, and color of it for the next release. But it's looking good!

**Comment by samuelclay** [comment]
Oh, I also don't see the pulsing bar at first load, only on subsequent page loads.

**Comment by dosiecki** [comment]
I'll add code to correctly disable the status message for non-debug builds so you can tweak visual stuff on top of that.

**Comment by dosiecki** [comment]
> Oh, I also don't see the pulsing bar at first load, only on subsequent
page loads.

Yeah, that is a limitation of the listview implementation. You should see
the text "loading" message if the list is empty and the pulsebar when the
list gets going. I can add the pulse bar to the very start, too, if you
want me to invest the time.

**Comment by samuelclay** [comment]
Yes, please. It's shown on every single feed detail load and makes the lag, what little of it is there, less noticeable.
