### ISSUE TITLE
iOS: Rotating device while viewing video stops video playback

### ISSUE THREAD

**Issue by jalsk** [samuelclay/NewsBlur#605]
If I start watching a video in my feed in portrait, then try to rotate to landscape, the video goes away and I'm back looking at my feed and have to press play on the video again.

Precondition: iPhone is in portrait

Steps to reproduce:
1. View feed story with embedded video (BoingBoing frequently does)
2. Tap on the video to begin playback
3. Video goes fullscreen, begins playing
4. Rotate iPhone to view video in landscape

Expected result: 
Video should continue playing, but in landscape

Actual result:
Video stops playing and original story is shown in landscape

This is a fairly minor issue, but I run into it on a daily basis and it would be a nice feature to have.

I'm using an iPhone 5S on T-Mobile, iOS 8.1, NewsBlur version 4.5.0

**Comment by honkon** [comment]
Still happens for me, even after clean install/default options

**Comment by samuelclay** [comment]
Hey @Dejal, any ideas on why this is happening? We fixed this multiple times due to its complexity, but always it's due to the view being redrawn when it shouldn't.

**Comment by Dejal** [comment]
Yeah, rotation is messy.  I could spend some time investigating and hopefully fixing if you like.  There might be a good reason for redrawing the view on rotation, though I agree ideally it shouldn't.
