### ISSUE TITLE
Android: Stabilise Pager Offsets

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#625]
Now that story sets can be updated (rather than cleared and replaced) it is quite possible for the meaning of "story N, given the selected sort order and filters" to change when newer stories arrive in the app.  Thus, when reading from story N to N+1 or N-1, users can repeat stories or miss stories.

The fundamental problem is with pagers navigating via cursor index, not some custom, sortable identifier.

There is a mitigation in place to never modify the story list with new stories while in the item list or reading views, but if the user taps out of the app to open a story or follow a link, the list may update when they go back to our app.  Thus, the existing mitigation is insufficient.

**Comment by dosiecki** [comment]
While the latest fixes now work around insertion of new stories at the head of the list, there yet remain issues with population in the middle or tail of the list that can destabilise offsets:

https://getsatisfaction.com/newsblur/topics/dozens-of-posts-skipped-while-reading

We're getting to the point where we may think long and hard about actually writing a non-indexed pager rather than keep working around all the bugs.

**Comment by dosiecki** [comment]
Just update with a few notes from user bug reports and email threads:  this bug is still very real, and is especially troublesome when reading saved or recently-read story lists, which have not been stabilized in the manner of other order-stable list types.

Any bugs relating to seemingly mismatched save/share/comment/title/author/url state when in story detail view can be tagged to this issue.

**Comment by samuelclay** [comment]
I asked the user to submit his in-app feedback here.

**Comment by dosiecki** [comment]
One thing I snuck into #754 was a change to completely stop using pager indicies.  The position in the pager is now always referred to by story hash, so no matter how the pager shifts, reorders, or otherwise changes, the correct story should stay selected.
