### ISSUE TITLE
Android: Address lag on version 4.0

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#626]
Looks like many people are complaining about lag. When most reinstall the app, everything's better. What can we do about this? I want an update about ASAP to either wipe the DB and make things fast or figure out where the lag is coming from.

**Comment by dosiecki** [comment]
Since the big DB refactor and addition of the maintenance routines, sqlite *DB-wide* lag seems to have been tamed.  If lag in any specific actions is found, let's create new issues for the specific problems.

**Comment by samuelclay** [comment]
Nicely done.
