### ISSUE TITLE
Android: why does the feed list redraw when I finish reading a story?

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#629]
I'm reading a story, hit the Done button, and get taken back to an empty feed list that takes a half second to populate.

**Comment by samuelclay** [comment]
This also happens on the story list (feed detail). User talks about it here: https://getsatisfaction.com/newsblur/topics/returning-to-all-stories-always-starts-from-the-beginning-of-the-list-on-android. 

Thing is, we used to preserve position. Can you change this so that the view scrolls to where the last selected story is when you go back to the story list from the story detail?

**Comment by vgivanovic** [comment]
@samuelclay Thanks for articulating what the real issue is much more succinctl than I did!

**Comment by dosiecki** [comment]
Fixed in #662 on all devices with sufficient memory.

**Comment by dosiecki** [comment]
> Can you change this so that the view scrolls to where the last selected story is when you go back to the story list from the story detail?

This was fixed some months ago.  Again, though, the system can throw out the old state if it needs to recover memory.  I just tested this on three devices and the position was maintained on all of them.  If this can be repro'd on a healthy device, please file a new issue (this one is not strictly related).
