### ISSUE TITLE
Android: Unread counts aren't being updated on some installs

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#634]
See https://getsatisfaction.com/newsblur/topics/in-main-list-unread-not-updating?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_15138655. Been getting quite a few reports about unread counts being stuck. Know why this would happen? Anyway, this should be the top priority right now.

**Comment by samuelclay** [comment]
Take a look at : https://getsatisfaction.com/newsblur/topics/every-thing-shows-no-worries-but-individual-feeds-do-have-unread-stories-inside-them?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_15234652

User says it was his SD card.

**Comment by dosiecki** [comment]
Ah, yeah, it would make sense that if storage were flaky, things might go awry.  Android has a bad (good?) habit of obscuring filesystem failures from apps.  This is why the vast majority of new devices don't have an SD slot anymore.

**Comment by samuelclay** [comment]
Looks like it's not the SD card: https://getsatisfaction.com/newsblur/topics/android-not-syncing-feeds-incorrect-unread-count

**Comment by samuelclay** [comment]
Another: https://getsatisfaction.com/newsblur/topics/android-unread-counts-stuck

**Comment by dosiecki** [comment]
Need a username to investigate.  Feel free to email if they don't want it on the issue log.

**Comment by manderson23** [comment]
Another username

https://getsatisfaction.com/newsblur/topics/android-2vg87b6ayhm27?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply[id]=15266161#reply_15266161

**Comment by dosiecki** [comment]
Logged in as user po******ck. 

`/reader/feeds/?update_counts=true' included feed id `453413` with `"nt": 1`. Main activity UI showed 1 unread for that feed.

Tapped into said feed and scrolled through results provided by `/reader/feed/453413?order=newest&page=1&f=453413&read_filter=all` and confirmed seeing no unreads in UI list.

Switched unread filter to Unread Only and confirmed `/reader/feed/453413?order=newest&page=1&f=453413&read_filter=unread` returned zero results and UI showed no stories.

Hit mark-all-read button and invoked `/reader/mark_feed_as_read/` with args `feed_id=453413`. Received `"code": 1, "result": "ok"` response.

Back in Main activity, refreshed feed/folder list.  `/reader/feeds/?update_counts=true` again returned data block for feed `453413` with `"nt": 1`, causing UI to show 1 unread.

As far as I can tell, the UI is reflecting the data provided by the API.  Am I missing something subtle?

**Comment by dosiecki** [comment]
This was the same situation observed when logged in as the Ca*******ds user, as reported via email where feed `181186` had 3 of these ghost unreads that won't go away.

One commonality I noticed is that all reports of this issue so far have come from non-premium users.

**Comment by samuelclay** [comment]
There's just more non-premiums than premiums. There is next to no difference otherwise. The river works differently, but when caching stories the premium/non-premium condition doesnt have an effect.

I would expect the API to be correct. It's probably their local devices not updating unread counts.

**Comment by dosiecki** [comment]
> I would expect the API to be correct. It's probably their local devices not updating unread counts.

See #issuecomment-71089710 above; the app is, to the best of my understanding, exactly displaying what the API returns in both of the repro cases we have seen so far.

**Comment by trestletech** [comment]
Ditto. I haven't been able to meaningfully use the app in weeks. Android, with SD card.

**Comment by samuelclay** [comment]
Closing this in lieu of #672, since a few minor versions have been launched since.
