### ISSUE TITLE
Android: Only fetch images after all stories have been downloaded

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#639]
I believe this is contributing to some of the lag. On iOS, after all stories are downloaded, a queue is setup to downloading each image, one at a time.

**Comment by dosiecki** [comment]
In addition to decoupling, the last two patches also added task priority and duty cycle limiting.  Resolving this, as it is mismatched with the architecture of the app.  Feel free to re-open if we find evidence of image fetch directly or indirectly impacting other sync threads.
