### ISSUE TITLE
Android: Unread Finder Buggy

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#640]
The new DB arch relaxes some constraints that seem to be confusing the "next unread" finder.  This should be exhaustively tested and fixed up to deal with them.

(reported in #612)

**Comment by dosiecki** [comment]
PR #649 addresses some of the all-out failures of the unread finder, but not the underlying speed problem it has.  A bit more work could be done to speed things up in feedsets that have thousands of unreads.

**Comment by samuelclay** [comment]
Is this related? https://getsatisfaction.com/newsblur/topics/dozens-of-posts-skipped-while-reading

**Comment by dosiecki** [comment]
User says they are sliding, so it would be unrelated the the unread search button.

Sounds to me like like yet another edge case of the ever-present problem with indexed pagers (#625).  Will confirm once we know what version they are on.

**Comment by mokelly** [comment]
Sorry, should have specified that in my report. I'm on the latest, 4.1.0, on an HTC M7 running Android 4.4.  Thanks for investigating!

**Comment by dosiecki** [comment]
Okay, will track the problem as part of #625.

**Comment by dosiecki** [comment]
Should be fully addressed by the changes in #662.  Leaving this open, however, since the new architecture would let us gut and greatly simplify the unread finder code, and prevent future bugs of this nature.

**Comment by dosiecki** [comment]
Implemented in #665.
