### ISSUE TITLE
Android: Fresh Comment Replies Don't Show

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#643]
Find a story shared by a friend where they commented.  Reply to the comment via the app.  Comment doesn't immediately show up in the app.

**Comment by dosiecki** [comment]
Looked into this, and was reminded what a mess comments and shares are.  They are the only action that doesn't use the ReadingAction system to provide offline support, they don't correctly update the local DB and lazily wait for a sync cycle to set local state, and attempt unsuccessfully to manipulate views in-place, causing crashes if not for some ugly catch blocks.

When this reaches priority, this whole mess of AsyncTasks should be gutted and replaced with proper loaders and the network actions should be brought into the same abstraction set as the rest of the app.  Otherwise, chasing down this bug might take more time than fixing the tech debt.

**Comment by samuelclay** [comment]
I'd like to get this fixed. Once we release the latest beta, I'd like to ensure that the unchanging unread counts bug is fixed. On that happens, let's get to work on the remaining old-style network calls.

**Comment by dosiecki** [comment]
I have been working on this for a few days now and it should be in the next pull.

**Comment by dosiecki** [comment]
Hah, it is impossibly good timing that the new comment-on-uncommented shares feature just launched, since I am literally right on the line of code where that needs to be plugged it.  Working on it as we speak.

**Comment by samuelclay** [comment]
Oh shoot, you're gonna beat me to it! I've got a build of iOS going out soon and I was planning on integrating this later this week.

Anyway, look for `friend_shares`. It's identical and `friend_comments` and all you need to do is adjust the icon size to be a bit smaller for both reshares and the original share. I also moved it to the middle (since it's smaller). Everything else was automatically handled by the exisitng code, so when I wrote it for both web and blurblogs, I only had to add a couple dozen lines of code.

**Comment by dosiecki** [comment]
Quick clarification (unrelated to the new feature):

Is it really true that each user can only have one top-level comment per story?  (I understand that there can be multiple replies to a given comment.)  The web UI seems to enforce this, and the Android code makes the same assumption, but the API data structure doesn't seem to specifically limit the cardinality in any way.

Never really noticed before, but I haven't ever seen multiple top-level comments by a single user.

**Comment by samuelclay** [comment]
Yes, that is correct. The only reason comments are in a list is to enforce date ASC order.

**Comment by dosiecki** [comment]
Still working on this.  The whole comments view was rather broken, so I am not only implementing the new reply-able shares, I am also fixing the base impl. (Fun fact: stories that had both comments by friends and the public only showed public comments.  Yay, discovering legacy code!)
