### ISSUE TITLE
Android: Can't share story to Facebook

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#650]
https://getsatisfaction.com/newsblur/topics/cant-send-stories-to-my-facebook-page-from-android-app

"Whenever I try to share a story from the Android app to a Facebook page that I manage, I get an error message telling me that the post failed. This started happening about a week to 10 days ago. At first, I thought it was a one-off error, but it happens every time."

**Comment by dosiecki** [comment]
Our share Intent is incredibly simple.  We populate the title (as the title) and the text content ("title - URL of the story").  What happens from there is up to any app that consumes the Intent.  I am not a Facebook app user, so I cannot check with it, but I checked via several other consumers of the share Intent (gmail, keep, sms, twitter) and they all work fine.

If someone with the Facebook app and an account can check to see if the app is producing any informative logs, that would be very helpful.

**Comment by manderson23** [comment]
I was able to share from the app into Facebook with no errors. This was onto my timeline. I notice that the user mentions sharing to a page that he manages so I don't know if that would make any difference.

**Comment by dosiecki** [comment]
Have tested this against the last few prod and beta releases and haven't seen any errors.  Our use of the share Intent honestly couldn't be made much simpler.  If we can ever get repro for how the Facebook app is (mis)using the Intent, we could consider working around their impl.
