### ISSUE TITLE
Android: show title text instead of alt text

### ISSUE THREAD

**Issue by anisse** [samuelclay/NewsBlur#651]
In the Android app, the alt text is shown on long press. It would be a better idea to show the title text; it would work in xkcd, but also on any website that wants to show a tooltip text on images.
The abstruse goose blog is good example of this.

**Comment by samuelclay** [comment]
Hmm, are we sure we want to do this? The hierarchy would be title > alt. So if both are used, use the title instead of alt. Otherwise use whatever we see.

But alt text is traditionally known as the place to put ... alt text. In Internet Explorer I know that title text gets shown on mouseover but alt text doesn't. So maybe we defer to IE? I'm OK with that.

**Comment by dosiecki** [comment]
While I understand that some sites use these tags for, er, "artistic" purposes (like xkcd), my primary concern is that they function as intended accessibility features. That functionality works pretty well on Android and is baked into the WebView.  

Replacing alt with title would be easy.  Adding title text will be multaplicatively more of a hack than adding alt text was.  If we do the latter, perhaps we show whichever of alt/title has more characters?  Anything further we do to support sites that (mis)use the tags is just a time/cost/maintainability decision.

**Comment by anisse** [comment]
I agree that the order should be title > alt. Also agreed that it should not lose its accessibility focus.

**Comment by anisse** [comment]
IMO, the algorithm should be: if title exist, show it. Then, if alt exist, show it. Keep it simple.

Also, as a data point, the what if blog uses title on images and no alt.

**Comment by anisse** [comment]
Any update on this ?

**Comment by samuelclay** [comment]
Well this is on the backlog, so it'll happen as soon as we prioritize it.

**Comment by dosiecki** [comment]
Implemented in #720.
