### ISSUE TITLE
Android: unescape html entities when showing alt text

### ISSUE THREAD

**Issue by anisse** [samuelclay/NewsBlur#652]
In the Android app, showing title text also show html entites; see for example this post in the android app:
https://www.newsblur.com/rss_feeds/original_story?story_hash=169:a6ca74 "Technically" (http://xkcd.com/1475/)

It shows like this:
`&quot;Technically that sentence started with 'well', so--&quot; &quot;Ooh, a rock with a fossil in it!&quot;`

My instinct is to convert html entities, but maybe you could show it in a webview. This needs to be examined.

**Comment by samuelclay** [comment]
Yes, this is definitely something we should be doing.
