### ISSUE TITLE
Android: Add Global Shared Stories

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#657]
This is an oversight and should have been there a while ago. Treat it just like All Shared Stories and place it at the very top. Just pass an extra parameter to get it. No need to count unreads, just use the data coming back for unread status. Don't save or cache the stories, as they shouldn't work offline.

http://www.newsblur.com/social/river_stories?page=1&order=newest&global_feed=true&read_filter=unread

**Comment by manderson23** [comment]
OK. I'll start looking at it.

**Comment by manderson23** [comment]
Can you point me to the icon you use for global shared stories?

**Comment by samuelclay** [comment]
https://github.com/samuelclay/NewsBlur/blob/master/media/img/icons/circular/ak-icon-global.png
