### ISSUE TITLE
Android: Fetching Recent Stories Fails

### ISSUE THREAD

**Issue by Nrbelex** [samuelclay/NewsBlur#659]
On Android, the list of feeds isn't updating, either automatically or when attempting to do so manually. It seems to get stuck Fetching Recent Stories.

Steps to reproduce:

1. Open Newsblur
2. Let it refresh/pull down to make sure everything is fully synced.
3. Select either Unread or Focus at the bottom (haven't tried All).
4. Select either All Stories or any folder (individual feeds seem to be ok).
5. Without selecting a story, scroll to the bottom of the list.

Expected behavior: Newsblur polls the server for additional stories. i.e. I currently have 300 unread Focus stories, but the list only shows 20 or so. When I scroll to the bottom of these 20, Newsblur should continue to load additional stories.

Actual behavior. Instead of loading additional stories, Newsblur says Fetching Recent Stories but never does so. See image:

https://d2r1vs3d9006ap.cloudfront.net/s3_images/1149927/RackMultipart20150131-23040-1x29coa-tmp_24304-Screenshot_2015-01-31-12-06-02-641098644_inline.png

In the last week or so, several people have reported this or similar issues:

https://getsatisfaction.com/newsblur/topics/android-feeds-dont-auto-update
https://getsatisfaction.com/newsblur/topics/android-feeds-not-refreshing-read-count-wrong
https://getsatisfaction.com/newsblur/topics/android-4-4-2-feeds-not-updated
https://getsatisfaction.com/newsblur/topics/android-stories-dont-load
https://getsatisfaction.com/newsblur/topics/android-is-really-slow-to-load
https://getsatisfaction.com/newsblur/topics/android-feeds-dont-refresh

Additional info:

app version: 4.1.0
android version: 5.0.1
device: LGE Nexus 5 (hammerhead)
memory: normal
speed: 59 in 128 
premium: yes

**Comment by dosiecki** [comment]
Have you tried reproducing this on the beta version perchance?

**Comment by Nrbelex** [comment]
Same issue in beta (4.2.0b1), except I don't even need to scroll before it tries and fails to Fetch Recent Stories (probably because there's no longer the cache of stories that the old version had).

**Comment by dosiecki** [comment]
Hmm, I haven't been able to reproduce this on any of my devices.  Best I can do for now is turn on lots of diagnostics for a future build and hope we can get it to someone proficient in log gathering.

**Comment by Nrbelex** [comment]
I tested again on a Samsung Galaxy S II (SPH-D710) and had the same problem using 4.2.0b1. Maybe it's specific to certain accounts?

**Comment by dosiecki** [comment]
If you are comfortable sharing your username, I can test with an impacted account.

**Comment by Nrbelex** [comment]
Sure thing--thanks for taking a look. Username is (...wait for it...) Nrbelex. I just ask that, if possible, you don't mark anything read.

**Comment by dosiecki** [comment]
Won't touch a thing. (and all access is audited)

**Comment by dosiecki** [comment]
Okay, did a quick test, and doesn't appear to be account-specific.  Was able to responsively fetch more stories for feeds, folders, and All Stories as far back as I tried in various modes.

I am going to add a bit of diagnostic logging and see if we can push up a release to Beta.  We'll need to catch logs from a device actually suffering the issue.

**Comment by Nrbelex** [comment]
Darn, was really hoping you'd see it. My story order is set to oldest, and my read filter is unread only, if that matters. 

Two things to note: I tried clearing all data and signing back in. Did nothing. 

Once I've opened and loaded a single feed, the stories from that feed show up in the all stories view, but nothing additional will load. 

Does the device have to be rooted to pull a log?

Thanks again.

**Comment by Nrbelex** [comment]
FYI, another report of what sounds like the same (or a similar) issue: https://getsatisfaction.com/newsblur/topics/android-sv69tshtfbydh

app version: 4.1.0
android version: 5.0.2
device: asus Nexus 7 (flo)
memory: normal
speed: 25 in 125
premium: no

**Comment by dosiecki** [comment]
A few potential fixes and some diagnostics were added in #662 to go after this.  Once the next beta version of the app is out, it would be great to have anyone experiencing this give it a try, since I still haven't found a way to reproduce this.

**Comment by Nrbelex** [comment]
Right before the update I cleared out all of my unread stories and all of my saved stories and the app began working as it should. I know this doesn't help you find or fix the underlying problem (sorry!), but I'll keep an eye out for its return.

**Comment by dosiecki** [comment]
Has anyone who had this issue been able to test on 4.2.1?

**Comment by dosiecki** [comment]
Haven't had any reports of this since the related fixes to story loading in the last prod patch.  Feel free to open a new issue if this can be repro'd in the latest beta.
