### ISSUE TITLE
Android: slow to load feeds

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#661]
See this discussion: https://getsatisfaction.com/newsblur/topics/android-is-really-slow-to-load?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_15339492. Ted is a long-time NewsBlur user, so let's try logging into his account and timing it ourselves.

**Comment by dosiecki** [comment]
Just tested my latest build on my N4 (2+ year old hardware) on a 15mbit/3mbit wifi connection.  Took about 7.5 seconds to load metadata for 841 feeds and 6.0 seconds to prefetch 395 unreads.  Both sound extremely typical.

I don't believe my alpha code is an order of magnitude better than what is in production, but we can confirm that after my next PR.

**Comment by manderson23** [comment]
That is much faster than on my n4. Loading 80 unreads took 10 second or so this morning. Metadata sync 13 second or so for maybe 80 feeds. Now I was just counting in my head but it does show the variance. On WiFi too.

**Comment by dosiecki** [comment]
Huh. I've a fair number of small tweaks queued up to pull, so perhaps they are significant in combination. (since I have tested them one at a time, qualitative metrics are difficult!) 

I will push to finish off my current task (better progress meter behaviour for users with prefetch off) so I can get these in beta.

**Comment by dosiecki** [comment]
Next Beta release includes some new profiling code to help us dig into why some devices are so much slower than others.

**Comment by dosiecki** [comment]
Anyone who has experienced this, definitely give the soon-to-be-released Beta a try and see if it helps any.

**Comment by manderson23** [comment]
Way faster. The metadata sync step dropped to maybe 2-3 seconds. Loading 84 unreads seemed much faster too.

**Comment by dosiecki** [comment]
Nice.  I think we are pushing the limits of sqlite and non-streaming gson, but I am also pretty happy with performance, even on my oldest devices.

**Comment by tedder** [comment]
this fixed mine- from ~75sec to ~5sec.

**Comment by samuelclay** [comment]
Ok @dosiecki, ready for prod?

**Comment by dosiecki** [comment]
Install stats for this week's beta haven't yet started to flow.  I would sleep a little bit better knowing that we have several dozen installs with no crashes before pushing wide.  Shouldn't take more than another 24 hours, in my experience.
