### ISSUE TITLE
Feed remains using Change Folders

### ISSUE THREAD

**Issue by camgregg** [samuelclay/NewsBlur#663]
When the 'Change Folder' item is used, the feed remains in the folder that it was originally in, as well as a copy being put in the newly selected folder. I have to then delete it fron the original folder. Firefox on Ubuntu.

**Comment by PrplHaz4** [comment]
same on Windows Chrome 40...confirmed deleting the dupe works to fix it

**Comment by samuelclay** [comment]
Right, that's the different between Change Folders and Move Folder. You have to unselect it from the current folder.
