### ISSUE TITLE
Android: River not showing stories in unread/oldest (for one user)

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#664]
Username: seer.

See https://getsatisfaction.com/newsblur/topics/unread-oldest-not-showing-on-android-app.

Ok, the fix for this is to add include_hidden=true to every river and feed call. Alternatively, don't bother including include_hidden=true and instead look for a `hidden_stories_count`. If it's non-zero, keep paging (as opposed to today's behavior of stopping when there are no stories left).

On iOS I just went with include_hidden=true.

**Comment by samuelclay** [comment]
See the last tip on http://www.newsblur.com/api#/reader/feed/:id

**Comment by dosiecki** [comment]
I am pretty confused here.  One assumption that is well-baked into the client is that stories are done paging when a blank page is received.  Wasn't this always the case?  I know I have seen the client incude red stories before, and we never have had that flag.

Just want to make sure I'm not missing a much larger issue.

**Comment by samuelclay** [comment]
So I changed the API a few weeks ago to actually remove hidden stories from the API unless explicitly asked for. This was to deal with clients like Reeder and others that would show hidden stories. I recommend just adding `include_hidden=true` to both the /reader/river_stories call and /reader/feed/:id call.

**Comment by dosiecki** [comment]
Oh, had no idea!  Glad I am not going crazy.  Fix incoming.

**Comment by dosiecki** [comment]
What about `/social/river_stories`, does it ever in(ex)clude hiddens and thus need the flag?

**Comment by samuelclay** [comment]
I'd just add it for now. It doesn't yet, but I may change that some day.

**Comment by dosiecki** [comment]
Patched in. Testing a few things and will send a PR with this and a few pending changes.

**Comment by dosiecki** [comment]
Implemented in #665.
