### ISSUE TITLE
Android: Folder Collapse Should Respect Folder Heirarchy

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#669]
https://getsatisfaction.com/newsblur/topics/can-you-have-a-nested-folder-structure-on-the-mobile-android-app

Due to the way we flatten the folder structure, users who rely upon numerous nested folders can't collapse a parent to hide many children.

**Comment by samuelclay** [comment]
Folder collapse I'm not as concerned about. I do, however, want reading by folder to also pull from all subfolders, which it does not currently do (like it does on the web).

**Comment by dosiecki** [comment]
Created #670 to track.  I believe that the fix for 670 will be 90% of the work to fix this, as well.

**Comment by jonwreed** [comment]
Thanks to you all - appreciated. @Samuel Newsblur is awesome, as a diehard Newsblur supporter I can say that the Android app isn't a good options for me unless I am able to collapse my subfolders into the parent as I can do on the desktop version, I have tried but I can't make it work very well. If you guys ever consider working on this, I'm happy to make a development expense donation. Thanks.

**Comment by dosiecki** [comment]
Turns out that this was indeed trivial once the groundwork for #670 was finally done.  Watch out for an upcoming Beta release!

**Comment by jonwreed** [comment]
sweet - smart work using one to do the last mile on the other....huge thanks and will look out for the beta!

**Comment by dosiecki** [comment]
Done in #679.
