### ISSUE TITLE
Android: Unread counts stuck

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#672]
Top three support issues on the board today:

https://getsatisfaction.com/newsblur/topics/android-unread-list-doesnt-update
https://getsatisfaction.com/newsblur/topics/android-new-article-counter-stuck
https://getsatisfaction.com/newsblur/topics/android-64d07mq5ew5e2

Any ideas?

**Comment by dosiecki** [comment]
Sounds a lot like #634, which is blocked on feedback as to whether we are interpreting the API correctly.

I can confirm if you have usernames to test.

**Comment by samuelclay** [comment]
I closed the other ticket since it was older than the current version. See if you can figure out why users are now having stuck unread counts.

**Comment by samuelclay** [comment]
I doubt it's user specific and more likely device or OS specific.

**Comment by samuelclay** [comment]
In other words, if you log on with your device and their username, it'll look fine.

**Comment by dosiecki** [comment]
In all previous examples, I was able to reproduce it on my devices (see the earlier-linked issue for details).  Confirming whether or not this is the case is key to finding a root cause.

**Comment by samuelclay** [comment]
Interesting. OK, I'm asking for usernames on all of those. Also, can you add a username field to the feedback-body that users are using for get satisfaction?

**Comment by dosiecki** [comment]
Yep, if you aren't worried that would be a breach of PII.

**Comment by samuelclay** [comment]
Nope, not worried as the user needs to explicitly submit the feedback and they have a chance to delete it.

**Comment by samuelclay** [comment]
So I think I found the bug. It was user-specific, actually. Although I figured that every time we logged in with the user's account, it looked correct. But if we had logged in on the web (or iOS), then they would have triggered a "repeat visitor" flag, which updates their last seen date. If that last seen date was more than 30 days ago, then their unread counts wouldn't be automatically counted.

Now, I have to wonder, are you calling /reader/refresh_feeds? The way Android is supposed to work is that you call /reader/feeds without saying count all unreads, then immediately call /reader/refresh_feeds to update the counts. But you may have update_counts=true in there, in which case that call is super slow and should be rewritten. 

Anyway, the repeat visitor flag was on three urls: /, /reader/load_feeds (now replaced by /reader/feeds), and /reader/refresh_feeds. If Android didn't call any of those, then there would definitely be a problem. I added /reader/feeds and I'm now seeing a handful of Android users call /reader/feeds with last-login-dates upwards of a few months, which means they havent hit the web in that long.

**Comment by amboar** [comment]
Just thought I'd drop in here - I filed the feedback at [1]. I'm not an Android developer but I am a Java guy amongst other things. If there's some further debugging needed I'm happy to dive in; Sounds like an issue specific to the Android app?

[1] https://getsatisfaction.com/newsblur/topics/android-unread-list-doesnt-update

**Comment by samuelclay** [comment]
Yep, looks like the /reader/feeds endpoint not being coupled with the /reader/refresh_feeds endpoint was the culprit. Everything should work great now. Thanks for your help!

**Comment by dosiecki** [comment]
Glad we cracked it!

> are you calling /reader/refresh_feeds? The way Android is supposed to work is that you call /reader/feeds without saying count all unreads, then immediately call /reader/refresh_feeds to update the counts. But you may have update_counts=true in there, in which case that call is super slow and should be rewritten

Well over a year ago, we switched from a 2-step metadata fetch to a 1-step metadata fetch, for performance reasons.  Rather than call `/reader/feeds?update_counts=false` and get stale counts, insert the stale data, call `/reader/refresh_feeds` and get fresh counts, and then update the fresh counts, we only call `/reader/feeds?update_counts=true` and do a single insert of fresh data.  Any speed advantage of splitting into two API calls is more than negated by the speed disadvantage of having to insert and update rather than just insert (updates cost a ton in our DB).  For users with many feeds, this can be an almost order-of-magnitude speedup in DB write times.

**Comment by dosiecki** [comment]
> I filed the feedback at [1]. I'm not an Android developer but I am a Java guy amongst other things. If there's some further debugging needed I'm happy to dive in;

We are always deeply gracious to receive detailed logs from anyone having trouble!  If your device is rooted, the "catlog" app can grab them into a zipfile very easily.  If not, you can set up the "adb" tool on any Java dev box and pull the logs over USB using the "adb logcat" command.
