### ISSUE TITLE
Android: Show Read Stories

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#674]
Right above the Saved Stories feed item, add a Read Stories feed. It should never be hidden. It should do the same thing as any other river view, except every story is guaranteed to be read_status:1 and does not need offline. Perhaps copying a page from the Global Shared Stories rules.

http://www.newsblur.com/api#/reader/read_stories

**Comment by dosiecki** [comment]
Duplicate of #561.
