### ISSUE TITLE
Android: Adjustable Ordering for Saved Stories

### ISSUE THREAD

**Issue by brianchris** [samuelclay/NewsBlur#676]
I love NewsBlur, and I find that the majority of time, I use it on my Android smartphone.  That being the case, would it be possible to have options for different story orders for the current feeds section & the saved stories section?  Specifically, I enjoy showing "oldest first" stories within my current feeds (so I can read things in the order they happened).  However for saved stories, I would prefer those to be sorted by "newest first," as the older it is, the less likely I am interested in the saved story.  I thought at one point the Android app used to behave like this natively, but I could be wrong about that.  Currently, I have to change the story order every time I go into "saved stories" on my Android device, and then I have to switch that back when I access my current feeds.  Thanks in advance for your consideration of this feature request!

**Comment by dosiecki** [comment]
Saved stories are always displayed in the order they were saved, not in the default feed order.  You can safely switch any feed or folder (or the default order) to oldest-first without affect saved stories.

**Comment by brianchris** [comment]
Thanks for your reply.  I may be very confused, but in the NewsBlur app on my Android smartphone, changing the “story order” option within preferences *does* change the story order of the saved stories.  If I am reading your reply correctly, you may not know that?  Now, that is not a bad thing, because I desire to change the story order for the saved items, however I was trying to request a separate option for how the app sorts feeds for the saved stories (one setting for the default feed order, and one setting for the saved items).  If this is a bad idea, too complicated to implement, I am hopelessly confused, or I am not explaining myself clearly enough, then I promise I will not bother you again with this feature request.  However, I felt there was a large enough misunderstanding between us initially, that I should make *one* attempt at clarifying my feature request.  Thanks again!

**Comment by samuelclay** [comment]
Hey Daniel, I think Brian's correct in that you should be able to change the story order in Saved Stories. You can do this on the web, so Android should be able to handle it just fine. Just use the same `order` key.

**Comment by dosiecki** [comment]
Now I am quite confused.  I just confirmed both on a test build and via the source code - there definitely is no option to change the order of saved stories in our Android app.  The order of saved stories is hard-coded in three different spots, and there does not even exist a menu item or preference key to change said order.

@brianchris - do you know what version of the Android app are you running?

**Comment by samuelclay** [comment]
That's weird, I checked on my N7 and only saw "default view" in the option under Saved Stories.

**Comment by dosiecki** [comment]
(I should add that I can certainly implement story ordering for saved stories, I would just love to know if we have a bug where that option is somehow showing up already.)

**Comment by samuelclay** [comment]
Oh, I read that wrong. There is *not* currently an option to change order for saved stories. Let's change that if it's trivial.

**Comment by brianchris** [comment]
I appear to be on Android app version 4.2.1, although it looks like that info may no longer be needed.  Regardless of whether an option for saved story order can be implemented (easily) or not, I really appreciate both of your's assistance with this topic.  Thank you!

**Comment by dosiecki** [comment]
I can confirm that there has never been any order for saved stories other than most-recently-saved-at-top.  Adding the reverse ordering will be medium-difficult, so I'll leave this open to track it until we have time.

**Comment by dosiecki** [comment]
Finally done in #836.
