### ISSUE TITLE
Android: Images are still downloaded after stories marked as read

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#677]
See https://getsatisfaction.com/newsblur/topics/android-busy-storing-images-even-after-everything-is-marked-as-read. Not too important to do, but if this is a quick 2 minute fix, then by all means.

**Comment by dosiecki** [comment]
Yeah, if you can somehow read more quickly than the images can be fetched, it is possible to out-pace the background process.

Right now we just keep a queue of image URLs that need to be fetched.  If we wanted to double-check that a story didn't get read in the moments between enqueue and fetch, we could query the DB and re-check read status.  I think the image prefetch thread runs at a low enough priority that it shouldn't slow things down *too* much.  I will give it a whirl.

**Comment by dosiecki** [comment]
It is a bit expensive to re-check that the stories associated with a given image are still unread before each and every image, but I added some logic to check in batches.  This should interrupt all but the first few fetches after marking something read.

**Comment by samuelclay** [comment]
Awesome, I let the user know on GS.
