### ISSUE TITLE
Google reader not available for Takeout

### ISSUE THREAD

**Issue by dittaeva** [samuelclay/NewsBlur#678]
When signing up for NewsBlur on the web you're taken through a welcome guide/wizard. In step 2 you are given the option of uploading an OPML-file and Google Reader starred stories.

While people might still have their starred stories saved somewhere, and export is not available from Google Takeout anymore, and probably hasn't been since [July 15, 2013](http://www.google.com/reader/about/).

I therefore suggest you remove the «Download from Takeout» link, perhaps even removing the feature alltogether.

**Comment by samuelclay** [comment]
Thanks for writing this up! Yeah, that dialog needed some love, since I don't get all too many new importers anymore. But this now looks better.
