### ISSUE TITLE
[Feature Request] Firefox Addon (Unread Counter)

### ISSUE THREAD

**Issue by Mosrite** [samuelclay/NewsBlur#684]
I just discovered Newsblur a few weeks ago and I immediately got the premium version because I really like it. However, I am missing a Firefox addon. Just a counter that indicates if there are any unread stories would already be enough. Maybe this could be added in the long run?
Thanks for considering my suggestion!

**Comment by samuelclay** [comment]
Problem is that there are two unread counts: grey and green (unread and focus). Having that much is too wide for a plugin. Other users have made things like this for Chrome, but there's nothing official. I'll leave it to others to create this plugin, as it's a bit too niche for me to work on now unless there's significant interest.

I suggest putting feature requests like this on getsatisfaction.com/newsblur, where it can get voted on.
