### ISSUE TITLE
Is there any bugs in apps/rss_feeds/models.py set_next_scheduled_update function?

### ISSUE THREAD

**Issue by echobfy** [samuelclay/NewsBlur#685]
delta = self.next_scheduled_update - datetime.datetime.now()
I think self.next_scheduled_update should be next_scheduled_update. Help...
self.next_scheduled_update stands for last fetch time, and next_scheduled_update is the time to next fetch.

**Comment by samuelclay** [comment]
It's poorly named by me but that's checking if the new fetch schedule is already stale then schedule a fetch. It's just comparing the new value to the old value.
