### ISSUE TITLE
[Feature Request] Add option to load mobile version in story view

### ISSUE THREAD

**Issue by Mosrite** [samuelclay/NewsBlur#686]
Hey,
I think it would be cool if there was an option to load sites in story view as mobile version. On smaller screens in split view I think mobile versions would be easier to read than desktop versions.
Thanks for considering my suggestion! :)

**Comment by samuelclay** [comment]
Unfortunately this isn't possible with a browser extension. NewsBlur can't force a website to do one or the other since they are sniffing user agents.

**Comment by Mosrite** [comment]
OK, I see. But it is possible to somehow force websites to fit into the frame? On my laptop story and original view are basically useless because I cannot read the story's text without scrolling.

**Comment by samuelclay** [comment]
Can you post a screenshot? That always helps.

**Comment by Mosrite** [comment]
![newsblur](https://cloud.githubusercontent.com/assets/5235694/7650845/c36f544c-fafa-11e4-91d9-047eca6dda4f.PNG)

Sorry for taking a while, but I finally uploaded a screenshot. As you can see, the original story is loaded but not really usable. Of course, I could scroll back and forth but that would be far from convenient. It would be easier to just open the story in a new tab.

**Comment by samuelclay** [comment]
Why not just use the Text view?

**Comment by Mosrite** [comment]
There are two reasons basically:
- I'm looking for a mode that works for every article. That's why I created this issue: https://github.com/samuelclay/NewsBlur/issues/687
Text View won't work for picture heavy or video articles.
- Text View doesn't parse sources as "Spiegel Online" properly. The headline is cut out, as is the teaser text. I think, especially the teaser part is important if I want to decide quickly whether I want to read an article at all.
