### ISSUE TITLE
Android: Volume next story buttons take you to first unread, not next unread

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#692]
See https://getsatisfaction.com/newsblur/topics/volume-button-next-button-takes-you-to-first-unread-not-next. The user is correct, it should use your current position is go to the next unread in the down/forward direction before it tries the up/backwards direction.

**Comment by manderson23** [comment]
In #653 we said the volume key navigation should tie into the same navigation as the next/prev overlay. Is that not what this is doing?

**Comment by samuelclay** [comment]
So the Next Unread button is also probably doing the same thing. Try this: find a site with 10 unreads, tap on the 5th unread. The Next Unread button should take you to stories in this order: 6, 7, 8, 9, 10, 4, 3, 2, 1.

**Comment by dosiecki** [comment]
Huh.  That is how I originally had it implemented, but I changed it to the current behaviour after getting feedback that it was wrong, IIRC.  I can pretty easily change it back, though this will probably be pretty confusing for users who have experienced the current behaviour for over a year.  Thoughts?

**Comment by samuelclay** [comment]
Yeah, check it on the web. It should work that way. Any negative feedback I'd be happy to handle.

**Comment by dosiecki** [comment]
Sounds good.  I'll tweak it back in the next round of changes.
