### ISSUE TITLE
Android: Interactions and Activities view

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#693]
Just like iOS and web.

![screen shot 2015-05-21 at may 21 10 56 02 am](https://cloud.githubusercontent.com/assets/44229/7755310/fd80ae5e-ffa7-11e4-8faa-22fd118ffd52.png)
![screen shot 2015-05-21 at may 21 10 58 04 am](https://cloud.githubusercontent.com/assets/44229/7755356/477f1716-ffa8-11e4-84aa-fb5833079cfb.png)

On iOS:

![img_2798 2](https://cloud.githubusercontent.com/assets/44229/7755342/33218ac4-ffa8-11e4-9b16-bbffbd05020c.PNG)
![img_2800 2](https://cloud.githubusercontent.com/assets/44229/7755346/333b7c0e-ffa8-11e4-8722-23c1bac9dc4f.PNG)

Note that I have a couple bugs to fix on iOS. It should strip HTML on interactions, and it should be loading those icons in Activity.

**Comment by samuelclay** [comment]
See github.com/samuelclay/newsblur/tree/master/templates/reader/interactions_module.html and github.com/samuelclay/newsblur/tree/master/templates/reader/activities_module.html for all of the categories and how they should be formatted.

**Comment by manderson23** [comment]
Thanks

**Comment by manderson23** [comment]
I assume on iOS the ">" takes you to the feed/story etc?

**Comment by samuelclay** [comment]
Correct, and not only that, but it scrolls you down to the comment too.

**Comment by manderson23** [comment]
Is your preference that you can click anywhere to navigate like on the web or that there is a ">" like iOS?

**Comment by samuelclay** [comment]
Tap anywhere, since you can't tap on individual pieces.

**Comment by manderson23** [comment]
So in iOS you can't actually tap on the links? The current Android code was attempting to make each part clickable (e.g. username was clickable on comment reply) but it would simplify things if we didn't need to do that.

**Comment by samuelclay** [comment]
Nope, not at all. They're just styled that way, it actually just takes you to the comment.

**Comment by manderson23** [comment]
@dosiecki I'm looking at navigating from saved story activity details to the saved story itself.
Am I right that given the following details
```
{"category": "star",
 "user_id": 40088,
 "title": null,
 "is_new": true,
 "story_feed_id": 76,
 "content": "\u2192 How Well Can You Hear Audio Quality?", 
"with_user_id": 40088, 
"feed_id": 76, 
"time_since": "9 hours",
 "date": "2015-06-04 10:48:57.712000",
 "content_id": "http://www.npr.org/sections/therecord/2015/06/02/411473508/how-well-can-you-hear-audio-quality", 
"with_user": null}
```
we don't actually have the information required to either start the saved reading activity via an intent or find the story from the database and create a new ReadingItemFragment? And is either of these the best approach anyway?

**Comment by dosiecki** [comment]
I think maybe you could key into the cursor by searching for feedId and the story URL?  It would be *much* easier if you have the storyHash.  The entire app basically runs on storyHashes.

**Comment by manderson23** [comment]
I did think the story has would be useful. Any chance of adding this to the response @samuelclay ?

**Comment by samuelclay** [comment]
Ok, added. Note that it may be null for `comment_like` interactions. They won't be null in the future, though. So just handle the null case by not opening the link, which is fine for now, since it will only affect older interactions.

**Comment by manderson23** [comment]
When you navigate to a shared/saved story from an activity should it show that story standalone or within the list of shared/saved stories? i.e. after navigating should you be able to page through the shared/saved stories list?

**Comment by samuelclay** [comment]
Yes, it should show the context. So if it's a shared story being re-shared by somebody, go to their blurblog. If it's a reply, go to the original story's feed (or blurblog), depending on what feed id you're given.

If in doubt, check what happens on the web. You should just be able to use the feed_id (and not the story_feed_id).

**Comment by manderson23** [comment]
What do you do on iOS if the saved story doesn't exist? I see on the web that goes to the saved stories list rather than a specific story.

**Comment by samuelclay** [comment]
Yes, that would be fine.

**Comment by manderson23** [comment]
On iOS does it scroll to the specific comment or the comment section? If the specific comment what do you use to identify it? I can't see anything related to a specific comment except the content in the comment_like response.

**Comment by samuelclay** [comment]
So I have iOS scroll to the comment (you use user_id, since user's can only have a single comment) and then pulse the comment in orange. But just scrolling to the comment section would be fine if that isn't trivial.

**Comment by manderson23** [comment]
@dosiecki I'm trying to implement scrolling to the comment section and I'm wondering if you have an ideas re: the best approach. For now I'm just trying to hard code scrolling to the reading_friend_comment_header when the ReadingItemFragment is opened.

I've tried http://stackoverflow.com/questions/21930954/how-to-scroll-to-specific-view-element-inside-scrollview-by-knowing-element-id but scrolling to a position seems to be complicated by the web view loading is content changing the length of the scroll view and also the comments being loaded in a different thread too so the position changes dynamically and isn't fixed until all web/comment loading is complete.

**Comment by dosiecki** [comment]
Yeah, the thing to do would be to set a flag indicating that you eventually want to scroll down, check it after all 3-4 async loads, keep track of what has finished, and only scroll after they are all done.  I suspect that bit of code is going to be nightmareish to maintain, though, so I would only pursue it if it is absolutely critical to the UX.

**Comment by manderson23** [comment]
@samuelclay is it enough to navigate to the story for comment activities/interactions?

**Comment by samuelclay** [comment]
Sure, that would be fine. Although on iOS it's no more work to find the correct comment, as the scrolling actually happens in javascript and it's just to a specific user_id (share comment). But scrolling to the comment section in general would be super helpful.

I'm thinking about a new comment feed which aggregates all of the activity your friends have: comments and replies, and presents them with super shortened stories. It's much better on the web, but perhaps we can figure out a way to build it on mobile. It's not going to launch for quite a while, though, as I have my hands full with Turn Touch.

**Comment by dosiecki** [comment]
Scrolling down to even the top of the comments section will require a coordinated await of at least the webview load, so going all the way to the correct comment shouldn't be too much more difficult, I would hope.

I think at the bare minimum we just need to watch `onProgressChanged` in our `WebChromeClient`.  I've got a barebones impl of the helper class in my branch (for an unrelated feature), I can push it upstream as soon as we get the bugfix beta sorted.

**Comment by manderson23** [comment]
Scrolling to comments was the last feature on my list. After some final testing and #704 is merged I will open a new PR for this. 

I can look again at adding scrolling to comments in a later PR once @dosiecki changes are merged in too.

**Comment by manderson23** [comment]
@samuelclay I've just had the Android app crash due to one of your comment like interactions having ```"title": null```. Is this expected?

**Comment by samuelclay** [comment]
Shoot, I broke this two days ago. I just fixed it and I'm going to fix all of the comment_like's with missing titles in a moment.

**Comment by manderson23** [comment]
@samuelclay when you said above a user can only have a single comment does this apply across public comments, friends comments and comment replies for a single story?

**Comment by samuelclay** [comment]
Thats correct.

**Comment by samuelclay** [comment]
Friends = people you follow, public = people you don't follow (so mutual exclusion). And comments vs shares are obvious. We just don't bother showing the fourth category of public shares.

**Comment by dosiecki** [comment]
I believe that as of this Beta release, this is alive and well!

**Comment by manderson23** [comment]
I have some work in progress code to scroll to the comments section after navigating kicking around that I haven't had a chance to finish. I'll try and get back to it soon.
