### ISSUE TITLE
Android: Latest System WebView Changes Reading UX

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#700]
On devices running Android version 5.0 or greater, the system WebView component is now updated more regularly, out-of-sync with overall OS updates.  The latest update pushed out to users (43.0.2357.121) greatly changed the behaviour of HTML links within an app.

The old, desired behaviour of opening links in the user's chosen browser has been replaced by opening the link within the same WebView View within the app.  This has caused countless bugs:

* Pages not conditioned (with our custom CSS) to be viewed in-app tend not to render entirely on-screen
* Scrolling of content can be badly broken
* Back-button functionality is broken - if a link is clicked, hitting back exits the Reading activity rather than going back to the page that contained the link
* In-app browser state is not shared with the user's browser, so logins don't work, nor does history get populated
* Much JavaScript tends to be broken in a constrained app View

I've had several reports from people saying this makes the app "unusable", so pursuing a fix for this ASAP.

**Comment by samuelclay** [comment]
Wait, which reports? Are you just getting direct emails or does this show up somewhere that's not GS? Did I miss it somehow?

**Comment by dosiecki** [comment]
Just verbal reports. (I try to convert as many people to NewsBlur as possible!)

Fix is done in 245d0d4.  I am tempted to say this should go into the next prod push, as it is quite an awful experience once your 5.0+ devices get that update.

**Comment by dosiecki** [comment]
Fixed in #702.
