### ISSUE TITLE
Feature request: Adding notes to saved stories.

### ISSUE THREAD

**Issue by rattasak** [samuelclay/NewsBlur#705]
Hi, 

I'm not sure how feasible or how much work this would be, but would it be possible to add the ability to add notes to saved stories? Sometimes I save stories that have a specific thing(s) that I would like to remember about it when I come back to it later. Right now I kind of hack this feature using the tags, but it can get unwieldy if the note is long. If the notes could also be searchable that would be amazing. 

Again, not sure how feasible or how much work this would be, but it would be really handy for some use cases I think. 

Thanks.

-rattasak

**Comment by samuelclay** [comment]
Hi Rattasak, you'll want to submit feature ideas as an 'Idea' on http://getsatisfaction.com/newsblur. This bug tracker is more for tracking bugs in the code.

**Comment by samuelclay** [comment]
That being said, I think this is a great idea and I'd love it if you posted it on get satisfaction!

**Comment by rattasak** [comment]
Hi Samuel, I posted it to the GetSatisfaction site as you suggested, though
it doesn't seem to
have gained much traction as an idea with other Newsblur users so far (:

**Comment by samuelclay** [comment]
What's the URL? I'll respond on there.

**Comment by rattasak** [comment]
https://getsatisfaction.com/newsblur/topics/adding-notes-to-saved-stories

Thanks for asking!

-sak

**Comment by beedell-roke** [comment]
@samuelclay, I want this feature, so that I am able to add a URI to [`fedora-infra/bodhi/issues/5949#issuecomment-5233693859`](https://github.com/fedora-infra/bodhi/issues/5949#issuecomment-5233693859) to its cited NB entrant, in my account. However, the GetSatisfaction URI appears to be 404, now.
