### ISSUE TITLE
Android: Crash on long press -> Delete Feed for Blurblogs

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#710]
I'm happy to fix this but was wondering what the preference would be:

1. Remove the option for Blurblogs.
2. Change it to "Unfollow" and trigger that action.

**Comment by dosiecki** [comment]
Fix shouldn't be too difficult.  The code to unfollow exists via other UI paths, it likely just needs to be wired up to that menu item.

**Comment by manderson23** [comment]
OK. I'll hook it up to unfollow and change the text that is shown too.

**Comment by samuelclay** [comment]
Yep, this is what we do on web and ios.
