### ISSUE TITLE
Android: Saved story count only updates on refresh

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#714]
When you save a story and navigate back to the main activity the saved story count has not updated. This also happens when you  unsave a story.
You need to force a refresh for the count to update.

**Comment by dosiecki** [comment]
If memory serves me correctly, there should even be a TODO or two in the code noting this.  I have always left it tabled since much of the data model for starred stories is likely to change when we add support for breaking down stars by feed or tag.

**Comment by manderson23** [comment]
OK. I just happened to notice since I saved more stories when I was away last week.

**Comment by dosiecki** [comment]
Lightweight impl. done in #720.
