### ISSUE TITLE
Web: Saved story notes with highlighting

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#722]
As requested here: https://getsatisfaction.com/newsblur/topics/adding-notes-to-saved-stories

Be able to select paragraphs to highlight (hiding rest of saved story), and add notes to highlights.

**Comment by rattasak** [comment]
Thanks for putting this on the todo list Samuel (:

**Comment by samuelclay** [comment]
It was this ticket that inspired me to cleanup the outstanding issues on NewsBlur's github repo. I'm hoping to build this someday.

**Comment by samuelclay** [comment]
Another thread with a similar use case: https://getsatisfaction.com/newsblur/topics/highlight_text_in_saved_stories?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_16305396

**Comment by samuelclay** [comment]
Dupe of #1035. I'm so close to launching this but I have a bug that's been around for 2 years and I can't figure it out.

**Comment by danieljhill** [comment]
Is the bug still present? Glad to see this on the list.

**Comment by samuelclay** [comment]
Just fixed it a few days ago! I'll be launching it this week, it's all ready to go. I might silently launch it tomorrow after I stress test it a bit more.
