### ISSUE TITLE
Android: Sanity-Check CPU/Battery Usage

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#723]
As the Android app has become more full-featured over the last few years, it has definitely become something of a resource hog when doing heavy reading sessions.  Additionally, it looks like the app very aggressively held CPU resources during conectivity issues earlier this week for some user configurations.

This task is to do a basic sanity check of how we behave in these circumstances, since being a battery-killer is pretty much a cardinal sin on mobile.

**Comment by samuelclay** [comment]
Awesome, this would be great work. Also, I feel like any work spent on eating less battery shows up in perf improvements.

For the record, NewsBlur on iOS eats battery at a similar rate as active web browsing and twitter do. Nothing out of the ordinary like camera or maps/gps.

**Comment by dosiecki** [comment]
After a few weeks of tesing on 4.4.4, 5.0.1, and 5.1.1, this looks to have been a great improvement.  NewsBlur doesn't even show up on the top battery/memory users list on some of my devices anymore.  We'll obviously keep working this down whenever reasonable, but I am calling this done for the sake of the existing complaints.

**Comment by samuelclay** [comment]
Excellent. So where are we on the latest beta? I remember I chose not to submit the latest beta to the play store as it had some showstopping bugs for me.

**Comment by dosiecki** [comment]
I've got a PR incoming that fixes those and the jump-to-activity bugs coming out today.
