### ISSUE TITLE
Share bookmarklet: Error trying to share story

### ISSUE THREAD

**Issue by Kraymer** [samuelclay/NewsBlur#725]
I've got a *"Sorry, but there was an error trying to share this story.*" message when
i push the "share this story" bookmarklet button.
Browser is Chrome.

Url I'm trying to share :
https://medium.com/dan-sanchez/miyazaki-s-beautiful-antiwar-dreams-44951be1be11

**Comment by samuelclay** [comment]
Looks like they are explicitly banning third-party bookmarklet shares. They've done this sort of thing before, so it's not out of the ordinary that they stepped it up.
