### ISSUE TITLE
Organize sites: just created folder do not appear in folders list for the next move

### ISSUE THREAD

**Issue by Kraymer** [samuelclay/NewsBlur#727]
<img width="844" alt="_7_1__newsblur" src="https://cloud.githubusercontent.com/assets/84227/9290776/a05e6478-439f-11e5-94ae-9b93d9d15e8d.png">

- open *Organize sites* dialog
- select 1 feed, click *Add folder* button, enter folder name (eg "Kindle") and *Move 1 site" button
- select other feed and try to move it to newly created *Kinder* folder

=> *Kindle* folder not available in list

**Comment by samuelclay** [comment]
Awesome, thanks for the perfect bug report!
