### ISSUE TITLE
Web: Saved searches

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#729]
Similar to saved story tags, just show a list of saved searches (applied to folders/feeds) and a button to save a search. Eventually expand to iOS and android.

**Comment by samuelclay** [comment]
Still would love to build this. Not sure if before or after story notifications or oauth send to services.

**Comment by ramseyt** [comment]
Hi, any update on getting this scheduled? This would be a big help for me!

**Comment by samuelclay** [comment]
This (and notifications) are the two next features I'm building. In fact, just yesterday I sketched out saved searches on my shower notepad. (Yes, I have a waterproof shower notepad.)

**Comment by Dejal** [comment]
Hey, me too!  Shower notepads are great for those inevitable shower thoughts.  Many a feature has been planned there.

**Comment by ramseyt** [comment]
Awesome, looking forward to it!

**Comment by ramseyt** [comment]
Any update on this? It would still be super useful for me!

**Comment by samuelclay** [comment]
Hey, this shipped a few months ago: http://blog.newsblur.com/post/158925569072/saved-searches-make-it-easy-to-create-custom-feeds

**Comment by ramseyt** [comment]
Awesome thanks a ton!
