### ISSUE TITLE
Web: Clicking "Return to NewsBlur" link results on messed up recursive layout

### ISSUE THREAD

**Issue by Kraymer** [samuelclay/NewsBlur#730]
![selection_092](https://cloud.githubusercontent.com/assets/84227/9328445/fc72744c-45a8-11e5-9039-baaf382091df.png)

Click *Return to NewsBlur* link

![selection_093](https://cloud.githubusercontent.com/assets/84227/9328450/0599e37a-45a9-11e5-8733-c7987509a864.png)

**Comment by samuelclay** [comment]
Consider this an easter egg. I'm a little more worried about that 500 error you're getting from the story. Does it happen to every story or just that one?

**Comment by Kraymer** [comment]
I don't have it any more.
