### ISSUE TITLE
Web: Impossible to add comment to blurblog story

### ISSUE THREAD

**Issue by Kraymer** [samuelclay/NewsBlur#731]
Unless I miss something obvious it's impossible to add a comment unless :  
- you're OP and add a comment **at moment of posting**
- you reply to an existing comment

Noticeably, I don't see how to add a comment _a posteriori_ to my own posts.

<img width="565" alt="_20_0__newsblur" src="https://cloud.githubusercontent.com/assets/84227/9376733/39f966ae-4711-11e5-9e5f-7ea1be9e3518.png">

**Comment by samuelclay** [comment]
Yep, you've found a long standing bug. I kind of left that one in until somebody said something. Problem is that I'm not sure exactly how to expose the "edit comment" UI without adding something. It's also not something that happens very often. This can only happen after you share a story from the app and then go to your blurblog and want to add a comment. Which is a reasonable thing to do, but I'd have to build a bit of interface for it and I don't have the time now to do that for what seems to be a lower priority. 

But thanks for being the first to point this out!
