### ISSUE TITLE
Android: add preference to auto-open first unread story.

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#734]
From https://getsatisfaction.com/newsblur/topics/android-app-directly-open-the-first-story-by-opening-a-folder

We have this on the web, so why not have it on Android?

**Comment by dosiecki** [comment]
Should this only work in folders or also in individual feeds?

**Comment by samuelclay** [comment]
Works on both (as well as on blurblogs). Obviously it only finds the first unread if there is one and doesn't kick you out if it doesn't find one.

**Comment by dosiecki** [comment]
So if you tap into a feed with no unreads, does it stay on the story list or does it open the first (already-read) story?

**Comment by samuelclay** [comment]
It stays on the story list. You can double check this behavior on the web.

**Comment by dosiecki** [comment]
Sounds good.  Implementation incoming.

**Comment by dosiecki** [comment]
Done in #795
