### ISSUE TITLE
Android: reduce notifications

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#736]
There is no need for a mark read notification. On iOS we have them for saved/unsaved, mark unread, and post-share (✅ Sent to Evernote). And for displaying various errors. 

I think Android just has one extra for marking a feed as read, which we should get rid of. Any others you can think of?

**Comment by dosiecki** [comment]
Done in d396d63bd34080af93b9fe8e167f85943ba72485 and 3e44f8cb1dd78f3b963449084238472f0558d84b.  Aside from errors (which will stay), there are 2 or 3 more stragglers from the original app that I will cut after pushing some in-flight stuff today.

**Comment by dosiecki** [comment]
Handled mark-read and few others that were extremely redundant to other UI updates in #737.  All that remain are for changes that can't otherwise be confirmed visually.
