### ISSUE TITLE
Android: Tapping a Social Interaction Jumps to Wrong Story

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#739]
Virtually 100% reproducible on my personal account.  In the profile activity, tapping on social interactions such as a friend replying to my comment will almost always open some other story that I have shared, but not the correct one.

**Comment by manderson23** [comment]
@dosiecki  unless you have already started looking at this I'm happy to pick it up.

**Comment by dosiecki** [comment]
Nope, plenty bogged down with other stuff.  Happy to grab logs or debug if you need.

**Comment by manderson23** [comment]
@dosiecki is the story it navigates to sometimes the last available for the social feed given the all/unread only setting?

**Comment by dosiecki** [comment]
> is the story it navigates to sometimes the last available for the social feed given the all/unread only setting?

In the case of people replying to my own comments on my own shares from my own socialfeed, it opens a random story in their socialfeed, not one in mine.  In the case of people replying to my comments on their shares on their socialfeeds, it opens a (seemingly?) random story in their socialfeed.

One thing of note is that if I back out of the story and tap the interaction a second time, it sometimes will open the correct story.  Not always, but sometimes, which makes me think this could be a timing/coordination bug?

**Comment by manderson23** [comment]
I have an idea about why it opens the wrong feed that I need to look into further.

As for the random story one issue is that if the story hash cannot be found for that feed it will show the last story available given the all/unread and newest/oldest setting. It just uses the story hash searching that was added. Could that somehow contribute to the timing issue? e.g. if the story matching the hash isn't loaded yet it exits the search too early but by the next attempt is has been loaded and is found?

**Comment by dosiecki** [comment]
> As for the random story one issue is that if the story hash cannot be found for that feed it will show the last story available given the all/unread and newest/oldest setting. It just uses the story hash searching that was added. Could that somehow contribute to the timing issue? e.g. if the story matching the hash isn't loaded yet it exits the search too early but by the next attempt is has been loaded and is found?

Yeah, sounds about right.  Might need to hold onto the hash and re-do the search after each API-page of stories loads until it gets found, since it is somewhat unlikely to be there at first?

**Comment by samuelclay** [comment]
Yep, that's right. You'll have to find the story in the feed, which could be a few pages in. Check how it works on the web, since they work the same way.
