### ISSUE TITLE
iOS: Mark older/newest as read

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#742]
Just needs a chooser when long pressing a story title. Shouldn't be too difficult to build.

https://getsatisfaction.com/newsblur/topics/ios-mark-older-newer-as-read

**Comment by Dejal** [comment]
Is there a server API to mark older/newer stories as read, or do I need to pass in all the story hashes via -syncStoryAsRead: (/reader/mark_story_hashes_as_read)?  Seems like it should be done on the server, since the iOS app may not have loaded all of the stories yet.

**Comment by samuelclay** [comment]
Yep, this is on the server. Take a look at how the web does it with a web inspector. (I do this myself sometimes when I can't remember parameters and looking it up by diving into apps/reader/views.py is too cumbersome.)

**Comment by samuelclay** [comment]
By the way, can you read (and write) python? The backend is a great resource to look at, since it's using Django's routes and views. It's all under apps/ and you'll want to first look at the `urls.py` file to figure out the url route to the `views.py` function. It's per-app, but the only apps you'll probably ever hit are `apps/reader` (user-specific), `apps/rss_feeds` (feed-specific), and `apps/social` (blurblog/sharing).

**Comment by samuelclay** [comment]
You'll find the parameters, accepted types, and optional parameters in those views.py files. And I'm happy to add convenience methods or parameters, just let me know what you'd like to see.

**Comment by Dejal** [comment]
Thanks.  No, I'm not familiar with python, though it's easy enough to read.  I've found what I need: "/reader/mark_feed_as_read" supports multiple feeds, a cutoff timestamp, and a direction.  There's even a -markFeedsRead:cutoffDays: method that I can use as a basis (using the story timestamp and adding the direction parameter).

**Comment by samuelclay** [comment]
Bingo, yep, that's the method you'll want. There's an outstanding bug where all stories that share the demarcating story's timestamp will also get marked as read, regardless of the order. But stories with the same timestamp aren't guaranteed to be in any order, so fixing that bug is a whole bundle of work that just won't happen.

**Comment by samuelclay** [comment]
Also remember that the order of "mark newer stories as read / mark older stories as read" is dependent on the story_order used. See the web for the lead on this. We also do this correctly on Android. 

 * Up should be "newer" when in "Newest first" story order. 
 * Down should be "older" when in "Newest first" story order
 * Up should be "older" when in "Oldest first" story order.

**Comment by samuelclay** [comment]
<img width="582" alt="screen shot 2015-10-28 at oct 28 1 15 55 pm" src="https://cloud.githubusercontent.com/assets/44229/10801731/09777c96-7d76-11e5-911e-5915075467fc.png">
