### ISSUE TITLE
Android: Search for Stories

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#745]
Someone mentioned this on GetSat, and I totally agree this would be wonderful, even if only for saved stories.

**Comment by samuelclay** [comment]
Should be easy enough to implement. It's built so that all you have to do is pass a `query` parameter to the feed/river request and you get back stories just as if they were from the normal feed. So just keep local state of a query. Clear it out when leaving the feed/folder.

**Comment by dosiecki** [comment]
Working on getting all the edge cases for this right, and discovered a web UI behaviour that I found very surprising and wanted to confirm it is working as expected:  when viewing a list of stories that have been filtered by a search query, doing a mark-all-read marks the entire unfiltered feed/river, not just the filtered subset.  Intended behaviour for the apps, too, or could mark-all-read also take the corresponding query parameter so that only what is shown in the list is marked?

**Comment by samuelclay** [comment]
Ohhh, that is an interesting idea! But I don't think I'm going to support that as I don't see it being used much. It's definitely come up a few times in the support forums, but it hasn't come up for a long while.

Although it wouldn't be too hard to handle on the backend. If people want this, though, they'll have to post on the get satisfaction forum.

**Comment by dosiecki** [comment]
Sounds reasonable.

**Comment by dosiecki** [comment]
Another question: should the `query` parameter work on all rivers?  On this one, I'm not seeing any effect: `https://www.newsblur.com/social/river_stories?page=1&order=newest&read_filter=all&query=foo` (it just returns the same stories with or without the filter.

**Comment by samuelclay** [comment]
Sorry, no search on shared stories. Again, this wouldn't be too hard to build, but I just don't see much justification. And nobody has ever asked for it.

**Comment by dosiecki** [comment]
Righto.  Just making sure I was using the API correctly.  I'll ensure shared stories views don't have the search option.

**Comment by dosiecki** [comment]
In my testing, I am noticing that searches are behaving as case-sensitive. Is this intentional? Can I pass some flag or prefix/postfix some characters to the query string by default to make search insensitive?

**Comment by dosiecki** [comment]
Now I am second-guessing myself.  The first time I did this search, it didn't return results for all capitalisations of "Asus", but now that I am running it again, it is:

https://www.newsblur.com/reader/feed/308521?order=newest&f=308521&query=Asus&page=1&include_hidden=true&read_filter=all

Between doing the two searches with the "Asus" casing, I did a search with "ASUS" as the query.  Did I somehow prime an index and change the behaviour for the second search of "Asus"?

**Comment by samuelclay** [comment]
Woooah, who knows. I'm using Elasticsearch, and just getting the mappings right was a hell of a time. 

https://github.com/samuelclay/NewsBlur/blob/master/apps/search/models.py#L199-L236

And here's where I do the querying:

https://github.com/samuelclay/NewsBlur/blob/master/apps/search/models.py#L274-L280

By using the 'standard' analyzer, all terms are lowercased when searched. That's what I've read, but I believe that's true.

**Comment by dosiecki** [comment]
Implemented in #854.
