### ISSUE TITLE
'Share on NewsBlur' bookmarklet getting stucked

### ISSUE THREAD

**Issue by Kraymer** [samuelclay/NewsBlur#750]
I've had the bookmarklet not functioning for some sites (like Medium) before but it's not about that here.  
Every time i press the button now, independantly of the site content it seems, I have ``(Sharing...) ``appearing in the page tab title and then nothing, no dialog pops up.  
I disabled my Ad-blocker with no effect.

**Comment by acdha** [comment]
The problem on Medium, The Guardian, etc. is CSP: https://developer.mozilla.org/en-US/docs/Web/Security/CSP

It would be very nice if there was a simple fall-back “Share Story” form like the Instaper add button which would do all of the title/html extraction server-side and would also make a nice fallback on the sites which have JavaScript / CSS which conflicts with the current sharing bookmarklet.

**Comment by Kraymer** [comment]
My bad, it was because of *Privacy badger* extension.

**Comment by samuelclay** [comment]
Thanks for following up!
