### ISSUE TITLE
Android: issue with text selection and swiping articles

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#763]
From a user:

Steps to reproduce
1. Go to story view
2. Select text
3. Swype to next article

Expected result
Selection tool bat goes away

Actual results
Selection bar stays, can't be dismissed unless you go back to the story with the selected text

-Charlie

**Comment by dosiecki** [comment]
This is the default system behaviour for ActionModes that are not yet destroyed.  Hitting the 'back' button should always cancel the selection even if it is offscreen.  Alternatively, it will reset itself if the user swipes one more story away from the original one, or if they leave the reading view.

It is possible that we could try to work around this, but it is likely to cause a good deal of spaghetti code and only work on some devices.

**Comment by samuelclay** [comment]
Ok, glad to hear it. No need to fix this then.

**Comment by idontusenumbers** [comment]
This happens to me once every few days. The use case is you hold your finger down right before swiping or to 'catch' the stupid snappy-springy animations, and it incidentally selects the word your finger is on, throwing the text toolbar. I can confirm swiping to the next, next article gets rid of the toolbar.

Can you not just destroy the action mode when the story is swiped?

**Comment by dosiecki** [comment]
Yeah, the swipe gesture to change pages can definitely cause headaches on some touchscreens.

As I mentioned above, tapping the 'back' button a single time should always cancel the text selection, even if offscreen.

Alternatively, this is one of the reasons why we offer a few other methods of changing stories:
1. the next/back buttons at the bottom right of the story screen.
2. in the main preferences for the app, you can enable volume key navigation to change stories

Finally, I do have an outstanding task to bring our app up to spec for accessible non-touchscreen navigation, so look out for that in a future release.
