### ISSUE TITLE
Android: Intelligence Training

### ISSUE THREAD

**Issue by GitHofi** [samuelclay/NewsBlur#764]
Hi

I would like to see the Intelligence Trainer build into the Android app.
While reading news on my mobile I am missing the possibility to immediately train the stories. After reading something interesting I have to mark the story as unread and wait till I return to my desktop and then have to remember which story I wanted to train.

Thanks
Chris

**Comment by dosiecki** [comment]
Not sure if it is obvious from the existing UI, but you *can* train on story authors tags from the app.  Just tap the tag or author name while reading the story.

As for training on story title text, that is in the works and is (somewhat unclearly) captured in #192.  I'll leave this open for more clear tracking.

**Comment by GitHofi** [comment]
Thanks for the tip regarding the 'tag of the story'. Unfortunately those tags are often nonexistent or are to generic for my feeds.
Glad to hear you are working on adding training on story title text - that's what I am using extensively.

**Comment by PetrPapousek** [comment]
As far as I can tell, the "Everything from this publisher" intelligence training option available on web is not available on the Android, right?
![everything_by_this_publisher](https://cloud.githubusercontent.com/assets/3639252/11437724/46737078-94f0-11e5-9326-19f4241ee7a7.png)

**Comment by dosiecki** [comment]
Correct.  At the moment, you can train on tags and authors. I am hoping to soon add titles and whole feeds/sites.

**Comment by dosiecki** [comment]
all of this (and much more) went live in the app last month!
