### ISSUE TITLE
stuttered scrolling of articles on iOS 9.0.2

### ISSUE THREAD

**Issue by kain88-de** [samuelclay/NewsBlur#766]
Using iOS 9.0.2 I started to notice that scrolling articles is stuttering, the scrolling isn't anywhere near a smooth experience anymore (independent if text or images are displayed). Everywhere else scrolling is still smooth.

Also thanks for creating newsblur. I enjoy using it on a daily basis.

**Comment by samuelclay** [comment]
Fixed in beta 3 (4.9.3). Should be out on TestFlight either today or tomorrow. I need to blog it so I can get emails.

**Comment by kain88-de** [comment]
thanks
