### ISSUE TITLE
iOS: Implement swipe to dismiss for Safari View Controller

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#769]
I didn't realize this was even possible, but it'd be great if NewsBlur let you swipe back to close the Safari View Controller like Tweetbot 4.0.2 does.

**Comment by samuelclay** [comment]
www.stringcode.co.uk/push-pop-modal-sfsafariviewcontroller-hacking-swipe-from-edge-gesture/

**Comment by Dejal** [comment]
Only works on iPad; doesn't work on iPhone as it pushes the Safari view controller instead of presenting it (and didn't work when I tried changing that, either).  Please let me know if you want me to continue working on supporting it on iPhone, or close this issue if iPad-only is okay.

**Comment by samuelclay** [comment]
I'd be happy to push the view controller instead of presenting it modally. That's the way the in-app browser works.

**Comment by samuelclay** [comment]
But yes, this definitely needs to support iphone.

**Comment by Dejal** [comment]
Works on both iPad and iPhone now.

**Comment by nriley** [comment]
Thanks for doing this; there are a couple issues I noticed.

First, when swiping to go back from the browser, its edge does not track my finger; it's noticeably ahead of it by the time I get to the right edge of the screen.  This doesn't happen in Tweetbot so I don't think it's necessary.  You can see a comparative video here: http://sabi.net/temp/newsblur-swiping.mov

Second, when I double-tap to open a story in the Safari view, the edit menu pops up briefly.  This doesn't happen with every article but I do notice it particularly with Blogger posts.  (The story also often scrolls, but that bug predates this addition, so I'll report it elsewhere :-)  Here are some examples:

![img_1789](https://cloud.githubusercontent.com/assets/68303/10716268/63dc9294-7b09-11e5-8462-e4edd2b03b37.jpg)
![img_1788](https://cloud.githubusercontent.com/assets/68303/10716269/6761ed7e-7b09-11e5-92a6-aefd43ead9ea.jpg)

**Comment by samuelclay** [comment]
@Dejal, can we a) fix the scrolling bug when double tapping to open the original story (the story shouldn't scroll when double tapping and a gesture is enabled), and b) fix the interactive swipe gesture on the safari in app browser so that it tracks accurately to the user's finger position?

**Comment by samuelclay** [comment]
So (a) is covered in #786. So let's just fix that finger position tracking bug.

**Comment by samuelclay** [comment]
It's still a fair bit finicky for me, but we'll see if other folks notice. It works 80% of the time.

**Comment by nriley** [comment]
It's now working 0% of the time for me — I can't swipe any more either in the simulator or on a real device.

**Comment by Dejal** [comment]
Maybe it'd be easier to activate the edge gesture if the hit zone were wider.  It's 5 points wide currently; I'll double that.

**Comment by samuelclay** [comment]
We should fix it in landscape mode on iPhone.

**Comment by nriley** [comment]
OK, if I am very careful to swipe from the exact edge of the screen, it does work. It definitely seems to be more sensitive than iOS's own phone swipe to go back gesture. Increasing the area seems like a good idea.

**Comment by Dejal** [comment]
@samuelclay yes, something wacky there.  I'll re-open to fix that.

@nriley yes, it can't be as generous with the swipe-able region, as that could interfere with web navigation.  But swiping from the edge works well.

**Comment by nriley** [comment]
The finger-edge offset is still off, though consistent, and the feel of it is still a bit different compared with the native swipe gesture (or Tweetbot's version for that matter) but it's usable now.  I'll deal with it...
