### ISSUE TITLE
iOS: Crash when deleting story tags

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#770]
Probably just when going from 1 to 0.

**Comment by Dejal** [comment]
This seems similar to #724 (crash with saved stories).  Though I'm not sure how to add or delete tags; I don't see any code that changes a "story_tags" array.  What are the steps to reproduce?

**Comment by samuelclay** [comment]
When you save a story using the Save Story button at the bottom of a story, you'll see a little text box that allows you to add a new saved story tag. The 1 to 0 references a story tag that only has a single story in it. You may have to add a tag, reload feeds, then remove that tag (by unsaving the story).

**Comment by Dejal** [comment]
Ah, thanks.  But when I do anything in the user tags view popover (adding a tag, clicking on a tag), it crashes with an invalid table sections exception.  Might be a separate issue.
