### ISSUE TITLE
iOS: Phone call bar pushes Safari View controller bar down too far

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#773]
![image1](https://cloud.githubusercontent.com/assets/44229/10594319/cf5b9a3e-7680-11e5-9a6f-60973f4a5619.PNG)
![image1](https://cloud.githubusercontent.com/assets/44229/10594320/d25c028c-7680-11e5-92c3-fecdafcae31d.PNG)
![image2](https://cloud.githubusercontent.com/assets/44229/10594322/d5e93a14-7680-11e5-830e-2552ab100bee.PNG)

**Comment by Dejal** [comment]
This seems to be an OS bug; it affects other apps like Tweetbot too (and [has a Radar](https://openradar.appspot.com/22608558)).  We can't control how it appears.

So probably should close this issue, unless you want to keep it as a reminder to check for an OS fix (perhaps as a low priority issue?).

Here's Tweetbot showing the same issue:

![img_0196](https://cloud.githubusercontent.com/assets/1318849/10776069/8542b7ce-7ccb-11e5-9ef4-12db67b25ebe.jpg)

**Comment by samuelclay** [comment]
Agreed, closed
