### ISSUE TITLE
iOS: on iPad, sharing comment box is missing after first share

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#775]
From Joe Angell:

The first time I share a story it works fine. The second time, though, brings up the keyboard but does not open pane containing the multiline edit field and the button to commit the share. Killing the app and relaunching it fixes the problem. This was seen when testing on an iPad. 

- Launch NewsBlur. 
- Share any story (tap the Share button, the tap the Share button in the new pane that opens). 
- Go to on any other story. 
- Tap Share for this story. The keyboard will appear, but the edit field and related buttons do not.

The screenshot shows the keyboard is visible, but the pane to type comments and the button to commit the submission is not. 

![image1](https://cloud.githubusercontent.com/assets/44229/10615954/83c28348-7717-11e5-9ce7-04fef9b0cbda.PNG)

**Comment by Dejal** [comment]
I am unable to reproduce this.  The share view always appears for me.

**Comment by samuelclay** [comment]
No worries, we can ship with this bug. Downgrading to high.

**Comment by jangellx** [comment]
I gave it another try her, and I'm able to reliably repro it every time on iOS 9.1 with an iPad Air 2. Here are some more detailed steps:
- Luanch NewsBlur
- Go to All Stories. If you don't have any unread stories, tell it to show all stories
- Tap on any story to see it in the story pane
- Tap the Share button to open the sharing pane
- Tap cancel to close the sharing pane
- Press the home button to leave the app
- Go back into NewsBlur
- In the same story, tap the Share button again. The keyboard appears, but the share pane itself does not. There is no way to submit or cancel sharing. Killing the app and restarting it fixes the problem until you next leave the app. 

Let me know if you need any more info. Thanks.
