### ISSUE TITLE
iOS: Selected text and then going back to story titles list shows glitch

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#779]
![image1](https://cloud.githubusercontent.com/assets/44229/10616303/4bf603fc-7719-11e5-99a0-5bc121e8071f.PNG)

**Comment by Dejal** [comment]
I can reproduce this, but not having any luck fixing it.

The generally accepted (but hacky) solution seems to be:

    self.webView.userInteractionEnabled = NO;
    self.webView.userInteractionEnabled = YES;

But that doesn't work when the view is disappearing.  Also,

    [self.webView endEditing:YES];

doesn't work, either.

I'll try again later, but let me know if you have any thoughts.

**Comment by samuelclay** [comment]
We should probably be blanking out the story detail when going back to story titles anyhow, so that the old story detail doesn't flash when choosing a new story. I've tried to do this, but it's not working for some reason. Just search for 'about:blank'.

**Comment by Dejal** [comment]
Yes, I tried blanking it, but as you found, that doesn't work either.  I agree that does seem like a two-issues-with-one-fix, though, so I might try to see why that doesn't work.
