### ISSUE TITLE
iOS: Press and hold for img alt text broken on iPhone 6s

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#781]

**Comment by Dejal** [comment]
I can't reproduce this.  It seems to work:

![img_0185](https://cloud.githubusercontent.com/assets/1318849/10684840/db30b74e-7906-11e5-9e36-797722385e6e.jpg)

**Comment by acdha** [comment]
Maybd it's only a problem on the 6S Plus? On mine, using either the latest release version or the TestFlight 4.9.3, nothing appears to happen when I press on an image – no menu, highlight, etc.

**Comment by Dejal** [comment]
I don't have a 6S Plus to test on, but that screenshot is my 6, which works.  I also tried a 6S and 6S Plus in the iOS Simulator, and it works fine there.  Maybe it's specific to the feed.  Can you give me an example of a feed and story that doesn't work for you?

**Comment by acdha** [comment]
It's a problem on every feed. I notice it most on https://newsblur.com/site/2318003/xkcd.com

**Comment by Dejal** [comment]
A great example, since they often have long alt text.  But it still works for me both on my 6 and the 6s Plus simulator.  Weird.

I'm trying to think if there's some usage reason... are you trying it in the story view, or a browser view?

**Comment by acdha** [comment]
It works in the in-app browser and in-app Safari. It does not work in the Story view and, now that I tried it, neither does the normal URL menu – e.g. long-pressing on a link does nothing, but it does open normally if you just tap it.

Using the same account on the same feed on the old iPhone 4S (it's _so_ small!) which I migrated everything on the 6S+ from, the long touch works normally.

**Comment by samuelclay** [comment]
Chris, are you on iOS 9.1 or 9.0?

**Comment by acdha** [comment]
9.1 now, but it happened with 9.0.1 and 9.0.2 as well.

**Comment by samuelclay** [comment]
Since I don't know how 3d touch works, are you trying both a 3d/force touch as well as a non-3d long press? Is there any difference? What happens when you do one or the other?

**Comment by acdha** [comment]
I've tried all three, and also after disabling 3D Touch entirely in the settings (it is, to be honest, not much more than a gimmick currently).

On my iPhone 4S when I long-press there's a brief flash of a rectangular translucent bubble before the menu displays. On the 6S I either see nothing or, rarely, see that bubble but the menu doesn't display:

![file oct 23 6 01 33 pm](https://cloud.githubusercontent.com/assets/46565/10705985/5d217fd2-79b0-11e5-9bf1-d190ae081f3d.png)

On links, nothing visible happens when I long-press on them.

**Comment by nriley** [comment]
Unfortunately it seems that you need an iPhone 6s to actually see this break.  I figured this one out, and added 3D Touch support while I was at it.  (Just fixed the message to use the correct marketing buzzword in the 2nd version of the commit.)  I picked 0.75 via trial and error; I can't seem to find anywhere that the peek/pop thresholds are accessible.

**Comment by samuelclay** [comment]
Sweet, thanks to @nriley to fixing this one. Gonna go close it unless the issue pops up again (har har). Look for the fix in the upcoming beta.

**Comment by acdha** [comment]
Works perfectly in the beta – thanks @nriley!
