### ISSUE TITLE
iOS: saved stories sidebar item doesn't appear after first save

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#784]
1. Have no saved stories.
2. Save a story.
3. Go back to the main feeds list; no saved stories item.
4. Relaunch and it appears.

**Comment by samuelclay** [comment]
Few users are going to hit this, since if they have saved story tags, at least some should be populated. Moving to medium priority.

**Comment by Dejal** [comment]
I don't think we need to change anything for this; simply reloading the feeds makes it appear, which is reasonable.  Closing.
