### ISSUE TITLE
iOS: Story scrolls when double-tapping

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#786]
Double-tapping a story causes it to scroll down slightly (if scrolling is possible).  This doesn't seem to happen with two finger double-tapping.

**Comment by samuelclay** [comment]
It should run the double tap action (which is defaulted to the Text view, IIRC). What do you have the gesture set to?

**Comment by nriley** [comment]
I had tried it both with the double-tap action set to “show original text” and “open original story”.  I just tried it with the action set to "mark as unread", and it still scrolls down (in addition to doing whatever it's supposed to do).

**Comment by samuelclay** [comment]
Yeah, it shouldn't do that. Hopefully a one line fix!

**Comment by Dejal** [comment]
@nriley is this on the iPad or iPhone?  Are you double-tapping in the sidebar (on the iPad) or in the story?  I can't get it to scroll in any of those situations.

**Comment by nriley** [comment]
This is on the iPhone. I'm double-tapping in the story. I can't reproduce this in the simulator, unfortunately.  What I have here is an iPhone 5s, where it doesn't happen, and a 6s, where it does.  If it's 6s-only and neither of you have a 6s, I can try to dig into the code myself but won't have any time until Sunday.

**Comment by samuelclay** [comment]
Yeah, this happens to me as well on the iPhone 6. Double tapping the story detail view is supposed to be a customizable gesture, but by default it also scrolls the story, just like it would in Safari (when it has nowhere to zoom).
