### ISSUE TITLE
iOS: need to update for iPad Pro

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#788]
For example, the login view has a background that assumes a 1024 wide or high screen, and no doubt there are other issues elsewhere.

![simulator screen shot 2015-10-25 20 34 51](https://cloud.githubusercontent.com/assets/1318849/10720767/03e8d038-7b58-11e5-96cd-8b97f68d1c06.png)

**Comment by samuelclay** [comment]
https://twitter.com/autorelease/status/657610833917153280

**Comment by samuelclay** [comment]
<img width="629" alt="screen shot 2015-10-26 at oct 26 4 17 47 pm" src="https://cloud.githubusercontent.com/assets/44229/10745236/1d248420-7bfd-11e5-88f9-6d955283f408.png">

**Comment by samuelclay** [comment]
Not that this excuses my behavior here (*cough*). /ht @74hc595

**Comment by Dejal** [comment]
Heh. :)  It was a reasonable approach... until Apple changed the rules.
