### ISSUE TITLE
iOS: more fonts

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#791]
*[Just adding this to keep track of it, and for any followup.]*

1. Change the story detail menu popover to use a navigation controller
2. Change the font segmented control to an item that pushes a new view.
3. Add this new view with a table listing the available fonts.
4. Add the new fonts.
5. Make them work in the story web view.

**Comment by Dejal** [comment]
Actually, should leave this open until the extra fonts have been added.

**Comment by samuelclay** [comment]
The new test font doesn't seem to be loading when I tap it.

**Comment by Dejal** [comment]
Reminder on adding new fonts:

1. Add the fonts to the project resources (**Resources/fonts** subfolder).
2. Add the font filenames to the Info.plist (**"Fonts provided by application"**).
3. Add a line in `-[FontSettingsViewController viewWillAppear:]` for the font name, using the `-addBundledFontWithName:` method, in alphabetic order.

That's it!  Let me know if you have any problems.

**Comment by samuelclay** [comment]
Hah, yep, just figured all of that out before seeing this comment. I only added whitney, gotham narrow, and chronicle. We can do without Sentinel. I also removed Avenir Condensed.

**Comment by samuelclay** [comment]
Also had to add the fonts used to the copy bundles section.
