### ISSUE TITLE
Android: Visual Update for Story View Controls

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#796]
See this screenshot. It needs smaller icons, lighter text, 1px of white text shadow in vertical only, and the half tone background color.

![img_3073](https://cloud.githubusercontent.com/assets/44229/10854680/7a44d740-7efa-11e5-91ae-4b02f9cffb8c.PNG)

**Comment by dosiecki** [comment]
One thing worth considering is that we have had some requests[1] by users to move the app more towards Android's "Material" design language, specifically with regard to usability of buttons.  I can certainly see why, as the crisp visual style makes it easier to spot widgets, especially when one has been using the newest OS version for a while, and the use of standard sizes can help with muscle memory.

While I wouldn't jump into a full redesign, the set of fixed and floating buttons on the Reading view, along with the buttons at the top/bottom of the first two views would be great first candidates to bring us closer to spec.  I can very quickly mock up some designs before hitting any code if we like.

[1] https://getsatisfaction.com/newsblur/topics/android-material-design-o2wiarwg0escd

**Comment by samuelclay** [comment]
Go for it, although to be honest, the iOS app doesn't confirm to iOS's flat design, and the web app doesn't quite look like anything else.

**Comment by dosiecki** [comment]
Also going to use this task to track some lingering work on the visuals for the reading activity like the missing gradient colour at the top of stories from feeds.

**Comment by dosiecki** [comment]
implemented in #912
