### ISSUE TITLE
Getting a maximum recursion depth error due to misconfigured redis logs

### ISSUE THREAD

**Issue by sbilly** [samuelclay/NewsBlur#797]
After import my OPML file and refresh page.It continuous occurred.

https://app.getsentry.com/share/group/34393035342e3931323535313532/

**Comment by samuelclay** [comment]
I'm not getting this on prod or dev, so you're going to have to ensure that you're running the same python version and pyredis version. What version of python do you have? You'll want 2.7.x. Also, make sure you are using all of the versions from requirements.txt
