### ISSUE TITLE
iOS: rotating iPad when viewing the new Safari view controller breaks NewsBlur layout on return

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#798]
In portrait mode on the iPad (Air 2, iOS 9.1) I'm looking at a story in NewsBlur, and I want to see the rest in the embedded Safari view controller. I tap the compass and Safari appears, but the content is easier to view in landscape mode. I rotate the iPad, and when I'm finished I hit Done to return leave Safari. Unfortunately, it seems NewsBlur didn't get the rotate message and is now displaying the story views incorrectly. 

![image](https://cloud.githubusercontent.com/assets/3717537/10868849/a137399a-8069-11e5-85b5-e681783dd809.png)

The above image shows the problem after closing Safari.  Steps:
- Make sure NewsBlur is set to use the new Safari view controller
- Hold the iPad in Portrait mode
- Go to Global Shared and view a story
- Tap the compass to open the Safari view
- Rotate the iPad to landscape mode
- Tap the done button to return to NewsBlur. Notice the layout seems to be shrunk as though it is still in portrait mode, even though we're in landscape mode. 

Thanks again

**Comment by jangellx** [comment]
Update: after posting this bug, I rotated the iPad or portrait, went back to NewsBlur and found the app like this:

![image](https://cloud.githubusercontent.com/assets/3717537/10868878/8ce3249e-806a-11e5-9108-72d0f091fe53.png)

So I guess once it gets into this state it has trouble getting back out of it.

**Comment by samuelclay** [comment]
Thanks! This has been fixed in another issue.
