### ISSUE TITLE
iOS: selecting a story in All Stories doesn't always show the story

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#801]
On iPad, selecting a story in the root All Stories list on the right-hand-side sometimes doesn't select and thus show the story after the feed list is shown in the sidebar.

**Comment by samuelclay** [comment]
Haven't seen this myself. I wonder how this bug happens, since tapping on a story copies the entire story collection over to the all site stories view.

**Comment by Dejal** [comment]
[Here's a video](http://www.dejal.com/files/temp/AllStories.mov). Happens on a device, too.

**Comment by samuelclay** [comment]
It's possible I broke something about the story finding logic. Does this happen every time or only after reading another feed and returning back to the dashboard?

**Comment by Dejal** [comment]
Not all the time, but often on first launch, or sporadic after that.  I haven't noticed a consistent pattern yet.  I'll investigate later.

**Comment by Dejal** [comment]
I haven't been able to reproduce this for a while, so I'm closing it.

**Comment by nriley** [comment]
This is timing sensitive (https://github.com/samuelclay/NewsBlur/blob/c9e02c600be5f28e83131f64f458ec462a5ad5e0/clients/ios/Classes/FeedDetailViewController.m#L1131) which explains why it magically disappeared.  Not sure why the check for animation in progress is there, but removing it fixes the problem.

**Comment by nriley** [comment]
Can we reopen this bug? From reviewing blame it looks like there was a race condition this check was trying to resolve, but it then no longer tries to load the try feed if it fails; perhaps we could just defer it?  @samuelclay, it looks like you added the code back in 2013 — any recollections?

Thanks.

**Comment by samuelclay** [comment]
Ok, that should do it.
