### ISSUE TITLE
iOS: Leaving and returning to the app on an iPad while viewing stories causes the panes to be incorrectly aligned

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#804]
iOS 9.1, iPad Air 2.  It seems that you need to be at least 3 stories down to trigger this behavior.  The further down you are, the worse the problem, I think.

- Launch NewsBlur
- Go to All Stories
- Tap the first story
- Click the Home button to leave the app
- Go back to NewsBlur (you have to wait a couple seconds, it seems; if you go back too fast the error won't show, presumably because NewsBlur hasn't shut down yet?).  Everything looks fine.

- Tap on the third story down
- Click the Home button
- After a few seconds, go back to NewsBlur.  The story panes is partially scrolled.

Repeat these steps, but for the fifth or sixth story down.  The story pane is in another different position.

![img_0051](https://cloud.githubusercontent.com/assets/3717537/10923129/35f989c2-824d-11e5-9d04-2a82b03f7f4e.jpg)

![img_0052](https://cloud.githubusercontent.com/assets/3717537/10923128/35f21ee4-824d-11e5-8cd9-61d0b3efce07.jpg)

**Comment by Dejal** [comment]
This was fixed yesterday for the next release (#774).
