### ISSUE TITLE
iOS: 3d Touch actions

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#806]
Ideas: add feed, all site stories, search (jumps to search bar in all site stories).

Thanks to https://twitter.com/sciriously/status/662068522722312193

**Comment by samuelclay** [comment]
Useful to know (from https://twitter.com/sciriously/status/662103571966521344)

"I use 3D-T on TweetBot (search), camera (straight to video), iBooks (specific book), Swarm (check in), Pinterest (trending)"

**Comment by Dejal** [comment]
[Click for a demo movie.](http://www.dejal.com/files/temp/force-touch.mov)

You can try it yourself in the iOS Simulator via the [SBShortcutMenuSimulator](https://github.com/DeskConnect/SBShortcutMenuSimulator) project.

**Comment by samuelclay** [comment]
Hoooooly crap this is amazing.

**Comment by samuelclay** [comment]
Can we have "Add Site" automatically focus the text box?

**Comment by samuelclay** [comment]
Or better yet, have it start on the folder selector (this should be true of any opening of the Add Site dialog. When opening, just immediately press the folder selector).
<img width="621" alt="screen shot 2015-11-05 at nov 5 6 02 58 pm" src="https://cloud.githubusercontent.com/assets/44229/10987374/8b3de4dc-83e7-11e5-83eb-82fc51d0861b.png">
