### ISSUE TITLE
iOS: search doesn't do anything for a free account

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#807]
Searching a feed doesn't do anything, presumably because my account (Dejal) is not a premium one.  Perhaps you could upgrade that account to premium so I can test those features.  I have a second account that can remain free, to test those.

For free accounts, should either hide the search box, since it doesn't work, or perhaps better display a message that this a premium feature when the user tries to use it (upsell opportunity!).

**Comment by samuelclay** [comment]
Yes, let's reuse the imagery from the feed list when Focus is selected but there are no unread stories.

If you want to use a test account, apple/california makes for a great user/pass test account.

**Comment by samuelclay** [comment]
Upgraded, btw. :+1:

**Comment by samuelclay** [comment]
<img width="621" alt="screen shot 2015-11-05 at nov 5 6 01 52 pm" src="https://cloud.githubusercontent.com/assets/44229/10987342/4ddcb9ce-83e7-11e5-8fbf-2c4100d4ba15.png">
