### ISSUE TITLE
iOS: add site tweaks

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#808]
@samuelclay commented in #806:

> ... have it start on the folder selector (this should be true of any opening of the Add Site dialog. When opening, just immediately press the folder selector).

Sure.  I could tighten up the size of the popover, too; there's a lot of empty space there.

Though I've never been a fan of pickers.  I realize you were trying to replicate the popup menu in the web app, but I'd think a checkmark table would look nicer, and be easier to use.  Let me know if you'd prefer that too.

**Comment by samuelclay** [comment]
I love that popover, that's why it's so big. But sure, go ahead and trim it down.

**Comment by samuelclay** [comment]
Another change I'd like to see is to not automatically add the site when the autocomplete option is chosen. This is just a single line that needs to be commented out.

**Comment by Dejal** [comment]
I'm not entirely sure what you mean by that last comment.  Entering some search text in the site field and clicking a site in the autocomplete table just puts the URL in the site field; it doesn't add it.

**Comment by samuelclay** [comment]
Looks like I already made that change. Awesome! 

OK, I'm going to add the new fonts and submit this to the App Store later today.

**Comment by Dejal** [comment]
Excellent.  We can close this, then.
