### ISSUE TITLE
iOS: exception when viewing only unread with no unread

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#815]
If there are no unread stories in a feed, and it is displayed only showing unread, the app crashes with this exception:

    -[NSNull rangeOfCharacterFromSet:]: unrecognized selector sent to instance 0x104fd4af0
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
        reason: '-[NSNull rangeOfCharacterFromSet:]: unrecognized selector sent to
        instance 0x104fd4af0'

**Comment by samuelclay** [comment]
Fixed in f8ed69056e913a7324b9b365feac14c4a8a4db0f.
