### ISSUE TITLE
iOS: Add another [+] row to the bottom of the saved story tags list

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#819]
In story detail, not on the feed list. Here's the support ticket: https://getsatisfaction.com/newsblur/topics/feature-request-add-tag-plus-sign-at-each-end-of-the-list. Would be handy, although we shouldn't show it for fewer than 10 tags.

**Comment by Dejal** [comment]
I think a better solution would be to move the [+] item out of the list, so it remains pinned at the top.

**Comment by samuelclay** [comment]
You're right, it'd work better as the section header.
