### ISSUE TITLE
iOS: improve iPad Pro split view support

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#820]
The sidebar is too wide in landscape split view on iPad Pro.  Should use the narrow class in this situation.

**Comment by Dejal** [comment]
I've been thinking about this.  It's not an easy problem, as the app currently doesn't use auto-layout (for most views) and size classes.

Possible solutions:

1. Take this opportunity to modernize the main views to auto-layout, size classes, and probably storyboards.  Not quite as bad as it might seem at first, since only the feeds, feed detail, page and story views would need to be changed, not the various popovers.  But those are still fairly major views.

2. Detect Split View use and hide the UISplitViewController and switch to an iPhone-like view hierarchy.  Ideally would need to restore the current view and scroll position.

3. Fake it by resizing the UISplitViewController's left pane to the available width (effectively making the right pane off-screen), and push the right pane onto the left one like on iPhone.

Or maybe some other solution.  Any thoughts on this?

The first solution is no doubt the best, since it'd solve the issue, future-proof the app, and probably reduce code and bugs.  It'd also be the most work, but work that probably needs to be done sometime.

**Comment by Dejal** [comment]
A 4th option would be when in Split View multitasking to simply make the left pane narrower, and perhaps omit the thumbnails, and reduce the margins on the story in the right pane.  That'd be the easiest option, and might be good enough.

**Comment by samuelclay** [comment]
Auto layout should be easy enough to build in, since I already converted the only difficult layout (the story traversal buttons) to auto layout. The other screens are just big table views.

**Comment by Dejal** [comment]
Alright, I'll do option 1, modernizing to auto-layout and size classes.

**Comment by Dejal** [comment]
I added a "5.1" branch for this yesterday.  I'll add subsequent non-fix changes to that branch.  You can merge it into master when you're ready to do the 5.1 release.  You could merge @nriley's changes into the 5.1 branch, too.

The split view support works well; when in split view, it uses the iPhone-style views, then switches back to the normal iPad style when leaving split view.  I'll close this now, but feel free to re-open if you find any issues.

**Comment by nriley** [comment]
Both of the #816 issues I reported were actually issues here; there were some remaining references to a UIPopoverController which was never set.  See pull request above.

**Comment by nriley** [comment]
Argh, I think my lack of iOS experience is showing. That last commit breaks "Train This Story" — it seems that the completion block never triggers in that case.  I can work around it by just triggering the block immediately if the presented view controller is a UINavigationController, but this seems wrong.  (You can trigger the crash it was trying to fix by reverting that commit, launching the app and typing 'a' twice.)

**Comment by nriley** [comment]
My fixes are merged into the 5.1 branch now.
