### ISSUE TITLE
Web: Show muted sites in All Sites

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#824]
https://getsatisfaction.com/newsblur/topics/improved-muted-sites?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Bpage%5D=1#reply_16330796

**Comment by manderson23** [comment]
+1 for this.

I was thinking today about muting some feeds before I go on holiday for a few weeks and the fact the I can't do that on Android. I was thinking that showing the muted feeds in All Sites on Android would be useful too.

**Comment by samuelclay** [comment]
This feature should show muted feeds in the All Sites filter, but with a red "OFF" instead of an unread count.

**Comment by samuelclay** [comment]
This ones for you @Splike

**Comment by Splike** [comment]
Thanks! Been looking forward to this! It will also be more coherent as Android already has this feature.

I've created a ticket to also have it be implemented in iOS, so it's coherent on all platforms (#1325).

**Comment by samuelclay** [comment]
Just launched. It's a beautiful change and I'm glad it's now live.

**Comment by Splike** [comment]
@samuelclay, I went to update my dark theme to support this new mute icon, and I noticed that it displays when the "Saved" stories view is chosen. It doesn't really make sense to display it in this view

![muted_saved](https://user-images.githubusercontent.com/7159527/84582997-bf845380-adf3-11ea-9091-81a099b08104.png)

**Comment by samuelclay** [comment]
I'm going to keep it in as I think a muted site should be marked as such everywhere it's shown. Thanks for the css update! I'm nearly done with my changes. I've changed a good amount but retained much of your extremely helpful work.
