### ISSUE TITLE
iOS: Scrolling doesn't work on every third story

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#827]
https://getsatisfaction.com/newsblur/topics/scrolling-gets-stuck-in-ios-version-5-01

Not sure what's causing it and I can't repro it.

**Comment by samuelclay** [comment]
Just added a deferred call to turn scrolling back on right when it's disabled. Still handles #786 properly.

**Comment by mrjbq7** [comment]
I'm not sure if related, but I've had so many problems scrolling in the new version (5.0 and later).  Sometimes it scrolls left to right when I mean to scroll up and down.  Sometimes it doesn't scroll down (perhaps this bug fixes it).

This might not be the best place for a generic "scrolling doesn't work very well" report, but...
