### ISSUE TITLE
Log in don't work and sign in redirect to non ssl 

### ISSUE THREAD

**Issue by FromBabylon** [samuelclay/NewsBlur#829]
When I reach newsblur instance through ssl it works. 
When i sign in it redirects to a non ssl connection (which was blocked on my server so I had to allow port 80) and I'm then logged in. However when I try to log in with the user I just regitered it just redirect to home page and will not log in. And I can re-register the same user.

So two problems : 
 - Why does log in redirect to non ssl connection
 - I can't re log with a previously registered user and can re-register it.

**Comment by samuelclay** [comment]
Yes, this is correct. If you want to remain on https, you need to set that as a preference. The reason for this is because NewsBlur pulls in a lot of http data, and for an optimal experience you need to also be on http.
