### ISSUE TITLE
Android: Keypad UX

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#837]
Was pointed out to me that some of the Android UI can't be completely navigated and used via keyboard/keypad due to focus and selection display issues.  This is not only a nice-to-have feature, this is the interface that is used by accessibility apps such as eye trackers and integrated joysticks for disabled users.

A surprising amount of the UI does already work if you focus via tap or mouse, we just need to iron out how to move from pane to pane in a sensible way.

**Comment by dosiecki** [comment]
Also discovered today this this is a blocker for supporting devices with hardware keys to scroll, since using the hardware key unavoidably pops us into key UX mode, which causes some ugly movement issues.

**Comment by carbin** [comment]
The BlackBerry Priv has a physical keyboard with capacitive keys so you can swipe up and down on the keyboard to scroll. In the NewsBlur app this works for the feed list but not for the story view. I think it's related to this issue.

**Comment by dosiecki** [comment]
Yeah, I should be clear - this is known to be broken in story view on all devices, and only partially working in the story list and feed list.  Just to set some expectations, this is going to be more of a long-term goal than a quick fix.  The way Android handles keyboard or keypad inputs is changing rapidly with newer versions of the OS and the story view in particular is somewhat out of our control, as we let the OS render story content and it steals keyboard control from us.  I have some ideas around how to make this work a bit better when we refresh the button UI on the story view.  I will ping this issue/task whenever there are changes that might merit some new testing and evaluation.
