### ISSUE TITLE
Backend: Many Common Embeds Broken

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#838]
Since many types of media embed (twitter, instagram, flickr, imgur, etc) have switched to using a specially-named DIV that triggers some javascript to load the actual content, many stories that consist mostly of these embeds (for example, a blog post about a series of tweets) show up and uselessly empty.  It seems that many RSS feeds strip out the required script tags for some reason, breaking the original content.  It would be fairly cheap/easy to re-enhance the story HTML with these missing tags if we see any of the well-known DIV names and fix the broken content and would really save our users the time and headache of leaving the app and having to load a whole web page.

**Comment by samuelclay** [comment]
Hmm, we have this problem on iOS and on the web. I think a server-side fix would be more appropriate.

**Comment by dosiecki** [comment]
I did one quick experiment where I had the story view scan a story for any `twitter-tweet` attribute and if I find it, I tack on a `<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>` at the end before pushing to the UI.  Worked a treat.

**Comment by samuelclay** [comment]
Ok, what I need to do is make this happen on the backend. Would you mind testing if instagram also works similarly? If all I need to do is add a script to the end of a story if it contains a string then I can add that this week.

**Comment by dosiecki** [comment]
Will give it a poke when I get back to my build env. (note to self: Looks like the magic string is `instagram-media` and the script should be something like `<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>`)

**Comment by dosiecki** [comment]
Okay, confirmed that replacing the stripped-out scripts at the end of the story body works just fine for Twitter and Instagram embeds.  It seems, however, that imgur embeds get even more mangled by content platforms than just having their scripts stripped, so until I find a feed that doesn't totally wreck them, I can't test.

Here are my search keys and the tags I append before the end of the body:

key | tag
--- | ---
`twitter-tweet` | `<script id="twitter-wjs" type="text/javascript" async defer src="http://platform.twitter.com/widgets.js"></script>`
`instagram-media` | `<script async defer src="http://platform.instagram.com/en_US/embeds.js"></script>`
`imgur-embed-pub` | `<script async src="http://s.imgur.com/min/embed.js" charset="utf-8"></script>`

The script tags are exactly as prescribed by the sites, though they might still work in more simplified forms.

**Comment by samuelclay** [comment]
I added instagram, but do you have any example feeds/stories for imgur and twitter?

**Comment by samuelclay** [comment]
9420924c1d51d7e6ba62d8ae48f5960adeab2407

**Comment by dosiecki** [comment]
I see instagram posts sporadically throughout lots of tumblr feeds.  Here is a random one where the most-recent post is an IG video embed:

https://www.newsblur.com/site/3652990/

And here is another (you'll need to go a dozen or so stories in, probably) that often uses both styles of Instagram embed that work and that don't work:

https://www.newsblur.com/site/3844191/

**Comment by samuelclay** [comment]
Looks like that second one has a twitter embed that looks to be working now.

**Comment by samuelclay** [comment]
Instagrams do too. Excellent!

**Comment by samuelclay** [comment]
Note that the feed needs to be insta-fetched (or automatically fetched) for the stories to be updated. Top feed is five hours old, so an insta-fetch fixed the images.

**Comment by dosiecki** [comment]
Very nice!  I imagine this will save me (everyone?) a ton of time popping in and out of browsers from time to time.

**Comment by samuelclay** [comment]
That's the hope. However, I can verify that for whatever reason, it isn't automatically working on iOS.

**Comment by dosiecki** [comment]
I know that back in the day, in order to get some other non-stripped embeds working, I had to ensure the HTML viewer component had all of the following enabled:
* javascript
* HTML5 local/dom storage
* file/cache access
Also had to ensure that the CSS overrides we were doing didn't restrict the dynamic divs or blockquotes from expanding when their scripts finally ran.

**Comment by samuelclay** [comment]
It's because I'm using scheme-less URIs.

//platform.twitter.com/widgets.js becomes file://platform.twitter.com/widgets.js. I would specify https, but Safari didn't let the embed happen due to mismatching schemes.

**Comment by dosiecki** [comment]
ahh, yeah, listed the tags in the table with the scheme included because some versions and configurations of the Android webview had similar issues.

**Comment by samuelclay** [comment]
Ok, moved to https. Works on iOS now. Will try and blog about this tomorrow. I should go find an imgur example too.

**Comment by samuelclay** [comment]
Looks like Android is doing something funky and clipping the embeds. See this story from Coding Horror. 
![Uploading 2015-12-10 19.06.31.png…]()

**Comment by samuelclay** [comment]
And this Instagram embed on Mission Mission.
![2015-12-10 19 09 12](https://cloud.githubusercontent.com/assets/44229/11725431/846b900c-9f2e-11e5-8988-3c8cbb4d362c.png)

**Comment by dosiecki** [comment]
See the note in #846, which contains the patch that prepared the Android app for these changes.

**Comment by samuelclay** [comment]
Ahh, sorry about that. I hadn't cleared my github inbox yet. I was prepping for a blog post, which it looks like I can still publish today. Thanks!

**Comment by samuelclay** [comment]
Blogged: http://blog.newsblur.com/post/134937976476/better-embeds-for-twitter-instagram-and-imgur

**Comment by dosiecki** [comment]
Nice.  If that Beta looks stable after a day, we can push it up to Prod whenever you like.  It contains quite a few fixes along with the embed tweaks.
