### ISSUE TITLE
iOS: Can't scroll horizontally after ~10th article

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#842]
Reported here: https://getsatisfaction.com/newsblur/topics/navigation-issues-on-ios-9-newsblur-app-iphone-5#reply_16396451

The offending commit appears to be b756e7c.  I don't understand why this code was deleted in the commit, but restoring it fixes the problem.

```patch
diff --git a/clients/ios/Classes/StoryPageControl.m b/clients/ios/Classes/StoryPageControl.m
index 42f0b8d..0916557 100644
--- a/clients/ios/Classes/StoryPageControl.m
+++ b/clients/ios/Classes/StoryPageControl.m
@@ -598,6 +598,9 @@
         [pageController clearStory];
     }
     
+    if (!suppressRedraw) {
+        [self resizeScrollView];
+    }
     [self setTextButton];
     [self.loadingIndicator stopAnimating];
     self.circularProgressView.hidden = NO;
```

**Comment by samuelclay** [comment]
Thanks for finding this one. I cut a bit too much out when working on rotation bugs. There aren't any on iPhone anymore, but the iPad still has some if you rotate while in the original story view.
