### ISSUE TITLE
iOS: Swiping between stories sometimes gets stuck

### ISSUE THREAD

**Issue by jalsk** [samuelclay/NewsBlur#849]
I typically use the NewsBlur iOS app by refreshing my feeds, clicking on "All stories" with the filter of oldest first and unread only selected, and then start swiping side to side to navigate between the stories. Recently I've run into an issue where occasionally I swipe the story to the left to go to the next story and the story gets "stuck". I can see the next story when it feels like I'm trying to pull the new story onto the screen, but I can't get it to come. Hitting the next story button seems to resolve the issue, but it is still a little annoying.

More specific repro steps (some of it may be irrelevant to the bug, but I'm including it for the sake of completeness):
1. Refresh feeds
2. Click on all stories
3. Ensure story filter set to unread only, oldest first
4. Begin swiping from the right side of the screen to the left to advance to the next story
5. After some number of successful swipes (maybe 10 or so?), one story will seem to get "stuck" where I'm unable to swipe it to the side. 

At this point, I can either press the next button to advance or back out to the list of stories, click on the latest story, and begin advancing by swiping side to side again.  

The story pulls to the side as though it is going to advance properly, but it feels like it has more gravity than other stories so refuses to advance (much like when you're scrolling to the top of a list on iOS and it is clear that pulling more won't actually make it go further).

I'm running the iPhone 6S Plus (64GB) on T-Mobile on iOS 9.2, although I also noticed this issue on 9.1. The app store tells me I'm running NewsBlur app version 5.0.2. If there's a debug build I can run that would let you get logs to help debug this, I'd be happy to do so. Also please let me know if you need any more information, I'd be happy to provide it! Love the app and service, long-time premium member (since Google Reader so rudely kicked me off!)

**Comment by samuelclay** [comment]
Thanks for reporting this so thoroughly. This has been fixed and submitted to the App Store earlier this week. Should be approved sometime next week.
