### ISSUE TITLE
Desktop Ticker

### ISSUE THREAD

**Issue by alexec** [samuelclay/NewsBlur#857]
Hi,

I love Newsblur, and I'll love it more if I has a news ticker.

Alex

**Comment by samuelclay** [comment]
If you'd like to see something like this get built it'll have to be a third-party extension or app. It would be great, but could possible use better backend notification support. I'm going to close this ticket until I commit to building something like this. 

If you want other folks to vote this up, head to getsatisfaction.com/newsblur and post this as an 'Idea'. I'd love to talk about it there.
