### ISSUE TITLE
iOS: Mark older/newer stories as read

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#858]
Like on web and android. Long-pressing a story should give you three options: mark newer/older as read (stories above line, dependent on story order),  mark older/newer (stories below line), and send story to...

**Comment by Dejal** [comment]
I already did that; long press on the left side, around the unread dot.  Long press on the right side (story title etc) shows the share sheet.

**Comment by Dejal** [comment]
Though if you prefer, I could combine them, so long pressing anywhere on the cell shows the existing options plus the Send Story To... option to show the share sheet.  An extra step, but perhaps more discoverable.

**Comment by samuelclay** [comment]
Oh shoot you did. I checked and didn't see it. Yes, we should combine them, as it's not very discoverable.

**Comment by Dejal** [comment]
Will do.

**Comment by Dejal** [comment]
This was done a while ago, so I'll close it.
