### ISSUE TITLE
Android: Adjustable Text Size for Lists

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#861]
The range of DPI values we're seeing in the wild across devices is getting wider and wider, making it hard to pick a correct font size for feed lists and story lists and story metadata.  We've now got compelling examples where our chosen size is both too small to read and too large to fit much on screen.  We should consider adding a text size chooser for the rest of the app, not just story reading.

**Comment by samuelclay** [comment]
Yes I agree. I have two sizers for web and iOS: feed and story list, and story detail.

**Comment by dosiecki** [comment]
done in #930
