### ISSUE TITLE
Backend: User-specific newsblur.com email address to convert newsletters into RSS

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#862]
From https://getsatisfaction.com/newsblur/topics/directing-email-newsletters-into-newsblur.

Need to figure out if it needs a big dialog with stats. Probably, as that would be ideal. Use mailgun to handle addresses.

**Comment by Daniel15** [comment]
Pretty sure you can close this now (http://blog.newsblur.com/post/146752875548/newsletters-in-your-newsblur). Thanks for the awesome feature! :smile:

**Comment by samuelclay** [comment]
Thanks for reminding me.
