### ISSUE TITLE
iOS: “All Sites” button disappears from feed detail view when returning from in-app Safari on iPad with stories on bottom

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#864]
Before:

<img width="688" alt="before" src="https://cloud.githubusercontent.com/assets/68303/12537450/a37ccd12-c28d-11e5-878f-7f925456df4d.png">

After:

<img width="688" alt="after" src="https://cloud.githubusercontent.com/assets/68303/12537451/a96b8772-c28d-11e5-92df-933db100ac12.png">

I spent an hour or so tracing through code trying to figure this one out but didn't have much luck, sorry.  You can work around it by dragging the divider to the bottom (and back up, if desired).

**Comment by samuelclay** [comment]
I'm thinking about having @Dejal rewrite the iPad's master detail navigation controller to allow better three pane support, but that would kill this vertical view. David, how hard would it be to rewrite the iPad's split pane view and turn it into a fully featured three column nav that also handles this style of nav?

**Comment by nriley** [comment]
I use that view all the time with the iPad in portrait, as above. Everything is too narrow with the story list on the left. Wonder if it could be made less janky though.

**Comment by Dejal** [comment]
I haven't spent any time investigating, but I think it'd be feasible to support the feeds sidebar plus the vertical story & feed detail views.  It'd work okay narrower.  Though we might only want to do that when in landscape or on an iPad Pro.

**Comment by nriley** [comment]
How about a slide-in panel like iOS Mail in portrait orientation?  I'd trade the horizontal split bar for that.  Really I just want to be able to have full-width stories in portrait on iPad.

**Comment by Dejal** [comment]
That could be an option, though personally I dislike that UI style.

**Comment by nriley** [comment]
Hey, if you can preserve the current view, that's fine too. :-)  Was just trying to offer a compromise.
