### ISSUE TITLE
Android: Crash when mark folder read selected for Global or All Shared Stories

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#866]
While testing changes for #856 I came across these crashes.

e.g
```
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
   at java.util.ArrayList.get(ArrayList.java:310)
   at com.newsblur.database.FolderListAdapter.getGroup(FolderListAdapter.java:233)
   at com.newsblur.fragment.FolderListFragment.onContextItemSelected(FolderListFragment.java:261)
```
@dosiecki is "mark forlder as read" meant to be supported here? I''m pretty much finished with the confirmation changes but would be happy to add this in.

**Comment by dosiecki** [comment]
Yeah, marking folders via context holds is certainly supported and works fine in my most recent build.  We'll need to look into whether that is a regression or an edge case with your account.

**Comment by manderson23** [comment]
OK. I didn't immediately think from the stack trace it was my changes but I'll pick it up and fix.

**Comment by dosiecki** [comment]
That code does tend to be a bit touchy due to the oversimplified way we handle pseudo-folders via constant offsets.  If the bug looks transient, don't stress it too much, since I am rewriting the way that class indexes groups and children in order to support reading of grouped stars.
