### ISSUE TITLE
Android: search breaks when query includes a space

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#868]
Searching for anything with a space in it causes the search function to spin forever.

**Comment by samuelclay** [comment]
Also, once I hit a "null" bug, I can't continue to search.

**Comment by samuelclay** [comment]
Actually, it's not a null stories bug at all. It's searching for anything with a space in it.

**Comment by dosiecki** [comment]
Hmm, looks like our HTTP lib isn't escaping out queries quite right.  Let me forcibly encode these and see if it helps.

**Comment by dosiecki** [comment]
> Also, once I hit a "null" bug, I can't continue to search.

I'm not certain what a "null bug" is. Can you give detailed steps to reproduce this?

**Comment by dosiecki** [comment]
Fixed the issue with special chars.

What should the exact wording of the custom zero-stories message be?  Are there any other circumstances in the app where a custom zero-stories message should be used?

**Comment by samuelclay** [comment]
Nah, don't worry about the custom message. No stories works just fine. Thanks for fixing the space bug! I'm going to release it as 7.0.1 immediately so I can blog it.

**Comment by samuelclay** [comment]
(immediately as in as soon as I get the PR for the fix).

**Comment by dosiecki** [comment]
Fixed in #869
