### ISSUE TITLE
Android: swap positions of search and mark read button

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#873]
See https://getsatisfaction.com/newsblur/topics/android-swap-positioning-of-mark-all-as-read-and-search-buttons

**Comment by dosiecki** [comment]
The only gotcha here is that Android draws action bar buttons as a stack
out from right to left, in priority order. The most important buttons have
to be on the left, generally speaking. Thus, in order to make MAAR move to
the right of search, it means MAAR is less important and will be bumped off
the bar and into overflow before search on smaller screens. I judged MAAR
most important, so it is in a position to more likely be shown.

**Comment by samuelclay** [comment]
Is there a way to cheat a bit? Do you know if a button is knocked off? If you can find out, then swap positions so MAAR is first, otherwise make it second.

**Comment by dosiecki** [comment]
Did a bit of digging, and there isn't any above-board way around the order being defined all at once.  There might be some way to just not populate the menu at all until runtime, measure the screen, guesstimate what would fit, and then populate it in the preferred order.

That, however, has a code smell that reeks a mile away.  If we are truly unhappy with the default system menu behaviour, I think we should prefer just blowing away the system actionbar and replace the whole thing with something of our own (like we did for the actionbars in the feed list activity).  Of course, that flexibility comes with all the same pitfalls of what we did on the feed list w.r.t. needing to write some custom code, and potentially defeating accessibility features.

A third, cheaper option would be to force-draw the actionbar icons the way we want them.  If there isn't really room for both, it will start eating into the space used by the feed incon and feed title, potentially clipping either or both.

**Comment by samuelclay** [comment]
I'm fine with eating away at the title. Let's do the cheaper option by just force drawing those two icons.

**Comment by dosiecki** [comment]
Per a discussion we had elsewhere, we have a good motivation to roll our own title/menu bar for the story list just like we did with the feed list.  That will give us the flexibility to implement this just as we like.

**Comment by dosiecki** [comment]
This has been out in the wild for so long, I fear switching locations would be incredibly risky and we haven't had recurring complaints about ordering.  If we ever decide to re-do the story list menuing system, it will probably be a bigger overhaul than just this, to avoid confusion.
