### ISSUE TITLE
Android: reduce share/save button icon size

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#877]
Looks like this on my new Samsung S5:

![2016-02-09 00 37 07](https://cloud.githubusercontent.com/assets/44229/12904282/31133a0c-ce83-11e5-869e-ebefb9442480.png)

Should look more like this:

![2016-02-08 16 46 15](https://cloud.githubusercontent.com/assets/44229/12904368/039c846a-ce84-11e5-981a-7daee3df9da6.png)

Also, can we switch the button colors to the two-tone colors above? #ECEDE9 to #E5E6E2, text in #B0B2AB.

Lastly, can we reduce the next/previous button sizes a bit to match iOS? They are too large right now for their purpose.

**Comment by samuelclay** [comment]
Oh, can we also add the feed gradient bar to the top of stories? It's there with the feed title when reading by folder. But notice that it's the smaller size (without text, but still about 12px in height) while reading an individual feed? This mirrors the web. All stories should have a feed gradient bar at top, visible text depending on feed/folder.

**Comment by dosiecki** [comment]
I am already tracking this in #796.  All the buttons on the Reading screen need a pass for consistency with the NewsBlur style and Android UX guidelines.  It is definitely in the works once blocking stability/hyperuser issues are finished up.

One thing that will eventually become a huge help is vector sources for the NewsBlur icons.  Any format I can easily open in Gimp or the like will do fine.

**Comment by dosiecki** [comment]
> Oh, can we also add the feed gradient bar to the top of stories? It's there with the feed title when reading by folder. But notice that it's the smaller size (without text, but still about 12px in height) while reading an individual feed? This mirrors the web. All stories should have a feed gradient bar at top, visible text depending on feed/folder.

We can put whatever we like below the actionbar without much fuss.  Just need a matrix of what should show in which story list types, how big it should be, and whether it should be fixed to the top or scroll with the story.  Changing out the actionbar is a bit more work (since it is system-provided), but is also feasible.  Definitely open a new, detailed issue for this if you like.

**Comment by samuelclay** [comment]
The feed gradient can move with the story. On iOS it is fixed, except it moves with the story if you pull down.

And oh my god, I just realized that the originals have never been in the repo because I added "originals/" to .gitignore because the original page server used the same folder name. Use 'media/img/originals/assets.psd'.

**Comment by samuelclay** [comment]
As for heights, just follow the relative sizes on iOS. Icons should be just a hair taller than their text.

**Comment by dosiecki** [comment]
Going to keep tracking this in existing issue #796.
