### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 4.7.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [samuelclay/NewsBlur#880]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 4.7.1.

**Comment by samuelclay** [comment]
I'm confused, what are you looking for?

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/repository/browse/?fdid=com.newsblur  

A changelog is part of any good project.  https://en.wikipedia.org/wiki/Changelog

**Comment by samuelclay** [comment]
We publish blog posts and a new features feed that acts as a changelog. We don't provide changes in a  changelog format though.

**Comment by locutis-of-borg-1999** [comment]
Well *I* didn't invent the whole, distributed revision control, source code management (SCM) scheme.  

But, it has evolved the way it has,  for goid reasons.  

*IF* it existed, in standards compliant format, you could simply have used:  https://github.com/samuelclay/NewsBlur/releases
