### ISSUE TITLE
iOS: Remove the white shadow from the top taskbar icons

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#885]
I checked the image assets and the white shadow isn't there, so iOS must be helpfully adding them.

**Comment by Dejal** [comment]
Actually, the white shadow under the activity, mark unread, settings, etc icons are in the image assets.

I could edit them out, but if you have source images, you could do it more easily and cleanly.

Here's an example, with a red background added to highlight it:

![screen shot 2016-02-29 at 21 37 13](https://cloud.githubusercontent.com/assets/1318849/13418697/ab6333e8-df2c-11e5-98c8-b13e6ff6577f.png)

(Personally, I don't think the shadow is too glaring even on the Dark theme, though it does stand out a bit.)

**Comment by samuelclay** [comment]
I checked the interactions button, but I checked the one in the web repo and not iOS. Looks like iOS just needs a new set of icons made. I'll get that done.
