### ISSUE TITLE
Android: Interactions/activities disappear on rotation

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#891]
After loading your profile if you rotate your devices the interactions/activities disappear.

I assume the appropriate state isn't being saved/restored.

**Comment by dosiecki** [comment]
Yeah, it looks like the profile Activity circumvents the sync & storage system used by the rest of the app and directly invokes the API cilent for data that are pushed straight to the UI.  Not necessarily a bad low-overhead design for a lesser-used Activity, but we'll need to rely on other tricks to get persistence. Freezing/Thawing from a bundle might be sufficient?

**Comment by dosiecki** [comment]
fixed in #893
