### ISSUE TITLE
iOS: Saved Stories tab with All/Unread/Focus

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#897]
Saved stories by feed, showing the saved count per feed in blue (same as the unread counts for saved stories). This exists on the web.

Adding `read_filter=starred` will get you the stories, per-feed. 

The counts are in `starred_counts` from /reader/feeds?flat=true. It is two parts merged:

```
...
{
    "count": 1,
    "feed_address": null,
    "feed_id": 5077457,
    "tag": null
},
{
    "count": 1,
    "feed_address": null,
    "feed_id": 97100,
    "tag": null
},
{
    "count": 5,
    "feed_address": "http://www.newsblur.com/reader/starred_rss/13/db0d7a788724/art",
    "feed_id": null,
    "tag": "Art"
},
{
    "count": 3,
    "feed_address": "http://www.newsblur.com/reader/starred_rss/13/db0d7a788724/",
    "feed_id": null,
    "tag": "being human"
},
...
```

The top two are the feed counts, bottom two are the tag counts. Why I merged the two I don't know but it's easy to separate them.

**Comment by Dejal** [comment]
Done.  I used a hacked graphic for the Saved button, so you'll want to replace that.  There are two images; the icon and name for iPhone and iPad landscape (unread_blue.png), and just the icon for iPad portrait (unread_blue_icn.png), since that is too narrow to fit all of the labels.

**Comment by Dejal** [comment]
Looks like this one has already been completed, so could be closed?

**Comment by samuelclay** [comment]
Yep, good catch.
