### ISSUE TITLE
Android: Missing fleuron at bottom of story titles list

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#903]
What it looks like now: 
![2016-04-05 03 47 40](https://cloud.githubusercontent.com/assets/44229/14270799/96b97b10-faa6-11e5-86bd-736a41119104.png)

Here's the fleuron:
![2016-04-04 20 49 13](https://cloud.githubusercontent.com/assets/44229/14270813/ba2df24c-faa6-11e5-8c78-beebbf56b63c.png)

**Comment by samuelclay** [comment]
While here, let's change the background color to match iOS. The white is too bright.

Also, do we have a ticket for the story image previews?

**Comment by dosiecki** [comment]
> Also, do we have a ticket for the story image previews? 

Created #904

**Comment by dosiecki** [comment]
Just to be clear, by 'fleuron' do you mean the little monochrome NewsBlur logo that demarks the end of a story list?

**Comment by samuelclay** [comment]
Correct. It's labeledl fleuron.png in the repo.

**Comment by samuelclay** [comment]
By the way, I'd love to see story thumbnails next. I can see them in this screenshot and I'd think they'd look great on Android as well. Obviously needs a preference for those who want the extra horizontal space for text.

**Comment by dosiecki** [comment]
>I'm not seeing these at the bottom of story title lists. I'm reading by folder and the last story doesn't budge from the bottom of the screen. 

Very odd.  Both the resource and the code to use it are in HEAD:

https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/res/drawable/fleuron.png
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/fragment/ItemListFragment.java#L173

Does your build process need an additional nudge to pick up new resource artifacts?  Maybe try a full nuke and rebuild?

**Comment by manderson23** [comment]
I've just pulled these changes and noticed that the bottom of the fleuron circle seems to be clipped?

**Comment by dosiecki** [comment]
> I've just pulled these changes and noticed that the bottom of the fleuron circle seems to be clipped? 

Yeah, I meant to ask about that.  The source PNG from the iOS tree was like that.

**Comment by samuelclay** [comment]
Looks fine to me on my S5. Releasing as 4.10.0b1.

**Comment by manderson23** [comment]
On Tue, 5 Jul 2016 21:48 Samuel Clay, <notifications@github.com> wrote:

> Looks fine to me on my S5. Releasing as 4.10.0b1.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/samuelclay/NewsBlur/issues/903#issuecomment-230598456>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABm0ofcpo2uUBSu85rhFRXu49qau-d95ks5qSsMygaJpZM4H_uHX>
> .
>

You can see it clipped on the Nexus 4.

**Comment by dosiecki** [comment]
This was the source image I stole from the iOS versions.  If there is a cleaner one without the bottom row of pixels missing, it would be easy to swap in.

https://github.com/samuelclay/NewsBlur/blob/master/clients/ios/Resources/fleuron%402x.png

**Comment by samuelclay** [comment]
Added new fleurons (and an original PSD if you want a different size).

**Comment by dosiecki** [comment]
done in #930

**Comment by manderson23** [comment]
Should the fleuron always be visible? When I navigate into a folder/feed for the first time it appears after the orange progress indicators. If I then go back out to the main view and then into a feed/folder I have previously viewed the fleuron isn't visible.

**Comment by dosiecki** [comment]
No. The fleuron should only appear when the app believes that there is no
way to get more stories, either because the API has indicated such or
because the app is offline.

If you are on the latest HEAD build and seeing it before or during loading,
please do post any repro details and an associated debug log.

**Comment by manderson23** [comment]
This is what I observered

1. Open app and wait for offline sync to complete
2. Press a feed to enter the list
3. The fleuron appears after the loading indicators have dissappeared
4. Go back to the feed list
5. Press the same feed as step 2 to enter the list again
6. No loading occurs and the fleuron isn't visible.

**Comment by dosiecki** [comment]
The fleuron should only show up if the sync service believes that the API has indicated that the feed or folder being viewed is out of stories:

https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/fragment/ItemListFragment.java#L173

This is tracked via a flag for each feed or folder that is set high when the API returns a zero-length list of stories for said feed or folder:

https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java#L677

I would suggest enabling verbose API logging to see what sequence of responses is causing this behaviour.
