### ISSUE TITLE
Android: Visual Update for State Toggle

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#908]
Update the all/unread/focus/saved toggle that appears under the feed list.  Includes updating to new icons, better formatting, and tweaks to fit on all screen sizes.

**Comment by dosiecki** [comment]
implemented in #912

**Comment by manderson23** [comment]
I've noticed an inconsistency between the colours on the circles in the navbar and the colours used in the toggle now.

The navbar has a grey circle for unread and a green circle for focus. Whereas the toggle now uses grey for focus instead of green.

Should the circles be consistent?

**Comment by samuelclay** [comment]
That's OK. It comes from the fact that on iOS, toolbars can't have color. They just need to be different. Also, I think it looks better in grey than it does using the unread bullet color.

**Comment by dosiecki** [comment]
Though I don't mind the look (the aesthetic of assets going monochrome when
in the toolbar is pretty consistent on many modern platforms), I have had
this same question in my head. It looks like they are similarly mismatched
on iOS from the screenshots I have seen, and Web still uses green / grey.
This would be rather simple to switch out, we just need to decide which is
desirable.

**Comment by samuelclay** [comment]
The web should probably change.
