### ISSUE TITLE
iOS: Mangled layout restoring app in landscape on iPad with stories on bottom

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#913]
![img_1717](https://cloud.githubusercontent.com/assets/68303/14995304/f7465014-1128-11e6-9b9b-d4ef1207da5e.JPG)

https://getsatisfaction.com/newsblur/topics/white-screen-if-i-exit-and-return-to-app

**Comment by samuelclay** [comment]
Repro steps: - Switch to landscape.
- Launch NewsBlur.
- Go into a story view.

Let's get this fixed for a patch release.

**Comment by Dejal** [comment]
I had a look at this tonight, and traced it as far as the `-layoutDashboardScreen` and `-layoutFeedDetailScreen` calls in `-[NBContainerViewController viewWillTransitionToSize:withTransitionCoordinator:]`.  This is called twice when in the background, to rotate to portrait and back to landscape to capture static images of the screen for the app switcher.

I haven't figured out a solution yet.  I can avoid the layout issue, but if the user rotates the device while in the background, the layout is messed up in a different way.

I'll continue working on this sometime tomorrow.

**Comment by samuelclay** [comment]
Submitted as v6.0.2.
