### ISSUE TITLE
Android: Custom server preference

### ISSUE THREAD

**Issue by Nekmo** [samuelclay/NewsBlur#921]
I just got NewsBlur install on my server but I can not see how to define the url of my server in Android application.

**Comment by dosiecki** [comment]
The Android app can be found in this repo, here:  https://github.com/samuelclay/NewsBlur/tree/master/clients/android/NewsBlur

The file where the API endpoint is defined can be found here:  https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java

**Comment by Nekmo** [comment]
Do I really need to modify the application for this? Is this a bad joke?

**Comment by samuelclay** [comment]
We should add a preference for defining a Custom Server. We have this on iOS.

**Comment by cedricpim** [comment]
Hi @samuelclay, any ideas on when this might be implemented? Or is there any android apps that would support NewsBlur with a custom server?

**Comment by samuelclay** [comment]
Hey @dosiecki, would this be easy to add?

**Comment by samuelclay** [comment]
I see referenced on #938 that this will have a login screen element. Don't bother adding a custom server to the login screen. Just add a preference. The user can login to NewsBlur first to make the domain switch.

**Comment by dosiecki** [comment]
On 29 December 2016 15:49:17 GMT-08:00, Samuel Clay <notifications@github.com> wrote:
>I see referenced on #938 that this will have a login screen element.
>Don't bother adding a custom server to the login screen. Just add a
>preference. The user can login to NewsBlur first to make the domain
>switch.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/samuelclay/NewsBlur/issues/921#issuecomment-269711629

Will the cookie received from the official server work with others? I figured that the login call that retrieves it needed to be to the same endpoint that would be hit by calls after changing it.

**Comment by samuelclay** [comment]
It's a local preference, so it would discard the cookie when connecting to a new server. I see your point in that if you can't login on your server then you're SOL because you can no longer access preferences. But they can reinstall the app. Not the best fix, but for somebody who is running their own server weren't not going to be doing custom UI work to support that beyond exposing the preference. Not yet anyhow.

**Comment by dosiecki** [comment]
The way the app is designed, the only time we attempt to acquire a cookie is on that login screen.  Discarding the cookie would just dump the user back to login and also reset state and preferences, including the custom endpoint.  Honestly, it will be much easier to add a quick field to the login screen to allow for a custom server. (prefs are, weirdly, sometimes more complex than a simple text field at the start)

**Comment by dosiecki** [comment]
implemented in #979 and now available in prod.
