### ISSUE TITLE
iPad: Locking iPad can lose story view, aborting AirPlay of videos

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#924]
I subscribe to a number of YouTube channels through NewsBlur.  I'll commonly Save stories containing videos to watch later on my iPad, streaming them to my AppleTV.

The problem is that the iPad will automatically lock after 5 minutes.  That's fine, since it's still playing on the TV through AirPlay.  The problem is that if the story is far enough down the Saved list (>20 stories down; I'm not sure of the exact value), when the iPad locks the story view is destroyed.  This of course cancels AirPlay, which means I now have to unlock my iPad, tap on a different story (because that story is already selected, even though the story view is empty), then tap back on the story I wanted, hit Play, and seek forward to where I think I was last time.

It gets pretty annoying.  It's actually been happening for a long time now, but I only recently figured out what was going on.

You can reproduce the disappearing story view without using AirPlay, and without playing a video:
- Launch NewsBlur
- Save 40+ stories
- Go to your saved stories
- Select the first story (it seems you have to do this first)
- Scroll down and select a story
- Hit the home button or lock the iPad
- Unlock the iPad, or just go back into NewsBlur
- Notice that the Story View is now empty.  If you were playing a video when the iPad was locked, it would stop playing.

Unfortunately, this isn't as deterministic as I'd like.  I had to do it a few times, selecting a story, locking, unlocking, selecting another story, locking, unlocking, etc. until it gave me the issue.  Of course it feels like it does it every time when I'm trying to watch a video over AirPlay.

Screenshot attached, but it's not very impressive, since it looks exactly the same as it does when you first go into the Saved list with no story selected.

Thanks!

![img_0109](https://cloud.githubusercontent.com/assets/3717537/16093396/b8fac422-3309-11e6-8f7a-a1ce37e50c42.jpg)

**Comment by jangellx** [comment]
Thanks!  I have the new version of the app, and the good news is that the story pane is indeed fixed to stay open.  Unfortunately, for some reason the video playback via AirPlay still stops sometimes when the iPad goes to sleep (it happened to my this morning).  I have no idea why, though; it's not deterministic enough to provide useful steps for.

**Comment by Dejal** [comment]
iOS can kill background apps if it needs memory for other apps.  Which might include other apps launched in the background while asleep.  That might be causing it.  If you go back into NewsBlur when AirPlay stops, is it still showing the story, or does it bounce back to the top level (indicating a fresh launch)?

I'm not sure what else could cause this.  If you can figure out any way to reproduce the issue or any more details, let us know.

**Comment by jangellx** [comment]
It's still showing the story on unlock.  However, it's no longer showing it playing.  I mean, it has the thumbnail image form the YouTube video and the red "play" button in the middle, as opposed to a video player showing paused video.

Come to think of it, I remember some odd times where the iPad would lock and video playback would stop, but when I unlocked it the story and the video player was showing paused video, and it automatically resumed on unlock.  I have no idea what trips one behavior or the other.

If I figure it out, I'll be sure to let you know.  Thanks again!

**Comment by jangellx** [comment]
Got some more info:  It seems that now whenever the iPad auto-locks, AirPlay stops.  So, every time, which means it should be easy to reproduce:

- Set your iPad to go to sleep in 1 minute
- Start playing a video in NewsBlur over AirPlay to an AppleTV
- Wait for the iPad to lock
- AirPlay stops.

Unlocking the iPad brings me back to the story I was on, but as I mentioned previously it just shows the video thumbnail with the white arrow on a red rounded box, not the iOS "this video is paused" thing.  Meaning, it looks like it's not playing the video anymore.  I have to hit play and seek back to where I was.

At least it's consistent now; hopefully that will help figure out what's going on.  Thanks

**Comment by Dejal** [comment]
Thanks for the additional info.  I'll re-open the issue.

**Comment by jangellx** [comment]
Another possibly useful detail is that I've noticed that sometimes when I unlock the device, the Story pane is empty for a very brief period before being refilled with the story pane.  This implies that the the Story view is being destroyed when the device locks... maybe?

Thanks again
