### ISSUE TITLE
Homepage: Lastpass compatability

### ISSUE THREAD

**Issue by brendan-r** [samuelclay/NewsBlur#925]
Hello there,

Firstly, thank you for Newsblur!

I have a feature request for the homepage: Lastpass compatibility.

Currently, while the username and password fields are recognized as such by Lastpass, clicking the autofill menus in the text fields does not populate them. I'm afraid I can't figure out exactly why this is the case. Newsblur is the only site where I've seen this behavior.

It's still possible to log in by typing/copying a username from the Lastpass browser extension, it's just slightly more mousework.

**Comment by brechmos** [comment]
This seems to work these days (worked for me on Mac/Chrome).  Lastpass has done a lot of upgrades in the past year.

**Comment by brendan-r** [comment]
And I tend to use Firefox these days! Closing.

**Comment by samuelclay** [comment]
Sweet, sorry for sitting on this but I'm glad it works.
