### ISSUE TITLE
[iOS][10.0 beta][iPad Air] Themes causing crashes

### ISSUE THREAD

**Issue by kb1ibt** [samuelclay/NewsBlur#926]
When using any theme other than default, selecting stories or trying to flow through folder trees in the app will crash. I ran it through XCode and it gives the following error: 
`CIColor not defined for the UIColor UIExtendedGrayColorSpace 0.666667 1; need to first convert colorspace.'`

I'll try to dig deeper through the code to see where that is being called from to backtrace it.

**Comment by kb1ibt** [comment]
another example of a crash causing event is clicking on the arrow to expand a collapsed folder.

**Comment by kb1ibt** [comment]
This issue does not impact my iPhone 6s Plus, only my iPad

**Comment by kb1ibt** [comment]
This issue persists in iOS10 beta2.

**Comment by kb1ibt** [comment]
this issue hasn't been occurring in quite a while, just this ticket hadn't been updated

**Comment by samuelclay** [comment]
Thanks for staying on top of it! I fix every bug I can find, so it's likely this was addressed. I also have a nice big update coming out in the next week or wo.
