### ISSUE TITLE
[iOS][10.0 beta] Pull to refresh doesn't work in some cases

### ISSUE THREAD

**Issue by kb1ibt** [samuelclay/NewsBlur#927]
Folder view does not pull down, when all folders are collapsed.
I have a small enough number of top level folders so when they are collapsed you cannot drag the view down to trigger the pull to refresh. However when I expand some of the folders enough that it now is taller than the screen height then the pull to refresh can be used.

**Comment by kb1ibt** [comment]
This issue continues to be a problem in iOS10 beta2

**Comment by nriley** [comment]
Might be a good opportunity to move to a standard `UIRefreshControl`.  I've been meaning to add refresh ability to other lists for a long time so you don't have to go back to the feed list.

**Comment by Dejal** [comment]
Fixed for #945.
