### ISSUE TITLE
Rotating iPhone while viewing story in "in-app Safari" exits Safari

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#929]
If you're reading a story in the in-app Safari view, then rotate the iPhone, it jumps back to the Story view instead of staying in the now-rotated Safari view.

- Launch NewsBlur on an iPhone (6s Plus here)
- In Settings, choose "in-app Safari" as your browser
- Look at a story
- Tap the Safari icon to show the story in in-app Safari
- Rotate the iPhone into Landscape orientation
- Safari view rotates, then slides off screen and you're returned to the story view.

This is mostly annoying if you were part way down the web page and rotated the iPhone (accidentally or on purpose), and now you have to both open the Safari view again and scroll back to where you were.

Unrelatedly, it might be useful to have a "go back to the safari view" button from the main page.  I've noticed that if I have, say, an embedded video (or an annoying auto-play ad) or something playing in the Safari view that if I leave it and go back to the Story view, that video it keeps playing with no obvious way to stop it (i.e.: you can hear the audio, and presumably it's using CPU time and bandwidth).  It seems like the Safari view should be killed/paused/whatever when it is closed.  I can open a separate issue for this if you like.

Thanks!

**Comment by samuelclay** [comment]
Looks like a regression on rotation causes the story to redraw.
