### ISSUE TITLE
Web: Mute a folder from folder menu

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#932]
I think it might be useful to be able to mute feeds at the folder level.

For example I have a Java folder and I'd like to mute all feeds within that folder if I'm away for a few weeks. It would be much better if I didn't have to go through all feeds in the folder.

**Comment by nriley** [comment]
This is possible now — just click on the folder title (or tap on iOS) in Mute Sites and all the feeds within it will mute/unmute.

**Comment by manderson23** [comment]
@nriley sorry I was looking for it in the folder menu popup menu (like you can for feeds). Would it be useful there @samuelclay ?

**Comment by samuelclay** [comment]
Yes, I agree it would be useful in the menu. I just added it as a menu item to individual feeds not too long ago.

**Comment by samuelclay** [comment]
I'm leaving this only accessible in the Organizer, which allows you to do this. But it's a slow process and the Organizer/Mute Feeds dialog are better for giving users an indication that this will take a little while.
