### ISSUE TITLE
Android: Support muted feeds

### ISSUE THREAD

**Issue by manderson23** [samuelclay/NewsBlur#933]
Add support for mute/unmute as follows:
- Menu option within a feed/folder view to mute/unmute
- Long press menu option for a feed/folder to mute/unmute
- Show muted feeds in all sites view (like #824 suggests) perhaps with a mute icon where the count would normally be?

Any feedback/suggestions @dosiecki @samuelclay

**Comment by manderson23** [comment]
A few questions.

1. Does Feed.active map to the muted state?
2. Are there API end points for mute/unmute of a feed?

**Comment by dosiecki** [comment]
My only context on this is that, about a year back, there was a task to ensure that if a feed's `active` field was set low, it is totally ignored upon receipt and is never even allowed into the DB.  See:
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java#L460

However, there are some vestiges of a plan to support display and manipulation of them in the system.  For instance, we have domain fields and DB bindings for it:
https://github.com/samuelclay/NewsBlur/blob/master/clients/android/NewsBlur/src/com/newsblur/domain/Feed.java#L21

**Comment by samuelclay** [comment]
Sounds good to me. I suppose web and iOS should show muted sites in All Stories as well.

**Comment by manderson23** [comment]
Is there an API end point I can call to mute or unmute a feed by feed ID?

**Comment by samuelclay** [comment]
You have to pass back the entire folder_feeds collection to save_feed_chooser.
