### ISSUE TITLE
Web: Redirect http to https on newsblur.com

### ISSUE THREAD

**Issue by akarambir** [samuelclay/NewsBlur#934]
I just realized today that newsblur.com allow now-secure http connections. Is there a specific reason for this? We should redirect/force https connections.

I understand that it is not related to code-base here and totally business/product decision.

**Comment by samuelclay** [comment]
Yep, there's a healthy number of users who want to be able to load http and https sites in the Story view, and if they are on https, they can't read a bunch of sites. For them it is not important to have protected communication. For those who want it, an https-only NewsBlur is easily usable.
