### ISSUE TITLE
Android: Rename "Send Full Story" or use Text view

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#936]
See https://getsatisfaction.com/newsblur/topics/android-send-full-story-to-doesnt-send-full-story. I'd be happy with either, but I agree that it shouldn't say Full Story unless it's the Text view. Perhaps make this conditional based on whether or not the Text view has been loaded for the story. Full Story when yes, "Story" when just the regular feed content.

**Comment by dosiecki** [comment]
fixed in #938
