### ISSUE TITLE
iOS: "No unread stories" message showing up in Saved stories view

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#939]
Screenshot says it all.
![img_0061](https://cloud.githubusercontent.com/assets/44229/17415407/9b14c1ea-5a3e-11e6-9963-42a145e4324c.PNG)

**Comment by Dejal** [comment]
Can you reproduce this? I can't, and can't see any obvious issues in the code.

**Comment by samuelclay** [comment]
I believe this was fixed. I mean it had to be by now. The way to check it to mark everything as read and then switch to Saved view.

**Comment by Dejal** [comment]
Looks fixed.
