### ISSUE TITLE
Support for MathML/LaTeX markup

### ISSUE THREAD

**Issue by jrr45** [samuelclay/NewsBlur#948]
Many scientific websites use a mix of MathML and LaTeX markup in titles and articles, (such as arXiv) adding support for these formats would greatly improve readability of articles.  The MathJax library (Apache license) would probably be an easy/fast way to do this.

**Comment by samuelclay** [comment]
Got any feed examples? I remember this request from like four years ago and still think about it. But I want multiple examples first, since this may be a bit tricky to implement so that it has no impact on other users.

**Comment by san-bil** [comment]
I'd go premium if the latex and mathjax rendering were a bit more consistant...

e.g. articles/feeds
https://mathematix.wordpress.com/2017/12/19/interchangeability-of-infimum-in-risk-measures/
https://terrytao.wordpress.com/2017/11/09/continuous-approximations-to-arithmetic-functions/
https://jeremykun.com/2017/11/08/binary-search-on-graphs/

It looks like tex is somehow 2-stage progressively rendered by the original page in the browser, but newsblur is only getting the first stage of the render. It's pretty uncomfortable reading at Quake-3 resolution for a long period of time.

jax example here (just doesn't get rendered...):
http://blog.echen.me/2017/05/30/exploring-lstms/

**Comment by samuelclay** [comment]
The top link looks like this to me:

![screen shot 2018-01-08 at jan 8 1 27 56 pm](https://user-images.githubusercontent.com/44229/34693254-c42d0a68-f477-11e7-94ee-b24e0e8303bd.png)

**Comment by samuelclay** [comment]
I need to know a bit more, since I don't want to include a 67KB library that very few people will use. Which formats are dominant and which of the formats that MathJax supports do you want?
