### ISSUE TITLE
Android: Quick theme switch

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#949]
On iOS we added a quick theme switch to the prefs menu. Can we do something similar on Android so a user can switch b/w light and dark without having to go into preferences?

![2016-09-12 17 33 04](https://cloud.githubusercontent.com/assets/44229/18457599/0d125994-790f-11e6-9ad4-7bbfb8ae8e3a.png)

**Comment by dosiecki** [comment]
Very much doable.  Just requires some custome code to break out of the system menu framework, but nothing too crazy.

**Comment by dosiecki** [comment]
#1049 has a basic implementation of this in place.  Android has made it progressively more difficult to get super-custom menus to behave well on all devices, so it is, for now, in the stock menu style.  However, in practice, it is still much snappier to switch themes on the fly and now requires the same number of taps as the iOS design.

Let me know if the circular icons are critical enough that we should invest the time in rewriting the whole menu from scratch.
