### ISSUE TITLE
iOS 10: Feed and Story title font size doesn't change when bold (unread)

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#950]
![2016-09-13 15 41 35](https://cloud.githubusercontent.com/assets/44229/18494021/9c9dc648-79c8-11e6-9cca-17623c6cd4ad.png)

**Comment by Dejal** [comment]
Want me to take a look at this while I'm here?  Let me know of any other issues or changes you'd like, too.

**Comment by samuelclay** [comment]
I'm looking around and can't find anything else wrong, so I think this would be it. Folks have had the beta for a couple months and have let me know that this was happening, so the rest sounds solid.
