### ISSUE TITLE
iOS:  Can't scroll feeds list in iOS 10 (iPhone and iPad)

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#951]
In NewsBlur 6.0.4 and iOS 10 (both iPhone and iPad), you can't scroll the feeds list anymore.  This also means that you can't drag to reload stories (you have to kill the app to force that).  The stories list scrolls fine, as does the story view pane.

I'd provide more detail, but that's not really much else to it -- simply tap and drag on the feeds list and notice that it doesn't scroll.

Thanks!

**Comment by Dejal** [comment]
This was fixed yesterday for the next release.

**Comment by jangellx** [comment]
Excellent -- thanks!  I was wondering if I should have just waited a bit; figured you would have found this pretty quickly once iOS 10 was out, but I figured it couldn't hurt, just in case...

**Comment by nriley** [comment]
This may also be a bit hardware specific — scrolling worked fine on my iPhone 6S but not on my old iPad Air.  In any case this should be fixed for everyone!

**Comment by jangellx** [comment]
I should have mentioned my hardware -- iPhone 6s Plus and iPad Air 2, not of which showed this issue.  Quite interesting that it's hardware specific.

Thanks again!

**Comment by samuelclay** [comment]
It's happens when the table view's content is shorter than the window. So you need to collapse all of your folders or carry 0 unreads with you to reproduce it.

**Comment by nriley** [comment]
Sorry yeah, I had figured that out a few months ago and forgot!

--Nicholas
