### ISSUE TITLE
opml import should check for duplicates

### ISSUE THREAD

**Issue by alanz** [samuelclay/NewsBlur#957]
I just switched to newsblur from feedly. 

Some time back I had signed up for newblur and imported my then feed list.

I just re-imported the current list into newblur (feedly.com is operational again, I was able to export as OPML)

But now the original feeds have been duplicated. 

So perhaps check if the feed already exists when doing an OPML import.

**Comment by samuelclay** [comment]
It does this, but if you move folders then it duplicates into the new folder. The Organizer (Manager > Organizer) should help you make quick work of the dupes, but I'd be interested to see a screenshot of the feed list to see exactly how it duped (sub folders can be tricky sometimes).

**Comment by alanz** [comment]
They were all at the same level, but I just checked the opml file and realised the feed URLs are actually different.

E.g.

```xml
<outline htmlUrl="http://ewn.co.za" text="Eyewitness News | Latest News" title="Eyewitness News | Latest News" type="rss" version="RSS" xmlUrl="http://ewn.co.za/RSS%20Feeds/Latest%20News" />
<outline htmlUrl="http://ewn.co.za" text="Eyewitness News | Latest News" title="Eyewitness News | Latest News" type="rss" version="RSS" xmlUrl="http://ewn.co.za/en/RSS%20Feeds/Latest%20News.aspx" />
```
