### ISSUE TITLE
Regression: `If-None-Match:`/`If-Modified-Since` headers for caching isn’t sent by feed fetcher

### ISSUE THREAD

**Issue by Aeyoun** [samuelclay/NewsBlur#959]
1. Subscribe to https://www.newsblur.com/site/6462590/feed-request-headers-echoed
2. Force update the feed
3. Force update the feed again
4. Look at the newest feed entry’s content message for a `If-None-Match` and `If-Modified-Since` headers.

No `If-None-Match` header is sent (and thus not echoed by this test feed). Breaks Newsblur’s RFC 3229+feed implementation. This is not fixed by pull request #958, but that pull request hides the `A-IM: feed` header when there is no `If-None-Match` header to go with it.

No `If-Modified-Since` header is sent, forcing servers to return the entire feed instead of a simple 304 Not Modified response.

I found [some evidence](https://blog.flameeyes.eu/2013/03/why-you-should-care-about-your-http-implementation/) that this used to work in the past.

**Comment by Aeyoun** [comment]
Never mind. The headers are correctly sent for scheduled feed updates, it’s just a problem when manually updating. That is probably a feature, however. My bad.

**Comment by samuelclay** [comment]
Ahh, this explains #958.
