### ISSUE TITLE
iOS: Returning to app on iPad reloads story

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#960]
From https://getsatisfaction.com/newsblur/topics/different-behaviour-ipad-vs-iphone-switching-windows:

I've noticed that when switching windows/apps on iPhone away from NewsBlur, for example if I open a link from a post in Safari, and then switch back to NewsBlur, it does not re-load the post, i.e. I'm back to exactly to where I had scrolled, or embedded video remains paused at the same spot. This is great. 

However on iPad, switching back to the NewsBlur app causes the post to refresh, losing my place or resetting the embedded video, which is annoying. 

Is there a way to get the app to work on iPad like it does on iPhone?

**Comment by Dejal** [comment]
I'm working on another client project at present, but will see what I can do after that, probably next week sometime.

**Comment by samuelclay** [comment]
Works great for me, thanks!
