### ISSUE TITLE
Threaded sort

### ISSUE THREAD

**Issue by yardenac** [samuelclay/NewsBlur#962]
Right now you can only sort feeds by date. But once https://github.com/samuelclay/NewsBlur/issues/961 is implemented, it will be useful to sort them by their subject line first, date second, the way many threading email clients do it.

An even more advanced feature would collapse all threads to look like one story, collapse read messages in each thread, and collapse quoted text in each message. Then you're basically Gmail.

**Comment by samuelclay** [comment]
Yeah, I think NewsBlur's newsletter feature should stop short of being a full on email read client. If you post a screenshot of the mailing list in NB that would benefit from this, I might reconsider, but I think this feature is best for promotional newsletters and one-off emails, not threads.
