### ISSUE TITLE
Android: Add preference for confirmation on mark older/newer stories as read

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#965]
This does not apply ot the mark as read button. This is strictly for marking older/newer stories as read. Defaults to no confirmation.

**Comment by dosiecki** [comment]
Should this work the way it does with the option for mark-all-read where it only applies to folders, or should it apply in all cases?

**Comment by samuelclay** [comment]
All cases, it's just for those two menu items.

**Comment by samuelclay** [comment]
Nope, not a blocker.

**Comment by manderson23** [comment]
I still think #584 is a better overall solution than confirm dialogs. But obviously a lot more work.

**Comment by samuelclay** [comment]
I agree but the will take too long and cost too much for the relative benefit.

**Comment by dosiecki** [comment]
Implemented in #970.
