### ISSUE TITLE
Contextual menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [samuelclay/NewsBlur#973]
When i perform these sequences of events, the menu on screen disappears:

Sequence 1:
1. Long Click on All Stories
2. Orientation Change

Sequence 2:
1. Click on Saved Stories
2. Long Click on story item in list
3. Orientation Change

Sequence 3:
1. Click on All Stories
2. Long Click on story item in list
3. Orientation Change

Sequence 4:
1. Click on Search feeds
2. Enter text to search
3. Long Click on feed item in list
4. Orientation Change

**Comment by dosiecki** [comment]
It is perfectly normal for context menus to disapear on device rotation. Pop up any '...' menu or a context menu in an app like Chrome or the Play Store and rotate your device: the menu will collapse. While I don't believe this behaviour is necessarily prescribed, neither is it even remotely uncommon.

In cases 1, 2, and 3, this is a function of the platform.

In case 4, though this is a result of the platform library we are using, I do agree it is annoying.  If enough people are impacted by it, we could dump the platform bit and write our own to fix it.

**Comment by dosiecki** [comment]
Addressed these issues in general and in specific in #972.
