### ISSUE TITLE
Action Overflow Menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [samuelclay/NewsBlur#974]
When i perform this sequence of events, the menu disappears:

1. Click on ... (More Options)
2. Orientation Change

**Comment by dosiecki** [comment]
It is perfectly normal for context menus to disapear on device rotation. Pop up any '...' menu or a context menu in an app like Chrome or the Play Store and rotate your device: the menu will collapse. While I don't believe this behaviour is necessarily prescribed, neither is it even remotely uncommon.  In this particular case, this is a function of the platform.
