### ISSUE TITLE
Edit Text changes value on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [samuelclay/NewsBlur#976]
Text field lose user input on device rotation

Event sequence:
1. Click on Search
2. Enter text in field
3. Orientation Change

**Comment by dosiecki** [comment]
Please be more specifc about which text field in which activity or dialogue is losing state for you.  We have spot-tested many, but you may be seeing device-specific behaviour, so we need much more info.  Issue #980 is tracking one known issue with one particular search field, but if you have others, please do note them here.
