### ISSUE TITLE
NewsBlur confused when the same subfolder name exists under different folder

### ISSUE THREAD

**Issue by dolohow** [samuelclay/NewsBlur#984]
1. When you click on subfolder the url does not include its subfolder.
2. When removing item from such subfolder it will be moved to different folder.

**Comment by eric11** [comment]
I have this same issue. For example, if I already have a root level directory called "Tech", and then add a subfolder under Blogs called Tech "Blogs --> Tech", I cannot place any feeds in the subfolder under blogs, while it is selectable in the folder selector the feed always appears under the original "Tech" folder.

**Comment by samuelclay** [comment]
Finally we will fix this. Follow #1322 for updates.
