### ISSUE TITLE
Android: Action/Sync Queue Can Become Blocked

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#989]
Over the last several months we have had very small but very steady number of bug reports from users about the app refusing to sync.  Debug info received from them shows a comon cause of the action queue becoming poisoned by blocking requests.

More recently, the sync logic was changed so that a *failed* action in the queue would not block the queue or the sync loop, on the suspicion that it was merely fatally bad actions poisoning the queue.  This improvement has not eradicated the issue, suggesting that the blocking actions are actually blocking in a network/execution sense and not just failing and being retried.

The commonly effective workaround of clearing app data suggest that there may exist a class of actions that are fatally impossible to incomplete.

Ideally, it would be great if we could devise a mechanism for getting raw debug/log info from users that experience this bug, so we can fix the root cause(s), since, whatever they are, they have totally evaded reproduction.  In the meantime, it may be necessary to break the in-order call contract and risk slight data loss about reading actions if the problem gets any more common.

**Comment by dosiecki** [comment]
Collecting for posterity some debug reports we have received that may be related to the issue:

* https://getsatisfaction.com/newsblur/topics/android-bemnmpwir2mmw
* https://getsatisfaction.com/newsblur/topics/android-app-not-working-rwkshjp896mbd
* https://getsatisfaction.com/newsblur/topics/android-new-version-no-unread-stories
* https://getsatisfaction.com/newsblur/topics/android-delays-reading-any-already-fetched-articles-while-catching-up-on-reading-actions-for-tens-of-seconds
* https://getsatisfaction.com/newsblur/topics/android-catching-up-reading-actions-forever
https://getsatisfaction.com/newsblur/topics/android-beta-5-0-app-could-not-find-any-new-stories-had-to-uninstall-and-reinstall

**Comment by dosiecki** [comment]
A couple of theories to pursue if this gets bad enough to do a deeper dive:

1) DB state gets corrupted or mismatched to structure in some way to create un-runnable actions. No direct evidence, but the fact that the bug sometimes happens right after upgrade points us in this direction as it is the one time the DB structure changes.

2) Some internal lock, file, or resource is getting raced for.  This hypothesis is a result of the observation that these reports just happened to start around the time story list thumbnails were launched, which use a great deal of resources asynchronously to load.

3) The app's network access is being throttled or interrupted.  Best direct evidence suggests that API calls are blackhole hanging.  Introducing synthetic packet loss is the *only* way this issue's UX has been reproduced in part, though it is not fatal unless loss is fairly high.  Users report good network access in general, suggesting it is something specific to the app as a client or the NB servers in particular.  This could be related to upgrades or thumbnails, as they are two times when our app hammers the network and the device / platform / network could be reacting.  It is unknown, though, why clearing app data would fix this, though.

**Comment by samuelclay** [comment]
I'm fine with some data loss if we can detect that the queue hasn't moved. I assume this will remove individual read actions, not a whole batch of them.

And this should be our top priority on Android, now that notifications are ready.

**Comment by samuelclay** [comment]
So high packet loss cause issues? We should probably be addressing that reproducible scenario first. Then figure out why the DB upgrade is a problem. On iOS, I just wipe out the offline stories database on upgrade. No state should be kept on the device apart from local UI preferences (minimized folders), so wiping it clean shouldn't pose a problem.

**Comment by dosiecki** [comment]
> So high packet loss cause issues?

They only way I have been able to repro the reported UX is *fatally* high packet loss, like, 50%+.  The app correctly tolerates anything reasonable.  Thus, I fear it is something of a red herring, especially because reinstalling wouldn't "fix" a network issue.

> Then figure out why the DB upgrade is a problem. On iOS, I just wipe out the offline stories database on upgrade. No state should be kept on the device apart from local UI preferences (minimized folders), so wiping it clean shouldn't pose a problem.

The problem is: we already do this.  Going theories: either the wipe isn't sticking (local DB bugs we need to address) or there is some app meta-state (throttling, etc) that is only clearable by a reinstall.

**Comment by dosiecki** [comment]
I have already logged dozens of hours trying to reproduce this in a way that mimics what folks are reporting, but have hit a wall.  What we really need is logs from someone who sees the issue.

**Comment by samuelclay** [comment]
I can post on Twitter but are people still being bit by this bug? Next time we upgrade the db, I can include a mention in the blog post to let us know if no new stories come in so we can debug. But what will we do for them when that happens? Just instruct the user to send us their logs? How easy is that for the non-developer?

**Comment by dosiecki** [comment]
On 9 February 2017 14:29:02 GMT-08:00, Samuel Clay <notifications@github.com> wrote:
>I can post on Twitter but are people still being bit by this bug? Next
>time we upgrade the db, I can include a mention in the blog post to let
>us know if no new stories come in so we can debug. But what will we do
>for them when that happens? Just instruct the user to send us their
>logs? How easy is that for the non-developer?

The unfortunate meta issue is that log collection is not possible for users unless they are rooted and willing to install a special app or they have a computer with a full development environment installed. 

We could, however, easily do automated log collection on failure in beta if we had an endpoint to which they could be sent. Something like a cname under the NewsBlur domain to an endpoint with a degenerately simple API that logs to disk or an s3 bucket would be ideal and would revolutionise our ability to debug rare issues. (this is what most grown-up Android apps do)

**Comment by samuelclay** [comment]
How about email? How often will this endpoint be hit and will it be automated or will the user be prompted to send it? How do we know when to send it? Is there a timeout?

**Comment by dosiecki** [comment]
On 9 February 2017 14:48:43 GMT-08:00, Samuel Clay <notifications@github.com> wrote:
>How about email? How often will this endpoint be hit and will it be
>automated or will the user be prompted to send it? How do we know when
>to send it? Is there a timeout?

Email isn't a bad idea, since I trust our users to actually engage. I can whip this up pretty quickly.   To what address should we post it?

**Comment by samuelclay** [comment]
Oh no, I meant you can send it to a URL and I'll have NewsBlur email it directly to you. I just want to know if this will be a heavy load or light load.

**Comment by dosiecki** [comment]
Ah, gotcha.  Come to think of it though, this inspires a thought - if the app is having network issues in the first place, attempting to send logs to the server might also fail.  If, however, other apps are working (as users report), sending via email would more reliably go through.  The trade-off is whether users will be willing to do the 2 or 3 extra clicks to send the email after experiencing a bug.

**Comment by samuelclay** [comment]
Ok, I'm fine with that, let the app send the email. CC android@newsblur.com when you do.

**Comment by dosiecki** [comment]
(since it never got tagged in the pull) #992 implemented this framework for another high-priority debug session.  We finally have a beta that would let someone experiencing this report it to us so we have any kind of clue how to go about handling it.

**Comment by dosiecki** [comment]
>  I wish there was an automatic way of clearing that broken network queue.

As of a few patches ago, the queue is no longer blocking unless a call fails in a way that looks like API access is failing repeatedly and without an understood cause.

We could certainly let the app blow past failed calls, but that has two risks: 1) we won't ever know when things do break and user data would be silently lost and 2) typical root causes of API failure are not call-specific, so the next part of the sync would just fail in a more complex way (right now we catch first failures on one-shot calls, not multi-step calls) and the resulting UX could be very unpredictable, if partially working.

However, it is looking like these failures are steadily increasing as weeks pass and I still don't have a single lead as to why.  If external forces are at play, our only recourse might be to give up on proper precondition enforcement for a time.  If anyone gets any feedback from users on the 5.1.x builds, definitely encourage them to use the new `Email a bug report` feature.

**Comment by samuelclay** [comment]
Would you be OK with promoting 5.1 to prod?

**Comment by dosiecki** [comment]
On 19 March 2017 16:10:33 GMT-07:00, Samuel Clay <notifications@github.com> wrote:
>Would you be OK with promoting 5.1 to prod?

Quite. I am experimenting with a version of 5.2 with the API ordering constraints relaxed, but I am not sure the workaround is net negative entropy. The sooner folk can send us detailed reports, the better.

**Comment by dosiecki** [comment]
I have to admit a gaffe on my part: I got mixed up which version got cut where and queue skipping is already in Production as of 5.0.x!

The fact that we are still seeing similar problems indicates something very interesting: whatever was making actions fail is *also* making the rest of sync fail.  Remaining cases of this are not due to a poisoned queue, but to a broad, common cause of API failures.

One the one hand, this is suddenly a much less specific bug (the network doesn't work), but on the other hand, we know it tends to affect multiple types of API call when it does occur, not just one, which eliminates more in-code causes.

Our focus on reproducing this should re-focus towards platform, library, configuration, or connection issues.  Of course, the new log collection framework should be invaluable if we can start getting folks to use it.

**Comment by dosiecki** [comment]
From what I can tell, this all boiled down to the spurious cookie problems and how to handle both them and real cookie expiration.  The fix appears to behaving well in Beta.
