### ISSUE TITLE
Android: Mark stories read on scroll

### ISSUE THREAD

**Issue by gabrielcossette** [samuelclay/NewsBlur#990]
Just like iOS, it would be great to add the "Mark stories read on scroll" feature to the Android client.

When you have a long list of articles to glance over, this is a needed enhancement if you don't want to mark articles as read one by one...

Thanks!

**Comment by dosiecki** [comment]
As a workaround, the Android client lets you long-press on a story in the list and mark all stories above or below it as read.  (this is how I accomplish the glance-and-mark workflow)

**Comment by samuelclay** [comment]
I really like the mark read on scroll feature. I use it on iOS but not on the web. I'd love to see this on Android.

**Comment by dosiecki** [comment]
deployed to Prod
